#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# BCM56991 64x200g port configuration.
# Support pipe numbers: 0, 1, 2, 3, 12, 13, 14, 15
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#

---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 3
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 7
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 9
            ?
                PORT_ID: 6
            :
                PC_PHYS_PORT_ID: 11
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 13
            ?
                PORT_ID: 8
            :
                PC_PHYS_PORT_ID: 15
            ?
                PORT_ID: 17     # Pipe1
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 18
            :
                PC_PHYS_PORT_ID: 19
            ?
                PORT_ID: 19
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 20
            :
                PC_PHYS_PORT_ID: 23
            ?
                PORT_ID: 21     # Pipe1
            :
                PC_PHYS_PORT_ID: 25
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 27
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 29
            ?
                PORT_ID: 24
            :
                PC_PHYS_PORT_ID: 31
            ?
                PORT_ID: 34     # Pipe2
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 35
            ?
                PORT_ID: 36
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 37
            :
                PC_PHYS_PORT_ID: 39
            ?
                PORT_ID: 38     # Pipe2
            :
                PC_PHYS_PORT_ID: 41
            ?
                PORT_ID: 39
            :
                PC_PHYS_PORT_ID: 43
            ?
                PORT_ID: 40
            :
                PC_PHYS_PORT_ID: 45
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 47
            ?
                PORT_ID: 51     # Pipe3
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 52
            :
                PC_PHYS_PORT_ID: 51
            ?
                PORT_ID: 53
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 54
            :
                PC_PHYS_PORT_ID: 55
            ?
                PORT_ID: 55     # Pipe3
            :
                PC_PHYS_PORT_ID: 57
            ?
                PORT_ID: 56
            :
                PC_PHYS_PORT_ID: 59
            ?
                PORT_ID: 57
            :
                PC_PHYS_PORT_ID: 61
            ?
                PORT_ID: 58
            :
                PC_PHYS_PORT_ID: 63
            ?
                PORT_ID: 204    # Pipe12
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 205
            :
                PC_PHYS_PORT_ID: 195
            ?
                PORT_ID: 206
            :
                PC_PHYS_PORT_ID: 197
            ?
                PORT_ID: 207
            :
                PC_PHYS_PORT_ID: 199
            ?
                PORT_ID: 208    # Pipe12
            :
                PC_PHYS_PORT_ID: 201
            ?
                PORT_ID: 209
            :
                PC_PHYS_PORT_ID: 203
            ?
                PORT_ID: 210
            :
                PC_PHYS_PORT_ID: 205
            ?
                PORT_ID: 211
            :
                PC_PHYS_PORT_ID: 207
            ?
                PORT_ID: 221    # Pipe13
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 222
            :
                PC_PHYS_PORT_ID: 211
            ?
                PORT_ID: 223
            :
                PC_PHYS_PORT_ID: 213
            ?
                PORT_ID: 224
            :
                PC_PHYS_PORT_ID: 215
            ?
                PORT_ID: 225    # Pipe13
            :
                PC_PHYS_PORT_ID: 217
            ?
                PORT_ID: 226
            :
                PC_PHYS_PORT_ID: 219
            ?
                PORT_ID: 227
            :
                PC_PHYS_PORT_ID: 221
            ?
                PORT_ID: 228
            :
                PC_PHYS_PORT_ID: 223
            ?
                PORT_ID: 238    # Pipe14
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 239
            :
                PC_PHYS_PORT_ID: 227
            ?
                PORT_ID: 240
            :
                PC_PHYS_PORT_ID: 229
            ?
                PORT_ID: 241
            :
                PC_PHYS_PORT_ID: 231
            ?
                PORT_ID: 242    # Pipe14
            :
                PC_PHYS_PORT_ID: 233
            ?
                PORT_ID: 243
            :
                PC_PHYS_PORT_ID: 235
            ?
                PORT_ID: 244
            :
                PC_PHYS_PORT_ID: 237
            ?
                PORT_ID: 245
            :
                PC_PHYS_PORT_ID: 239
            ?
                PORT_ID: 255    # Pipe15
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 256
            :
                PC_PHYS_PORT_ID: 243
            ?
                PORT_ID: 257
            :
                PC_PHYS_PORT_ID: 245
            ?
                PORT_ID: 258
            :
                PC_PHYS_PORT_ID: 247
            ?
                PORT_ID: 259    # Pipe15
            :
                PC_PHYS_PORT_ID: 249
            ?
                PORT_ID: 260
            :
                PC_PHYS_PORT_ID: 251
            ?
                PORT_ID: 261
            :
                PC_PHYS_PORT_ID: 253
            ?
                PORT_ID: 262
            :
                PC_PHYS_PORT_ID: 255
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: [[1, 8],
                          [17, 24],
                          [34, 41],
                          [51, 58],
                          [204, 211],
                          [221, 228],
                          [238, 245],
                          [255, 262]]
            :
                ENABLE: 1
                SPEED: 200000
                NUM_LANES: 4
                FEC_MODE: PC_FEC_RS544_2XN
                MAX_FRAME_SIZE: 9416
...
