#
# $Id$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for dpp subdirectory
#

LOCALDIR = src/soc/dnxc/swstate

include ${SDK}/make/Make.config

#
# Take the subdirs 'auto_generated utils'
#
subdirs = auto_generated utils types

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxcswstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

