# $Id: $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id$
# Makefile for Firelight SOC driver Library
#

LOCALDIR = src/soc/esw/firelight

include ${SDK}/make/Make.config

lib = libsoc_firelight

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
