/*! \file bcmmgmt_complist.h
 *
 * List of supported components.
 *
 * The macro BCMMGMT_COMPLIST_ENTRY must be defined before this file
 * is included. The macro will be undefined implicitly.
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

BCMMGMT_COMPLIST_ENTRY(TRM, 0)
BCMMGMT_COMPLIST_ENTRY(LT, 1)
BCMMGMT_COMPLIST_ENTRY(BD, 2)
BCMMGMT_COMPLIST_ENTRY(CFG, 3)
BCMMGMT_COMPLIST_ENTRY(DRD, 4)
BCMMGMT_COMPLIST_ENTRY(LTD, 5)
BCMMGMT_COMPLIST_ENTRY(PTM, 6)
BCMMGMT_COMPLIST_ENTRY(LTM, 7)
BCMMGMT_COMPLIST_ENTRY(IMM_FE, 8)
BCMMGMT_COMPLIST_ENTRY(IMM_BE, 9)
BCMMGMT_COMPLIST_ENTRY(FP, 10)
BCMMGMT_COMPLIST_ENTRY(LM, 11)
BCMMGMT_COMPLIST_ENTRY(ECMP, 12)
BCMMGMT_COMPLIST_ENTRY(TRUNK, 13)
BCMMGMT_COMPLIST_ENTRY(LTP, 14)
BCMMGMT_COMPLIST_ENTRY(PC, 15)
BCMMGMT_COMPLIST_ENTRY(METER, 16)
BCMMGMT_COMPLIST_ENTRY(TNL, 17)
BCMMGMT_COMPLIST_ENTRY(VLAN, 18)
BCMMGMT_COMPLIST_ENTRY(TM, 19)
BCMMGMT_COMPLIST_ENTRY(ECN, 20)
BCMMGMT_COMPLIST_ENTRY(LRD, 21)
BCMMGMT_COMPLIST_ENTRY(L2, 22)
BCMMGMT_COMPLIST_ENTRY(EVM, 23)
BCMMGMT_COMPLIST_ENTRY(PORT, 24)
BCMMGMT_COMPLIST_ENTRY(DLB, 25)
BCMMGMT_COMPLIST_ENTRY(MIRROR, 26)
BCMMGMT_COMPLIST_ENTRY(RM_HASH, 27)
BCMMGMT_COMPLIST_ENTRY(RM_TCAM, 28)
BCMMGMT_COMPLIST_ENTRY(RM_ALPM, 29)
BCMMGMT_COMPLIST_ENTRY(UFT, 30)
BCMMGMT_COMPLIST_ENTRY(DI, 31)
BCMMGMT_COMPLIST_ENTRY(ALPM, 32)
BCMMGMT_COMPLIST_ENTRY(ALPM_BE, 33)
BCMMGMT_COMPLIST_ENTRY(CTR_FLEX, 34)
BCMMGMT_COMPLIST_ENTRY(LB, 35)
BCMMGMT_COMPLIST_ENTRY(AGM, 36)
BCMMGMT_COMPLIST_ENTRY(ISSU, 37)
BCMMGMT_COMPLIST_ENTRY(CTR_EFLEX, 38)
BCMMGMT_COMPLIST_ENTRY(CTR_DBGSEL, 39)
BCMMGMT_COMPLIST_ENTRY(LDH, 40)
BCMMGMT_COMPLIST_ENTRY(PHB, 41)
BCMMGMT_COMPLIST_ENTRY(SER, 42)
BCMMGMT_COMPLIST_ENTRY(MON, 43)
BCMMGMT_COMPLIST_ENTRY(UFT_BE, 44)
BCMMGMT_COMPLIST_ENTRY(FLEX_DIGEST, 45)
BCMMGMT_COMPLIST_ENTRY(CTR_EVICT, 46)
BCMMGMT_COMPLIST_ENTRY(L3, 47)
BCMMGMT_COMPLIST_ENTRY(FLEX_QOS, 48)
BCMMGMT_COMPLIST_ENTRY(UDF, 49)
BCMMGMT_COMPLIST_ENTRY(ECMP_MEMBER_DEST, 50)
BCMMGMT_COMPLIST_ENTRY(STATE_EFLEX, 51)
BCMMGMT_COMPLIST_ENTRY(OAM, 52)
BCMMGMT_COMPLIST_ENTRY(TS, 53)
BCMMGMT_COMPLIST_ENTRY(SEC, 54)
#undef BCMMGMT_COMPLIST_ENTRY
