# $Id
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for Helix5 SOC driver Library
#

LOCALDIR = src/soc/esw/helix5

include ${SDK}/make/Make.config

SUBDIR_HELIX5_FLEXPORT = flexport

subdirs := $(SUBDIR_HELIX5_FLEXPORT)

lib = libsoc_helix5

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

