# $Id: Makefile,v 1.97 2011/09/01 08:06:42 mlarsen Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/shadow

export BCM_HIDE_DISPATCHABLE=1

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libbcm_shadow
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
