

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_INGR_CONGESTION_H_

#define _DNX_DATA_MAX_INGR_CONGESTION_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_INGR_CONGESTION_INFO_THRESHOLD_GRANULARITY (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WORDS_RESOLUTION (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_BYTES_THRESHOLD_GRANULARITY (256)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_DROPPED_REASONS_CGM (33)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_MAX_GAIN (31)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_GRANULARITY (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_PDS_IN_PDB (4)

#define DNX_DATA_MAX_INGR_CONGESTION_INFO_LATENCY_BASED_ADMISSION_REJECT_FLOW_PROFILE_VALUE (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_LATENCY_BASED_ADMISSION_CGM_EXTENDED_PROFILES_ENABLE_VALUE (1)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_LATENCY_BASED_ADMISSION_MAX_SUPPORTED_PROFILE (31)


#define DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MIN (0)


#define DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MAX (7)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_RATE_CLASS (64)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_RATE_CLASS_NOF_BITS (6)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_COMPENSATION_PROFILES (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_DEFAULT_COMPENSATION (24)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_LATENCY_BINS (8)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_VOQ_CONGESTION_NOTIFICATION_FIFO_SIZE (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_RATE_CLASS_NOF (16)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_RATE_CLASS_NOF (4)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_NOF (4)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_B_NOF (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_C_NOF (128)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_D_NOF (256)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_NOF (147)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_HW_NOF (148)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_NOF (1024)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_HW_NOF (1024)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_NIF_VSQ_E_NOF (144)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_NON_NIF_VSQ_F_NOF (71)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_POOL_NOF (2)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_CONNECTION_CLASS_NOF (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_TC_PG_PROFILE_NOF (16)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_CONGESTION_NOTIFICATION_FIFO_SIZE (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_CONGESTION_NOTIFICATION_FIFO_SIZE (32)


#define DNX_DATA_MAX_INGR_CONGESTION_INIT_FIFO_SIZE (256)


#define DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_NOF_GROUPS (8)


#define DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_AGING_CLOCKS_RESOLUTION (1024)




#endif 

