

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_SCH_H_

#define _DNX_DATA_MAX_SCH_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_SCH_GENERAL_NOF_SLOW_PROFILES (2)


#define DNX_DATA_MAX_SCH_GENERAL_NOF_SLOW_LEVELS (8)


#define DNX_DATA_MAX_SCH_GENERAL_CYCLES_PER_CREDIT_TOKEN (12)


#define DNX_DATA_MAX_SCH_GENERAL_NOF_FMQ_CLASS (4)


#define DNX_DATA_MAX_SCH_PS_MIN_PRIORITY_FOR_TCG (4)


#define DNX_DATA_MAX_SCH_PS_MAX_NOF_TCG (8)


#define DNX_DATA_MAX_SCH_PS_NOF_HRS_IN_PS (8)


#define DNX_DATA_MAX_SCH_PS_MAX_TCG_WEIGHT (1023)


#define DNX_DATA_MAX_SCH_PS_TC_TCG_CALENDAR_ACCESS_PERIOD (3)


#define DNX_DATA_MAX_SCH_FLOW_NOF_HR    (1024)


#define DNX_DATA_MAX_SCH_FLOW_NOF_CL    (65536)


#define DNX_DATA_MAX_SCH_FLOW_NOF_SE    (131072)


#define DNX_DATA_MAX_SCH_FLOW_NOF_FLOWS (393216)


#define DNX_DATA_MAX_SCH_FLOW_REGION_SIZE (1024)


#define DNX_DATA_MAX_SCH_FLOW_NOF_REGIONS (384)


#define DNX_DATA_MAX_SCH_FLOW_NOF_HR_REGIONS (4)


#define DNX_DATA_MAX_SCH_FLOW_NOF_CONNECTORS_ONLY_REGIONS (256)


#define DNX_DATA_MAX_SCH_FLOW_FLOW_IN_REGION_MASK (1023)


#define DNX_DATA_MAX_SCH_FLOW_MIN_CONNECTOR_BUNDLE_SIZE (4)


#define DNX_DATA_MAX_SCH_FLOW_CONN_IDX_INTERDIG_FLOW (2)


#define DNX_DATA_MAX_SCH_FLOW_SHAPER_FLIPFLOPS_NOF (20)


#define DNX_DATA_MAX_SCH_SE_DEFAULT_COS (252)


#define DNX_DATA_MAX_SCH_SE_NOF_COLOR_GROUP (3)


#define DNX_DATA_MAX_SCH_SE_MAX_HR_WEIGHT (4096)


#define DNX_DATA_MAX_SCH_SE_CL_CLASS_PROFILE_NOF (512)


#define DNX_DATA_MAX_SCH_INTERFACE_NOF_BIG_CALENDARS (8)


#define DNX_DATA_MAX_SCH_INTERFACE_NOF_CHANNELIZED_CALENDARS (64)


#define DNX_DATA_MAX_SCH_INTERFACE_BIG_CALENDAR_SIZE (1024)


#define DNX_DATA_MAX_SCH_INTERFACE_NOF_SCH_INTERFACES (136)


#define DNX_DATA_MAX_SCH_INTERFACE_CAL_SPEED_RESOLUTION (128)


#define DNX_DATA_MAX_SCH_INTERFACE_RESERVED (136)


#define DNX_DATA_MAX_SCH_DEVICE_DRM_RESOLUTION (128)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_TAG_AGGREGATE_SE_2 (2)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_TAG_AGGREGATE_SE_4 (4)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_TAG_AGGREGATE_SE_8 (8)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_SHARED_SHAPER_MAX_TAG_VALUE (8)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_TAG_SIZE_AGGREGATE_SE (8)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_TAG_SIZE_CON (8)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_TYPE_CON_REG_START (0)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_ALLOC_INVALID_FLOW (0)


#define DNX_DATA_MAX_SCH_SCH_ALLOC_DEALLOC_FLOW_IDS (16)


#define DNX_DATA_MAX_SCH_DBAL_SCHEDULER_ENABLE_GROUPING_FACTOR (8)


#define DNX_DATA_MAX_SCH_DBAL_SCHEDULER_ENABLE_DBAL_MULT_FACTOR (255)


#define DNX_DATA_MAX_SCH_DBAL_FLOW_BITS (19)


#define DNX_DATA_MAX_SCH_DBAL_SE_BITS   (17)


#define DNX_DATA_MAX_SCH_DBAL_CL_BITS   (16)


#define DNX_DATA_MAX_SCH_DBAL_HR_BITS   (10)


#define DNX_DATA_MAX_SCH_DBAL_INTERFACE_BITS (8)


#define DNX_DATA_MAX_SCH_DBAL_CALENDAR_BITS (6)


#define DNX_DATA_MAX_SCH_DBAL_FLOW_SHAPER_MANT_BITS (8)


#define DNX_DATA_MAX_SCH_DBAL_PS_SHAPER_QUANTA_BITS (13)


#define DNX_DATA_MAX_SCH_DBAL_PS_SHAPER_MAX_BURST_BITS (17)


#define DNX_DATA_MAX_SCH_DBAL_DRM_NOF_LINKS_MAX (192)




#endif 

