

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_GTIMER_H_

#define _DNX_DATA_MAX_GTIMER_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_GTIMER_FDTL_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_FDTL_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_PEM_BLOCK_INDEX_SIZE (3)


#define DNX_DATA_MAX_GTIMER_PEM_BLOCK_INDEX_MAX_VALUE (7)


#define DNX_DATA_MAX_GTIMER_CDU_BLOCK_INDEX_SIZE (4)


#define DNX_DATA_MAX_GTIMER_CDU_BLOCK_INDEX_MAX_VALUE (9)


#define DNX_DATA_MAX_GTIMER_ESB_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ESB_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_BDM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_BDM_BLOCK_INDEX_MIN_VALUE (1)


#define DNX_DATA_MAX_GTIMER_BDM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_HBC_BLOCK_INDEX_SIZE (4)


#define DNX_DATA_MAX_GTIMER_HBC_BLOCK_INDEX_MAX_VALUE (15)


#define DNX_DATA_MAX_GTIMER_ECGM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ECGM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_CFC_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_CFC_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_CGM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_CGM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_CRPS_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_CRPS_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_DDHA_BLOCK_INDEX_SIZE (2)


#define DNX_DATA_MAX_GTIMER_DDHA_BLOCK_INDEX_MAX_VALUE (3)


#define DNX_DATA_MAX_GTIMER_DDP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_DDP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_DQM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_DQM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_EDB_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_EDB_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_EPNI_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_EPNI_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_EPRE_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_EPRE_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_EPS_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_EPS_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ERPP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ERPP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ETPPA_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ETPPA_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ETPPB_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ETPPB_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ETPPC_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ETPPC_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_FQP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_FQP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ILE_BLOCK_INDEX_SIZE (3)


#define DNX_DATA_MAX_GTIMER_ILE_BLOCK_INDEX_MAX_VALUE (7)


#define DNX_DATA_MAX_GTIMER_IPPA_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPPA_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPPB_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPPB_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPPC_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPPC_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPPD_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPPD_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPPE_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPPE_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPPF_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPPF_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPS_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPS_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IPT_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IPT_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IQM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IQM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_IRE_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_IRE_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ITPP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ITPP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_ITPPD_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_ITPPD_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_KAPS_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_KAPS_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_MCP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_MCP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_MRPS_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_MRPS_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_NMG_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_NMG_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_OCB_BLOCK_INDEX_SIZE (3)


#define DNX_DATA_MAX_GTIMER_OCB_BLOCK_INDEX_MAX_VALUE (7)


#define DNX_DATA_MAX_GTIMER_PDM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_PDM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_PQP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_PQP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_RQP_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_RQP_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_SCH_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_SCH_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_SIF_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_SIF_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_SPB_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_SPB_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_SQM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_SQM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_TCAM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_TCAM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_TDU_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_TDU_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_DCC_BLOCK_INDEX_SIZE (2)


#define DNX_DATA_MAX_GTIMER_DCC_BLOCK_INDEX_MAX_VALUE (3)


#define DNX_DATA_MAX_GTIMER_CDB_BLOCK_INDEX_SIZE (4)


#define DNX_DATA_MAX_GTIMER_CDB_BLOCK_INDEX_MAX_VALUE (15)


#define DNX_DATA_MAX_GTIMER_CDBM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_CDBM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_CDPM_BLOCK_INDEX_SIZE (5)


#define DNX_DATA_MAX_GTIMER_CDPM_BLOCK_INDEX_MAX_VALUE (17)


#define DNX_DATA_MAX_GTIMER_OCBM_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_OCBM_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_MSS_BLOCK_INDEX_SIZE (1)


#define DNX_DATA_MAX_GTIMER_MSS_BLOCK_INDEX_MAX_VALUE (1)


#define DNX_DATA_MAX_GTIMER_MSD_BLOCK_INDEX_SIZE (3)


#define DNX_DATA_MAX_GTIMER_MSD_BLOCK_INDEX_MAX_VALUE (7)




#endif 

