

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_FABRIC_H_

#define _DNX_DATA_MAX_FABRIC_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_FABRIC_GENERAL_NOF_LCPLLS (2)


#define DNX_DATA_MAX_FABRIC_GENERAL_FMAC_CLOCK_KHZ (906250)


#define DNX_DATA_MAX_FABRIC_LINKS_NOF_LINKS (192)


#define DNX_DATA_MAX_FABRIC_LINKS_NOF_LINKS_PER_CORE (96)


#define DNX_DATA_MAX_FABRIC_LINKS_MAX_LINK_ID (191)


#define DNX_DATA_MAX_FABRIC_LINKS_MAX_SPEED (53125)


#define DNX_DATA_MAX_FABRIC_LINKS_USEC_BETWEEN_LOAD_BALANCING_EVENTS (1000000)


#define DNX_DATA_MAX_FABRIC_LINKS_KR_FEC_SUPPORTED (1)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_INSTANCES_FMAC (48)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_LINKS_IN_FMAC (4)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_INSTANCES_FSRD (24)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_LINKS_IN_FSRD (8)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_FMACS_IN_FSRD (2)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_PMS (24)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_LINKS_IN_PM (8)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_FMACS_IN_PM (2)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_INSTANCES_FDTL (2)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_LINKS_IN_FDTL (112)


#define DNX_DATA_MAX_FABRIC_BLOCKS_NOF_SBUS_CHAINS (2)


#define DNX_DATA_MAX_FABRIC_REACHABILITY_RESOLUTION (32)


#define DNX_DATA_MAX_FABRIC_REACHABILITY_GEN_PERIOD (6)


#define DNX_DATA_MAX_FABRIC_REACHABILITY_FULL_CYCLE_PERIOD_USEC (50)


#define DNX_DATA_MAX_FABRIC_REACHABILITY_WATCHDOG_RESOLUTION (4096)


#define DNX_DATA_MAX_FABRIC_REACHABILITY_WATCHDOG_PERIOD_USEC (100)


#define DNX_DATA_MAX_FABRIC_MESH_MAX_MC_ID (131071)


#define DNX_DATA_MAX_FABRIC_MESH_MAX_NOF_DEST (3)


#define DNX_DATA_MAX_FABRIC_CELL_NOF_PRIORITIES (4)


#define DNX_DATA_MAX_FABRIC_CELL_VSC256_MAX_SIZE (272)


#define DNX_DATA_MAX_FABRIC_CELL_SR_CELL_HEADER_OFFSET (32)


#define DNX_DATA_MAX_FABRIC_CELL_SR_CELL_NOF_INSTANCES (12)


#define DNX_DATA_MAX_FABRIC_PIPES_MAX_NOF_PIPES (3)


#define DNX_DATA_MAX_FABRIC_PIPES_MAX_NOF_CONTEXTS (3)


#define DNX_DATA_MAX_FABRIC_PIPES_MAX_NOF_SUBCONTEXTS (6)


#define DNX_DATA_MAX_FABRIC_MESH_TOPOLOGY_MESH_INIT (13)


#define DNX_DATA_MAX_FABRIC_MESH_TOPOLOGY_MESH_CONFIG_1 (2)


#define DNX_DATA_MAX_FABRIC_CGM_NOF_RCI_LEVELS (8)


#define DNX_DATA_MAX_FABRIC_CGM_NOF_RCI_THRESHOLD_LEVELS (3)


#define DNX_DATA_MAX_FABRIC_CGM_EGRESS_DROP_TH_CLOCKS_RESOLUTION (16)


#define DNX_DATA_MAX_FABRIC_CGM_EGRESS_FIFO_FC_THRESHOLD (32)


#define DNX_DATA_MAX_FABRIC_CGM_STATIC_SHAPER_CREDIT_RESOLUTION_BYTES (31)


#define DNX_DATA_MAX_FABRIC_DTQS_MAX_NOF_SUBDTQS (6)


#define DNX_DATA_MAX_FABRIC_DTQS_MAX_SIZE (2048)


#define DNX_DATA_MAX_FABRIC_DTQS_OCB_ONLY_SIZE (128)


#define DNX_DATA_MAX_FABRIC_DBAL_LINK_RCI_THRESHOLD_BITS_NOF (11)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_LLFC_THRESHOLD_BITS_NOF (11)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_LLFC_THRESHOLD_MAX_VALUE (1024)


#define DNX_DATA_MAX_FABRIC_DBAL_EGRESS_FIFO_DROP_THRESHOLD_BITS_NOF (12)


#define DNX_DATA_MAX_FABRIC_DBAL_EGRESS_FIFO_DROP_THRESHOLD_MAX_VALUE (2048)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_LINK_FIFO_BASE_ADDRESS_BITS_NOF (11)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_LINK_FIFO_BASE_ADDRESS_MAX_VALUE (768)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_EGRESS_FIFO_BASE_ADDRESS_BITS_NOF (12)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_EGRESS_FIFO_BASE_ADDRESS_MAX_VALUE (2048)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_EGRESS_FIFO_FC_THRESHOLD_BITS_NOF (12)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_EGRESS_FIFO_FC_THRESHOLD_MAX_VALUE (2048)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_EGRESS_DROP_MC_LOW_PRIO_TH_BITS_NOF (11)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_INGRESS_FC_THRESHOLD_MAX_VALUE (12)


#define DNX_DATA_MAX_FABRIC_DBAL_CGM_STATIC_SHAPER_CALENDAR_BITS_NOF (8)


#define DNX_DATA_MAX_FABRIC_DBAL_FABRIC_TRANSMIT_WFQ_INDEX_BITS_NOF (4)


#define DNX_DATA_MAX_FABRIC_DBAL_FABRIC_TRANSMIT_WFQ_INDEX_MAX_VALUE (9)


#define DNX_DATA_MAX_FABRIC_DBAL_MESH_TOPOLOGY_INIT_CONFIG_2_BITS_NOF (5)


#define DNX_DATA_MAX_FABRIC_DBAL_FABRIC_TRANSMIT_DTQ_FC_THRESHOLDS_BITS_NOF (12)


#define DNX_DATA_MAX_FABRIC_DBAL_FABRIC_TRANSMIT_PDQ_SIZE_BITS_NOF (15)


#define DNX_DATA_MAX_FABRIC_MESH_MC_NOF_REPLICATION (5)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_S2D_PDQ_SIZE (1023)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_SRAM_FC_TH (700)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_MIXS_FC_TH (700)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_MIXD_FC_TH (700)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_MIX_MIXS_FC_TH (600)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_MIX_MIXD_FC_TH (600)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_OCB_FC_TH (700)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_DRAM_DELETE_FC_TH (900)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_SRAM_DELETE_FC_TH (200)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_S2D_FC_TH (873)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_SRAM_EIR_FC_TH (800)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_MIXS_EIR_FC_TH (800)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_MIXD_EIR_FC_TH (800)


#define DNX_DATA_MAX_FABRIC_TRANSMIT_PDQ_OCB_EIR_FC_TH (700)




#endif 

