

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ESEM_H_

#define _DNX_DATA_MAX_ESEM_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES (3)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS (4)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NO_ACTION (0)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE (1)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_AC (8)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE (16)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION (60)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES (5)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS (6)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS (64)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD (2)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4 (48)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE (52)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION (60)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_NATIVE (12)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_AC (13)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_SFLOW_SAMPLE_INTERFACE (14)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_DUAL_HOMING (15)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_VXLAN (11)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_PROFILES (16)


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_ALLOCABLE_PROFILES (8)




#endif 

