

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_STAT_H_

#define _DNX_DATA_MAX_STAT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_STAT_STAT_PP_MAX_IRPP_PROFILE_VALUE (31)


#define DNX_DATA_MAX_STAT_STAT_PP_MAX_ETPP_PROFILE_VALUE (31)


#define DNX_DATA_MAX_STAT_STAT_PP_MAX_ETPP_COUNTING_PROFILE_VALUE (3)


#define DNX_DATA_MAX_STAT_STAT_PP_MAX_ETPP_METERING_PROFILE_VALUE (31)


#define DNX_DATA_MAX_STAT_STAT_PP_MAX_ERPP_PROFILE_VALUE (8)


#define DNX_DATA_MAX_STAT_STAT_PP_ETPP_REVERSED_STAT_CMD (1)


#define DNX_DATA_MAX_STAT_STAT_PP_ETPP_ENC_STAT_CMD_IS_REVERSED (1)


#define DNX_DATA_MAX_STAT_STAT_PP_ETPP_EGRESS_VSI_ALWAYS_PUSHED (1)


#define DNX_DATA_MAX_STAT_STAT_PP_IRPP_START_PROFILE_VALUE (1)


#define DNX_DATA_MAX_STAT_STAT_PP_ERPP_START_PROFILE_VALUE (1)


#define DNX_DATA_MAX_STAT_STAT_PP_ETPP_START_PROFILE_VALUE (1)


#define DNX_DATA_MAX_STAT_STAT_PP_ETPP_COUNTING_START_PROFILE_VALUE (1)


#define DNX_DATA_MAX_STAT_STAT_PP_ETPP_METERING_START_PROFILE_VALUE (4)


#define DNX_DATA_MAX_STAT_DROP_REASONS_NOF_DROP_REASONS (46)




#endif 

