

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ARR_NAT_H_

#define _DNX_DATA_MAX_ARR_NAT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_VSI_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_VSI_FORMATS___PREFIX_1 (1835008)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_VSI_FORMATS___PREFIX_2 (1572864)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_VSI_FORMATS___PREFIX_4 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_VSI_FORMATS___PREFIX_5 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_1 (3221225472)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_2 (268435456)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_3 (536870912)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_4 (805306368)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_5 (1073741824)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_6 (1342177280)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_13 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_7 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_ETPP_ETPS_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_ETPP_ETPS_FORMATS___PREFIX_13 (0)


#define DNX_DATA_MAX_ARR_NAT_PREFIX_ETPP_ETPS_FORMATS___PREFIX_14 (0)




#endif 

