

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_MODULE_TESTING_H_

#define _DNX_DATA_MAX_MODULE_TESTING_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF (305419896)


#define DNX_DATA_MAX_MODULE_TESTING_UNSUPPORTED_UNSUPPORTED_DEF (0)


#define DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_SIGNED (0)


#define DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_UNSIGNED (4294967295)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_CORES (2)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_ADD_CORES (3)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_MUL_CORES (6)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_DIV_CORES (1)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_OP_CORES (7)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_VRF_FIELD_SIZE (17)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_FIELD_DEFINE_EXAMPLE (2)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_MAX_VAL (5)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_FIELD_SIZE (4)




#endif 

