

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ARR_STANDARD_1_H_

#define _DNX_DATA_MAX_ARR_STANDARD_1_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_ENTRY_FORMAT___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_ENTRY_FORMAT___PREFIX_2 (12582912)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_ENTRY_FORMAT___PREFIX_3 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_ENTRY_FORMAT___PREFIX_4 (8388608)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_ENTRY_FORMAT___PREFIX_5 (9437184)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_ENTRY_FORMAT___PREFIX_6 (2097152)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_1 (1835008)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_2 (1572864)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_3 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_4 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_5 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_6 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_VSI_FORMATS___PREFIX_7 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_1 (3221225472)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_2 (268435456)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_3 (536870912)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_4 (805306368)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_5 (1073741824)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_6 (1342177280)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FWD_STAGE_FORMATS___PREFIX_7 (2013265920)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_1 (4194304)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_2 (1572864)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_3 (2097152)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_4 (2097152)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_5 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_6 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_7 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_8 (12582912)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_9 (2097152)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_10 (16252928)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_11 (16515072)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_12 (7340032)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_13 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_14 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_IN_LIF_FORMATS___PREFIX_15 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_IRPP_FEC_SUPER_ENTRY_FORMAT___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_0 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_1 (192)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_2 (224)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_3 (60)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_4 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_5 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_6 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_7 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_8 (224)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_9 (255)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_10 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_11 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_12 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_13 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_14 (0)


#define DNX_DATA_MAX_ARR_STANDARD_1_PREFIX_ETPP_ETPS_FORMATS___PREFIX_15 (0)




#endif 

