

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_DEV_INIT_H_

#define _DNX_DATA_MAX_DEV_INIT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_DEV_INIT_TIME_INIT_TOTAL_THRESH (18034800)


#define DNX_DATA_MAX_DEV_INIT_TIME_APPL_INIT_TOTAL_THRESH (19550400)


#define DNX_DATA_MAX_DEV_INIT_PROPERTIES_NAME_MAX (128)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_FORWARDING_CONTEXT_SELECTION_MASK_OFFSET (39)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_FORWARDING_CONTEXT_SELECTION_RESULT_OFFSET (78)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_TERMINATION_CONTEXT_SELECTION_MASK_OFFSET (50)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_TERMINATION_CONTEXT_SELECTION_RESULT_OFFSET (100)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_TRAP_CONTEXT_SELECTION_MASK_OFFSET (31)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_TRAP_CONTEXT_SELECTION_RESULT_OFFSET (62)


#define DNX_DATA_MAX_DEV_INIT_CONTEXT_FWD_REYCLE_PRIORITY_SIZE (2)


#define DNX_DATA_MAX_DEV_INIT_CMC_CMC_NUM (2)


#define DNX_DATA_MAX_DEV_INIT_CMC_NUM_CPU_COSQ (64)




#endif 

