

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_DRAM_H_

#define _DNX_DATA_MAX_DRAM_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_DRAM_HBM_DEFAULT_MODEL_PART_NUM (64)


#define DNX_DATA_MAX_DRAM_HBM_NOF_TDU_PER_CORE (0)


#define DNX_DATA_MAX_DRAM_HBM_WDS_SIZE  (256)


#define DNX_DATA_MAX_DRAM_GDDR6_NOF_CA_BITS (11)


#define DNX_DATA_MAX_DRAM_GDDR6_BYTES_PER_CHANNEL (2)


#define DNX_DATA_MAX_DRAM_GDDR6_TRAINING_FIFO_DEPTH (6)


#define DNX_DATA_MAX_DRAM_GDDR6_READOUT_TO_READOUT_PRD (3)


#define DNX_DATA_MAX_DRAM_GDDR6_REFRESH_TO_READOUT_PRD (35)


#define DNX_DATA_MAX_DRAM_GDDR6_READOUT_DONE_TO_DONE_PRD (10)


#define DNX_DATA_MAX_DRAM_GENERAL_INFO_OTP_RESTORE_VERSION (2)


#define DNX_DATA_MAX_DRAM_GENERAL_INFO_MAX_NOF_DRAMS (2)


#define DNX_DATA_MAX_DRAM_GENERAL_INFO_NOF_CHANNELS (8)


#define DNX_DATA_MAX_DRAM_GENERAL_INFO_MR_MASK (4095)


#define DNX_DATA_MAX_DRAM_GENERAL_INFO_NOF_MRS (16)


#define DNX_DATA_MAX_DRAM_GENERAL_INFO_PHY_ADDRESS_MASK (4095)


#define DNX_DATA_MAX_DRAM_ADDRESS_TRANSLATION_MATRIX_COLUMN_SIZE (30)


#define DNX_DATA_MAX_DRAM_ADDRESS_TRANSLATION_PHYSICAL_ADDRESS_TRANSACTION_SIZE (32)


#define DNX_DATA_MAX_DRAM_ADDRESS_TRANSLATION_NOF_ATMS (2)


#define DNX_DATA_MAX_DRAM_ADDRESS_TRANSLATION_NOF_TDUS_PER_DRAM (2)


#define DNX_DATA_MAX_DRAM_ADDRESS_TRANSLATION_NOF_TDUS (0)


#define DNX_DATA_MAX_DRAM_BUFFERS_NOF_BDBS (131072)


#define DNX_DATA_MAX_DRAM_BUFFERS_NOF_FPC_BANKS (4)


#define DNX_DATA_MAX_DRAM_DRAM_BLOCK_LEAKY_BUCKET_WINDOW_SIZE (5000)


#define DNX_DATA_MAX_DRAM_DRAM_BLOCK_WMR_RESET_ON_DEASSERT (1)


#define DNX_DATA_MAX_DRAM_DRAM_BLOCK_WMR_FULL_SIZE (50)


#define DNX_DATA_MAX_DRAM_DRAM_BLOCK_AVERAGE_READ_INFLIGHTS_ASSERT_THRESHOLD (24)


#define DNX_DATA_MAX_DRAM_DRAM_BLOCK_AVERAGE_READ_INFLIGHTS_FULL_SIZE (44)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_TRC_NOF_BITS (7)


#define DNX_DATA_MAX_DRAM_DBAL_WPR_INCREMENT_THRESHOLD_NOF_BITS (26)


#define DNX_DATA_MAX_DRAM_DBAL_AVERAGE_READ_INFLIGHTS_INCREMENT_THRESHOLD_NOF_BITS (20)


#define DNX_DATA_MAX_DRAM_DBAL_AVERAGE_READ_INFLIGHTS_DECREMENT_THRESHOLD_NOF_BITS (20)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_PLL_PDIV_NOF_BITS (6)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_PLL_CH_MDIV_NOF_BITS (9)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_PLL_FREFEFF_INFO_NOF_BITS (8)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_PLL_AUX_POST_ENABLEB_NOF_BITS (4)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_PLL_CH_ENABLEB_NOF_BITS (8)


#define DNX_DATA_MAX_DRAM_DBAL_HBM_PLL_AUX_POST_DIFFCMOS_EN_NOF_BITS (4)


#define DNX_DATA_MAX_DRAM_DBAL_DRAM_BIST_MODE_NOF_BITS (32)


#define DNX_DATA_MAX_DRAM_FIRMWARE_NOF_HBM_SPARE_DATA_RESULTS (24)


#define DNX_DATA_MAX_DRAM_FIRMWARE_SBUS_CLOCK_DIVIDER (1)


#define DNX_DATA_MAX_DRAM_FIRMWARE_SNAP_STATE_INIT_DONE (18)




#endif 

