

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_TRAP_H_

#define _DNX_DATA_MAX_TRAP_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_TRAP_INGRESS_PROTOCOL_TRAPS_LIF_PROFILE_STARTING_OFFSET (1024)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_PREDEFEIND_TRAPS (256)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_USER_DEFINED_TRAPS (224)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_1588_TRAPS (8)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_ENTRIES_ACTION_TABLE (512)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_PROTOCOL_TRAP_PROFILES (4)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_RECYCLE_CMDS (16)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_PROGRAMMABLE_TRAPS (8)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_LIF_TRAPS (8)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_ICMP_COMPRESSED_TYPES (32)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_STAT_OBJS (10)


#define DNX_DATA_MAX_TRAP_INGRESS_MAX_NOF_STAT_OBJS_TO_OVERWRITE (2)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_ERROR_CODE_PROFILES (4)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_SCI_PROFILES (4)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_ERROR_CODES (256)


#define DNX_DATA_MAX_TRAP_INGRESS_NOF_SCIS (1024)


#define DNX_DATA_MAX_TRAP_ERPP_NOF_ERPP_APP_TRAPS (19)


#define DNX_DATA_MAX_TRAP_ERPP_NOF_ERPP_FORWARD_PROFILES (8)


#define DNX_DATA_MAX_TRAP_ERPP_NOF_ERPP_USER_CONFIGURABLE_PROFILES (7)


#define DNX_DATA_MAX_TRAP_ERPP_NOF_ERPP_SNIF_PROFILES (4)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_ETPP_APP_TRAPS (11)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_ETPP_USER_CONFIGURABLE_PROFILES (4)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_ETPP_TRAP_PROFILES (7)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_ETPP_OAM_TRAPS (7)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_ETPP_SNIF_PROFILES (9)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_MTU_PROFILES (8)


#define DNX_DATA_MAX_TRAP_ETPP_NOF_ETPP_LIF_TRAPS (4)


#define DNX_DATA_MAX_TRAP_ETPP_MAX_MTU_VALUE (12287)


#define DNX_DATA_MAX_TRAP_ETPP_TRAP_CONTEXT_PORT_PROFILE_4B (1)


#define DNX_DATA_MAX_TRAP_STRENGTH_MAX_STRENGTH (15)


#define DNX_DATA_MAX_TRAP_STRENGTH_MAX_SNP_STRENGTH (7)


#define DNX_DATA_MAX_TRAP_STRENGTH_MAX_INGRESS_TO_EGRESS_COMPRESSED_STRENGTH (7)


#define DNX_DATA_MAX_TRAP_REGISTER_NAME_CHANGES_OUT_LIF_MCDB_PTR_SIGNAL (2)


#define DNX_DATA_MAX_TRAP_REGISTER_NAME_CHANGES_ADDED_N (1)


#define DNX_DATA_MAX_TRAP_REGISTER_NAME_CHANGES_PER_PP_PORT_CHANGE (1)


#define DNX_DATA_MAX_TRAP_REGISTER_NAME_CHANGES_VISIBILITY_SIGNAL_0 (1)




#endif 

