

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_INGR_REASSEMBLY_H_

#define _DNX_DATA_MAX_INGR_REASSEMBLY_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_INGR_REASSEMBLY_CONTEXT_NOF_CONTEXTS (512)


#define DNX_DATA_MAX_INGR_REASSEMBLY_CONTEXT_INVALID_CONTEXT (511)


#define DNX_DATA_MAX_INGR_REASSEMBLY_RCY_NOF_INTERFACES (2)


#define DNX_DATA_MAX_INGR_REASSEMBLY_PRIORITY_NIF_ETH_PRIORITIES_NOF (2)


#define DNX_DATA_MAX_INGR_REASSEMBLY_PRIORITY_MIRROR_PRIORITIES_NOF (2)


#define DNX_DATA_MAX_INGR_REASSEMBLY_PRIORITY_RCY_PRIORITIES_NOF (2)


#define DNX_DATA_MAX_INGR_REASSEMBLY_PRIORITY_PRIORITIES_NOF (2)


#define DNX_DATA_MAX_INGR_REASSEMBLY_PRIORITY_CGM_PRIORITIES_NOF (2)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_REASSEMBLY_CONTEXT_BITS (9)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_INTERFACE_BITS (8)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_INTERFACE_MAX (159)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_CONTEXT_MAP_BASE_ADDRESS_BITS (13)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_CONTEXT_MAP_BASE_ADDRESS_MAX (6143)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_CONTEXT_MAP_BASE_OFFEST_EXT_MAX (6146)


#define DNX_DATA_MAX_INGR_REASSEMBLY_DBAL_INTERLEAVED_INTERFACE_MAX (15)




#endif 

