

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ESB_H_

#define _DNX_DATA_MAX_ESB_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_ESB_QUEUES (154)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ETH_QUEUES (128)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ILKN_QUEUES (16)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_ILKN_TDM_QUEUES (4)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_FLEXE_QUEUES (82)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_SPECIAL_QUEUES (10)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_RESERVED_QUEUES (2)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_FPC (4)


#define DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_BUFFERS (4096)


#define DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_LEN (256)


#define DNX_DATA_MAX_ESB_GENERAL_ILKN_CREDITS_RESOLUTION (48)


#define DNX_DATA_MAX_ESB_GENERAL_ILKN_CREDITS_RATE_RESOLUTION (50000)


#define DNX_DATA_MAX_ESB_GENERAL_FPC_PTR_SIZE (10)


#define DNX_DATA_MAX_ESB_GENERAL_NOF_BUFFERS_PER_FPC (1024)


#define DNX_DATA_MAX_ESB_GENERAL_L1_MUX_CAL_RES (5000)


#define DNX_DATA_MAX_ESB_GENERAL_TM_EGR_QUEUING_MUX_CAL_RES (7500)


#define DNX_DATA_MAX_ESB_DBAL_PM_INTERNAL_PORT_SIZE (7)


#define DNX_DATA_MAX_ESB_DBAL_COUNTER_CONFIG_MASK_SIZE (8)




#endif 

