

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_PORT_H_

#define _DNX_DATA_MAX_PORT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_PORT_STATIC_ADD_DEFAULT_SPEED_FOR_SPECIAL_IF (10000)


#define DNX_DATA_MAX_PORT_GENERAL_ERP_TM_PORT (255)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_CHANNELS (256)


#define DNX_DATA_MAX_PORT_GENERAL_FABRIC_PHYS_OFFSET (144)


#define DNX_DATA_MAX_PORT_GENERAL_PP_DSP_SIZE (10)


#define DNX_DATA_MAX_PORT_GENERAL_INGRESS_VLAN_DOMAIN_SIZE (11)


#define DNX_DATA_MAX_PORT_GENERAL_VLAN_DOMAIN_SIZE (11)


#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_SIZE (21)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP (63)


#define DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_WIDTH_START_OFFSET (6)


#define DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_START_INPUT_OFFSET (12)


#define DNX_DATA_MAX_PORT_EGRESS_NOF_IFS (64)




#endif 

