

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_MPLS_H_

#define _DNX_DATA_MAX_MPLS_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_MPLS_GENERAL_NOF_MPLS_TERMINATION_PROFILES (8)


#define DNX_DATA_MAX_MPLS_GENERAL_NOF_MPLS_PUSH_PROFILES (7)


#define DNX_DATA_MAX_MPLS_GENERAL_NOF_BITS_MPLS_LABEL (20)


#define DNX_DATA_MAX_MPLS_GENERAL_LOG_NOF_MPLS_RANGE_ELEMENTS (3)


#define DNX_DATA_MAX_MPLS_GENERAL_NOF_MPLS_RANGE_ELEMENTS (8)


#define DNX_DATA_MAX_MPLS_GENERAL_MPLS_SPECIAL_LABEL_ENCAP_HANDLING (1)


#define DNX_DATA_MAX_MPLS_GENERAL_MPLS_CONTROL_WORD_SUPPORTED (1)


#define DNX_DATA_MAX_MPLS_GENERAL_MPLS_SECOND_STAGE_PARSER_HANDLING (0)


#define DNX_DATA_MAX_MPLS_GENERAL_MPLS_CONTROL_WORD_FLAG_BITS_LSB (24)


#define DNX_DATA_MAX_MPLS_GENERAL_FHEI_MPS_TYPE_NOF_BITS (7)


#define DNX_DATA_MAX_MPLS_GENERAL_MPLS_SPECULATIVE_LEARNING_HANDLING (0)




#endif 

