

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_INSTRU_H_

#define _DNX_DATA_MAX_INSTRU_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_INSTRU_IPT_PROFILE_SIZE (6)


#define DNX_DATA_MAX_INSTRU_IPT_METADATA_BITMAP_SIZE (10)


#define DNX_DATA_MAX_INSTRU_IPT_METADATA_EDIT_SIZE (6)


#define DNX_DATA_MAX_INSTRU_IPT_NODE_ID_PADDING_SIZE (5)


#define DNX_DATA_MAX_INSTRU_SFLOW_MAX_NOF_SFLOW_ENCAPS (16)


#define DNX_DATA_MAX_INSTRU_SFLOW_NOF_SFLOW_RAW_ENTRIES_PER_STACK (2)


#define DNX_DATA_MAX_INSTRU_IFA_INGRESS_TOD_FEATURE (1)


#define DNX_DATA_MAX_INSTRU_IFA_MAX_LENGHT_CHECK_FOR_IFA2 (1)


#define DNX_DATA_MAX_INSTRU_EVENTOR_RX_EVPCK_HEADER_SIZE (16)


#define DNX_DATA_MAX_INSTRU_EVENTOR_TX_BUILDER_MAX_HEADER_SIZE (124)


#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_CONTEXTS (16)


#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_CONTEXTS_BITS (4)


#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_BUILDERS (16)


#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_BUILDERS_BITS (4)


#define DNX_DATA_MAX_INSTRU_EVENTOR_NOF_SRAM_BANKS (8)


#define DNX_DATA_MAX_INSTRU_EVENTOR_SRAM_BANK_BITS (3)


#define DNX_DATA_MAX_INSTRU_EVENTOR_SRAM_BANKS_FULL_SIZE (16384)


#define DNX_DATA_MAX_INSTRU_EVENTOR_SRAM_BANKS_NET_SIZE (13312)


#define DNX_DATA_MAX_INSTRU_EVENTOR_BUILDER_MAX_BUFFER_SIZE (1600)


#define DNX_DATA_MAX_INSTRU_EVENTOR_RX_MAX_BUFFER_SIZE (1600)


#define DNX_DATA_MAX_INSTRU_EVENTOR_AXI_SRAM_OFFSET (3892314112)


#define DNX_DATA_MAX_INSTRU_EVENTOR_IS_EXTRA_WORDS_COPY (1)


#define DNX_DATA_MAX_INSTRU_SYNCED_COUNTERS_INTERVAL_PERIOD_SIZE_HW (64)


#define DNX_DATA_MAX_INSTRU_SYNCED_COUNTERS_MAX_INTERVAL_PERIOD_SIZE (48)


#define DNX_DATA_MAX_INSTRU_SYNCED_COUNTERS_MAX_NOF_INTERVALS (16)


#define DNX_DATA_MAX_INSTRU_SYNCED_COUNTERS_CGM_WRITE_COUNTER_WRAP_AROUND (1024)


#define DNX_DATA_MAX_INSTRU_SYNCED_COUNTERS_BYTES_IN_WORD (16)




#endif 

