

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_FIELD_H_

#define _DNX_DATA_MAX_FIELD_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FFC (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FFC_GROUPS (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_ONE_LOWER (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_ONE_UPPER (15)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_TWO_LOWER (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_TWO_UPPER (31)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_THREE_LOWER (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_THREE_UPPER (47)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_FOUR_LOWER (48)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FFC_GROUP_FOUR_UPPER (63)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEYS (10)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEYS_ALLOC (5)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEYS_ALLOC_FOR_TCAM (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEYS_ALLOC_FOR_EXEM (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEYS_ALLOC_FOR_MDB_DT (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_MASKS_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FES_ID_PER_ARRAY (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FES_ARRAY (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FES_INSTRUCTION_PER_CONTEXT (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FES_PROGRAMS (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_PROG_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_PROGRAM_SELECTION_CAM_MASK_NOF_BITS (95)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_CS_CONTAINER_5_SELECTED_BITS_SIZE (9)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_CONTEXTS (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_LINK_PROFILES (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_CS_LINES (128)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_ACTIONS (128)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_QUALIFIERS (128)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_80B_ZONES (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEY_ZONES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_KEY_ZONE_BITS (80)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FES_ACTION (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FES_KEY_SELECT (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FES_KEY_SELECTS_ON_ONE_ACTIONS_LINE (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FEM_CONDITION_MS_BIT_MIN_VALUE (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FEM_CONDITION_MS_BIT_MAX_VALUE (31)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_PROGRAMS (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_PROGRAMS (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_LOG_NOF_BITS_IN_FEM_KEY_SELECT (5)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_KEY_SELECT (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FEM_KEY_SELECT_RESOLUTION_IN_BITS (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_LOG_NOF_BITS_IN_FEM_MAP_DATA_FIELD (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_MAP_DATA_FIELD (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_ACTION_FEMS_2_15 (24)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_ACTION_FEMS_0_1 (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_ACTION (24)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_CONDITION (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_CONDITION (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_MAP_INDEX (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_MAP_INDEX (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_BITS_IN_FEM_ID (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_ID (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NUM_FEMS_WITH_SHORT_ACTION (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NUM_BITS_IN_FEM_FIELD_SELECT (6)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_ID_PER_ARRAY (8)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_ARRAY (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEMS_PER_CONTEXT (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_FEM_ACTION_OVERRIDING_BITS (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_DEFAULT_STRENGTH (5)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_COMPARE_PAIRS_IN_COMPARE_MODE (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_COMPARE_KEYS_IN_COMPARE_MODE (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_COMPARE_KEY_SIZE (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_L4_OPS_RANGES_LEGACY (24)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_EXT_L4_OPS_RANGES (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_PKT_HDR_RANGES (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_NOF_OUT_LIF_RANGES (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FES_KEY_SELECT_FOR_ZERO_BIT (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FES_SHIFT_FOR_ZERO_BIT (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_USES_SMALL_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_USES_LARGE_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_CMP_SELECTION (15)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FES_INSTRUCTION_SIZE (11)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_FES_PGM_ID_OFFSET (6)


#define DNX_DATA_MAX_FIELD_BASE_IPMF1_DIR_EXT_SINGLE_KEY_SIZE (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_FFC (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_FFC_GROUPS (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_FFC_GROUP_ONE_LOWER (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_FFC_GROUP_ONE_UPPER (31)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEYS (5)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEYS_ALLOC (5)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEYS_ALLOC_FOR_TCAM (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEYS_ALLOC_FOR_EXEM (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEYS_ALLOC_FOR_DIR_EXT (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEYS_ALLOC_FOR_MDB_DT (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_MASKS_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_FES_ID_PER_ARRAY (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_FES_ARRAY (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_FES_INSTRUCTION_PER_CONTEXT (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_CS_LINES (128)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_CONTEXTS (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_PROGRAM_SELECTION_CAM_MASK_NOF_BITS (95)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_QUALIFIERS (128)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_80B_ZONES (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEY_ZONES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_NOF_KEY_ZONE_BITS (80)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_FES_KEY_SELECT_FOR_ZERO_BIT (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_FES_SHIFT_FOR_ZERO_BIT (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_USES_SMALL_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_USES_LARGE_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF2_DIR_EXT_SINGLE_KEY_SIZE (160)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FFC (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FFC_GROUPS (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_FFC_GROUP_ONE_LOWER (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_FFC_GROUP_ONE_UPPER (31)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEYS (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEYS_ALLOC (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEYS_ALLOC_FOR_TCAM (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEYS_ALLOC_FOR_EXEM (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEYS_ALLOC_FOR_DIR_EXT (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEYS_ALLOC_FOR_MDB_DT (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_MASKS_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FES_ID_PER_ARRAY (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FES_ARRAY (1)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FES_INSTRUCTION_PER_CONTEXT (16)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FES_PROGRAMS (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_PROG_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_PROGRAM_SELECTION_CAM_MASK_NOF_BITS (95)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_CS_SCRATCH_PAD_SIZE (33)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_CONTEXTS (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_CS_LINES (128)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_ACTIONS (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_QUALIFIERS (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_80B_ZONES (2)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEY_ZONES (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_KEY_ZONE_BITS (80)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_BITS_IN_FES_ACTION (32)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_BITS_IN_FES_KEY_SELECT (64)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_FES_KEY_SELECTS_ON_ONE_ACTIONS_LINE (3)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_DEFAULT_STRENGTH (6)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_NOF_OUT_LIF_RANGES (7)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_FES_KEY_SELECT_FOR_ZERO_BIT (4)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_FES_SHIFT_FOR_ZERO_BIT (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_USES_SMALL_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_USES_LARGE_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_FES_INSTRUCTION_SIZE (10)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_FES_PGM_ID_OFFSET (5)


#define DNX_DATA_MAX_FIELD_BASE_IPMF3_DIR_EXT_SINGLE_KEY_SIZE (160)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FFC (20)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FFC_GROUPS (1)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_FFC_GROUP_ONE_LOWER (0)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_FFC_GROUP_ONE_UPPER (19)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEYS (4)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEYS_ALLOC (4)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEYS_ALLOC_FOR_TCAM (2)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEYS_ALLOC_FOR_EXEM (1)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEYS_ALLOC_FOR_DIR_EXT (1)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_MASKS_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FES_ID_PER_ARRAY (12)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FES_ARRAY (1)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FES_INSTRUCTION_PER_CONTEXT (12)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FES_PROGRAMS (32)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_PROG_PER_FES (4)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_PROGRAM_SELECTION_CAM_MASK_NOF_BITS (37)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_CS_LINES (128)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_CONTEXTS (64)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_ACTIONS (64)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_QUALIFIERS (64)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_80B_ZONES (2)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEY_ZONES (4)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_KEY_ZONE_BITS (80)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_BITS_IN_FES_ACTION (32)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_BITS_IN_FES_KEY_SELECT (64)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_FES_KEY_SELECTS_ON_ONE_ACTIONS_LINE (1)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_NOF_L4_OPS_RANGES_LEGACY (24)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_FES_KEY_SELECT_FOR_ZERO_BIT (0)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_FES_SHIFT_FOR_ZERO_BIT (60)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_USES_SMALL_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_USES_LARGE_EXEM (0)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_FES_INSTRUCTION_SIZE (9)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_FES_PGM_ID_OFFSET (4)


#define DNX_DATA_MAX_FIELD_BASE_EPMF_DIR_EXT_SINGLE_KEY_SIZE (32)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_NOF_FFC (38)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_NOF_FFC_GROUPS (1)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_FFC_GROUP_ONE_LOWER (0)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_FFC_GROUP_ONE_UPPER (37)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_NOF_KEYS (2)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_NOF_CONTEXTS (64)


#define DNX_DATA_MAX_FIELD_BASE_IFWD2_NOF_CS_LINES (128)


#define DNX_DATA_MAX_FIELD_KBP_NOF_FGS  (32)


#define DNX_DATA_MAX_FIELD_KBP_MAX_SINGLE_KEY_SIZE (160)


#define DNX_DATA_MAX_FIELD_KBP_NOF_ACL_KEYS_MASTER_MAX (3)


#define DNX_DATA_MAX_FIELD_KBP_NOF_ACL_KEYS_FG_MAX (3)


#define DNX_DATA_MAX_FIELD_KBP_MIN_ACL_NOF_FFC (8)


#define DNX_DATA_MAX_FIELD_KBP_MAX_FWD_CONTEXT_NUM_FOR_ONE_APPTYPE (5)


#define DNX_DATA_MAX_FIELD_KBP_MAX_ACL_CONTEXT_NUM (64)


#define DNX_DATA_MAX_FIELD_KBP_SIZE_APPTYPE_PROFILE_ID (6)


#define DNX_DATA_MAX_FIELD_KBP_KEY_BMP  (196656)


#define DNX_DATA_MAX_FIELD_KBP_APPTYPE_USER_1ST (128)


#define DNX_DATA_MAX_FIELD_KBP_APPTYPE_USER_NOF (16)


#define DNX_DATA_MAX_FIELD_KBP_MAX_PAYLOAD_SIZE_PER_OPCODE (248)


#define DNX_DATA_MAX_FIELD_TCAM_KEY_SIZE_HALF (80)


#define DNX_DATA_MAX_FIELD_TCAM_KEY_SIZE_SINGLE (160)


#define DNX_DATA_MAX_FIELD_TCAM_KEY_SIZE_DOUBLE (320)


#define DNX_DATA_MAX_FIELD_TCAM_DT_MAX_KEY_SIZE (11)


#define DNX_DATA_MAX_FIELD_TCAM_ACTION_SIZE_HALF (32)


#define DNX_DATA_MAX_FIELD_TCAM_ACTION_SIZE_SINGLE (64)


#define DNX_DATA_MAX_FIELD_TCAM_ACTION_SIZE_DOUBLE (128)


#define DNX_DATA_MAX_FIELD_TCAM_KEY_MODE_SIZE (2)


#define DNX_DATA_MAX_FIELD_TCAM_ENTRY_SIZE_SINGLE_KEY_HW (164)


#define DNX_DATA_MAX_FIELD_TCAM_ENTRY_SIZE_SINGLE_VALID_BITS_HW (2)


#define DNX_DATA_MAX_FIELD_TCAM_ENTRY_SIZE_HALF_PAYLOAD_HW (32)


#define DNX_DATA_MAX_FIELD_TCAM_HW_BANK_SIZE (4096)


#define DNX_DATA_MAX_FIELD_TCAM_SMALL_BANK_SIZE (256)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_BIG_BANK_LINES (4096)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_SMALL_BANK_LINES (512)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_BIG_BANKS (12)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_SMALL_BANKS (4)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_BANKS (16)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_PAYLOAD_TABLES (32)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_ACCESS_PROFILES (64)


#define DNX_DATA_MAX_FIELD_TCAM_ACTION_WIDTH_SELECTOR_SIZE (2)


#define DNX_DATA_MAX_FIELD_TCAM_CASCADED_DATA_NOF_BITS (20)


#define DNX_DATA_MAX_FIELD_TCAM_BIG_BANK_KEY_NOF_BITS (11)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_ENTRIES_160_BITS (25600)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_ENTRIES_80_BITS (51200)


#define DNX_DATA_MAX_FIELD_TCAM_TCAM_BANKS_SIZE (65536)


#define DNX_DATA_MAX_FIELD_TCAM_TCAM_BANKS_LAST_INDEX (61952)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_TCAM_HANDLERS (64)


#define DNX_DATA_MAX_FIELD_TCAM_MAX_PREFIX_SIZE (5)


#define DNX_DATA_MAX_FIELD_TCAM_MAX_PREFIX_VALUE (32)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_KEYS_IN_DOUBLE_KEY (2)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_KEYS_MAX (2)


#define DNX_DATA_MAX_FIELD_TCAM_ACCESS_PROFILE_HALF_KEY_MODE (0)


#define DNX_DATA_MAX_FIELD_TCAM_ACCESS_PROFILE_SINGLE_KEY_MODE (1)


#define DNX_DATA_MAX_FIELD_TCAM_ACCESS_PROFILE_DOUBLE_KEY_MODE (3)


#define DNX_DATA_MAX_FIELD_TCAM_TCAM_ENTRIES_PER_HIT_INDICATION_ENTRY (8)


#define DNX_DATA_MAX_FIELD_TCAM_MAX_TCAM_PRIORITY (2147483647)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_BIG_BANKS_SRAMS (24)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_SMALL_BANKS_SRAMS (8)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_BIG_BANK_LINES_PER_SRAM (256)


#define DNX_DATA_MAX_FIELD_TCAM_NOF_SMALL_BANK_LINES_PER_SRAM (32)


#define DNX_DATA_MAX_FIELD_TCAM_APP_DB_ID_SIZE (6)


#define DNX_DATA_MAX_FIELD_GROUP_NOF_FGS (128)


#define DNX_DATA_MAX_FIELD_GROUP_NOF_ACTION_PER_FG (32)


#define DNX_DATA_MAX_FIELD_GROUP_NOF_QUALS_PER_FG (32)


#define DNX_DATA_MAX_FIELD_GROUP_NOF_KEYS_PER_FG_MAX (3)


#define DNX_DATA_MAX_FIELD_GROUP_ID_FEC (127)


#define DNX_DATA_MAX_FIELD_GROUP_PAYLOAD_MAX_SIZE (320)


#define DNX_DATA_MAX_FIELD_EFES_MAX_NOF_KEY_SELECTS_PER_FIELD_IO (11)


#define DNX_DATA_MAX_FIELD_FEM_MAX_NOF_KEY_SELECTS_PER_FIELD_IO (21)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_CONTEXT (0)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_ITMH_CONTEXT (63)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_ITMH_PPH_CONTEXT (62)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_J1_ITMH_CONTEXT (58)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_J1_ITMH_PPH_CONTEXT (57)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_STACKING_CONTEXT (61)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_OAM_CONTEXT (60)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_OAM_REFLECTOR_CONTEXT (59)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_OAM_UPMEP_CONTEXT (54)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_J1_LEARNING_2NDPASS_CONTEXT (56)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_RCH_REMOVE_CONTEXT (55)


#define DNX_DATA_MAX_FIELD_CONTEXT_DEFAULT_NAT_CONTEXT (53)


#define DNX_DATA_MAX_FIELD_CONTEXT_NOF_HASH_KEYS (6)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_PRESEL_ID_IPMF1 (1)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_ITMH_PRESEL_ID_IPMF1 (126)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_ITMH_PPH_PRESEL_ID_IPMF1 (125)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_ITMH_PPH_OAMP_PRESEL_ID_IPMF1 (122)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_ITMH_PRESEL_ID_IPMF1 (124)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_ITMH_PPH_PRESEL_ID_IPMF1 (123)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_ITMH_PPH_OAMP_PRESEL_ID_IPMF1 (121)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_STACKING_PRESEL_ID_IPMF1 (120)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_LEARN_PRESEL_ID_1ST_PASS_IPMF1 (3)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_LEARN_PRESEL_ID_2ND_PASS_IPMF1 (4)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_NAT_PRESEL_ID_IPMF1 (119)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_ITMH_PPH_PRESEL_ID_IPMF3 (126)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_ITMH_PPH_PRESEL_ID_IPMF3 (117)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_ROO_IPV4_PRESEL_ID_IPMF3 (125)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_ROO_IPV6_PRESEL_ID_IPMF3 (124)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_W_O_ROO_NO_RIF_IPV4_PRESEL_ID_IPMF3 (123)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_W_O_ROO_NO_RIF_IPV6_PRESEL_ID_IPMF3 (122)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_W_O_ROO_WITH_RIF_IPV4_PRESEL_ID_IPMF3 (121)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_OAM_W_O_ROO_WITH_RIF_IPV6_PRESEL_ID_IPMF3 (120)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_IPV4_MC_IN_LIF_PRESEL_ID_IPMF3 (119)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_IPV6_MC_IN_LIF_PRESEL_ID_IPMF3 (118)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_RCH_REMOVE_PRESEL_ID_IPMF3 (114)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_PHP_PRESEL_ID_IPMF3 (115)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_SWAP_PRESEL_ID_IPMF3 (116)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_J1_SAME_PORT_PRESEL_ID_EPMF (2)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_DEFAULT_LEARN_LIMIT_PRESEL_ID_EPMF (1)


#define DNX_DATA_MAX_FIELD_PRESELECTOR_NUM_CS_INLIF_PROFILE_ENTRIES (256)


#define DNX_DATA_MAX_FIELD_QUAL_USER_1ST (2048)


#define DNX_DATA_MAX_FIELD_QUAL_USER_NOF (256)


#define DNX_DATA_MAX_FIELD_QUAL_VW_1ST  (8292)


#define DNX_DATA_MAX_FIELD_QUAL_VW_NOF  (100)


#define DNX_DATA_MAX_FIELD_QUAL_MAX_BITS_IN_QUAL (160)


#define DNX_DATA_MAX_FIELD_QUAL_INGRESS_PBUS_HEADER_LENGTH (1152)


#define DNX_DATA_MAX_FIELD_QUAL_EGRESS_PBUS_HEADER_LENGTH (1024)


#define DNX_DATA_MAX_FIELD_QUAL_IFWD2_PBUS_SIZE (3239)


#define DNX_DATA_MAX_FIELD_QUAL_IPMF1_PBUS_SIZE (3391)


#define DNX_DATA_MAX_FIELD_QUAL_IPMF2_PBUS_SIZE (1384)


#define DNX_DATA_MAX_FIELD_QUAL_IPMF3_PBUS_SIZE (1849)


#define DNX_DATA_MAX_FIELD_QUAL_EPMF_PBUS_SIZE (2573)


#define DNX_DATA_MAX_FIELD_QUAL_INGRESS_NOF_LAYER_RECORDS (8)


#define DNX_DATA_MAX_FIELD_QUAL_INGRESS_LAYER_RECORD_SIZE (32)


#define DNX_DATA_MAX_FIELD_QUAL_EGRESS_NOF_LAYER_RECORDS (5)


#define DNX_DATA_MAX_FIELD_QUAL_EGRESS_LAYER_RECORD_SIZE (30)


#define DNX_DATA_MAX_FIELD_QUAL_AC_LIF_WIDE_SIZE (28)


#define DNX_DATA_MAX_FIELD_ACTION_USER_1ST (2048)


#define DNX_DATA_MAX_FIELD_ACTION_USER_NOF (256)


#define DNX_DATA_MAX_FIELD_ACTION_VW_1ST (8292)


#define DNX_DATA_MAX_FIELD_ACTION_VW_NOF (100)


#define DNX_DATA_MAX_FIELD_VIRTUAL_WIRE_SIGNALS_NOF (128)


#define DNX_DATA_MAX_FIELD_VIRTUAL_WIRE_ACTIONS_PER_SIGNAL_NOF (10)


#define DNX_DATA_MAX_FIELD_VIRTUAL_WIRE_GENERAL_DATA_USER_GENERAL_CONTAINERS_SIZE (384)


#define DNX_DATA_MAX_FIELD_VIRTUAL_WIRE_IPMF1_GENERAL_DATA_INDEX (4)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_NOF_ING_IN_LIF (2)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_NOF_EG_IN_LIF (2)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_NOF_ING_ETH_RIF (2)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_NOF_EG_ETH_RIF (2)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_INGRESS_PP_PORT_KEY_GEN_VAR_SIZE (64)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_MAX_PORT_PROFILE_SIZE (64)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_NOF_BITS_IN_PORT_PROFILE (24)


#define DNX_DATA_MAX_FIELD_PROFILE_BITS_NOF_BITS_IN_INGRESS_PP_PORT_GENERAL_DATA (40)


#define DNX_DATA_MAX_FIELD_DIR_EXT_HALF_KEY_SIZE (80)


#define DNX_DATA_MAX_FIELD_DIR_EXT_SINGLE_KEY_SIZE (160)


#define DNX_DATA_MAX_FIELD_DIR_EXT_DOUBLE_KEY_SIZE (320)


#define DNX_DATA_MAX_FIELD_STATE_TABLE_ADDRESS_SIZE_ENTRY_MAX (13)


#define DNX_DATA_MAX_FIELD_STATE_TABLE_DATA_SIZE_ENTRY_MAX (8)


#define DNX_DATA_MAX_FIELD_STATE_TABLE_ADDRESS_MAX_ENTRY_MAX (8191)


#define DNX_DATA_MAX_FIELD_STATE_TABLE_WR_BIT_SIZE_RW (1)


#define DNX_DATA_MAX_FIELD_STATE_TABLE_OPCODE_SIZE_RMW (5)


#define DNX_DATA_MAX_FIELD_MAP_KEY_SIZE (20)


#define DNX_DATA_MAX_FIELD_MAP_ACTION_SIZE_SMALL (30)


#define DNX_DATA_MAX_FIELD_MAP_ACTION_SIZE_MID (60)


#define DNX_DATA_MAX_FIELD_MAP_ACTION_SIZE_LARGE (120)


#define DNX_DATA_MAX_FIELD_MAP_IPMF1_KEY_SELECT (2)


#define DNX_DATA_MAX_FIELD_MAP_IPMF2_KEY_SELECT (2)


#define DNX_DATA_MAX_FIELD_MAP_IPMF3_KEY_SELECT (2)


#define DNX_DATA_MAX_FIELD_HASH_MAX_KEY_SIZE (320)


#define DNX_DATA_MAX_FIELD_UDH_TYPE_COUNT (4)


#define DNX_DATA_MAX_FIELD_UDH_TYPE_0_LENGTH (0)


#define DNX_DATA_MAX_FIELD_UDH_TYPE_1_LENGTH (4)


#define DNX_DATA_MAX_FIELD_UDH_TYPE_2_LENGTH (4)


#define DNX_DATA_MAX_FIELD_UDH_TYPE_3_LENGTH (4)


#define DNX_DATA_MAX_FIELD_SYSTEM_HEADERS_NOF_PROFILES (16)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_APP_DB_ID_SIZE (6)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_APP_DB_ID_SIZE (6)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_MAX_KEY_SIZE (80)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_MAX_KEY_SIZE (160)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_MAX_RESULT_SIZE (60)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_MAX_RESULT_SIZE (60)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_MAX_CONTAINER_SIZE (120)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_MAX_CONTAINER_SIZE (240)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_KEY_HASH_SIZE (13)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_KEY_HASH_SIZE (13)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_MIN_APP_DB_ID_RANGE (48)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_MIN_APP_DB_ID_RANGE (48)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_MAX_APP_DB_ID_RANGE (63)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_MAX_APP_DB_ID_RANGE (63)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_IPMF2_KEY (4)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_IPMF2_KEY_PART (0)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_IPMF2_KEY_HW_VALUE (4)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_IPMF2_KEY_HW_BITS (3)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_IPMF1_KEY_CONFIGURABLE (1)


#define DNX_DATA_MAX_FIELD_EXEM_LARGE_IPMF1_KEY (4)


#define DNX_DATA_MAX_FIELD_EXEM_SMALL_NOF_FLUSH_PROFILES (8)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_FLUSH_MACHINE_NOF_ENTRIES (4)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_ENTRY_EXTRA_BITS_FOR_HASH (17)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_SEXEM_ENTRY_MAX_SIZE (137)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_LEXEM_ENTRY_MAX_SIZE (257)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_COMMAND_BIT_TRANSPLANT (0)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_COMMAND_BIT_DELETE (1)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_COMMAND_BIT_CLEAR_HIT_BIT (3)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_NOF_BITS_SOURCE (3)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_SOURCE_BIT_FOR_SCAN (0)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_SOURCE_BIT_FOR_PIPE (1)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_SOURCE_BIT_FOR_MRQ (2)


#define DNX_DATA_MAX_FIELD_EXEM_LEARN_FLUSH_MACHINE_NOF_BITS_ACCESSED (1)


#define DNX_DATA_MAX_FIELD_ACE_ACE_ID_SIZE (6)


#define DNX_DATA_MAX_FIELD_ACE_KEY_SIZE (22)


#define DNX_DATA_MAX_FIELD_ACE_KEY_HASH_SIZE (17)


#define DNX_DATA_MAX_FIELD_ACE_APP_DB_ID_SIZE (0)


#define DNX_DATA_MAX_FIELD_ACE_PAYLOAD_SIZE (110)


#define DNX_DATA_MAX_FIELD_ACE_MIN_KEY_RANGE_PMF (3932160)


#define DNX_DATA_MAX_FIELD_ACE_MAX_KEY_RANGE_PMF (4194303)


#define DNX_DATA_MAX_FIELD_ACE_MIN_ACE_ID_DYNAMIC_RANGE (1)


#define DNX_DATA_MAX_FIELD_ACE_NOF_ACE_ID (64)


#define DNX_DATA_MAX_FIELD_ACE_NOF_ACTION_PER_ACE_FORMAT (8)


#define DNX_DATA_MAX_FIELD_ACE_ROW_SIZE (120)


#define DNX_DATA_MAX_FIELD_ACE_MIN_ENTRY_SIZE (30)


#define DNX_DATA_MAX_FIELD_ACE_ACE_ID_PMF_ALLOC_FIRST (48)


#define DNX_DATA_MAX_FIELD_ACE_ACE_ID_PMF_ALLOC_LAST (63)


#define DNX_DATA_MAX_FIELD_ACE_NOF_MASKS_PER_FES (2)


#define DNX_DATA_MAX_FIELD_ACE_NOF_FES_ID_PER_ARRAY (8)


#define DNX_DATA_MAX_FIELD_ACE_NOF_FES_ARRAY (1)


#define DNX_DATA_MAX_FIELD_ACE_NOF_FES_INSTRUCTION_PER_CONTEXT (8)


#define DNX_DATA_MAX_FIELD_ACE_NOF_FES_PROGRAMS (64)


#define DNX_DATA_MAX_FIELD_ACE_NOF_PROG_PER_FES (1)


#define DNX_DATA_MAX_FIELD_ACE_NOF_BITS_IN_FES_ACTION (32)


#define DNX_DATA_MAX_FIELD_ACE_FES_SHIFT_FOR_ZERO_BIT (110)


#define DNX_DATA_MAX_FIELD_ACE_FES_INSTRUCTION_SIZE (21)


#define DNX_DATA_MAX_FIELD_ACE_FES_SHIFT_OFFSET (1)


#define DNX_DATA_MAX_FIELD_ACE_FES_INVALID_BITS_OFFSET (8)


#define DNX_DATA_MAX_FIELD_ACE_FES_TYPE_OFFSET (13)


#define DNX_DATA_MAX_FIELD_ACE_FES_ACE_ACTION_OFFSET (14)


#define DNX_DATA_MAX_FIELD_ACE_FES_CHOSEN_MASK_OFFSET (20)


#define DNX_DATA_MAX_FIELD_ENTRY_DIR_EXT_NOF_FIELDS (6)


#define DNX_DATA_MAX_FIELD_ENTRY_NOF_ACTION_PARAMS_PER_ENTRY (4)


#define DNX_DATA_MAX_FIELD_ENTRY_NOF_QUAL_PARAMS_PER_ENTRY (5)


#define DNX_DATA_MAX_FIELD_L4_OPS_UDP_POSITION (9)


#define DNX_DATA_MAX_FIELD_L4_OPS_TCP_POSITION (8)


#define DNX_DATA_MAX_FIELD_L4_OPS_NOF_RANGE_ENTRIES (32)


#define DNX_DATA_MAX_FIELD_L4_OPS_NOF_EXT_ENCODERS (4)


#define DNX_DATA_MAX_FIELD_L4_OPS_NOF_EXT_TYPES (4)


#define DNX_DATA_MAX_FIELD_L4_OPS_NOF_CONFIGURABLE_RANGES (2)


#define DNX_DATA_MAX_FIELD_ENCODED_QUAL_ACTIONS_OFFSET_TRAP_STRENGTH_OFFSET (9)


#define DNX_DATA_MAX_FIELD_ENCODED_QUAL_ACTIONS_OFFSET_TRAP_QUALIFIER_OFFSET (13)


#define DNX_DATA_MAX_FIELD_ENCODED_QUAL_ACTIONS_OFFSET_SNIFF_QUALIFIER_OFFSET (12)


#define DNX_DATA_MAX_FIELD_ENCODED_QUAL_ACTIONS_OFFSET_MIRROR_QUALIFIER_OFFSET (9)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_EQUAL (4)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_NOT_EQUAL (0)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_SMALLER (2)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_NOT_SMALLER (3)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_BIGGER (5)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_NOT_BIGGER (1)


#define DNX_DATA_MAX_FIELD_COMPARE_OPERAND_NOF_OPERANDS (6)


#define DNX_DATA_MAX_FIELD_DIAG_BYTES_TO_REMOVE_MASK (15)


#define DNX_DATA_MAX_FIELD_DIAG_LAYERS_TO_REMOVE_SIZE_IN_BIT (3)


#define DNX_DATA_MAX_FIELD_DIAG_LAYERS_TO_REMOVE_MASK (7)


#define DNX_DATA_MAX_FIELD_DIAG_NOF_SIGNALS_PER_ACTION (10)


#define DNX_DATA_MAX_FIELD_DIAG_NOF_SIGNALS_PER_QUALIFIER (10)


#define DNX_DATA_MAX_FIELD_DIAG_KEY_SIGNAL_SIZE_IN_WORDS (5)


#define DNX_DATA_MAX_FIELD_DIAG_RESULT_SIGNAL_SIZE_IN_WORDS (2)


#define DNX_DATA_MAX_FIELD_DIAG_DT_RESULT_SIGNAL_SIZE_IN_WORDS (4)


#define DNX_DATA_MAX_FIELD_DIAG_HIT_SIGNAL_SIZE_IN_WORDS (1)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FFC (64)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_KEYS (10)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_MASKS_PER_FES (4)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FES_ID_PER_ARRAY (16)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FES_ARRAY (2)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FES_INSTRUCTION_PER_CONTEXT (32)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FES_PROGRAMS (32)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_PROG_PER_FES (4)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_PROGRAM_SELECTION_LINES (128)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_PROGRAM_SELECTION_CAM_MASK_NOF_BITS (95)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_CS_LINES (128)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_CONTEXTS (64)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_ACTIONS (128)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_QUALIFIERS (128)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_80B_ZONES (2)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_KEY_ZONES (4)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_KEY_ZONE_BITS (80)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_BITS_IN_FES_ACTION (32)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_BITS_IN_FES_KEY_SELECT (64)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FES_KEY_SELECTS_ON_ONE_ACTIONS_LINE (3)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FFC_IN_QUAL (6)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_BITS_IN_FFC (32)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FFC_IN_UINT32 (2)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_ACTION_PER_GROUP (32)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_LAYER_RECORDS (8)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_LAYER_RECORD_SIZE (32)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_L4_OPS_RANGES_LEGACY (24)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_PKT_HDR_RANGES (3)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_OUT_LIF_RANGES (7)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_KBR_SIZE (160)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_COMPARE_PAIRS (2)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_COMPARE_PAIRS_IN_COMPARE_MODE (2)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_COMPARE_KEYS_IN_COMPARE_MODE (2)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_BITS_IN_FEM_ACTION (24)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FEM_CONDITION (16)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FEM_MAP_INDEX (4)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_FEM_ID (16)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_NOF_ARRAY_IDS (4)


#define DNX_DATA_MAX_FIELD_COMMON_MAX_VAL_DBAL_PAIRS (10)


#define DNX_DATA_MAX_FIELD_INIT_FEC_DEST (1)


#define DNX_DATA_MAX_FIELD_INIT_L4_TRAP (1)


#define DNX_DATA_MAX_FIELD_INIT_OAM_LAYER_INDEX (1)


#define DNX_DATA_MAX_FIELD_INIT_OAM_STAT (1)


#define DNX_DATA_MAX_FIELD_INIT_FLOW_ID (1)


#define DNX_DATA_MAX_FIELD_INIT_ROO     (1)


#define DNX_DATA_MAX_FIELD_INIT_JR1_IPMC_INLIF (1)


#define DNX_DATA_MAX_FIELD_INIT_J1_SAME_PORT (1)


#define DNX_DATA_MAX_FIELD_INIT_J1_LEARNING (1)


#define DNX_DATA_MAX_FIELD_INIT_LEARN_LIMIT (1)


#define DNX_DATA_MAX_FIELD_INIT_J1_PHP  (1)


#define DNX_DATA_MAX_FIELD_FEATURES_ECC_ENABLE (1)


#define DNX_DATA_MAX_FIELD_FEATURES_SWITCH_TO_ACL_CONTEXT (1)


#define DNX_DATA_MAX_FIELD_FEATURES_PER_PP_PORT_PMF_PROFILE_CS_OFFSET (83)


#define DNX_DATA_MAX_FIELD_FEATURES_TCAM_RESULT_FLIP_ECO (1)


#define DNX_DATA_MAX_FIELD_FEATURES_TCAM_RESULT_HALF_PAYLOAD_ON_MSB (1)


#define DNX_DATA_MAX_FIELD_FEATURES_PARSING_START_OFFSET_MSB_MEANINGLESS (1)


#define DNX_DATA_MAX_FIELD_FEATURES_KBP_OPCODE_IN_IPMF1_CS (1)


#define DNX_DATA_MAX_FIELD_FEATURES_KBP_HITBITS_CORRECT_IN_IPMF1_CS (1)


#define DNX_DATA_MAX_FIELD_FEATURES_EXEM_VMV_REMOVABLE_FROM_PAYLOAD (1)


#define DNX_DATA_MAX_FIELD_FEATURES_MULTIPLE_DYNAMIC_MEM_ENABLERS (1)


#define DNX_DATA_MAX_FIELD_FEATURES_AACL_SUPER_GROUP_HANDLER_ENABLE (1)


#define DNX_DATA_MAX_FIELD_FEATURES_AACL_TCAM_SWAP_ENABLE (1)


#define DNX_DATA_MAX_FIELD_FEATURES_EXTENDED_L4_OPS (1)


#define DNX_DATA_MAX_FIELD_FEATURES_STATE_TABLE_IPMF1_KEY_SELECT (1)


#define DNX_DATA_MAX_FIELD_FEATURES_STATE_TABLE_ACR_BUS (1)


#define DNX_DATA_MAX_FIELD_FEATURES_STATE_TABLE_ATOMIC_RMW (1)


#define DNX_DATA_MAX_FIELD_FEATURES_HITBIT_VOLATILE (1)


#define DNX_DATA_MAX_FIELD_FEATURES_FEM_REPLACE_MSB_INSTEAD_LSB (1)


#define DNX_DATA_MAX_FIELD_FEATURES_NO_PARSER_RESOURCES (1)


#define DNX_DATA_MAX_FIELD_FEATURES_DIR_EXT_EPMF (1)


#define DNX_DATA_MAX_FIELD_FEATURES_HASHING_PROCESS_LSB_TO_MSB (1)


#define DNX_DATA_MAX_FIELD_FEATURES_EXEM_AGE_FLUSH_SCAN (1)

#define DNX_DATA_MAX_FIELD_SIGNAL_SIZES_DUAL_QUEUE_SIZE (4)

#define DNX_DATA_MAX_FIELD_SIGNAL_SIZES_PACKET_HEADER_SIZE (8)

#define DNX_DATA_MAX_FIELD_SIGNAL_SIZES_ECN (3)


#define DNX_DATA_MAX_FIELD_SIGNAL_SIZES_CONGESTION_INFO (3)

#define DNX_DATA_MAX_FIELD_SIGNAL_SIZES_PARSING_START_OFFSET_SIZE (9)


#define DNX_DATA_MAX_FIELD_DNX_DATA_INTERNAL_LR_ETH_IS_DA_MAC_VALID (1)

#define DNX_DATA_MAX_FIELD_TESTS_LEARN_INFO_ACTIONS_STRUCTURE_CHANGE (1)

#define DNX_DATA_MAX_FIELD_TESTS_INGRESS_TIME_STAMP_INCREASED (1)

#define DNX_DATA_MAX_FIELD_TESTS_ACE_DEBUG_SIGNALS_EXIST (1)




#endif 

