# $Id: Makefile 2016/07/02 10:55:00 msivaram Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw/techsupport/vfp

include ${SDK}/make/Make.config

lib = libtsvfp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
