# $Id:  Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id: Makefile,v 1.3 2011/08/21 07:21:28 bhanup Exp $
# Makefile for Trident2plus SOC driver Library
#

LOCALDIR = src/soc/esw/trident2p

include ${SDK}/make/Make.config

lib = libsoc_trident2p

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

