#
# $Id: Makefile,v 1.4 2016/11/17 10:43:54 royv Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/mpls_l2vpn

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxmpls_l2vpn

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
