/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:    tomahawk_phy.c
 * Purpose: Maintains all the debug information for phy
 *          feature for Tomahawk.
*/

#include <appl/diag/techsupport.h>
#include <soc/mcm/allenum.h>

extern char * techsupport_phy_diag_cmdlist[];
extern char * techsupport_phy_sw_dump_cmdlist[];

/* "phy" feature's diag command list valid only for Tomahawk */
char * techsupport_phy_tomahawk_diag_cmdlist[] = {
     "phy ce",
     "phy xe",
     "phy diag xe AN",
     "phy diag ce AN",
     "phy diag xe dsc debug u=0 if=line",
     "phy diag ce dsc debug u=0 if=line",
     "phy diag xe dsc debug u=1 if=sys",
     "phy diag ce dsc debug u=1 if=sys",
     "phy diag xe eyescan u=0 if=line",
     "phy diag xe eyescan u=1 if=sys",
     "phy diag ce eyescan u=0 if=line",
     "phy diag ce eyescan u=1 if=sys",
     NULL /* Must be the last element in this structure */
};

#ifndef BCM_SW_STATE_DUMP_DISABLE
/* "phy" feature's software dump command list valid only for Tomahawk */
char * techsupport_phy_tomahawk_sw_dump_cmdlist[] = {
    NULL /* Must be the last element in this structure */
};
#endif /* BCM_SW_STATE_DUMP_DISABLE */


/* Structure that maintains memory list for
 * "phy" feature for Tomahawk chipset. */
static soc_mem_t techsupport_phy_tomahawk_memory_table_list[] = {
   PORT_TABm,
   MAC_BLOCKm,
   VLAN_MACm,
   LINK_STATUSm,
   PORT_COS_MAPm,
   COS_MAP_SELm,
   CPU_COS_MAPm,
   THDI_PORT_PG_CNTRS_RT1m,
   THDI_PORT_PG_CNTRS_RT2m,
   THDI_PORT_PG_CONFIGm,
   THDI_PORT_SP_CNTRS_RTm,
   THDI_PORT_SP_CONFIGm,
   MMU_CTR_MC_DROP_MEM_XPE0_PIPE0m,
   MMU_CTR_MC_DROP_MEM_XPE0_PIPE1m,
   MMU_CTR_MC_DROP_MEM_XPE1_PIPE2m,
   MMU_CTR_MC_DROP_MEM_XPE1_PIPE3m,
   MMU_CTR_MC_DROP_MEM_XPE2_PIPE0m,
   MMU_CTR_MC_DROP_MEM_XPE2_PIPE1m,
   MMU_CTR_MC_DROP_MEM_XPE3_PIPE2m,
   MMU_CTR_MC_DROP_MEM_XPE3_PIPE3m,
   MMU_CTR_UC_DROP_MEM_XPE0_PIPE0m,
   MMU_CTR_UC_DROP_MEM_XPE0_PIPE1m,
   MMU_CTR_UC_DROP_MEM_XPE1_PIPE2m,
   MMU_CTR_UC_DROP_MEM_XPE1_PIPE3m,
   MMU_CTR_UC_DROP_MEM_XPE2_PIPE0m,
   MMU_CTR_UC_DROP_MEM_XPE2_PIPE1m,
   MMU_CTR_UC_DROP_MEM_XPE3_PIPE2m,
   MMU_CTR_UC_DROP_MEM_XPE3_PIPE3m,
   MMU_CTR_ING_DROP_MEMm,
   MMU_THDU_CONFIG_PORT_PIPE0m,
   MMU_THDU_CONFIG_PORT_PIPE1m,
   MMU_THDU_CONFIG_PORT_PIPE2m,
   MMU_THDU_CONFIG_PORT_PIPE3m,
   MMU_THDU_CONFIG_QGROUP_PIPE0m,
   MMU_THDU_CONFIG_QGROUP_PIPE1m,
   MMU_THDU_CONFIG_QGROUP_PIPE2m,
   MMU_THDU_CONFIG_QGROUP_PIPE3m,
   MMU_THDU_CONFIG_QGROUP0_PIPE0m,
   MMU_THDU_CONFIG_QGROUP0_PIPE1m,
   MMU_THDU_CONFIG_QGROUP0_PIPE2m,
   MMU_THDU_CONFIG_QGROUP0_PIPE3m,
   MMU_THDU_CONFIG_QGROUP1_PIPE0m,
   MMU_THDU_CONFIG_QGROUP1_PIPE1m,
   MMU_THDU_CONFIG_QGROUP1_PIPE2m,
   MMU_THDU_CONFIG_QGROUP1_PIPE3m,
   MMU_THDU_CONFIG_QUEUE_PIPE0m,
   MMU_THDU_CONFIG_QUEUE_PIPE1m,
   MMU_THDU_CONFIG_QUEUE_PIPE2m,
   MMU_THDU_CONFIG_QUEUE_PIPE3m,
   MMU_THDU_CONFIG_QUEUE0_PIPE0m,
   MMU_THDU_CONFIG_QUEUE0_PIPE1m,
   MMU_THDU_CONFIG_QUEUE0_PIPE2m,
   MMU_THDU_CONFIG_QUEUE0_PIPE3m,
   MMU_THDU_CONFIG_QUEUE1_PIPE0m,
   MMU_THDU_CONFIG_QUEUE1_PIPE1m,
   MMU_THDU_CONFIG_QUEUE1_PIPE2m,
   MMU_THDU_CONFIG_QUEUE1_PIPE3m,
   MMU_THDU_COUNTER_PORT_XPE0_PIPE0m,
   MMU_THDU_COUNTER_PORT_XPE0_PIPE1m,
   MMU_THDU_COUNTER_PORT_XPE1_PIPE2m,
   MMU_THDU_COUNTER_PORT_XPE1_PIPE3m,
   MMU_THDU_COUNTER_PORT_XPE2_PIPE0m,
   MMU_THDU_COUNTER_PORT_XPE2_PIPE1m,
   MMU_THDU_COUNTER_PORT_XPE3_PIPE2m,
   MMU_THDU_COUNTER_PORT_XPE3_PIPE3m,
   MMU_THDU_COUNTER_QGROUP_XPE0_PIPE0m,
   MMU_THDU_COUNTER_QGROUP_XPE0_PIPE1m,
   MMU_THDU_COUNTER_QGROUP_XPE1_PIPE2m,
   MMU_THDU_COUNTER_QGROUP_XPE1_PIPE3m,
   MMU_THDU_COUNTER_QGROUP_XPE2_PIPE0m,
   MMU_THDU_COUNTER_QGROUP_XPE2_PIPE1m,
   MMU_THDU_COUNTER_QGROUP_XPE3_PIPE2m,
   MMU_THDU_COUNTER_QGROUP_XPE3_PIPE3m,
   MMU_THDU_COUNTER_QUEUE_XPE0_PIPE0m,
   MMU_THDU_COUNTER_QUEUE_XPE0_PIPE1m,
   MMU_THDU_COUNTER_QUEUE_XPE1_PIPE2m,
   MMU_THDU_COUNTER_QUEUE_XPE1_PIPE3m,
   MMU_THDU_COUNTER_QUEUE_XPE2_PIPE0m,
   MMU_THDU_COUNTER_QUEUE_XPE2_PIPE1m,
   MMU_THDU_COUNTER_QUEUE_XPE3_PIPE2m,
   MMU_THDU_COUNTER_QUEUE_XPE3_PIPE3m,
   MMU_THDU_OFFSET_QGROUP_PIPE0m,
   MMU_THDU_OFFSET_QGROUP_PIPE1m,
   MMU_THDU_OFFSET_QGROUP_PIPE2m,
   MMU_THDU_OFFSET_QGROUP_PIPE3m,
   MMU_THDU_OFFSET_QGROUP0_PIPE0m,
   MMU_THDU_OFFSET_QGROUP0_PIPE1m,
   MMU_THDU_OFFSET_QGROUP0_PIPE2m,
   MMU_THDU_OFFSET_QGROUP0_PIPE3m,
   MMU_THDU_OFFSET_QGROUP1_PIPE0m,
   MMU_THDU_OFFSET_QGROUP1_PIPE1m,
   MMU_THDU_OFFSET_QGROUP1_PIPE2m,
   MMU_THDU_OFFSET_QGROUP1_PIPE3m,
   MMU_THDU_OFFSET_QUEUE_PIPE0m,
   MMU_THDU_OFFSET_QUEUE_PIPE1m,
   MMU_THDU_OFFSET_QUEUE_PIPE2m,
   MMU_THDU_OFFSET_QUEUE_PIPE3m,
   MMU_THDU_OFFSET_QUEUE0_PIPE0m,
   MMU_THDU_OFFSET_QUEUE0_PIPE1m,
   MMU_THDU_OFFSET_QUEUE0_PIPE2m,
   MMU_THDU_OFFSET_QUEUE0_PIPE3m,
   MMU_THDU_OFFSET_QUEUE1_PIPE0m,
   MMU_THDU_OFFSET_QUEUE1_PIPE1m,
   MMU_THDU_OFFSET_QUEUE1_PIPE2m,
   MMU_THDU_OFFSET_QUEUE1_PIPE3m,
   MMU_THDU_Q_TO_QGRP_MAP_PIPE0m,
   MMU_THDU_Q_TO_QGRP_MAP_PIPE1m,
   MMU_THDU_Q_TO_QGRP_MAP_PIPE2m,
   MMU_THDU_Q_TO_QGRP_MAP_PIPE3m,
   MMU_THDU_RESUME_PORT_PIPE0m,
   MMU_THDU_RESUME_PORT_PIPE1m,
   MMU_THDU_RESUME_PORT_PIPE2m,
   MMU_THDU_RESUME_PORT_PIPE3m,
   MMU_THDU_RESUME_PORT0_PIPE0m,
   MMU_THDU_RESUME_PORT0_PIPE1m,
   MMU_THDU_RESUME_PORT0_PIPE2m,
   MMU_THDU_RESUME_PORT0_PIPE3m,
   MMU_THDU_RESUME_PORT1_PIPE0m,
   MMU_THDU_RESUME_PORT1_PIPE1m,
   MMU_THDU_RESUME_PORT1_PIPE2m,
   MMU_THDU_RESUME_PORT1_PIPE3m,
   MMU_THDU_RESUME_PORT2_PIPE0m,
   MMU_THDU_RESUME_PORT2_PIPE1m,
   MMU_THDU_RESUME_PORT2_PIPE2m,
   MMU_THDU_RESUME_PORT2_PIPE3m,
   MMU_THDU_RESUME_QGROUP_XPE0_PIPE0m,
   MMU_THDU_RESUME_QGROUP_XPE0_PIPE1m,
   MMU_THDU_RESUME_QGROUP_XPE1_PIPE2m,
   MMU_THDU_RESUME_QGROUP_XPE1_PIPE3m,
   MMU_THDU_RESUME_QGROUP_XPE2_PIPE0m,
   MMU_THDU_RESUME_QGROUP_XPE2_PIPE1m,
   MMU_THDU_RESUME_QGROUP_XPE3_PIPE2m,
   MMU_THDU_RESUME_QGROUP_XPE3_PIPE3m,
   MMU_THDU_RESUME_QUEUE_XPE0_PIPE0m,
   MMU_THDU_RESUME_QUEUE_XPE0_PIPE1m,
   MMU_THDU_RESUME_QUEUE_XPE1_PIPE2m,
   MMU_THDU_RESUME_QUEUE_XPE1_PIPE3m,
   MMU_THDU_RESUME_QUEUE_XPE2_PIPE0m,
   MMU_THDU_RESUME_QUEUE_XPE2_PIPE1m,
   MMU_THDU_RESUME_QUEUE_XPE3_PIPE2m,
   MMU_THDU_RESUME_QUEUE_XPE3_PIPE3m,
   MMU_THDM_DB_PORTSP_CONFIG_PIPE0m,
   MMU_THDM_DB_PORTSP_CONFIG_PIPE1m,
   MMU_THDM_DB_PORTSP_CONFIG_PIPE2m,
   MMU_THDM_DB_PORTSP_CONFIG_PIPE3m,
   MMU_THDM_DB_PORTSP_CONFIG_A_PIPE0m,
   MMU_THDM_DB_PORTSP_CONFIG_A_PIPE1m,
   MMU_THDM_DB_PORTSP_CONFIG_A_PIPE2m,
   MMU_THDM_DB_PORTSP_CONFIG_A_PIPE3m,
   MMU_THDM_DB_PORTSP_CONFIG_B_PIPE0m,
   MMU_THDM_DB_PORTSP_CONFIG_B_PIPE1m,
   MMU_THDM_DB_PORTSP_CONFIG_B_PIPE2m,
   MMU_THDM_DB_PORTSP_CONFIG_B_PIPE3m,
   MMU_THDM_DB_PORTSP_CONFIG_C_PIPE0m,
   MMU_THDM_DB_PORTSP_CONFIG_C_PIPE1m,
   MMU_THDM_DB_PORTSP_CONFIG_C_PIPE2m,
   MMU_THDM_DB_PORTSP_CONFIG_C_PIPE3m,
   MMU_THDM_DB_QUEUE_CONFIG_A_PIPE0m,
   MMU_THDM_DB_QUEUE_CONFIG_A_PIPE1m,
   MMU_THDM_DB_QUEUE_CONFIG_A_PIPE2m,
   MMU_THDM_DB_QUEUE_CONFIG_A_PIPE3m,
   MMU_THDM_DB_QUEUE_CONFIG_B_PIPE0m,
   MMU_THDM_DB_QUEUE_CONFIG_B_PIPE1m,
   MMU_THDM_DB_QUEUE_CONFIG_B_PIPE2m,
   MMU_THDM_DB_QUEUE_CONFIG_B_PIPE3m,
   MMU_THDM_DB_QUEUE_CONFIG_C_PIPE0m,
   MMU_THDM_DB_QUEUE_CONFIG_C_PIPE1m,
   MMU_THDM_DB_QUEUE_CONFIG_C_PIPE2m,
   MMU_THDM_DB_QUEUE_CONFIG_C_PIPE3m,
   MMU_THDM_DB_QUEUE_CONFIG_PIPE0m,
   MMU_THDM_DB_QUEUE_CONFIG_PIPE1m,
   MMU_THDM_DB_QUEUE_CONFIG_PIPE2m,
   MMU_THDM_DB_QUEUE_CONFIG_PIPE3m,
   MMU_THDM_DB_QUEUE_COUNT_XPE0_PIPE0m,
   MMU_THDM_DB_QUEUE_COUNT_XPE0_PIPE1m,
   MMU_THDM_DB_QUEUE_COUNT_XPE1_PIPE2m,
   MMU_THDM_DB_QUEUE_COUNT_XPE1_PIPE3m,
   MMU_THDM_DB_QUEUE_COUNT_XPE2_PIPE0m,
   MMU_THDM_DB_QUEUE_COUNT_XPE2_PIPE1m,
   MMU_THDM_DB_QUEUE_COUNT_XPE3_PIPE2m,
   MMU_THDM_DB_QUEUE_COUNT_XPE3_PIPE3m,
   MMU_THDM_DB_QUEUE_OFFSET_PIPE0m,
   MMU_THDM_DB_QUEUE_OFFSET_PIPE1m,
   MMU_THDM_DB_QUEUE_OFFSET_PIPE2m,
   MMU_THDM_DB_QUEUE_OFFSET_PIPE3m,
   MMU_THDM_DB_QUEUE_OFFSET_A_PIPE0m,
   MMU_THDM_DB_QUEUE_OFFSET_A_PIPE1m,
   MMU_THDM_DB_QUEUE_OFFSET_A_PIPE2m,
   MMU_THDM_DB_QUEUE_OFFSET_A_PIPE3m,
   MMU_THDM_DB_QUEUE_OFFSET_B_PIPE0m,
   MMU_THDM_DB_QUEUE_OFFSET_B_PIPE1m,
   MMU_THDM_DB_QUEUE_OFFSET_B_PIPE2m,
   MMU_THDM_DB_QUEUE_OFFSET_B_PIPE3m,
   MMU_THDM_DB_QUEUE_OFFSET_C_PIPE0m,
   MMU_THDM_DB_QUEUE_OFFSET_C_PIPE1m,
   MMU_THDM_DB_QUEUE_OFFSET_C_PIPE2m,
   MMU_THDM_DB_QUEUE_OFFSET_C_PIPE3m,
   MMU_THDM_DB_QUEUE_RESUME_XPE0_PIPE0m,
   MMU_THDM_DB_QUEUE_RESUME_XPE0_PIPE1m,
   MMU_THDM_DB_QUEUE_RESUME_XPE1_PIPE2m,
   MMU_THDM_DB_QUEUE_RESUME_XPE1_PIPE3m,
   MMU_THDM_DB_QUEUE_RESUME_XPE2_PIPE0m,
   MMU_THDM_DB_QUEUE_RESUME_XPE2_PIPE1m,
   MMU_THDM_DB_QUEUE_RESUME_XPE3_PIPE2m,
   MMU_THDM_DB_QUEUE_RESUME_XPE3_PIPE3m,
   MMU_THDM_MCQE_PORTSP_CONFIG_PIPE0m,
   MMU_THDM_MCQE_PORTSP_CONFIG_PIPE1m,
   MMU_THDM_MCQE_PORTSP_CONFIG_PIPE2m,
   MMU_THDM_MCQE_PORTSP_CONFIG_PIPE3m,
   MMU_THDM_MCQE_PORTSP_CONFIG_A_PIPE0m,
   MMU_THDM_MCQE_PORTSP_CONFIG_A_PIPE1m,
   MMU_THDM_MCQE_PORTSP_CONFIG_A_PIPE2m,
   MMU_THDM_MCQE_PORTSP_CONFIG_A_PIPE3m,
   MMU_THDM_MCQE_PORTSP_CONFIG_B_PIPE0m,
   MMU_THDM_MCQE_PORTSP_CONFIG_B_PIPE1m,
   MMU_THDM_MCQE_PORTSP_CONFIG_B_PIPE2m,
   MMU_THDM_MCQE_PORTSP_CONFIG_B_PIPE3m,
   MMU_THDM_MCQE_PORTSP_CONFIG_C_PIPE0m,
   MMU_THDM_MCQE_PORTSP_CONFIG_C_PIPE1m,
   MMU_THDM_MCQE_PORTSP_CONFIG_C_PIPE2m,
   MMU_THDM_MCQE_PORTSP_CONFIG_C_PIPE3m,
   MMU_THDM_MCQE_QUEUE_CONFIG_PIPE0m,
   MMU_THDM_MCQE_QUEUE_CONFIG_PIPE1m,
   MMU_THDM_MCQE_QUEUE_CONFIG_PIPE2m,
   MMU_THDM_MCQE_QUEUE_CONFIG_PIPE3m,
   MMU_THDM_MCQE_QUEUE_CONFIG_A_PIPE0m,
   MMU_THDM_MCQE_QUEUE_CONFIG_A_PIPE1m,
   MMU_THDM_MCQE_QUEUE_CONFIG_A_PIPE2m,
   MMU_THDM_MCQE_QUEUE_CONFIG_A_PIPE3m,
   MMU_THDM_MCQE_QUEUE_CONFIG_B_PIPE0m,
   MMU_THDM_MCQE_QUEUE_CONFIG_B_PIPE1m,
   MMU_THDM_MCQE_QUEUE_CONFIG_B_PIPE2m,
   MMU_THDM_MCQE_QUEUE_CONFIG_B_PIPE3m,
   MMU_THDM_MCQE_QUEUE_CONFIG_C_PIPE0m,
   MMU_THDM_MCQE_QUEUE_CONFIG_C_PIPE1m,
   MMU_THDM_MCQE_QUEUE_CONFIG_C_PIPE2m,
   MMU_THDM_MCQE_QUEUE_CONFIG_C_PIPE3m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE0_PIPE0m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE0_PIPE1m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE1_PIPE2m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE1_PIPE3m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE2_PIPE0m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE2_PIPE1m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE3_PIPE2m,
   MMU_THDM_MCQE_QUEUE_COUNT_XPE3_PIPE3m,
   MMU_THDM_MCQE_QUEUE_OFFSET_PIPE0m,
   MMU_THDM_MCQE_QUEUE_OFFSET_PIPE1m,
   MMU_THDM_MCQE_QUEUE_OFFSET_PIPE2m,
   MMU_THDM_MCQE_QUEUE_OFFSET_PIPE3m,
   MMU_THDM_MCQE_QUEUE_OFFSET_A_PIPE0m,
   MMU_THDM_MCQE_QUEUE_OFFSET_A_PIPE1m,
   MMU_THDM_MCQE_QUEUE_OFFSET_A_PIPE2m,
   MMU_THDM_MCQE_QUEUE_OFFSET_A_PIPE3m,
   MMU_THDM_MCQE_QUEUE_OFFSET_B_PIPE0m,
   MMU_THDM_MCQE_QUEUE_OFFSET_B_PIPE1m,
   MMU_THDM_MCQE_QUEUE_OFFSET_B_PIPE2m,
   MMU_THDM_MCQE_QUEUE_OFFSET_B_PIPE3m,
   MMU_THDM_MCQE_QUEUE_OFFSET_C_PIPE0m,
   MMU_THDM_MCQE_QUEUE_OFFSET_C_PIPE1m,
   MMU_THDM_MCQE_QUEUE_OFFSET_C_PIPE2m,
   MMU_THDM_MCQE_QUEUE_OFFSET_C_PIPE3m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE0_PIPE0m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE0_PIPE1m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE1_PIPE2m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE1_PIPE3m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE2_PIPE0m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE2_PIPE1m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE3_PIPE2m,
   MMU_THDM_MCQE_QUEUE_RESUME_XPE3_PIPE3m,
   EGR_MACDA_OUI_PROFILEm,
   EGR_MAC_DA_PROFILEm,
   INVALIDm /* Must be the last element in this structure */
};

/* Structure that maintains register list for
 * "phy" feature for Tomahawk chipset. */
techsupport_reg_t techsupport_phy_tomahawk_reg_list[] = {
   {MMU_THDR_DB_CONFIGr, register_type_global },
   {MMU_THDR_DB_CONFIG_SPr, register_type_global },
   {MMU_THDR_DB_SP_SHARED_LIMITr, register_type_global },
   {MMU_THDR_DB_RESUME_COLOR_LIMIT_SPr, register_type_global },
   {MMU_THDR_DB_STATUS_SPr, register_type_global },
   {MMU_THDR_DB_SHARED_COUNT_SPr, register_type_global },
   {MMU_THDR_DB_CONFIG_PRIQr, register_type_global },
   {MMU_THDR_DB_CONFIG1_PRIQr, register_type_global },
   {MMU_THDR_DB_LIMIT_COLOR_PRIQr, register_type_global },
   {MMU_THDR_DB_RESET_OFFSET_COLOR_PRIQr, register_type_global },
   {MMU_THDR_DB_LIMIT_MIN_PRIQr, register_type_global },
   {MMU_THDR_DB_STATUS_PRIQr, register_type_global },
   {MMU_THDR_DB_SHARED_COUNT_PRIQr, register_type_global },
   {MMU_THDR_DB_MIN_COUNT_PRIQr, register_type_global },
   {MMU_THDR_DB_BYPASSr, register_type_global },
   {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP_64_XPE0r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP_64_XPE1r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP_64_XPE2r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP_64_XPE3r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP_64_XPE0r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP_64_XPE1r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP_64_XPE2r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP_64_XPE3r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP0_64_XPE0r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP0_64_XPE1r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP0_64_XPE2r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP0_64_XPE3r, register_type_global },
   {MMU_THDM_MCQE_DEVICE_BYPASSr, register_type_global },
   {MMU_THDM_MCQE_DEVICE_THR_CONFIGr, register_type_global },
   {MMU_THDM_MCQE_EN_COR_ERR_RPTr, register_type_global },
   {MMU_THDM_MCQE_MEMORY_TMr, register_type_global },
   {MMU_THDM_MCQE_POOL_DROP_STATESr, register_type_global },
   {MMU_THDM_MCQE_POOL_RED_RESUME_LIMITr, register_type_global },
   {MMU_THDM_MCQE_POOL_RED_SHARED_LIMITr, register_type_global },
   {MMU_THDM_MCQE_POOL_RESUME_LIMITr, register_type_global },
   {MMU_THDM_MCQE_POOL_SHARED_COUNTr, register_type_global },
   {MMU_THDM_MCQE_POOL_SHARED_LIMITr, register_type_global },
   {MMU_THDM_MCQE_POOL_YELLOW_RESUME_LIMITr, register_type_global },
   {MMU_THDM_MCQE_POOL_YELLOW_SHARED_LIMITr, register_type_global },
   {MMU_THDM_MCQE_QUEUE_RESUME_OFFSET_PROFILE_REDr, register_type_global },
   {MMU_THDM_MCQE_QUEUE_RESUME_OFFSET_PROFILE_YELLOWr, register_type_global },
   {MMU_THDM_MCQE_PORTSP_SHARED_COUNT_XPE0r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_SHARED_COUNT_XPE1r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_SHARED_COUNT_XPE2r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_SHARED_COUNT_XPE3r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_THRESHOLD_PROFILE_SEL_XPE0r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_THRESHOLD_PROFILE_SEL_XPE1r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_THRESHOLD_PROFILE_SEL_XPE2r, register_type_global },
   {MMU_THDM_MCQE_PORTSP_THRESHOLD_PROFILE_SEL_XPE3r, register_type_global },
   {MMU_THDM_DB_PORTSP_DROP_STATE_BMP_64_XPE0r, register_type_global },
   {MMU_THDM_DB_PORTSP_DROP_STATE_BMP_64_XPE1r, register_type_global },
   {MMU_THDM_DB_PORTSP_DROP_STATE_BMP_64_XPE2r, register_type_global },
   {MMU_THDM_DB_PORTSP_DROP_STATE_BMP_64_XPE3r, register_type_global },
   {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP_64_XPE0r, register_type_global },
   {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP_64_XPE1r, register_type_global },
   {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP_64_XPE2r, register_type_global },
   {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP_64_XPE3r, register_type_global },
   {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP_64_XPE0r, register_type_global },
   {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP_64_XPE1r, register_type_global },
   {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP_64_XPE2r, register_type_global },
   {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP_64_XPE3r, register_type_global },
   {MMU_THDM_DB_DEVICE_BYPASSr, register_type_global },
   {MMU_THDM_DB_DEVICE_THR_CONFIGr, register_type_global },
   {MMU_THDM_DB_EN_COR_ERR_RPTr, register_type_global },
   {MMU_THDM_DB_MEMORY_TMr, register_type_global },
   {MMU_THDM_DB_POOL_DROP_STATESr, register_type_global },
   {MMU_THDM_DB_POOL_RED_RESUME_LIMITr, register_type_global },
   {MMU_THDM_DB_POOL_RED_SHARED_LIMITr, register_type_global },
   {MMU_THDM_DB_POOL_RESUME_LIMITr, register_type_global },
   {MMU_THDM_DB_POOL_SHARED_COUNTr, register_type_global },
   {MMU_THDM_DB_POOL_SHARED_LIMITr, register_type_global },
   {MMU_THDM_DB_POOL_YELLOW_RESUME_LIMITr, register_type_global },
   {MMU_THDM_DB_POOL_YELLOW_SHARED_LIMITr, register_type_global },
   {MMU_THDM_DB_PORTSP_SHARED_COUNTr, register_type_global },
   {MMU_THDM_DB_PORTSP_THRESHOLD_PROFILE_SELr, register_type_global },
   {MMU_THDM_DB_PORTSP_TOTAL_COUNTr, register_type_global },
   {MMU_THDM_DB_QUEUE_RESUME_OFFSET_PROFILE_REDr, register_type_global },
   {MMU_THDM_DB_QUEUE_RESUME_OFFSET_PROFILE_YELLOWr, register_type_global },
   {THDI_BUFFER_CELL_LIMIT_PUBLIC_POOLr, register_type_global },
   {THDI_BUFFER_CELL_LIMIT_SPr, register_type_global },
   {THDI_BYPASSr, register_type_global },
   {THDI_CELL_RESET_LIMIT_OFFSET_SPr, register_type_global },
   {THDI_CELL_SPAP_RED_OFFSET_SPr, register_type_global },
   {THDI_CELL_SPAP_YELLOW_OFFSET_SPr, register_type_global },
   {THDI_EN_COR_ERR_RPTr, register_type_global },
   {THDI_FLOW_CONTROL_XOFF_STATEr, register_type_global },
   {THDI_GLOBAL_HDRM_COUNTr, register_type_global },
   {THDI_GLOBAL_HDRM_LIMITr, register_type_global },
   {THDI_GLOBAL_HDRM_RESERVEDr, register_type_global },
   {THDI_INPUT_PORT_XON_ENABLESr, register_type_global },
   {THDI_MEMORY_PTPG_CFG_MEM_TMr, register_type_global },
   {THDI_MEMORY_PTSP_CFG_MEM_TMr, register_type_global },
   {THDI_MEM_INIT_STATUSr, register_type_global },
   {THDI_POOL_CONFIGr, register_type_global },
   {THDI_POOL_DROP_STATEr, register_type_global },
   {THDI_POOL_SHARED_COUNT_SPr, register_type_global },
   {THDI_PORT_LIMIT_STATESr, register_type_global },
   {THDI_PORT_MAX_PKT_SIZEr, register_type_global },
   {THDI_PORT_PG_SPIDr, register_type_global },
   {THDI_PORT_PRI_GRP0r, register_type_global },
   {THDI_PORT_PRI_GRP1r, register_type_global },
   {THDI_TOTAL_CELL_COUNT_PUBLIC_POOLr, register_type_global },
   {THDI_TO_OOBFC_SP_STr, register_type_global },
   {DROP_PKT_CNT_RQE_BYTE_64r, register_type_global },
   {DROP_PKT_CNT_RQE_PKTr, register_type_global },
   {DROP_PKT_CNT_RQE_REDr, register_type_global },
   {DROP_PKT_CNT_RQE_YELr, register_type_global },
   {RQE_PRIORITY_SCHEDULING_TYPEr, register_type_global },
   {CLMAC_CLEAR_ECC_STATUSr, register_type_global },
   {CLMAC_CLEAR_FIFO_STATUSr, register_type_global },
   {CLMAC_CLEAR_RX_LSS_STATUSr, register_type_global },
   {CLMAC_CTRLr, register_type_global },
   {CLMAC_E2E_CTRLr, register_type_global },
   {CLMAC_E2ECC_DATA_HDR_0r, register_type_global },
   {CLMAC_E2ECC_DATA_HDR_1r, register_type_global },
   {CLMAC_E2ECC_MODULE_HDR_0r, register_type_global },
   {CLMAC_E2ECC_MODULE_HDR_1r, register_type_global },
   {CLMAC_E2EFC_DATA_HDR_0r, register_type_global },
   {CLMAC_E2EFC_DATA_HDR_1r, register_type_global },
   {CLMAC_E2EFC_MODULE_HDR_0r, register_type_global },
   {CLMAC_E2EFC_MODULE_HDR_1r, register_type_global },
   {CLMAC_ECC_CTRLr, register_type_global },
   {CLMAC_ECC_FORCE_DOUBLE_BIT_ERRr, register_type_global },
   {CLMAC_ECC_FORCE_SINGLE_BIT_ERRr, register_type_global },
   {CLMAC_EEE_1_SEC_LINK_STATUS_TIMERr, register_type_global },
   {CLMAC_EEE_CTRLr, register_type_global },
   {CLMAC_EEE_TIMERSr, register_type_global },
   {CLMAC_FIFO_STATUSr, register_type_global },
   {CLMAC_GMII_EEE_CTRLr, register_type_global },
   {CLMAC_HIGIG_HDR_0r, register_type_global },
   {CLMAC_HIGIG_HDR_1r, register_type_global },
   {CLMAC_LAG_FAILOVER_STATUSr, register_type_global },
   {CLMAC_LLFC_CTRLr, register_type_global },
   {CLMAC_MEM_CTRLr, register_type_global },
   {CLMAC_MODEr, register_type_global },
   {CLMAC_PAUSE_CTRLr, register_type_global },
   {CLMAC_PFC_CTRLr, register_type_global },
   {CLMAC_PFC_DAr, register_type_global },
   {CLMAC_PFC_OPCODEr, register_type_global },
   {CLMAC_PFC_TYPEr, register_type_global },
   {CLMAC_RX_CDC_ECC_STATUSr, register_type_global },
   {CLMAC_RX_CTRLr, register_type_global },
   {CLMAC_RX_LLFC_MSG_FIELDSr, register_type_global },
   {CLMAC_RX_LSS_CTRLr, register_type_global },
   {CLMAC_RX_LSS_STATUSr, register_type_global },
   {CLMAC_RX_MAC_SAr, register_type_global },
   {CLMAC_RX_MAX_SIZEr, register_type_global },
   {CLMAC_RX_TS_MEM_ECC_STATUSr, register_type_global },
   {CLMAC_RX_VLAN_TAGr, register_type_global },
   {CLMAC_SPARE0r, register_type_global },
   {CLMAC_SPARE1r, register_type_global },
   {CLMAC_TIMESTAMP_ADJUSTr, register_type_global },
   {CLMAC_TX_CDC_ECC_STATUSr, register_type_global },
   {CLMAC_TX_CRC_CORRUPT_CTRLr, register_type_global },
   {CLMAC_TX_CTRLr, register_type_global },
   {CLMAC_TX_LLFC_MSG_FIELDSr, register_type_global },
   {CLMAC_TX_MAC_SAr, register_type_global },
   {CLMAC_TX_TIMESTAMP_FIFO_DATAr, register_type_global },
   {CLMAC_TX_TIMESTAMP_FIFO_STATUSr, register_type_global },
   {CLMAC_TXFIFO_CELL_CNTr, register_type_global },
   {CLMAC_TXFIFO_CELL_REQ_CNTr, register_type_global },
   {CLMAC_VERSION_IDr, register_type_global },
   {XLMAC_CLEAR_ECC_STATUSr, register_type_global },
   {XLMAC_CLEAR_FIFO_STATUSr, register_type_global },
   {XLMAC_CLEAR_RX_LSS_STATUSr, register_type_global },
   {XLMAC_CTRLr, register_type_global },
   {XLMAC_E2E_CTRLr, register_type_global },
   {XLMAC_E2ECC_DATA_HDR_0r, register_type_global },
   {XLMAC_E2ECC_DATA_HDR_1r, register_type_global },
   {XLMAC_E2ECC_MODULE_HDR_0r, register_type_global },
   {XLMAC_E2ECC_MODULE_HDR_1r, register_type_global },
   {XLMAC_E2EFC_DATA_HDR_0r, register_type_global },
   {XLMAC_E2EFC_DATA_HDR_1r, register_type_global },
   {XLMAC_E2EFC_MODULE_HDR_0r, register_type_global },
   {XLMAC_E2EFC_MODULE_HDR_1r, register_type_global },
   {XLMAC_ECC_CTRLr, register_type_global },
   {XLMAC_ECC_FORCE_DOUBLE_BIT_ERRr, register_type_global },
   {XLMAC_ECC_FORCE_SINGLE_BIT_ERRr, register_type_global },
   {XLMAC_EEE_1_SEC_LINK_STATUS_TIMERr, register_type_global },
   {XLMAC_EEE_CTRLr, register_type_global },
   {XLMAC_EEE_TIMERSr, register_type_global },
   {XLMAC_FIFO_STATUSr, register_type_global },
   {XLMAC_GMII_EEE_CTRLr, register_type_global },
   {XLMAC_HIGIG_HDR_0r, register_type_global },
   {XLMAC_HIGIG_HDR_1r, register_type_global },
   {XLMAC_LAG_FAILOVER_STATUSr, register_type_global },
   {XLMAC_LLFC_CTRLr, register_type_global },
   {XLMAC_MEM_CTRLr, register_type_global },
   {XLMAC_MODEr, register_type_global },
   {XLMAC_PAUSE_CTRLr, register_type_global },
   {XLMAC_PFC_CTRLr, register_type_global },
   {XLMAC_PFC_DAr, register_type_global },
   {XLMAC_PFC_OPCODEr, register_type_global },
   {XLMAC_PFC_TYPEr, register_type_global },
   {XLMAC_RX_CDC_ECC_STATUSr, register_type_global },
   {XLMAC_RX_CTRLr, register_type_global },
   {XLMAC_RX_LLFC_MSG_FIELDSr, register_type_global },
   {XLMAC_RX_LSS_CTRLr, register_type_global },
   {XLMAC_RX_LSS_STATUSr, register_type_global },
   {XLMAC_RX_MAC_SAr, register_type_global },
   {XLMAC_RX_MAX_SIZEr, register_type_global },
   {XLMAC_RX_VLAN_TAGr, register_type_global },
   {XLMAC_SPARE0r, register_type_global },
   {XLMAC_SPARE1r, register_type_global },
   {XLMAC_TIMESTAMP_ADJUSTr, register_type_global },
   {XLMAC_TX_CDC_ECC_STATUSr, register_type_global },
   {XLMAC_TX_CRC_CORRUPT_CTRLr, register_type_global },
   {XLMAC_TX_CTRLr, register_type_global },
   {XLMAC_TX_LLFC_MSG_FIELDSr, register_type_global },
   {XLMAC_TX_MAC_SAr, register_type_global },
   {XLMAC_TX_TIMESTAMP_FIFO_DATAr, register_type_global },
   {XLMAC_TX_TIMESTAMP_FIFO_STATUSr, register_type_global },
   {XLMAC_TXFIFO_CELL_CNTr, register_type_global },
   {XLMAC_TXFIFO_CELL_REQ_CNTr, register_type_global },
   {XLMAC_VERSION_IDr, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_109_100r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_119_110r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_129_120r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_139_130r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_149_140r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_159_150r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_169_160r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_179_170r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_189_180r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_19_10r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_191_190r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_29_20r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_39_30r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_49_40r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_59_50r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_69_60r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_79_70r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_89_80r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_9_0r, register_type_global },
   {CMIC_MIIM_BUS_SEL_MAP_99_90r, register_type_global },
   {CMIC_MIIM_LINK_STATUS_0r, register_type_global },
   {CMIC_MIIM_LINK_STATUS_1r, register_type_global },
   {CMIC_MIIM_LINK_STATUS_2r, register_type_global },
   {CMIC_MIIM_LINK_STATUS_3r, register_type_global },
   {CMIC_MIIM_LINK_STATUS_4r, register_type_global },
   {CMIC_MIIM_LINK_STATUS_5r, register_type_global },
   {INVALIDr, register_type_global } /* Must be the last element in this structure */
};

/* Structure that maintains  diag cmdlist, reg_list, mem_list  for
 * "phy" feature for Tomahawk chipset. */
techsupport_data_t techsupport_phy_tomahawk_data = {
    techsupport_phy_diag_cmdlist,
    techsupport_phy_tomahawk_reg_list,
    techsupport_phy_tomahawk_memory_table_list,
    techsupport_phy_tomahawk_diag_cmdlist
#ifndef BCM_SW_STATE_DUMP_DISABLE
    , techsupport_phy_sw_dump_cmdlist,
    techsupport_phy_tomahawk_sw_dump_cmdlist
#endif /* BCM_SW_STATE_DUMP_DISABLE */
};

