
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SWSTATEDNX_GENERAL

#include <soc/dnxc/swstate/dnxc_sw_state_c_includes.h>
#include <soc/dnxc/swstate/auto_generated/access/dnxc_module_ids_access.h>



const char *
dnxc_module_id_e_get_name(dnxc_module_id_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("INVALID_MODULE_ID", value, INVALID_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("SWSTATE_INTERNAL_MODULE_ID", value, SWSTATE_INTERNAL_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ADAPTER_MODULE_ID", value, ADAPTER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_BFD_MODULE_ID", value, ALGO_BFD_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_CONSISTENT_HASHING_MODULE_ID", value, ALGO_CONSISTENT_HASHING_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_ECGM_MODULE_ID", value, ALGO_ECGM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_FAILOVER_MODULE_ID", value, ALGO_FAILOVER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_FIELD_MODULE_ID", value, DNX_ALGO_FIELD_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_FIELD_KEY_ALLOC_MODULE_ID", value, DNX_ALGO_FIELD_KEY_ALLOC_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_FLEXE_CORE_MODULE_ID", value, DNX_ALGO_FLEXE_CORE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_FLEXE_GENERAL_MODULE_ID", value, DNX_ALGO_FLEXE_GENERAL_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_L2_MODULE_ID", value, ALGO_L2_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_L3_MODULE_ID", value, ALGO_L3_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_LIF_PROFILE_MODULE_ID", value, ALGO_LIF_PROFILE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_MPLS_MODULE_ID", value, ALGO_MPLS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_OAM_MODULE_ID", value, ALGO_OAM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_OAMP_MODULE_ID", value, ALGO_OAMP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_PORT_MODULE_ID", value, DNX_ALGO_PORT_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_PORT_IMB_MODULE_ID", value, DNX_ALGO_PORT_IMB_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_PORT_PP_MODULE_ID", value, ALGO_PORT_PP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("PPMC_MODULE_ID", value, PPMC_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_PTP_MODULE_ID", value, ALGO_PTP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_QOS_MODULE_ID", value, ALGO_QOS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_RX_MODULE_ID", value, ALGO_RX_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_SAT_MODULE_ID", value, ALGO_SAT_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_STAT_PP_MODULE_ID", value, ALGO_STAT_PP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_STG_MODULE_ID", value, ALGO_STG_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_TDM_MODULE_ID", value, ALGO_TDM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_TRUNK_MODULE_ID", value, ALGO_TRUNK_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_TUNNEL_MODULE_ID", value, ALGO_TUNNEL_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("COSQ_LATENCY_MODULE_ID", value, COSQ_LATENCY_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("CRPS_MODULE_ID", value, CRPS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("CRPS_EVICTION_MODULE_ID", value, CRPS_EVICTION_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ECMP_MODULE_ID", value, ECMP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_EGQ_AM_MODULE_ID", value, DNX_EGQ_AM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("EXAMPLE_RES_MNGR_MODULE_ID", value, EXAMPLE_RES_MNGR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("EXAMPLE_TEMP_MNGR_MODULE_ID", value, EXAMPLE_TEMP_MNGR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("FLOW_CONTROL_MODULE_ID", value, FLOW_CONTROL_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("INGRESS_COMPENSATION_MODULE_ID", value, INGRESS_COMPENSATION_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_INGRESS_CONGESTION_MODULE_ID", value, DNX_INGRESS_CONGESTION_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_INGRESS_REASSEMBLY_MODULE_ID", value, DNX_INGRESS_REASSEMBLY_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("INSTRU_MODULE_ID", value, INSTRU_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_IPQ_ALLOC_MNGR_MODULE_ID", value, DNX_IPQ_ALLOC_MNGR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("LIF_MNGR_MODULE_ID", value, LIF_MNGR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("LIF_TABLE_MNGR_MODULE_ID", value, LIF_TABLE_MNGR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("METER_MODULE_ID", value, METER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_MIRROR_MODULE_ID", value, DNX_MIRROR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("MULTICAST_MODULE_ID", value, MULTICAST_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("PHANTOM_QUEUES_MODULE_ID", value, PHANTOM_QUEUES_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("PORT_TPID_MODULE_ID", value, PORT_TPID_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_SCH_ALLOC_MNGR_MODULE_ID", value, DNX_SCH_ALLOC_MNGR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("SEC_MODULE_ID", value, SEC_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("VLAN_MODULE_ID", value, VLAN_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_FIELD_ACTION_MODULE_ID", value, DNX_ALGO_FIELD_ACTION_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_LANE_MAP_MODULE_ID", value, DNX_ALGO_LANE_MAP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("ALGO_LIF_MODULE_ID", value, ALGO_LIF_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ALGO_SYNCE_MODULE_ID", value, DNX_ALGO_SYNCE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_COSQ_INGRESS_MODULE_ID", value, DNX_COSQ_INGRESS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DBAL_MODULE_ID", value, DBAL_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_BIER_DB_MODULE_ID", value, DNX_BIER_DB_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_EGR_DB_MODULE_ID", value, DNX_EGR_DB_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIFODMA_MODULE_ID", value, DNX_FIFODMA_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_IRE_PACKET_GENERATOR_MODULE_ID", value, DNX_IRE_PACKET_GENERATOR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_OFP_RATE_MODULE_ID", value, DNX_OFP_RATE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_RX_MODULE_ID", value, DNX_RX_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_TIME_SW_STATE_MODULE_ID", value, DNX_TIME_SW_STATE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_TRAPS_MODULE_ID", value, DNX_TRAPS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_VISIBILITY_MODULE_ID", value, DNX_VISIBILITY_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_DRAM_MODULE_ID", value, DNX_DRAM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_ECGM_MODULE_ID", value, DNX_ECGM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("EXAMPLE_MODULE_ID", value, EXAMPLE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FABRIC_MODULE_ID", value, DNX_FABRIC_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_MODULE_ID", value, DNX_FIELD_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTIONS_MODULE_ID", value, DNX_FIELD_ACTIONS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_APPTYPE_MODULE_ID", value, DNX_FIELD_APPTYPE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_CONTEXT_MODULE_ID", value, DNX_FIELD_CONTEXT_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_MODULE_ID", value, DNX_FIELD_GROUP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_MODULE_ID", value, DNX_FIELD_KEY_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUALIFIER_MODULE_ID", value, DNX_FIELD_QUALIFIER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_RANGE_MODULE_ID", value, DNX_FIELD_RANGE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_ACCESS_MODULE_ID", value, DNX_FIELD_TCAM_ACCESS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_ACCESS_MAPPER_MODULE_ID", value, DNX_FIELD_TCAM_ACCESS_MAPPER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_ACCESS_PROFILE_MODULE_ID", value, DNX_FIELD_TCAM_ACCESS_PROFILE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_BANK_MODULE_ID", value, DNX_FIELD_TCAM_BANK_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_CACHE_MODULE_ID", value, DNX_FIELD_TCAM_CACHE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_HIT_INDICATION_MODULE_ID", value, DNX_FIELD_TCAM_HIT_INDICATION_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_LOCATION_MODULE_ID", value, DNX_FIELD_TCAM_LOCATION_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_MANAGER_MODULE_ID", value, DNX_FIELD_TCAM_MANAGER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_TCAM_PREFIX_MODULE_ID", value, DNX_FIELD_TCAM_PREFIX_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("FLUSH_MODULE_ID", value, FLUSH_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_HARD_RESET_MODULE_ID", value, DNX_HARD_RESET_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("INSTRU_COUNTERS_MODULE_ID", value, INSTRU_COUNTERS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("INTERRUPT_MODULE_ID", value, INTERRUPT_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_IPQ_MODULE_ID", value, DNX_IPQ_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_IQS_MODULE_ID", value, DNX_IQS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("KBP_MODULE_ID", value, KBP_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("KBP_COMMON_MODULE_ID", value, KBP_COMMON_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("KBP_FWD_TCAM_ACCESS_MAPPER_MODULE_ID", value, KBP_FWD_TCAM_ACCESS_MAPPER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("L2_MODULE_ID", value, L2_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("MDB_MODULE_ID", value, MDB_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("MDB_EM_MODULE_ID", value, MDB_EM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("MDB_KAPS_MODULE_ID", value, MDB_KAPS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("OAM_MODULE_ID", value, OAM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_PORT_IMB_MODULE_ID", value, DNX_PORT_IMB_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("REFLECTOR_MODULE_ID", value, REFLECTOR_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_SCH_CONFIG_MODULE_ID", value, DNX_SCH_CONFIG_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_SCHEDULER_MODULE_ID", value, DNX_SCHEDULER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("SRV6_MODULE_ID", value, SRV6_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("STIF_MODULE_ID", value, STIF_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_STK_SYS_MODULE_ID", value, DNX_STK_SYS_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("SWITCH_MODULE_ID", value, SWITCH_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("TDM_MODULE_ID", value, TDM_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("TRUNK_MODULE_ID", value, TRUNK_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_SW_STATE_DEFRAGMENTED_CHUNK_MODULE_ID", value, DNX_SW_STATE_DEFRAGMENTED_CHUNK_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_SW_STATE_HASH_TABLE_MODULE_ID", value, DNX_SW_STATE_HASH_TABLE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_SW_STATE_SORTED_LIST_MODULE_ID", value, DNX_SW_STATE_SORTED_LIST_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNXC_MODULE_ID", value, DNXC_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("MULTITHREAD_ANALYZER_MODULE_ID", value, MULTITHREAD_ANALYZER_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("WB_ENGINE_MODULE_ID", value, WB_ENGINE_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNXF_MODULE_ID", value, DNXF_MODULE_ID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("NOF_MODULE_ID", value, NOF_MODULE_ID);

    return NULL;
}



#undef BSL_LOG_MODULE
