#
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dnx/pemladrv/virtual_dbs

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/shared

lib = libsoc_dnxpemladrv_virtualdbs

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
