#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

ifdef YAML
SDK_CPPFLAGS += -I$(YAML)/include -DYAML
endif

include $(SDK)/make/sublib.mk
