# $Id: Makefile,v 1.1 2004/02/24 07:46:29 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dnx/adapter

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxcmodel

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

