/* 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
*/

#ifndef __FGL_CONFIGURATION_INCLUDED__
#define __FGL_CONFIGURATION_INCLUDED__

#ifdef BCM_FLAIR_SUPPORT

typedef enum jer_fabric_costom_operation_e {
    BCM_JER_FABRIC_FGL_EGRESS_CONFIG_GET=0,
    BCM_JER_FABRIC_FGL_EGRESS_CONFIG_SET,
    BCM_JER_FABRIC_FGL_INGRESS_CONFIG_GET,
    BCM_JER_FABRIC_FGL_INGRESS_CONFIG_SET,
    BCM_JER_FABRIC_FGL_LOOPBACK_CONFIG_GET,
    BCM_JER_FABRIC_FGL_LOOPBACK_CONFIG_SET,
    BCM_JER_FABRIC_FGL_INGRESS_TDM_CONTEXT_DROP_GET,
    BCM_JER_FABRIC_FGL_INGRESS_TDM_CONTEXT_DROP_SET,
    BCM_JER_FABRIC_EGR_MC_MAPPING_MODE_GET,
    BCM_JER_FABRIC_EGR_MC_MAPPING_MODE_SET,
    BCM_JER_FABRIC_ECI_TDM_CONFIG_TABLE_GET,
    BCM_JER_FABRIC_ECI_TDM_CONFIG_TABLE_SET,
    BCM_JER_FABRIC_ECI_EGR_PORT_MAP_TABLE_GET,
    BCM_JER_FABRIC_ECI_EGR_PORT_MAP_TABLE_SET,
    BCM_JER_FABRIC_ECI_EGR_MCT_TABLE_GET,
    BCM_JER_FABRIC_ECI_EGR_MCT_TABLE_SET,
    BCM_JER_FABRIC_ECI_EGR_MCT_MAPPING_TABLE_GET,
    BCM_JER_FABRIC_ECI_EGR_MCT_MAPPING_TABLE_SET,
    BCM_JER_FABRIC_CUSTOM_OPERATION_NUMBER
} jer_fabric_costom_operation_t;

int jer_fabric_fgl_custom_api_init(int unit);
int jer_fabric_fgl_custom_api_deinit(int unit);

#endif /* BCM_FLAIR_SUPPORT */

#endif

