# $Id: Makefile,v 1.5 2008/01/16 23:35:04 majotk Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC SAL support
#

LOCALDIR = src/sal/appl

include ${SDK}/make/Make.config

subdirs=${targetbase} editline

include ${SDK}/make/Make.subdirs


lib = libsal_appl

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend



