# $Id: Makefile,v 1.1.2.1 2010/10/08 21:45:11 tusharty Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/triumph3

include ${SDK}/make/Make.config

lib = libtriumph3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
