
#ifndef INCLUDED_KAPS_JR1_TBLRQT_H
#define INCLUDED_KAPS_JR1_TBLRQT_H

typedef enum
{
    NLM_FIB_PREFIX_INSERT,
    NLM_FIB_PREFIX_DELETE,
    NLM_FIB_PREFIX_UPDATE_AD,
    NLM_FIB_PREFIX_UPDATE_AD_ADDRESS,
    NLM_FIB_PREFIX_INSERT_WITH_INDEX
} NlmTblRqtCode;

#endif
