#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#

LOCALDIR = libs/kaps_jr1

include ${SDK}/make/Make.config

lib = libkaps_jr1

INCDIR += -I${SDK}/libs/kaps_jr1/include
INCDIR += -I${SDK}/libs/kaps_jr1

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
