# $Id: Makefile,v 1.1.2.1 2012/11/18 00:50:37 wyuan Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# Makefile for Tomahawk SOC driver Library
#

LOCALDIR = src/soc/esw/tomahawk3/traffic_manager

include ${SDK}/make/Make.config

lib = libsoc_tomahawk3_trafficmanager

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

