#
# $Id: Makefile,v 1.0 2018/12/18 11:02:45 vg889851 Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/cosq/flow_control

include ${SDK}/make/Make.config

#subdirs = port

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxcosqflow_control

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

