/** \file dnx/swstate/auto_generated/types/dnx_algo_synce_types.h
 *
 * sw state types (structs/enums/typedefs)
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 */

#ifndef __DNX_ALGO_SYNCE_TYPES_H__
#define __DNX_ALGO_SYNCE_TYPES_H__

#include <soc/dnxc/swstate/dnxc_sw_state_h_includes.h>
#include <soc/dnxc/swstate/auto_generated/types/dnxc_types.h>
/*
 * STRUCTs
 */

/**
 * SyncE Data Base
 */
typedef struct {
    /**
     * Fabric SyncE status Data Base
     */
    soc_dnxc_synce_status_t fabric_synce_status;
} dnx_algo_synce_db_t;


#endif /* __DNX_ALGO_SYNCE_TYPES_H__ */
