# -*- Makefile -*-
# $Id: Makefile,v 1.2 2004/03/09 00:36:46 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

include ${SDK}/make/Make.config

subdirs= shared

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
