# $Id: Makefile,v 1.2 2007/08/06 22:06:10 mmussol Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/raptor

include ${SDK}/make/Make.config

lib = libraptor

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
