#
# $Id: Makefile,v 1.2 2011/08/21 07:20:25 bhanup Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for dfe subdirectory
#

LOCALDIR = src/soc/dfe/fe3200

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dfe_fe3200

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

