# $Id
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for Hurricane4 SOC driver Library
#

LOCALDIR = src/soc/esw/hurricane4

include ${SDK}/make/Make.config

SUBDIR_HURRICANE4_FLEXPORT = flexport

subdirs := $(SUBDIR_HURRICANE4_FLEXPORT)

lib = libsoc_hurricane4

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

