#
# $Id: Makefile Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dpp/QUX/

include ${SDK}/make/Make.config

lib = libsoc_dpp_qux

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
