# $Id: Makefile,v 1.5.40.1 2013/05/10 04:08:39 kirankum Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.

LOCALDIR = src/soc/kbp/alg_kbp

include ${SDK}/make/Make.config

subdirs += portability

include ${SDK}/make/Make.subdirs
include ${SDK}/make/Make.depend
