# $Id: Makefile,v 1.1.4.1 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/katana

include ${SDK}/make/Make.config

lib = libkatana

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
