#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

include $(SDK)/make/libname.mk

ifndef SYSTEM_INTERFACE
SYSTEM_INTERFACE = xgssim
endif

SUBDIRS := conf_examples conf probe/$(SYSTEM_INTERFACE)
include $(SDK)/make/subdir.mk

include $(SDK)/make/lib.mk
