# $Id: Makefile,v 1.2 2005/01/17 19:52:53 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/humv

include ${SDK}/make/Make.config

lib = libhumv

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
