/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File: tomahawk3_l3uc.c
 *
 * Purpose:
 *    Maintains all the debug information for l3uc feature for tomahawk3
 *
 * Note: This file is auto-generated. Manual edits
 *       to it will be lost when it is auto-regenerated.
 */

#include <appl/diag/techsupport.h>
#include <soc/mcm/allenum.h>

extern char * techsupport_l3uc_diag_cmdlist[];
extern char * techsupport_l3uc_sw_dump_cmdlist[];

/* "l3uc" feature's diag command list valid only for tomahawk3 */
char * techsupport_l3uc_tomahawk3_diag_cmdlist[] = {
    NULL /* Must be the last element in this structure */
};

#ifndef BCM_SW_STATE_DUMP_DISABLE
/* "l3uc" feature's software dump command list valid only for tomahawk3 */
char * techsupport_l3uc_tomahawk3_sw_dump_cmdlist[] = {
    NULL /* Must be the last element in this structure */
};
#endif /* BCM_SW_STATE_DUMP_DISABLE */


/* Structure that maintains memory list for
 * "l3uc" feature for tomahawk3 chipset. */
static soc_mem_t techsupport_l3uc_tomahawk3_memory_table_list[] = {
    DLB_ECMP_EEM_CONFIGURATIONm,
    DLB_ECMP_ETHERTYPE_ELIGIBILITY_MAPm,
    DLB_ECMP_FINAL_MEMBERS_QUALITY_MEASUREm,
    DLB_ECMP_FLOWSET_MEMBER_PIPE0m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE1m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE2m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE3m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE4m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE5m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE6m,
    DLB_ECMP_FLOWSET_MEMBER_PIPE7m,
    DLB_ECMP_FLOWSET_PIPE0m,
    DLB_ECMP_FLOWSET_PIPE1m,
    DLB_ECMP_FLOWSET_PIPE2m,
    DLB_ECMP_FLOWSET_PIPE3m,
    DLB_ECMP_FLOWSET_PIPE4m,
    DLB_ECMP_FLOWSET_PIPE5m,
    DLB_ECMP_FLOWSET_PIPE6m,
    DLB_ECMP_FLOWSET_PIPE7m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE0m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE1m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE2m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE3m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE4m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE5m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE6m,
    DLB_ECMP_FLOWSET_TIMESTAMP_PAGE_PIPE7m,
    DLB_ECMP_GLB_QUANTIZE_THRESHOLDm,
    DLB_ECMP_GROUP_ALT_NHI_MEMBERS_0_TO_12m,
    DLB_ECMP_GROUP_ALT_NHI_MEMBERS_13_TO_25m,
    DLB_ECMP_GROUP_ALT_NHI_MEMBERS_26_TO_38m,
    DLB_ECMP_GROUP_ALT_NHI_MEMBERS_39_TO_51m,
    DLB_ECMP_GROUP_ALT_NHI_MEMBERS_52_TO_63m,
    DLB_ECMP_GROUP_ALT_PORT_MEMBERS_0_TO_15m,
    DLB_ECMP_GROUP_ALT_PORT_MEMBERS_16_TO_31m,
    DLB_ECMP_GROUP_ALT_PORT_MEMBERS_32_TO_47m,
    DLB_ECMP_GROUP_ALT_PORT_MEMBERS_48_TO_63m,
    DLB_ECMP_GROUP_CONTROLm,
    DLB_ECMP_GROUP_MEMBERSHIPm,
    DLB_ECMP_GROUP_MONITOR_CONTROLm,
    DLB_ECMP_GROUP_NHI_MEMBERS_0_TO_12m,
    DLB_ECMP_GROUP_NHI_MEMBERS_13_TO_25m,
    DLB_ECMP_GROUP_NHI_MEMBERS_26_TO_38m,
    DLB_ECMP_GROUP_NHI_MEMBERS_39_TO_51m,
    DLB_ECMP_GROUP_NHI_MEMBERS_52_TO_63m,
    DLB_ECMP_GROUP_PORT_MEMBERS_0_TO_15m,
    DLB_ECMP_GROUP_PORT_MEMBERS_16_TO_31m,
    DLB_ECMP_GROUP_PORT_MEMBERS_32_TO_47m,
    DLB_ECMP_GROUP_PORT_MEMBERS_48_TO_63m,
    DLB_ECMP_GROUP_STATS_PIPE0m,
    DLB_ECMP_GROUP_STATS_PIPE1m,
    DLB_ECMP_GROUP_STATS_PIPE2m,
    DLB_ECMP_GROUP_STATS_PIPE3m,
    DLB_ECMP_GROUP_STATS_PIPE4m,
    DLB_ECMP_GROUP_STATS_PIPE5m,
    DLB_ECMP_GROUP_STATS_PIPE6m,
    DLB_ECMP_GROUP_STATS_PIPE7m,
    DLB_ECMP_LINK_CONTROLm,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE0m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE1m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE2m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE3m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE4m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE5m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE6m,
    DLB_ECMP_OPTIMAL_CANDIDATE_PIPE7m,
    DLB_ECMP_PORT_AVG_QUALITY_MEASUREm,
    DLB_ECMP_PORT_INST_QUALITY_MEASUREm,
    DLB_ECMP_PORT_QUALITY_MAPPINGm,
    DLB_ECMP_PORT_QUALITY_UPDATE_MEASURE_CONTROLm,
    DLB_ECMP_PORT_STATEm,
    DLB_ECMP_QUANTIZED_AVG_QUALITY_MEASUREm,
    DLB_ECMP_QUANTIZE_CONTROLm,
    DLB_ECMP_SER_FIFOm,
    ECMP_GROUP_HIERARCHICALm,
    EGR_IP_ECN_TO_EXP_MAPPING_TABLEm,
    EGR_IP_TO_INT_CN_MAPPINGm,
    EGR_IP_TUNNEL_IPV6m,
    EGR_IP_TUNNEL_MPLSm,
    EGR_IP_TUNNELm,
    EGR_L3_INTFm,
    EGR_L3_NEXT_HOP_2m,
    EGR_L3_NEXT_HOPm,
    EGR_MAC_DA_PROFILEm,
    EGR_TUNNEL_ECN_ENCAPm,
    ING_L3_NEXT_HOPm,
    ING_TUNNEL_ECN_DECAPm,
    IPV4_IN_IPV6_PREFIX_MATCH_TABLEm,
    IP_OPTION_CONTROL_PROFILE_TABLEm,
    IP_TO_INT_CN_MAPPINGm,
    L3_DEFIP_ALPM_LEVEL2_ECCm,
    L3_DEFIP_ALPM_LEVEL2_HIT_ONLYm,
    L3_DEFIP_ALPM_LEVEL2_SINGLEm,
    L3_DEFIP_ALPM_LEVEL2m,
    L3_DEFIP_ALPM_LEVEL3_ECCm,
    L3_DEFIP_ALPM_LEVEL3_HIT_ONLYm,
    L3_DEFIP_ALPM_LEVEL3_SINGLEm,
    L3_DEFIP_ALPM_LEVEL3m,
    L3_DEFIP_DATA_LEVEL1m,
    L3_DEFIP_LEVEL1_HIT_ONLYm,
    L3_DEFIP_LEVEL1m,
    L3_DEFIP_PAIR_LEVEL1m,
    L3_DEFIP_TCAM_LEVEL1m,
    L3_ECMP_COUNTm,
    L3_ECMPm,
    L3_ENTRY_ACTION_TABLE_Am,
    L3_ENTRY_ACTION_TABLE_Bm,
    L3_ENTRY_DOUBLEm,
    L3_ENTRY_ECCm,
    L3_ENTRY_HASH_CONTROLm,
    L3_ENTRY_HIT_ONLYm,
    L3_ENTRY_KEY_ATTRIBUTESm,
    L3_ENTRY_KEY_BUFFER_0_PIPE0m,
    L3_ENTRY_KEY_BUFFER_0_PIPE1m,
    L3_ENTRY_KEY_BUFFER_0_PIPE2m,
    L3_ENTRY_KEY_BUFFER_0_PIPE3m,
    L3_ENTRY_KEY_BUFFER_0_PIPE4m,
    L3_ENTRY_KEY_BUFFER_0_PIPE5m,
    L3_ENTRY_KEY_BUFFER_0_PIPE6m,
    L3_ENTRY_KEY_BUFFER_0_PIPE7m,
    L3_ENTRY_KEY_BUFFER_1_PIPE0m,
    L3_ENTRY_KEY_BUFFER_1_PIPE1m,
    L3_ENTRY_KEY_BUFFER_1_PIPE2m,
    L3_ENTRY_KEY_BUFFER_1_PIPE3m,
    L3_ENTRY_KEY_BUFFER_1_PIPE4m,
    L3_ENTRY_KEY_BUFFER_1_PIPE5m,
    L3_ENTRY_KEY_BUFFER_1_PIPE6m,
    L3_ENTRY_KEY_BUFFER_1_PIPE7m,
    L3_ENTRY_ONLY_DOUBLEm,
    L3_ENTRY_ONLY_QUADm,
    L3_ENTRY_ONLY_SINGLEm,
    L3_ENTRY_QUADm,
    L3_ENTRY_REMAP_TABLE_Am,
    L3_ENTRY_REMAP_TABLE_Bm,
    L3_ENTRY_SINGLEm,
    L3_IIF_PROFILEm,
    L3_IIFm,
    L3_MTU_VALUESm,
    L3_TUNNEL_ACTION_TABLE_Am,
    L3_TUNNEL_ACTION_TABLE_Bm,
    L3_TUNNEL_DOUBLEm,
    L3_TUNNEL_ECCm,
    L3_TUNNEL_HASH_CONTROLm,
    L3_TUNNEL_KEY_ATTRIBUTESm,
    L3_TUNNEL_KEY_BUFFER_PIPE0m,
    L3_TUNNEL_KEY_BUFFER_PIPE1m,
    L3_TUNNEL_KEY_BUFFER_PIPE2m,
    L3_TUNNEL_KEY_BUFFER_PIPE3m,
    L3_TUNNEL_KEY_BUFFER_PIPE4m,
    L3_TUNNEL_KEY_BUFFER_PIPE5m,
    L3_TUNNEL_KEY_BUFFER_PIPE6m,
    L3_TUNNEL_KEY_BUFFER_PIPE7m,
    L3_TUNNEL_QUADm,
    L3_TUNNEL_REMAP_TABLE_Am,
    L3_TUNNEL_REMAP_TABLE_Bm,
    L3_TUNNEL_SINGLEm,
    MY_STATION_TCAM_DATA_ONLYm,
    MY_STATION_TCAM_ENTRY_ONLYm,
    MY_STATION_TCAMm,
    PROT_NHI_TABLE_1m,
    VRFm,
    INVALIDm /* Must be the last element in this structure */
};

/* Structure that maintains register list for
 * "l3uc" feature for tomahawk3 chipset. */
techsupport_reg_t techsupport_l3uc_tomahawk3_reg_list[] = {
    { CPU_CONTROL_0r, register_type_global },
    { CPU_CONTROL_1r, register_type_global },
    { CPU_CONTROL_Mr, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE0r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE1r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE2r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE3r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE4r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE5r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE6r, register_type_global },
    { DLB_ECMP_CURRENT_TIME_PIPE7r, register_type_global },
    { DLB_ECMP_HW_RESET_CONTROLr, register_type_global },
    { DLB_ECMP_INTR_ENABLEr, register_type_global },
    { DLB_ECMP_INTR_STATUSr, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE0r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE1r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE2r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE3r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE4r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE5r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE6r, register_type_global },
    { DLB_ECMP_MONITOR_CONTROL_PIPE7r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE0r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE1r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE2r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE3r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE4r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE5r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE6r, register_type_global },
    { DLB_ECMP_MONITOR_IFP_CONTROL_PIPE7r, register_type_global },
    { DLB_ECMP_MONITOR_MIRROR_CONFIGr, register_type_global },
    { DLB_ECMP_QUALITY_MEASURE_CONTROLr, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE0r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE1r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE2r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE3r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE4r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE5r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE6r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_0_PIPE7r, register_type_global },
    { DLB_ECMP_RAM_CONTROL_1r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE0r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE1r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE2r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE3r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE4r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE5r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE6r, register_type_global },
    { DLB_ECMP_RANDOM_SELECTION_CONTROL_PIPE7r, register_type_global },
    { DLB_ECMP_REFRESH_DISABLEr, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE0r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE1r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE2r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE3r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE4r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE5r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE6r, register_type_global },
    { DLB_ECMP_REFRESH_INDEX_PIPE7r, register_type_global },
    { DLB_ECMP_SER_CONTROL_2r, register_type_global },
    { DLB_ECMP_SER_CONTROLr, register_type_global },
    { DLB_ECMP_SER_FIFO_CTRLr, register_type_global },
    { DLB_ECMP_SER_FIFO_STATUSr, register_type_global },
    { DLB_ID_0_TO_63_ENABLEr, register_type_global },
    { DLB_ID_64_TO_127_ENABLEr, register_type_global },
    { DOS_CONTROL_2r, register_type_global },
    { DOS_CONTROL_3r, register_type_global },
    { DOS_CONTROLr, register_type_global },
    { ECMP_GROUP_DLB_ID_OFFSETr, register_type_global },
    { ECN_CONTROLr, register_type_global },
    { EGR_ECN_CONTROLr, register_type_global },
    { ICMP_ERROR_TYPEr, register_type_global },
    { ING_CONFIG_64r, register_type_global },
    { IPV6_MIN_FRAG_SIZEr, register_type_global },
    { PROTOCOL_PKT_CONTROLr, register_type_global },
    { PROT_NHI_CONFIGr, register_type_global },
    { INVALIDr, register_type_global } /* Must be the last element in this structure */
};

/* Structure that maintains diag cmdlist, reg_list, mem_list  for
 * "l3uc" feature for tomahawk3 chipset. */
techsupport_data_t techsupport_l3uc_tomahawk3_data = {
    techsupport_l3uc_diag_cmdlist,
    techsupport_l3uc_tomahawk3_reg_list,
    techsupport_l3uc_tomahawk3_memory_table_list,
    techsupport_l3uc_tomahawk3_diag_cmdlist
#ifndef BCM_SW_STATE_DUMP_DISABLE
    , techsupport_l3uc_sw_dump_cmdlist,
    techsupport_l3uc_tomahawk3_sw_dump_cmdlist
#endif /* BCM_SW_STATE_DUMP_DISABLE */
};
