# $Id$
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id$
# Makefile for Hurricane3 SOC driver Library
#

LOCALDIR = src/soc/esw/hurricane3

include ${SDK}/make/Make.config

lib = libsoc_hurricane3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
