#
# $Id: Makefile,v 1.2 2011/11/08 15:12:39 dayad Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/appl/dfe

include ${SDK}/make/Make.config

lib = libappl_dfe_interrupts

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
