#
# $Id:$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# 
# Makefile for SOC swstate utils subdirectory
#
LOCALDIR = src/soc/dnxc/swstate/utils

include ${SDK}/make/Make.config

lib = libsoc_dnxcswstate_utils

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
