
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_FIFODMA_H_

#define _DNX_DATA_MAX_FIFODMA_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_FIFODMA_GENERAL_NOF_FIFODMA_CHANNELS (1)

#undef DNX_DATA_MAX_FIFODMA_GENERAL_NOF_FIFODMA_CHANNELS
#define DNX_DATA_MAX_FIFODMA_GENERAL_NOF_FIFODMA_CHANNELS (12)


#define DNX_DATA_MAX_FIFODMA_GENERAL_MIN_NOF_HOST_ENTRIES (1)

#undef DNX_DATA_MAX_FIFODMA_GENERAL_MIN_NOF_HOST_ENTRIES
#define DNX_DATA_MAX_FIFODMA_GENERAL_MIN_NOF_HOST_ENTRIES (64)


#define DNX_DATA_MAX_FIFODMA_GENERAL_MAX_NOF_HOST_ENTRIES (1)

#undef DNX_DATA_MAX_FIFODMA_GENERAL_MAX_NOF_HOST_ENTRIES
#define DNX_DATA_MAX_FIFODMA_GENERAL_MAX_NOF_HOST_ENTRIES (16384)





#endif 

