
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_TSN_H_

#define _DNX_DATA_MAX_TSN_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_TIME (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_TIME
#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_TIME (128)


#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_ATTEMPTS (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_ATTEMPTS
#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_ATTEMPTS (8)


#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_TX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_TX
#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_TX (512)


#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_TX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_TX
#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_TX (64)


#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_RX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_RX
#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_RX (256)


#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_RX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_RX
#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_RX (64)


#define DNX_DATA_MAX_TSN_PREEMPTION_FRAG_SIZE_BYTES_IN_HW_UNIT (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_FRAG_SIZE_BYTES_IN_HW_UNIT
#define DNX_DATA_MAX_TSN_PREEMPTION_FRAG_SIZE_BYTES_IN_HW_UNIT (8)


#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_NS (1)

#undef DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_NS
#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_NS (1000)


#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_MIN_NS (1)

#undef DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_MIN_NS
#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_MIN_NS (400)


#define DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_NOF_BITS (1)

#undef DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_NOF_BITS
#define DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_NOF_BITS (48)


#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_NOF_BITS (1)

#undef DNX_DATA_MAX_TSN_TIME_TAS_TOD_NOF_BITS
#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_NOF_BITS (48)


#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_SOURCE (1)

#undef DNX_DATA_MAX_TSN_TIME_TAS_TOD_SOURCE
#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_SOURCE (1)


#define DNX_DATA_MAX_TSN_TAS_MAX_TIME_INTERVALS_ENTRIES (1)

#undef DNX_DATA_MAX_TSN_TAS_MAX_TIME_INTERVALS_ENTRIES
#define DNX_DATA_MAX_TSN_TAS_MAX_TIME_INTERVALS_ENTRIES (127)


#define DNX_DATA_MAX_TSN_TAS_NOF_TAS_PORTS (1)

#undef DNX_DATA_MAX_TSN_TAS_NOF_TAS_PORTS
#define DNX_DATA_MAX_TSN_TAS_NOF_TAS_PORTS (66)


#define DNX_DATA_MAX_TSN_TAS_MAX_PROFILES_PER_PORT (1)

#undef DNX_DATA_MAX_TSN_TAS_MAX_PROFILES_PER_PORT
#define DNX_DATA_MAX_TSN_TAS_MAX_PROFILES_PER_PORT (2)





#endif 

