
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_SRV6_H_

#define _DNX_DATA_MAX_SRV6_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_PSP_EXTENDED (1)

#undef DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_PSP_EXTENDED
#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_PSP_EXTENDED (23)


#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_PSP (1)

#undef DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_PSP
#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_PSP (9)


#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USP (1)

#undef DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USP
#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USP (23)


#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USP_1PASS (1)

#undef DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USP_1PASS
#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USP_1PASS (9)


#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USD_1PASS (1)

#undef DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USD_1PASS
#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_TERMINATED_SIDS_USD_1PASS (9)


#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_LOCATORS (1)

#undef DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_LOCATORS
#define DNX_DATA_MAX_SRV6_TERMINATION_MAX_NOF_LOCATORS (0)


#define DNX_DATA_MAX_SRV6_ENCAPSULATION_MAX_NOF_ENCAP_SIDS_MAIN_PASS (1)

#undef DNX_DATA_MAX_SRV6_ENCAPSULATION_MAX_NOF_ENCAP_SIDS_MAIN_PASS
#define DNX_DATA_MAX_SRV6_ENCAPSULATION_MAX_NOF_ENCAP_SIDS_MAIN_PASS (5)


#define DNX_DATA_MAX_SRV6_ENCAPSULATION_NOF_ENCAP_SIDS_EXTENDED_PASS (1)

#undef DNX_DATA_MAX_SRV6_ENCAPSULATION_NOF_ENCAP_SIDS_EXTENDED_PASS
#define DNX_DATA_MAX_SRV6_ENCAPSULATION_NOF_ENCAP_SIDS_EXTENDED_PASS (5)





#endif 

