
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_SNIF_H_

#define _DNX_DATA_MAX_SNIF_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_STANDARD (1)

#undef DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_STANDARD
#define DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_STANDARD (0)


#define DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_SFLOW (1)

#undef DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_SFLOW
#define DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_SFLOW (1)


#define DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_MIRROR_ON_DROP (1)

#undef DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_MIRROR_ON_DROP
#define DNX_DATA_MAX_SNIF_GENERAL_CUD_TYPE_MIRROR_ON_DROP (2)


#define DNX_DATA_MAX_SNIF_INGRESS_NOF_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_NOF_PROFILES
#define DNX_DATA_MAX_SNIF_INGRESS_NOF_PROFILES (32)


#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_NOF_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_MIRROR_NOF_PROFILES
#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_NOF_PROFILES (16)


#define DNX_DATA_MAX_SNIF_INGRESS_NOF_MIRROR_ON_DROP_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_NOF_MIRROR_ON_DROP_PROFILES
#define DNX_DATA_MAX_SNIF_INGRESS_NOF_MIRROR_ON_DROP_PROFILES (8)


#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_NOF_VLAN_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_MIRROR_NOF_VLAN_PROFILES
#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_NOF_VLAN_PROFILES (6)


#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_DEFAULT_TAGGED_PROFILE (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_MIRROR_DEFAULT_TAGGED_PROFILE
#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_DEFAULT_TAGGED_PROFILE (6)


#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_UNTAGGED_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_MIRROR_UNTAGGED_PROFILES
#define DNX_DATA_MAX_SNIF_INGRESS_MIRROR_UNTAGGED_PROFILES (7)


#define DNX_DATA_MAX_SNIF_INGRESS_PROB_MAX_VAL (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_PROB_MAX_VAL
#define DNX_DATA_MAX_SNIF_INGRESS_PROB_MAX_VAL (16777215)


#define DNX_DATA_MAX_SNIF_INGRESS_CROP_SIZE (1)

#undef DNX_DATA_MAX_SNIF_INGRESS_CROP_SIZE
#define DNX_DATA_MAX_SNIF_INGRESS_CROP_SIZE (256)


#define DNX_DATA_MAX_SNIF_EGRESS_MIRROR_NOF_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_MIRROR_NOF_PROFILES
#define DNX_DATA_MAX_SNIF_EGRESS_MIRROR_NOF_PROFILES (8)


#define DNX_DATA_MAX_SNIF_EGRESS_SNOOP_NOF_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_SNOOP_NOF_PROFILES
#define DNX_DATA_MAX_SNIF_EGRESS_SNOOP_NOF_PROFILES (8)


#define DNX_DATA_MAX_SNIF_EGRESS_MIRROR_NOF_VLAN_PROFILES (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_MIRROR_NOF_VLAN_PROFILES
#define DNX_DATA_MAX_SNIF_EGRESS_MIRROR_NOF_VLAN_PROFILES (7)


#define DNX_DATA_MAX_SNIF_EGRESS_MIRROR_DEFAULT_PROFILE (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_MIRROR_DEFAULT_PROFILE
#define DNX_DATA_MAX_SNIF_EGRESS_MIRROR_DEFAULT_PROFILE (7)


#define DNX_DATA_MAX_SNIF_EGRESS_PROB_MAX_VAL (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_PROB_MAX_VAL
#define DNX_DATA_MAX_SNIF_EGRESS_PROB_MAX_VAL (-1)


#define DNX_DATA_MAX_SNIF_EGRESS_PROB_NOF_BITS (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_PROB_NOF_BITS
#define DNX_DATA_MAX_SNIF_EGRESS_PROB_NOF_BITS (32)


#define DNX_DATA_MAX_SNIF_EGRESS_PROBABILITY_NOF_PROFILES (1)

#define DNX_DATA_MAX_SNIF_EGRESS_CROP_SIZE_NOF_PROFILES (1)

#define DNX_DATA_MAX_SNIF_EGRESS_CROP_SIZE_GRANULARITY (1)

#undef DNX_DATA_MAX_SNIF_EGRESS_CROP_SIZE_GRANULARITY
#define DNX_DATA_MAX_SNIF_EGRESS_CROP_SIZE_GRANULARITY (128)





#endif 

