
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SWSTATEDNX_GENERAL

#include <soc/dnxc/swstate/dnxc_sw_state_c_includes.h>
#include <soc/dnx/swstate/auto_generated/access/dnx_field_access.h>



const char *
dnx_field_stage_e_get_name(dnx_field_stage_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_INVALID", value, DNX_FIELD_STAGE_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_FIRST", value, DNX_FIELD_STAGE_FIRST);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_IPMF1", value, DNX_FIELD_STAGE_IPMF1);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_IPMF2", value, DNX_FIELD_STAGE_IPMF2);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_IPMF3", value, DNX_FIELD_STAGE_IPMF3);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_EPMF", value, DNX_FIELD_STAGE_EPMF);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_ACE", value, DNX_FIELD_STAGE_ACE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_EXTERNAL", value, DNX_FIELD_STAGE_EXTERNAL);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_L4_OPS", value, DNX_FIELD_STAGE_L4_OPS);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_STAGE_NOF", value, DNX_FIELD_STAGE_NOF);

    return NULL;
}




const char *
dnx_field_group_type_e_get_name(dnx_field_group_type_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_INVALID", value, DNX_FIELD_GROUP_TYPE_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_FIRST", value, DNX_FIELD_GROUP_TYPE_FIRST);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_TCAM", value, DNX_FIELD_GROUP_TYPE_TCAM);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_DIRECT_TABLE_TCAM", value, DNX_FIELD_GROUP_TYPE_DIRECT_TABLE_TCAM);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_DIRECT_TABLE_MDB", value, DNX_FIELD_GROUP_TYPE_DIRECT_TABLE_MDB);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_EXEM", value, DNX_FIELD_GROUP_TYPE_EXEM);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_STATE_TABLE", value, DNX_FIELD_GROUP_TYPE_STATE_TABLE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_DIRECT_EXTRACTION", value, DNX_FIELD_GROUP_TYPE_DIRECT_EXTRACTION);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_CONST", value, DNX_FIELD_GROUP_TYPE_CONST);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_KBP", value, DNX_FIELD_GROUP_TYPE_KBP);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_GROUP_TYPE_NOF", value, DNX_FIELD_GROUP_TYPE_NOF);

    return NULL;
}




const char *
dnx_field_key_length_type_e_get_name(dnx_field_key_length_type_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_INVALID", value, DNX_FIELD_KEY_LENGTH_TYPE_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_DT", value, DNX_FIELD_KEY_LENGTH_TYPE_DT);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_HALF", value, DNX_FIELD_KEY_LENGTH_TYPE_HALF);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_SINGLE", value, DNX_FIELD_KEY_LENGTH_TYPE_SINGLE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_DOUBLE", value, DNX_FIELD_KEY_LENGTH_TYPE_DOUBLE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_NONE", value, DNX_FIELD_KEY_LENGTH_TYPE_NONE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_KEY_LENGTH_TYPE_NOF", value, DNX_FIELD_KEY_LENGTH_TYPE_NOF);

    return NULL;
}




const char *
dnx_field_action_length_type_e_get_name(dnx_field_action_length_type_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_INVALID", value, DNX_FIELD_ACTION_LENGTH_TYPE_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_TCAM_HALF", value, DNX_FIELD_ACTION_LENGTH_TYPE_TCAM_HALF);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_TCAM_SINGLE", value, DNX_FIELD_ACTION_LENGTH_TYPE_TCAM_SINGLE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_TCAM_DOUBLE", value, DNX_FIELD_ACTION_LENGTH_TYPE_TCAM_DOUBLE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_LEXEM", value, DNX_FIELD_ACTION_LENGTH_TYPE_LEXEM);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_SEXEM", value, DNX_FIELD_ACTION_LENGTH_TYPE_SEXEM);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_ACE", value, DNX_FIELD_ACTION_LENGTH_TYPE_ACE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_DIR_EXT", value, DNX_FIELD_ACTION_LENGTH_TYPE_DIR_EXT);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_KBP", value, DNX_FIELD_ACTION_LENGTH_TYPE_KBP);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_MDB_DT", value, DNX_FIELD_ACTION_LENGTH_TYPE_MDB_DT);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_NONE", value, DNX_FIELD_ACTION_LENGTH_TYPE_NONE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_STATE_TABLE", value, DNX_FIELD_ACTION_LENGTH_TYPE_STATE_TABLE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_LENGTH_TYPE_NOF", value, DNX_FIELD_ACTION_LENGTH_TYPE_NOF);

    return NULL;
}




const char *
dnx_field_layer_index_e_get_name(dnx_field_layer_index_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_INVALID", value, DNX_FIELD_LAYER_INDEX_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_0", value, DNX_FIELD_LAYER_INDEX_0);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_1", value, DNX_FIELD_LAYER_INDEX_1);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_2", value, DNX_FIELD_LAYER_INDEX_2);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_3", value, DNX_FIELD_LAYER_INDEX_3);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_4", value, DNX_FIELD_LAYER_INDEX_4);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_5", value, DNX_FIELD_LAYER_INDEX_5);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_6", value, DNX_FIELD_LAYER_INDEX_6);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_INDEX_7", value, DNX_FIELD_LAYER_INDEX_7);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_LAYER_NOF", value, DNX_FIELD_LAYER_NOF);

    return NULL;
}




const char *
dnx_field_input_type_e_get_name(dnx_field_input_type_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_INVALID", value, DNX_FIELD_INPUT_TYPE_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_LAYER_FWD", value, DNX_FIELD_INPUT_TYPE_LAYER_FWD);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_LAYER_ABSOLUTE", value, DNX_FIELD_INPUT_TYPE_LAYER_ABSOLUTE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_META_DATA", value, DNX_FIELD_INPUT_TYPE_META_DATA);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_META_DATA2", value, DNX_FIELD_INPUT_TYPE_META_DATA2);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_LAYER_RECORDS_FWD", value, DNX_FIELD_INPUT_TYPE_LAYER_RECORDS_FWD);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_LAYER_RECORDS_ABSOLUTE", value, DNX_FIELD_INPUT_TYPE_LAYER_RECORDS_ABSOLUTE);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_KBP", value, DNX_FIELD_INPUT_TYPE_KBP);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_CASCADED", value, DNX_FIELD_INPUT_TYPE_CASCADED);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_CONST", value, DNX_FIELD_INPUT_TYPE_CONST);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_INPUT_TYPE_NOF", value, DNX_FIELD_INPUT_TYPE_NOF);

    return NULL;
}




const char *
dnx_field_action_class_e_get_name(dnx_field_action_class_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_INVALID", value, DNX_FIELD_ACTION_CLASS_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_FIRST", value, DNX_FIELD_ACTION_CLASS_FIRST);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_STATIC", value, DNX_FIELD_ACTION_CLASS_STATIC);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_USER", value, DNX_FIELD_ACTION_CLASS_USER);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_SW", value, DNX_FIELD_ACTION_CLASS_SW);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_VW", value, DNX_FIELD_ACTION_CLASS_VW);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_ACTION_CLASS_NOF", value, DNX_FIELD_ACTION_CLASS_NOF);

    return NULL;
}




const char *
dnx_field_qual_class_e_get_name(dnx_field_qual_class_e value)
{
    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_INVALID", value, DNX_FIELD_QUAL_CLASS_INVALID);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_FIRST", value, DNX_FIELD_QUAL_CLASS_FIRST);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_META", value, DNX_FIELD_QUAL_CLASS_META);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_META2", value, DNX_FIELD_QUAL_CLASS_META2);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_LAYER_RECORD", value, DNX_FIELD_QUAL_CLASS_LAYER_RECORD);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_USER", value, DNX_FIELD_QUAL_CLASS_USER);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_HEADER", value, DNX_FIELD_QUAL_CLASS_HEADER);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_SW", value, DNX_FIELD_QUAL_CLASS_SW);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_VW", value, DNX_FIELD_QUAL_CLASS_VW);

    DNX_SW_STATE_ENUM_COMPARE_AND_GET_NAME("DNX_FIELD_QUAL_CLASS_NOF", value, DNX_FIELD_QUAL_CLASS_NOF);

    return NULL;
}



#undef BSL_LOG_MODULE
