# -*- Makefile -*-
# $Id: Makefile,v 1.2 2004/03/05 18:55:51 mlarsen Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = systems/linux/kernel/user/shared

include ${SDK}/make/Make.config

CFLAGS += -I../../modules/include

lib = libuser

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
