/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from Logical Table mapping files.
 *
 * Tool: $SDK/INTERNAL/fltg/bin/fltg
 *
 * Edits to this file will be lost when it is regenerated.
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#ifndef BCM56990_B0_LTD_CONFIG_VARIANT_H
#define BCM56990_B0_LTD_CONFIG_VARIANT_H

#ifndef DOXYGEN_IGNORE_AUTOGEN

#if BCMDRD_CONFIG_INCLUDE_BCM56990_B0
#ifndef BCMLTD_CONFIG_INCLUDE_BCM56990_B0_BASE
#define BCMLTD_CONFIG_INCLUDE_BCM56990_B0_BASE BCMLTD_CONFIG_INCLUDE_VARIANT_DEFAULT
#endif
#else
#define BCMLTD_CONFIG_INCLUDE_BCM56990_B0_BASE 0
#endif

#define BCMLTD_VARIANT_BCM56990_B0_BASE 4
#define BCMLTD_VARIANT_LOCAL_BCM56990_B0_BASE 0

#endif /* DOXYGEN_IGNORE_AUTOGEN */

#endif /* BCM56990_B0_LTD_CONFIG_VARIANT_H */
