# $Id: $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM MONTEREY driver Library
#

LOCALDIR = src/bcm/esw/monterey

include ${SDK}/make/Make.config

lib = libmonterey

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

