#
# $Id: Makefile,v 1.3 2012/02/27 15:20:19 omri Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dpp/PORT/

include ${SDK}/make/Make.config

lib = libsoc_dpp_port

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
