/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:    tomahawk_cos.c
 * Purpose: Maintains all the debug information for cos
 *          feature for tomahawk.
*/

#include <appl/diag/techsupport.h>
#include <soc/mcm/allenum.h>

extern char * techsupport_cos_diag_cmdlist[];
extern char * techsupport_cos_sw_dump_cmdlist[];

/* "cos" feature's diag command list valid only for Tomahawk */
char * techsupport_cos_tomahawk_diag_cmdlist[] = {
     NULL /* Must be the last element in this structure */
 };

#ifndef BCM_SW_STATE_DUMP_DISABLE
/* "cos" feature's software dump command list valid only for Tomahawk */
char * techsupport_cos_tomahawk_sw_dump_cmdlist[] = {
    NULL /* Must be the last element in this structure */
};
#endif /* BCM_SW_STATE_DUMP_DISABLE */


/* Structure that maintains memory list for
 * "cos" feature for Tomahawk chipset. */
static soc_mem_t techsupport_cos_tomahawk_memory_table_list[] = {
    CPU_TS_MAPm,
    ING_ETAG_PCP_MAPPINGm,
    ING_MPLS_EXP_MAPPINGm,
    ING_OUTER_DOT1P_MAPPING_TABLEm,
    DSCP_TABLEm,
    ING_PRI_CNG_MAPm,
    ING_UNTAGGED_PHBm,
    ING_ROUTED_INT_PRI_MAPPINGm,
    COS_MAP_SELm,
    CPU_COS_MAPm,
    IFP_COS_MAPm,
    INT_CN_TO_MMUIF_MAPPINGm,
    PHB2_COS_MAPm,
    PORT_COS_MAPm,
    THDI_PORT_PG_BST_XPE0_PIPE0m,
    THDI_PORT_PG_BST_XPE0_PIPE3m,
    THDI_PORT_PG_BST_XPE1_PIPE0m,
    THDI_PORT_PG_BST_XPE1_PIPE3m,
    THDI_PORT_PG_BST_XPE2_PIPE1m,
    THDI_PORT_PG_BST_XPE2_PIPE2m,
    THDI_PORT_PG_BST_XPE3_PIPE1m,
    THDI_PORT_PG_BST_XPE3_PIPE2m,
    THDI_PORT_SP_BST_XPE0_PIPE0m,
    THDI_PORT_SP_BST_XPE0_PIPE3m,
    MMU_WRED_AVG_QSIZEm,
    MMU_WRED_CONFIGm,
    MMU_WRED_PORT_SP_DROP_THDm,
    MMU_WRED_PORT_SP_DROP_THD_MARKm,
    MMU_WRED_PORT_SP_SHARED_COUNTm,
    MMU_WRED_AVG_QSIZE_XPE0_PIPE0m,
    MMU_WRED_AVG_QSIZE_XPE0_PIPE1m,
    MMU_WRED_AVG_QSIZE_XPE1_PIPE2m,
    MMU_WRED_AVG_QSIZE_XPE1_PIPE3m,
    MMU_WRED_AVG_QSIZE_XPE2_PIPE0m,
    MMU_WRED_AVG_QSIZE_XPE2_PIPE1m,
    MMU_WRED_AVG_QSIZE_XPE3_PIPE2m,
    MMU_WRED_AVG_QSIZE_XPE3_PIPE3m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE0_PIPE0m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE0_PIPE1m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE1_PIPE2m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE1_PIPE3m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE2_PIPE0m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE2_PIPE1m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE3_PIPE2m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_XPE3_PIPE3m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE0_PIPE0m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE0_PIPE1m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE1_PIPE2m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE1_PIPE3m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE2_PIPE0m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE2_PIPE1m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE3_PIPE2m,
    MMU_WRED_UC_QUEUE_TOTAL_COUNT_FROM_REMOTE_XPE3_PIPE3m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE0_PIPE0m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE0_PIPE1m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE1_PIPE2m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE1_PIPE3m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE2_PIPE0m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE2_PIPE1m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE3_PIPE2m,
    MMU_WRED_UC_QUEUE_DROP_THD_0_XPE3_PIPE3m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE0_PIPE0m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE0_PIPE1m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE1_PIPE2m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE1_PIPE3m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE2_PIPE0m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE2_PIPE1m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE3_PIPE2m,
    MMU_WRED_UC_QUEUE_DROP_THD_1_XPE3_PIPE3m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE0_PIPE0m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE0_PIPE1m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE1_PIPE2m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE1_PIPE3m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE2_PIPE0m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE2_PIPE1m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE3_PIPE2m,
    MMU_WRED_UC_QUEUE_DROP_THD_MARK_XPE3_PIPE3m,
    MMU_WRED_DROP_CURVE_PROFILE_0m,
    MMU_WRED_DROP_CURVE_PROFILE_0_Am,
    MMU_WRED_DROP_CURVE_PROFILE_0_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_1m,
    MMU_WRED_DROP_CURVE_PROFILE_1_Am,
    MMU_WRED_DROP_CURVE_PROFILE_1_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_2m,
    MMU_WRED_DROP_CURVE_PROFILE_2_Am,
    MMU_WRED_DROP_CURVE_PROFILE_2_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_3m,
    MMU_WRED_DROP_CURVE_PROFILE_3_Am,
    MMU_WRED_DROP_CURVE_PROFILE_3_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_4m,
    MMU_WRED_DROP_CURVE_PROFILE_4_Am,
    MMU_WRED_DROP_CURVE_PROFILE_4_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_5m,
    MMU_WRED_DROP_CURVE_PROFILE_5_Am,
    MMU_WRED_DROP_CURVE_PROFILE_5_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_6m,
    MMU_WRED_DROP_CURVE_PROFILE_6_Am,
    MMU_WRED_DROP_CURVE_PROFILE_6_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_7m,
    MMU_WRED_DROP_CURVE_PROFILE_7_Am,
    MMU_WRED_DROP_CURVE_PROFILE_7_Bm,
    MMU_WRED_DROP_CURVE_PROFILE_8m,
    MMU_WRED_DROP_CURVE_PROFILE_8_Am,
    MMU_WRED_DROP_CURVE_PROFILE_8_Bm,
    MMU_THDU_BST_QUEUE_XPE0_PIPE0m,
    MMU_THDU_BST_QUEUE_XPE0_PIPE1m,
    MMU_THDU_BST_QUEUE_XPE1_PIPE2m,
    MMU_THDU_BST_QUEUE_XPE1_PIPE3m,
    MMU_THDU_BST_QUEUE_XPE2_PIPE0m,
    MMU_THDU_BST_QUEUE_XPE2_PIPE1m,
    MMU_THDU_BST_QUEUE_XPE3_PIPE2m,
    MMU_THDU_BST_QUEUE_XPE3_PIPE3m,
    MMU_THDU_Q_TO_QGRP_MAP_PIPE0m,
    MMU_THDU_Q_TO_QGRP_MAP_PIPE1m,
    MMU_THDU_Q_TO_QGRP_MAP_PIPE2m,
    MMU_THDU_Q_TO_QGRP_MAP_PIPE3m,
    MMU_THDM_DB_QUEUE_BST_XPE0_PIPE0m,
    MMU_THDM_DB_QUEUE_BST_XPE0_PIPE1m,
    MMU_THDM_DB_QUEUE_BST_XPE1_PIPE2m,
    MMU_THDM_DB_QUEUE_BST_XPE1_PIPE3m,
    MMU_THDM_DB_QUEUE_BST_XPE2_PIPE0m,
    MMU_THDM_DB_QUEUE_BST_XPE2_PIPE1m,
    MMU_THDM_DB_QUEUE_BST_XPE3_PIPE2m,
    MMU_THDM_DB_QUEUE_BST_XPE3_PIPE3m,
    MMU_MTRO_EGRMETERINGBUCKET_MEM_PIPE0m,
    MMU_MTRO_EGRMETERINGBUCKET_MEM_PIPE1m,
    MMU_MTRO_EGRMETERINGBUCKET_MEM_PIPE2m,
    MMU_MTRO_EGRMETERINGBUCKET_MEM_PIPE3m,
    MMU_MTRO_EGRMETERINGCONFIG_MEM_PIPE0m,
    MMU_MTRO_EGRMETERINGCONFIG_MEM_PIPE1m,
    MMU_MTRO_EGRMETERINGCONFIG_MEM_PIPE2m,
    MMU_MTRO_EGRMETERINGCONFIG_MEM_PIPE3m,
    MMU_MTRO_BUCKET_L0_MEM_PIPE0m,
    MMU_MTRO_BUCKET_L0_MEM_PIPE1m,
    MMU_MTRO_BUCKET_L0_MEM_PIPE2m,
    MMU_MTRO_BUCKET_L0_MEM_PIPE3m,
    MMU_MTRO_BUCKET_L1_MEM_PIPE0m,
    MMU_MTRO_BUCKET_L1_MEM_PIPE1m,
    MMU_MTRO_BUCKET_L1_MEM_PIPE2m,
    MMU_MTRO_BUCKET_L1_MEM_PIPE3m,
    MMU_MTRO_L0_MEM_PIPE0m,
    MMU_MTRO_L0_MEM_PIPE1m,
    MMU_MTRO_L0_MEM_PIPE2m,
    MMU_MTRO_L0_MEM_PIPE3m,
    MMU_MTRO_L1_MEM_PIPE0m,
    MMU_MTRO_L1_MEM_PIPE1m,
    MMU_MTRO_L1_MEM_PIPE2m,
    MMU_MTRO_L1_MEM_PIPE3m,
    Q_SCHED_L0_WEIGHT_MEM_PIPE0m,
    Q_SCHED_L0_WEIGHT_MEM_PIPE1m,
    EGR_DSCP_TABLEm,
    EGR_ETAG_PCP_MAPPINGm,
    EGR_MPLS_EXP_MAPPING_1m,
    EGR_MPLS_EXP_MAPPING_2m,
    EGR_PRI_CNG_MAPm,
    EGR_DSCP_ECN_MAPm,
    EGR_INT_CN_TO_IP_MAPPINGm,
    EGR_MPLS_EXP_PRI_MAPPINGm,
    INVALIDm /* Must be the last element in this structure */
};

/* Structure that maintains register list for
 * "cos" feature for Tomahawk chipset. */
techsupport_reg_t techsupport_cos_tomahawk_reg_list[] = {
    {CFAPBSTSTATr, register_type_global },
    {CMIC_CMC0_CH0_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC0_CH0_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC0_CH1_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC0_CH1_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC0_CH2_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC0_CH2_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC0_CH3_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC0_CH3_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC0_PROGRAMMABLE_COS_MASK0r, register_type_global },
    {CMIC_CMC0_PROGRAMMABLE_COS_MASK1r, register_type_global },
    {CMIC_CMC1_CH0_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC1_CH0_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC1_CH1_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC1_CH1_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC1_CH2_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC1_CH2_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC1_CH3_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC1_CH3_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC1_PROGRAMMABLE_COS_MASK0r, register_type_global },
    {CMIC_CMC1_PROGRAMMABLE_COS_MASK1r, register_type_global },
    {CMIC_CMC2_CH0_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC2_CH0_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC2_CH1_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC2_CH1_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC2_CH2_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC2_CH2_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC2_CH3_COS_CTRL_RX_0r, register_type_global },
    {CMIC_CMC2_CH3_COS_CTRL_RX_1r, register_type_global },
    {CMIC_CMC2_PROGRAMMABLE_COS_MASK0r, register_type_global },
    {CMIC_CMC2_PROGRAMMABLE_COS_MASK1r, register_type_global },
    {CMIC_PKT_COS_0r, register_type_global },
    {CMIC_PKT_COS_1r, register_type_global },
    {CMIC_PKT_COS_QUEUES_HIr, register_type_global },
    {CMIC_PKT_COS_QUEUES_LOr, register_type_global },
    {ING_COS_MODE_64r, register_type_global },
    {ING_MIRROR_COS_CONTROLr, register_type_global },
    {MMU_GCFG_BST_HW_SNAPSHOT_ENr, register_type_global },
    {MMU_GCFG_BST_SNAPSHOT_ACTION_ENr, register_type_global },
    {MMU_GCFG_BST_TRACKING_ENABLEr, register_type_global },
    {MMU_GCFG_MISCCONFIGr, register_type_global },
    {MMU_SCFG_MISCCONFIGr, register_type_global },
    {MMU_SCFG_SC_CPU_INT_ENr, register_type_global },
    {MMU_TO_XPORT_BKPr, register_type_global },
    {MMU_WRED_EN_COR_ERR_RPTr, register_type_global },
    {MMU_XCFG_XPE_CPU_INT_ENr, register_type_global },
    {MTRO_REFRESH_CONFIGr, register_type_global },
    {MTRO_REFRESH_STATUSr, register_type_global },
    {PRIO2COS_PROFILEr, register_type_global },
    {PRIORITY_CONTROLr, register_type_global },
    {Q_SCHED_PORT_CONFIGr, register_type_global },
    {STORM_CONTROL_METER_CONFIGr, register_type_global },
    {STORM_CONTROL_METER_MAPPINGr, register_type_global },
    {THD_MISC_CONTROLr, register_type_global },
    {THDI_HDRM_POOL_CFGr, register_type_global },
    {THDI_PORT_PG_SPIDr, register_type_global },
    {THDI_PORT_PRI_GRP0r, register_type_global },
    {WRED_CONG_NOTIFICATION_RESOLUTION_TABLEr, register_type_global },
    {WRED_POOL_INST_CONG_LIMIT_0r, register_type_global },
    {WRED_POOL_INST_CONG_LIMIT_1r, register_type_global },
    {WRED_POOL_INST_CONG_LIMIT_2r, register_type_global },
    {WRED_POOL_INST_CONG_LIMIT_3r, register_type_global },
    {WRED_REFRESH_CONTROLr, register_type_global },
    {WREDMEMDEBUG_AVG_QSIZE_TMr, register_type_global },
    {WREDMEMDEBUG_CONFIG_TMr, register_type_global },
    {WREDMEMDEBUG_DROP_CURVE_PROFILE_TMr, register_type_global },
    {WREDMEMDEBUG_PORT_SP_DROP_THD_TMr, register_type_global },
    {WREDMEMDEBUG_PORT_SP_SHARED_COUNT_TMr, register_type_global },
    {WREDMEMDEBUG_UC_QUEUE_DROP_THD_0_TMr, register_type_global },
    {WREDMEMDEBUG_UC_QUEUE_DROP_THD_1_TMr, register_type_global },
    {WREDMEMDEBUG_UC_QUEUE_DROP_THD_MARK_TMr, register_type_global },
    {WREDMEMDEBUG_UC_QUEUE_TOTAL_COUNT_TMr, register_type_global },
    {XPORT_TO_MMU_BKPr, register_type_global },
    {INVALIDr, register_type_global } /* Must be the last element in this structure */
};

/* Structure that maintains  diag cmdlist, reg_list, mem_list  for
 * "cos" feature for Tomahawk chipset. */
techsupport_data_t techsupport_cos_tomahawk_data = {
    techsupport_cos_diag_cmdlist,
    techsupport_cos_tomahawk_reg_list,
    techsupport_cos_tomahawk_memory_table_list,
    techsupport_cos_tomahawk_diag_cmdlist
#ifndef BCM_SW_STATE_DUMP_DISABLE
    , techsupport_cos_sw_dump_cmdlist,
    techsupport_cos_tomahawk_sw_dump_cmdlist
#endif /* BCM_SW_STATE_DUMP_DISABLE */
};

