/*! \file bcm56990_b0_fp_egr_qual_db.c
 *
 * EFP qualifier configuration DB initialization function
 * for Tomahawk-4 B0(56990_B0).
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <shr/shr_error.h>
#include <shr/shr_debug.h>
#include <bcmfp/bcmfp_internal.h>
#include <bcmfp/chip/bcm56990_b0_fp.h>
#include <bcmltd/chip/bcmltd_id.h>

#define BSL_LOG_MODULE BSL_LS_BCMFP_DEV

int
bcmfp_bcm56990_b0_egress_qual_cfg_db_init(int unit,
                                          bcmfp_stage_t *stage)
{
    uint32_t offset1 = 0;
    uint32_t offset2 = 0;
    uint32_t offset3 = 0;
    uint32_t offset4 = 0;
    uint32_t offset7 = 0;
    uint32_t offset8 = 0;
    uint32_t fid = 0;
    bcmfp_qual_flags_bmp_t qual_flags;

    BCMFP_QUAL_CFG_OFF_DECL;

    SHR_FUNC_ENTER(unit);

    SHR_NULL_CHECK(stage, SHR_E_PARAM);

    sal_memset(&qual_flags, 0, sizeof(bcmfp_qual_flags_bmp_t));

    /* EFP_KEY4(L2 Key) Qualifiers */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 105, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP mapped to EFP_KEY4_L3_CLASS_ID_SELECTOR
     * in bcm56990_b0*/
    /* U_EG_NEXT_HOP_CLASS_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* U_L3_IIF_CLASS_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* O_NEXT_HOP_CLASS_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* O_L3_IIF_CLASS_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP_GROUP_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 20, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVP_GROUP_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 20, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_DVP, 6);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVPf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 93, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 33, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_COLORf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 97, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L2_FORMATf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 46, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ETHERTYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 154, 48);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SRC_MACf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 106, 48);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DST_MACf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 82, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 99, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L3_ROUTABLE_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 202, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_MIRR_COPYf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 205, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 217, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_CFIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 218, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 221, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SFLOW_SAMPLEDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 202, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VLAN_OUTER_PRESENTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 203, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OPAQUE_TAG_PRESENTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 37, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_PORT_GRP_OR_PORT_SYSTEM_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 16, 4);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_ID_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 4, 6);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY4_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_CPU_COSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 100, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 65, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 65, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VRFf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 65, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VPNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 79, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 91, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_CNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 35, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DROP_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY4, offset4 + 36, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_PORT_GRP_OR_PORT_SYSTEM_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EFP_KEY1(IPv4 Key) Qualifiers */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 154, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 102, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 20, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_COLORf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 106, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_FRAGf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 207, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_TCP_FLAGSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 122, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4DST_PORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 138, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4SRC_PORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 138, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ICMP_TYPE_CODEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 223, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_TTLf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 108, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_PROTOCOLf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 23, 32);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DST_IP4f;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 175, 32);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SRC_IP4f;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 215, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_TOSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 91, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 116, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L3_ROUTABLE_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 155, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_MIRR_COPYf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 158, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 170, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_CFIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 171, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 174, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SFLOW_SAMPLEDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 156, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VLAN_OUTER_PRESENTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 65, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 117, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 16, 4);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_ID_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 4, 12)
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 4, 12)
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP_GROUP_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 4, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVP_GROUP_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 74, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 74, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VRFf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 74, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VPNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 88, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 100, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_CNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 55, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DROP_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset1 + 56, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_PORT_GRP_OR_PORT_SYSTEM_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EFP_KEY2 (IPv6 Singlewide Key) Qualifiers */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 193, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 195, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_PROTOCOLf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 59, 128);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_IP_ADDR, EGR_MODE_SIP6);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SRC_IP6f;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 59, 128);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_IP_ADDR, EGR_MODE_DIP6);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DST_IP6f;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 59, 64);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_IP_ADDR, EGR_MODE_SIP_DIP_64);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SRC_IP6_HIGHf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 123, 64);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_IP_ADDR, EGR_MODE_SIP_DIP_64);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DST_IP6_HIGHf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 222, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_TOSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 48, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 187, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L3_ROUTABLE_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 194, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_MIRR_COPYf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 205, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 221, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SFLOW_SAMPLEDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 217, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_CFIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 218, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTER_VLAN_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 203, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VLAN_OUTER_PRESENTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 16, 4);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_ID_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY2_CLASS_ID, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP_GROUP_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY1, offset2 + 4, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY1_CLASS_ID, 6);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVP_GROUP_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 188, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 31, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 31, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VRFf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 31, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VPNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 45, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 57, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_CNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 21, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DROP_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY2, offset2 + 22, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_PORT_GRP_OR_PORT_SYSTEM_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EFP_KEY3 (IPv6 Double Wide Key) Qualifiers */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 211, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 212, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_SRV6_SRH_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 168, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 17, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_COLORf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 172, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_FRAGf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 213, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_TCP_FLAGSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 179, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4DST_PORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 195, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_L4SRC_PORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 195, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ICMP_TYPE_CODEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 221, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_TTLf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 20, 128);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DST_IP6f;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 157, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_FIRST_EH_SUBCODEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 149, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_FIRST_EH_PROTOf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 174, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_IP_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY3_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY3_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY3_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY3_CLASS_ID, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP_GROUP_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 4, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY3_CLASS_ID, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVP_GROUP_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 166, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_CNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY3, offset3 + 148, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DROP_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EFP_KEY7(Loopback Key) qualifiers. LOOPBACK_MH */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 0, 8);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_PP_PORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 0, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_TRAFFIC_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_COLORf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 90, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_MASQUERADE_PKT_PROFILEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 93, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VISIBILITY_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 94, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_SRC_PORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 111, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 116, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_LOOPBACK_QUEUEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 43, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 33, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 54, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 20, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_COLORf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 16, 4);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY7_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_ID_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY7_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY7_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY7_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY7_CLASS_ID, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY7_CLASS_ID, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP_GROUP_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 4, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY3_CLASS_ID, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVP_GROUP_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 52, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_CNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 23, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DROP_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY7, offset7 + 24, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_PORT_GRP_OR_PORT_SYSTEM_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EFP_KEY8(Bytes After L2 Key) Qualifiers */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 33, 64);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_DISABLE, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_BYTES_0_7_AFTER_L2HEADERf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 97, 64);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_DISABLE, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_BYTES_8_15_AFTER_L2HEADERf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 161, 16);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_DISABLE, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_BYTES_16_17_AFTER_L2HEADERf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_UNDERLAY_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 3);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_NHOP_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 20, 12);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_L3_IIF_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP_GROUP_ID */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 20, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_DVP, 5);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVP_GROUP_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    /* EGR_DVP */
    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 20, 13);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_DVP, 6);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_EGR_DVPf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 234, 4);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_PRIf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 177, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_COLORf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 190, 16);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ETHERTYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 223, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 238, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_MIRR_COPYf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 16, 4);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_ID_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 0);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_ING_CLASS_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 4, 9);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_OUTPORTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 4, 6);
    BCMFP_QUAL_CFG_CTRL_SEL_ADD(BCMFP_EXT_CTRL_SEL_EGR_KEY8_CLASS_ID, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_CPU_COSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 206, 12);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_VLAN_IDf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 206, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VRFf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 206, 14);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_VPNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 220, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_FWD_TYPEf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 232, 2);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_INT_CNf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 179, 1);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_DROP_PKTf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

    BCMFP_QUAL_CFG_INIT(unit);
    BCMFP_QUAL_CFG_OFFSET_ADD(0, BCMFP_EXT_SECTION_FPF3, EFP_KEY8, offset8 + 180, 9);
    fid = FP_EGR_GRP_TEMPLATEt_QUAL_PORT_GRP_OR_PORT_SYSTEM_CLASSf;
    BCMFP_QUAL_CFG_INSERT(unit, stage, fid, qual_flags);

exit:
    SHR_FUNC_EXIT();
}
