#
#   $Id: Makefile,v 1.2 2011/01/03 18:48:20 pspreadb Exp $
# 
# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for ces/sal subdirectory
#
LOCALDIR = src/soc/ces/sal

CFLAGS = 
include ${SDK}/make/Make.config


lib = libsoc_sal
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
