# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/shadow

export BCM_HIDE_DISPATCHABLE=1

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs

lib = libbcm_shadow
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
