# $Id: Makefile 2016/06/16 11:21:00 msivaram Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw/techsupport/mmu

include ${SDK}/make/Make.config

lib = libtsmmu

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
