/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:    trident2plus_mmu.c
 * Purpose: Maintains all the debug information for mmu
 *          feature for trident2plus.
*/

#include <appl/diag/techsupport.h>
#include <soc/mcm/allenum.h>

extern char * techsupport_mmu_diag_cmdlist[];
extern char * techsupport_mmu_sw_dump_cmdlist[];

/* "mmu" feature's diag command list valid for Trident2plus */
char * techsupport_mmu_trident2plus_diag_cmdlist[] = {
     NULL /* Must be the last element in this structure */
 };

#ifndef BCM_SW_STATE_DUMP_DISABLE
/* "MMU" feature's software dump command list valid for Trident2plus */
char * techsupport_mmu_trident2plus_sw_dump_cmdlist[] = {
    NULL /* Must be the last element in this structure */
};
#endif /* BCM_SW_STATE_DUMP_DISABLE */


/* Structure that maintains memory list for
 * "mmu" feature for Trident2plus chipset. */
static soc_mem_t techsupport_mmu_trident2plus_memory_table_list[] = {
    THDI_PORT_PG_CNTRS_RT1_Xm,
    THDI_PORT_PG_CNTRS_RT1_Ym,
    THDI_PORT_PG_CNTRS_RT2_Xm,
    THDI_PORT_PG_CNTRS_RT2_Ym,
    THDI_PORT_PG_CONFIG_Xm,
    THDI_PORT_PG_CONFIG_Ym,
    THDI_PORT_SP_CNTRS_RT_Xm,
    THDI_PORT_SP_CNTRS_RT_Ym,
    THDI_PORT_SP_CONFIG_Xm,
    THDI_PORT_SP_CONFIG_Ym,
    MMU_THDU_XPIPE_CONFIG_PORTm,
    MMU_THDU_XPIPE_CONFIG_QGROUPm,
    MMU_THDU_XPIPE_CONFIG_QUEUEm,
    MMU_THDU_XPIPE_COUNTER_PORTm,
    MMU_THDU_XPIPE_COUNTER_QGROUPm,
    MMU_THDU_XPIPE_COUNTER_QUEUEm,
    MMU_THDU_XPIPE_OFFSET_QGROUPm,
    MMU_THDU_XPIPE_OFFSET_QUEUEm,
    MMU_THDU_XPIPE_Q_TO_QGRP_MAPm,
    MMU_THDU_XPIPE_RESUME_PORTm,
    MMU_THDU_XPIPE_RESUME_QGROUPm,
    MMU_THDU_XPIPE_RESUME_QUEUEm,
    MMU_THDU_YPIPE_CONFIG_PORTm,
    MMU_THDU_YPIPE_CONFIG_QGROUPm,
    MMU_THDU_YPIPE_CONFIG_QUEUEm,
    MMU_THDU_YPIPE_COUNTER_PORTm,
    MMU_THDU_YPIPE_COUNTER_QGROUPm,
    MMU_THDU_YPIPE_COUNTER_QUEUEm,
    MMU_THDU_YPIPE_OFFSET_QGROUPm,
    MMU_THDU_YPIPE_OFFSET_QUEUEm,
    MMU_THDU_YPIPE_Q_TO_QGRP_MAPm,
    MMU_THDU_YPIPE_RESUME_PORTm,
    MMU_THDU_YPIPE_RESUME_QGROUPm,
    MMU_THDU_YPIPE_RESUME_QUEUEm,
    MMU_THDM_DB_PORTSP_CONFIG_0m,
    MMU_THDM_DB_PORTSP_CONFIG_1m,
    MMU_THDM_DB_QUEUE_CONFIG_0m,
    MMU_THDM_DB_QUEUE_CONFIG_1m,
    MMU_THDM_DB_QUEUE_COUNT_0m,
    MMU_THDM_DB_QUEUE_COUNT_1m,
    MMU_THDM_DB_QUEUE_OFFSET_0m,
    MMU_THDM_DB_QUEUE_OFFSET_1m,
    MMU_THDM_DB_QUEUE_RESUME_0m,
    MMU_THDM_DB_QUEUE_RESUME_1m,
    MMU_THDM_MCQE_PORTSP_CONFIG_0m,
    MMU_THDM_MCQE_PORTSP_CONFIG_1m,
    MMU_THDM_MCQE_QUEUE_CONFIG_0m,
    MMU_THDM_MCQE_QUEUE_CONFIG_1m,
    MMU_THDM_MCQE_QUEUE_COUNT_0m,
    MMU_THDM_MCQE_QUEUE_COUNT_1m,
    MMU_THDM_MCQE_QUEUE_OFFSET_0m,
    MMU_THDM_MCQE_QUEUE_OFFSET_1m,
    MMU_THDM_MCQE_QUEUE_RESUME_0m,
    MMU_THDM_MCQE_QUEUE_RESUME_1m,
    MMU_CTR_ING_DROP_MEMm,
    MMU_CTR_UC_DROP_MEMm,
    MMU_CTR_MC_DROP_MEM0m,
    MMU_CTR_MC_DROP_MEM1m,
    MMU_CTR_MTRI_DROP_MEMm,
    MMU_CTR_COLOR_DROP_MEMm,
    EGR_EDB_XMIT_CTRLm,
    ES_PIPE0_LLS_L0_PARENTm,
    ES_PIPE0_LLS_L1_PARENTm,
    ES_PIPE0_LLS_L2_PARENTm,
    ES_PIPE1_LLS_L0_PARENTm,
    ES_PIPE1_LLS_L1_PARENTm,
    ES_PIPE1_LLS_L2_PARENTm,
    MMU_INTFI_FC_ST_TBL0m,
    MMU_INTFI_FC_ST_TBL1m,
    MMU_INTFI_FC_ST_TBL2m,
    MMU_INTFI_PFC_ST_TBLm,
    MMU_INTFI_XPIPE_FC_MAP_TBL0m,
    MMU_INTFI_XPIPE_FC_MAP_TBL1m,
    MMU_INTFI_XPIPE_FC_MAP_TBL2m,
    MMU_INTFI_YPIPE_FC_MAP_TBL0m,
    MMU_INTFI_YPIPE_FC_MAP_TBL1m,
    MMU_INTFI_YPIPE_FC_MAP_TBL2m,
    ES_PIPE0_LLS_L0_XOFFm,
    ES_PIPE0_LLS_L1_XOFFm,
    ES_PIPE0_LLS_L2_XOFFm,
    ES_PIPE1_LLS_L0_XOFFm,
    ES_PIPE1_LLS_L1_XOFFm,
    ES_PIPE1_LLS_L2_XOFFm,
    CPU_COS_MAPm,
    PORT_COS_MAPm,
    INVALIDm /* Must be the last element in this structure */
};

/* Structure that maintains register list for
 * "mmu" feature for Trident2plus chipset. */
techsupport_reg_t techsupport_mmu_trident2plus_reg_list[] = {
    {THDI_BUFFER_CELL_LIMIT_PUBLIC_POOLr, register_type_global},
    {THDI_BUFFER_CELL_LIMIT_SPr, register_type_global},
    {THDI_BYPASSr, register_type_global},
    {THDI_CELL_RESET_LIMIT_OFFSET_SPr, register_type_global},
    {THDI_CELL_SPAP_RED_OFFSET_SPr, register_type_global},
    {THDI_CELL_SPAP_YELLOW_OFFSET_SPr, register_type_global},
    {THDI_EN_COR_ERR_RPTr, register_type_global},
    {THDI_FLOW_CONTROL_XOFF_STATEr, register_type_global},
    {THDI_GLOBAL_HDRM_COUNT_PIPEXr, register_type_global},
    {THDI_GLOBAL_HDRM_COUNT_PIPEYr, register_type_global},
    {THDI_GLOBAL_HDRM_LIMIT_PIPEXr, register_type_global},
    {THDI_GLOBAL_HDRM_LIMIT_PIPEYr, register_type_global},
    {THDI_GLOBAL_HDRM_RESERVED_PIPEXr, register_type_global},
    {THDI_GLOBAL_HDRM_RESERVED_PIPEYr, register_type_global},
    {THDI_INPUT_PORT_XON_ENABLESr, register_type_global},
    {THDI_MEMORY_PTPG_CFG_MEM_TM_0r, register_type_global},
    {THDI_MEMORY_PTPG_CFG_MEM_TM_1r, register_type_global},
    {THDI_MEMORY_PTSP_CFG_MEM_TM_0r, register_type_global},
    {THDI_MEMORY_PTSP_CFG_MEM_TM_1r, register_type_global},
    {THDI_MEM_INIT_STATUSr, register_type_global},
    {THDI_POOL_CONFIGr, register_type_global},
    {THDI_POOL_DROP_STATEr, register_type_global},
    {THDI_POOL_SHARED_COUNT_SPr, register_type_global},
    {THDI_PORT_LIMIT_STATESr, register_type_global},
    {THDI_PORT_MAX_PKT_SIZEr, register_type_global},
    {THDI_PORT_PG_SPIDr, register_type_global},
    {THDI_PORT_PRI_GRP0r, register_type_global},
    {THDI_PORT_PRI_GRP1r, register_type_global},
    {THDI_TOTAL_CELL_COUNT_PUBLIC_POOLr, register_type_global},
    {THDI_TO_OOBFC_SP_STr, register_type_global},
    {THDU_BYPASSr, register_type_global},
    {THDU_DEBUGr, register_type_global},
    {THDU_OUTPUT_PORT_RX_ENABLE0_64r, register_type_global},
    {THDU_OUTPUT_PORT_RX_ENABLE1_64r, register_type_global},
    {THDU_PORT_E2ECC_COS_SPIDr, register_type_global},
    {MMU_THDU_EN_COR_ERR_RPTr, register_type_global},
    {OP_THDU_CONFIGr, register_type_global},
    {OP_UC_QUEUE_DROP_STATE_Xr, register_type_global},
    {OP_UC_QUEUE_DROP_STATE_Yr, register_type_global},
    {OP_UC_PORT_DROP_STATE_Xr, register_type_global},
    {OP_UC_PORT_DROP_STATE_Yr, register_type_global},
    {OP_UC_QGROUP_DROP_STATE_Xr, register_type_global},
    {OP_UC_QGROUP_DROP_STATE_Yr, register_type_global},
    {MMU_THDM_DB_DEVICE_BYPASSr, register_type_global},
    {MMU_THDM_DB_DEVICE_THR_CONFIGr, register_type_global},
    {MMU_THDM_DB_EN_COR_ERR_RPTr, register_type_global},
    {MMU_THDM_DB_MEMORY_TMr, register_type_global},
    {MMU_THDM_DB_POOL_DROP_STATESr, register_type_global},
    {MMU_THDM_DB_POOL_RED_RESUME_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_RED_SHARED_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_RESUME_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_SHARED_COUNTr, register_type_global},
    {MMU_THDM_DB_POOL_SHARED_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_YELLOW_RESUME_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_YELLOW_SHARED_LIMITr, register_type_global},
    {MMU_THDM_DB_PORTSP_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RX_ENABLE0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RX_ENABLE1_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_SHARED_COUNTr, register_type_global},
    {MMU_THDM_DB_PORTSP_THRESHOLD_PROFILE_SELr, register_type_global},
    {MMU_THDM_DB_PORTSP_TOTAL_COUNTr, register_type_global},
    {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_DB_QUEUE_RESUME_OFFSET_PROFILE_REDr, register_type_global},
    {MMU_THDM_DB_QUEUE_RESUME_OFFSET_PROFILE_YELLOWr, register_type_global},
    {MMU_THDM_MCQE_DEVICE_BYPASSr, register_type_global},
    {MMU_THDM_MCQE_DEVICE_THR_CONFIGr, register_type_global},
    {MMU_THDM_MCQE_EN_COR_ERR_RPTr, register_type_global},
    {MMU_THDM_MCQE_MEMORY_TMr, register_type_global},
    {MMU_THDM_MCQE_POOL_DROP_STATESr, register_type_global},
    {MMU_THDM_MCQE_POOL_RED_RESUME_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_RED_SHARED_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_RESUME_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_SHARED_COUNTr, register_type_global},
    {MMU_THDM_MCQE_POOL_SHARED_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_YELLOW_RESUME_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_YELLOW_SHARED_LIMITr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RX_ENABLE0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RX_ENABLE1_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_SHARED_COUNTr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_THRESHOLD_PROFILE_SELr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_TOTAL_COUNTr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_MCQE_QUEUE_RESUME_OFFSET_PROFILE_REDr, register_type_global},
    {MMU_THDM_MCQE_QUEUE_RESUME_OFFSET_PROFILE_YELLOWr, register_type_global},
    {MMU_THDR_DB_BYPASSr, register_type_global},
    {MMU_THDR_DB_CONFIGr, register_type_global},
    {MMU_THDR_DB_CONFIG1_PRIQr, register_type_global},
    {MMU_THDR_DB_CONFIG_PRIQr, register_type_global},
    {MMU_THDR_DB_CONFIG_SPr, register_type_global},
    {MMU_THDR_DB_LIMIT_COLOR_PRIQr, register_type_global},
    {MMU_THDR_DB_LIMIT_MIN_PRIQr, register_type_global},
    {MMU_THDR_DB_MIN_COUNT_PRIQr, register_type_global},
    {MMU_THDR_DB_RESET_OFFSET_COLOR_PRIQr, register_type_global},
    {MMU_THDR_DB_RESUME_COLOR_LIMIT_SPr, register_type_global},
    {MMU_THDR_DB_SHARED_COUNT_PRIQr, register_type_global},
    {MMU_THDR_DB_SHARED_COUNT_SPr, register_type_global},
    {MMU_THDR_DB_SP_SHARED_LIMITr, register_type_global},
    {MMU_THDR_DB_STATUS_PRIQr, register_type_global},
    {MMU_THDR_DB_STATUS_SPr, register_type_global},
    {MMU_THDR_QE_BYPASSr, register_type_global},
    {MMU_THDR_QE_CONFIGr, register_type_global},
    {MMU_THDR_QE_CONFIG1_PRIQr, register_type_global},
    {MMU_THDR_QE_CONFIG_PRIQr, register_type_global},
    {MMU_THDR_QE_CONFIG_SPr, register_type_global},
    {MMU_THDR_QE_LIMIT_COLOR_PRIQr, register_type_global},
    {MMU_THDR_QE_LIMIT_MIN_PRIQr, register_type_global},
    {MMU_THDR_QE_MIN_COUNT_PRIQr, register_type_global},
    {MMU_THDR_QE_RESET_OFFSET_COLOR_PRIQr, register_type_global},
    {MMU_THDR_QE_RESUME_COLOR_LIMIT_SPr, register_type_global},
    {MMU_THDR_QE_SHARED_COLOR_LIMIT_SPr, register_type_global},
    {MMU_THDR_QE_SHARED_COUNT_PRIQr, register_type_global},
    {MMU_THDR_QE_SHARED_COUNT_SPr, register_type_global},
    {MMU_THDR_QE_STATUSr, register_type_global},
    {MMU_THDR_QE_STATUS_PRIQr, register_type_global},
    {MMU_THDR_QE_STATUS_SPr, register_type_global},
    {PGW_OBM0_CONTROLr, register_type_global},
    {PGW_OBM0_PRIORITY_MAPr, register_type_global},
    {PGW_OBM0_SHARED_CONFIGr, register_type_global},
    {PGW_OBM0_THRESHOLDr, register_type_global},
    {PGW_OBM1_CONTROLr, register_type_global},
    {PGW_OBM1_PRIORITY_MAPr, register_type_global},
    {PGW_OBM1_SHARED_CONFIGr, register_type_global},
    {PGW_OBM1_THRESHOLDr, register_type_global},
    {PGW_OBM2_CONTROLr, register_type_global},
    {PGW_OBM2_PRIORITY_MAPr, register_type_global},
    {PGW_OBM2_SHARED_CONFIGr, register_type_global},
    {PGW_OBM2_THRESHOLDr, register_type_global},
    {PGW_OBM3_CONTROLr, register_type_global},
    {PGW_OBM3_PRIORITY_MAPr, register_type_global},
    {PGW_OBM3_SHARED_CONFIGr, register_type_global},
    {PGW_OBM3_THRESHOLDr, register_type_global},
    {PGW_OBM_PORT0_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT10_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT11_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT12_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT13_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT14_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT15_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT1_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT2_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT3_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT4_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT5_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT6_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT7_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT8_FC_CONFIGr, register_type_global},
    {PGW_OBM_PORT9_FC_CONFIGr, register_type_global},
    {ASF_PORT_CFGr, register_type_global},
    {CELL_ASM_CUT_THRU_THRESHOLDr, register_type_global},
    {CFAPBANKFULLr, register_type_global},
    {CFAPFULLTHRESHOLDRESETr, register_type_global},
    {CFAPFULLTHRESHOLDSETr, register_type_global},
    {ENQ_ASF_HS_OVERSUB_ENr, register_type_global},
    {ENQ_CONFIGr, register_type_global},
    {ES_PIPE0_ASF_CREDIT_THRESH_HIr, register_type_global},
    {ES_PIPE0_ASF_CREDIT_THRESH_LOr, register_type_global},
    {ES_PIPE1_ASF_CREDIT_THRESH_HIr, register_type_global},
    {ES_PIPE1_ASF_CREDIT_THRESH_LOr, register_type_global},
    {ING_COS_MODE_64r, register_type_global},
    {PORT_PFC_CFG0r, register_type_global},
    {PORT_PFC_CFG1r, register_type_global},
    {PORT_PFC_CFG2r, register_type_global},
    {PRIO2COS_PROFILEr, register_type_global},
    {MMU_TO_XPORT_BKPr, register_type_global},
    {XPORT_TO_MMU_BKPr, register_type_global},
    {MMU_LLFC_TX_CONFIG_1r, register_type_global},
    {MMU_LLFC_TX_CONFIG_2r, register_type_global},
    {XLMAC_PFC_CTRLr, register_type_global},
    {XLMAC_PAUSE_CTRLr, register_type_global},
    {XLMAC_PFC_TYPEr, register_type_global},
    {XLMAC_PFC_OPCODEr, register_type_global},
    {XLMAC_PFC_DAr, register_type_global},
    {XLMAC_TX_MAC_SAr, register_type_global},
    {CLMAC_PFC_CTRLr, register_type_global},
    {CLMAC_PAUSE_CTRLr, register_type_global},
    {CLMAC_PFC_TYPEr, register_type_global},
    {CLMAC_PFC_OPCODEr, register_type_global},
    {CLMAC_PFC_DAr, register_type_global},
    {CLMAC_TX_MAC_SAr, register_type_global},
    {ES_PIPE0_LLS_FC_CONFIGr, register_type_global},
    {ES_PIPE1_LLS_FC_CONFIGr, register_type_global},
    {INVALIDr, register_type_global } /* Must be the last element in this structure */
};

/* Structure that maintains  diag cmdlist, reg_list, mem_list  for
 * "mmu" feature for Trident2plus chipset. */
techsupport_data_t techsupport_mmu_trident2plus_data = {
    techsupport_mmu_diag_cmdlist,
    techsupport_mmu_trident2plus_reg_list,
    techsupport_mmu_trident2plus_memory_table_list,
    techsupport_mmu_trident2plus_diag_cmdlist
#ifndef BCM_SW_STATE_DUMP_DISABLE
    , techsupport_mmu_sw_dump_cmdlist,
   techsupport_mmu_trident2plus_sw_dump_cmdlist
#endif /* BCM_SW_STATE_DUMP_DISABLE */
};

