# $Id: Makefile,v 1.1 2004/03/03 07:11:15 dtalayco Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#
LOCALDIR = src/soc/mcm

include ${SDK}/make/Make.config

lib = libsoc_mcm
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
