# $Id: Makefile,v 1.2 2012/12/21 10:17:54 kirankum Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.

LOCALDIR = src/soc/kbp/alg_kbp/portability

include ${SDK}/make/Make.config

lib = libsoc_alg_kbp_portable

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
