# $Id: Makefile,v 1.0 2019/07/19 shaurya Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM FIELD AACL Library
#

LOCALDIR = src/bcm/esw/field_compression

include ${SDK}/make/Make.config

lib = libfieldcomp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

