# $Id: Makefile,v 1.1 2006/05/04 14:34:52 mmussol Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/enduro

include ${SDK}/make/Make.config

lib = libenduro

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
