/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:        cint_error_entry.h
 * Purpose:     Declare error constants depending on CINT_ERROR_LIST_ENTRY
 */

#ifndef CINT_ERROR_LIST_ENTRY
#error CINT_ERROR_LIST_ENTRY needs definition
#endif

CINT_ERROR_LIST_ENTRY(INTERNAL)
CINT_ERROR_LIST_ENTRY(MEMORY)
CINT_ERROR_LIST_ENTRY(PARAM)
CINT_ERROR_LIST_ENTRY(EXISTS)
CINT_ERROR_LIST_ENTRY(UNSUPPORTED)
CINT_ERROR_LIST_ENTRY(TYPE_NOT_FOUND)
CINT_ERROR_LIST_ENTRY(BAD_VARIABLE)
CINT_ERROR_LIST_ENTRY(BAD_TYPE)
CINT_ERROR_LIST_ENTRY(NOT_FOUND)
CINT_ERROR_LIST_ENTRY(BAD_EXPRESSION)
CINT_ERROR_LIST_ENTRY(BAD_OPERATOR)
CINT_ERROR_LIST_ENTRY(BAD_OPERANDS)
CINT_ERROR_LIST_ENTRY(BAD_AST)
CINT_ERROR_LIST_ENTRY(BREAK)
CINT_ERROR_LIST_ENTRY(CONTINUE)
CINT_ERROR_LIST_ENTRY(RETURN)
CINT_ERROR_LIST_ENTRY(EXIT)

#undef CINT_ERROR_LIST_ENTRY
