#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

#include $(SDK)/make/sublib.mk
include $(SDK)/make/libname.mk
include $(SDK)/make/subdir.mk

-include comp_ext.mk
-include generated/comp_patch.mk

include $(SDK)/make/lib.mk
