#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#
# Makefile for dnx/dnx_data/auto_generated subdirectory
#

LOCALDIR = src/soc/dnx/intr/auto_generated/j2p

include ${SDK}/make/Make.config


include ${SDK}/make/Make.subdirs

lib = libsoc_dnxintragj2p

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

