# $Id:$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SDK board driver Library
#

LOCALDIR = src/board

include ${SDK}/make/Make.config

subdirs=manager support stack driver
include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
