# $Id: Makefile 2017/27/02 23:05:00 patild Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw/techsupport/ledup

include ${SDK}/make/Make.config

lib = libtsledup

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
