#
# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#
# Makefile for phy/tscmod/src subdirectory
#
LOCALDIR = src/soc/phy/tscmod/src

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/src/soc/phy/tscmod/include
INCDIR += -I${SDK}/src/soc/phy

lib = libsoc_tscmod
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
