# $Id: Makefile,v 1.3 2011/07/26 17:39:50 miyarn Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/metrolite

include ${SDK}/make/Make.config

lib = libmetrolite

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
