# $Id: Makefile Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# Makefile for Trident3 SOC driver Library
#

LOCALDIR = src/soc/esw/tdm/trident3/

include ${SDK}/make/Make.config

lib = libsoc_tdm_td3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

