#
# $Id: Makefile,v 1.1.2.1 2015/02/02 10:00:00 srajesh Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for phy/phy8806x/src subdirectory
#
LOCALDIR = src/soc/phy/phy8806x/src

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/src/soc/phy/phy8806x/include

lib = libsoc_phy8806x
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
