# $Id: Makefile,v 1.3 2011/03/25 18:46:45 morrier Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for Broadcom Command Monitor (BCM) diagnostic tests
#

LOCALDIR = src/appl/test

CFGFLAGS += -DSOURCE_CHECK_LIBAPPL

include ${SDK}/make/Make.config

lib = libtest
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
