# -*- Makefile -*-
# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#
LOCALDIR = systems/linux/kernel/modules/shared

include ${SDK}/make/Make.config

lib = libkern

include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
