#
# $Id: Makefile,v 1.1 2012/02/28 11:04:53 afridman Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
export TARGET
export BLDDIR
export LIBDIR

LOCALDIR = src/appl/dcmn/rx_los

include ${SDK}/make/Make.config

lib = libappl_dcmn_rx_los

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

