#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/cosq

include ${SDK}/make/Make.config
subdirs += flow_control egress ingress scheduler aqm latency


include ${SDK}/make/Make.subdirs

lib = libbcm_dnxcosq

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

