/*------------------------------------------------------------------------------
 * 
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 *  Broadcom Corporation
 *  Proprietary and Confidential information
 *  All rights reserved
 *  This source file is the property of Broadcom Corporation, and
 *  may not be copied or distributed in any isomorphic form without the
 *  prior written consent of Broadcom Corporation.
 *------------------------------------------------------------------------------
 *  Description: Defines for the Speed Table, AM Table, and UM Table access APIs
 *----------------------------------------------------------------------------*/

#ifndef _TSCOMOD_DPLL_SPEED_CTRL_DEFINES_H_
#define _TSCOMOD_DPLL_SPEED_CTRL_DEFINES_H_

/*-------- Defines for table dimensions --------*/
#define TSCOMOD_DPLL_SPD_CTRL_SPD_ID_TBL_SIZE 64
#define TSCOMOD_DPLL_SPD_CTRL_AM_TBL_SIZE 64
#define TSCOMOD_DPLL_SPD_CTRL_UM_TBL_SIZE 64
#define TSCOMOD_DPLL_SPD_CTRL_SPD_ID_TBL_ENTRY_WIDTH 161
#define TSCOMOD_DPLL_SPD_CTRL_AM_TBL_ENTRY_WIDTH 73
#define TSCOMOD_DPLL_SPD_CTRL_UM_TBL_ENTRY_WIDTH 48

/*-------- Defines for fields of Speed ID Table --------*/
#define TSCOMOD_DPLL_SPD_ID_TBL_AM_TABLE_INDEX_OFFSET 0
#define TSCOMOD_DPLL_SPD_ID_TBL_AM_TABLE_INDEX_WIDTH 6
#define TSCOMOD_DPLL_SPD_ID_TBL_AM_TABLE_INDEX_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_AM_TABLE_INDEX_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_FEC_ARCH_OFFSET 6
#define TSCOMOD_DPLL_SPD_ID_TBL_FEC_ARCH_WIDTH 4
#define TSCOMOD_DPLL_SPD_ID_TBL_FEC_ARCH_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_FEC_ARCH_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_SYMBOL_INTERLEAVE_OFFSET 10
#define TSCOMOD_DPLL_SPD_ID_TBL_SYMBOL_INTERLEAVE_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_SYMBOL_INTERLEAVE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_SYMBOL_INTERLEAVE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_TC_XOR_CONTROL_OFFSET 11
#define TSCOMOD_DPLL_SPD_ID_TBL_TC_XOR_CONTROL_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_TC_XOR_CONTROL_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_TC_XOR_CONTROL_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_OFFSET 12
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_OFFSET 14
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH 4
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_OFFSET 18
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_OFFSET 20
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH 17
#define TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_OFFSET 37
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH 8
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_OFFSET 45
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH 8
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_OFFSET 53
#define TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_OFFSET 55
#define TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_WIDTH 3
#define TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_OFFSET 58
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH 8
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_OFFSET 66
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH 8
#define TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_OFFSET 74
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_OFFSET 75
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_WINDOW_MODE_OFFSET 76
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_WINDOW_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_WINDOW_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_BER_WINDOW_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_TRIGGER_COUNT_OFFSET 78
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_BER_TRIGGER_COUNT_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_QUOTIENT_OFFSET 79
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH 7
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_QUOTIENT_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_REMAINDER_OFFSET 86
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_REMAINDER_WIDTH 11
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_REMAINDER_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_REMAINDER_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_DIVISOR_OFFSET 97
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_DIVISOR_WIDTH 11
#define TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_DIVISOR_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_CREDIT_DIVISOR_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_OFFSET 108
#define TSCOMOD_DPLL_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_SCR_MODE_OFFSET 109
#define TSCOMOD_DPLL_SPD_ID_TBL_SCR_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_SCR_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_SCR_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_CODEC_MODE_OFFSET 111
#define TSCOMOD_DPLL_SPD_ID_TBL_CODEC_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_CODEC_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_CODEC_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_TRAINING_EN_OFFSET 113
#define TSCOMOD_DPLL_SPD_ID_TBL_TRAINING_EN_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_TRAINING_EN_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_TRAINING_EN_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_AN_TIMER_SELECT_OFFSET 114
#define TSCOMOD_DPLL_SPD_ID_TBL_AN_TIMER_SELECT_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_AN_TIMER_SELECT_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_AN_TIMER_SELECT_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_WATERMARK_OFFSET 115
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_WATERMARK_WIDTH 4
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_WATERMARK_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_WATERMARK_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_L_TPMA_WATERMARK_OFFSET 119
#define TSCOMOD_DPLL_SPD_ID_TBL_L_TPMA_WATERMARK_WIDTH 3
#define TSCOMOD_DPLL_SPD_ID_TBL_L_TPMA_WATERMARK_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_L_TPMA_WATERMARK_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_OFFSET 122
#define TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH 8
#define TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_OFFSET 130
#define TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH 14
#define TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_AM_LOCK_FSM_MODE_OFFSET 144
#define TSCOMOD_DPLL_SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_AM_LOCK_FSM_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_START_MODE_OFFSET 145
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_START_MODE_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_START_MODE_MASK ((1 << TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_START_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_ENABLE_OFFSET 146
#define TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_ENABLE_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_ENABLE_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_ENABLE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_OFFSET 147
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_INPUT_WIDTH_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_OFFSET 149
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_WIDTH 2
#define TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_T_PMA_OUTPUT_WIDTH_MODE_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_OFFSET 151
#define TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_BIT_MUX_MODE_MODIFIER_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_MODIFIER_OFFSET 152
#define TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_MODIFIER_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_MODIFIER_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_NUM_LANES_MODIFIER_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_MAPPING_SEL_OFFSET 153
#define TSCOMOD_DPLL_SPD_ID_TBL_MAPPING_SEL_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_MAPPING_SEL_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_MAPPING_SEL_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_VERSION_OFFSET 154
#define TSCOMOD_DPLL_SPD_ID_TBL_VERSION_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_VERSION_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_VERSION_WIDTH) - 1)
#define TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_2_OFFSET 155
#define TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_2_WIDTH 1
#define TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_2_MASK ((1 <<  TSCOMOD_DPLL_SPD_ID_TBL_HI_SER_2_WIDTH) - 1)

#endif  /* TSCOMOD_DPLL_SPEED_CTRL_DEFINES_H_ */

