#
#   $Id: Makefile,v 1.2 2011/01/03 18:48:18 pspreadb Exp $
# 
# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for ces/clsbuilder subdirectory
#
LOCALDIR = src/soc/ces/clsbuilder
CFLAGS = 
include ${SDK}/make/Make.config
#CFLAGS += -fno-strict-aliasing

lib = libsoc_clsbuilder
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
 