# $Id: Makefile,v 1.3 2004/03/03 09:33:47 brb Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC SAL support (Unix)
#
LOCALDIR = src/sal/appl/unix

include ${SDK}/make/Make.config

lib = libsal_appl_plat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
