
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNXF_DATA_MAX_PORT_H_

#define _DNXF_DATA_MAX_PORT_H_




#ifndef BCM_DNXF_SUPPORT
#error "This file is for use by DNXF family only!"
#endif


#define DNXF_DATA_MAX_PORT_GENERAL_NOF_LINKS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_NOF_LINKS
#define DNXF_DATA_MAX_PORT_GENERAL_NOF_LINKS (192)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_NOF_PMS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_NOF_PMS
#define DNXF_DATA_MAX_PORT_GENERAL_NOF_PMS (24)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_MAX_BUCKET_FILL_RATE (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_MAX_BUCKET_FILL_RATE
#define DNXF_DATA_MAX_PORT_GENERAL_MAX_BUCKET_FILL_RATE (11)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_LINK_MASK (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_LINK_MASK
#define DNXF_DATA_MAX_PORT_GENERAL_LINK_MASK (255)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_ALDWP_MAX_VAL (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_ALDWP_MAX_VAL
#define DNXF_DATA_MAX_PORT_GENERAL_ALDWP_MAX_VAL (63)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_FMAC_CLOCK_KHZ (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_FMAC_CLOCK_KHZ
#define DNXF_DATA_MAX_PORT_GENERAL_FMAC_CLOCK_KHZ (892000)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_SPEED_MAX (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_SPEED_MAX
#define DNXF_DATA_MAX_PORT_GENERAL_SPEED_MAX (53125)

#endif 

#define DNXF_DATA_MAX_PORT_GENERAL_FMAC_TX_PADDING_MIN_PORT_SPEED (1)

#define DNXF_DATA_MAX_PORT_GENERAL_NOF_BER_PROJ_ERROR_ANALYZER_COUNTERS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_GENERAL_NOF_BER_PROJ_ERROR_ANALYZER_COUNTERS
#define DNXF_DATA_MAX_PORT_GENERAL_NOF_BER_PROJ_ERROR_ANALYZER_COUNTERS (16)

#endif 

#define DNXF_DATA_MAX_PORT_LANE_MAP_LANE_MAP_BOUND (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_LANE_MAP_LANE_MAP_BOUND
#define DNXF_DATA_MAX_PORT_LANE_MAP_LANE_MAP_BOUND (4)

#endif 

#define DNXF_DATA_MAX_PORT_PLL_NOF_LCPLL (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_PLL_NOF_LCPLL
#define DNXF_DATA_MAX_PORT_PLL_NOF_LCPLL (4)

#endif 

#define DNXF_DATA_MAX_PORT_PLL_NOF_PORT_IN_LCPLL (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_PLL_NOF_PORT_IN_LCPLL
#define DNXF_DATA_MAX_PORT_PLL_NOF_PORT_IN_LCPLL (48)

#endif 

#define DNXF_DATA_MAX_PORT_PLL_FABRIC_CLOCK_FREQ_IN_DEFAULT (1)

#define DNXF_DATA_MAX_PORT_PLL_FABRIC_CLOCK_FREQ_OUT_DEFAULT (1)

#define DNXF_DATA_MAX_PORT_PLL_NOF_PLLS_PER_PM (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_PLL_NOF_PLLS_PER_PM
#define DNXF_DATA_MAX_PORT_PLL_NOF_PLLS_PER_PM (2)

#endif 

#define DNXF_DATA_MAX_PORT_PLL_NOF_CONFIG_WORDS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_PLL_NOF_CONFIG_WORDS
#define DNXF_DATA_MAX_PORT_PLL_NOF_CONFIG_WORDS (8)

#endif 

#define DNXF_DATA_MAX_PORT_SYNCE_FABRIC_DIV_MIN (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_SYNCE_FABRIC_DIV_MIN
#define DNXF_DATA_MAX_PORT_SYNCE_FABRIC_DIV_MIN (2)

#endif 

#define DNXF_DATA_MAX_PORT_SYNCE_FABRIC_DIV_MAX (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_PORT_SYNCE_FABRIC_DIV_MAX
#define DNXF_DATA_MAX_PORT_SYNCE_FABRIC_DIV_MAX (16)

#endif 




#endif 

