
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNXF_DATA_MAX_DEVICE_H_

#define _DNXF_DATA_MAX_DEVICE_H_




#ifndef BCM_DNXF_SUPPORT
#error "This file is for use by DNXF family only!"
#endif


#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_PVT_MONITORS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_GENERAL_NOF_PVT_MONITORS
#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_PVT_MONITORS (4)

#endif 

#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_MAIN_MONITORS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_GENERAL_NOF_MAIN_MONITORS
#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_MAIN_MONITORS (4)

#endif 

#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_BASE (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_GENERAL_PVT_BASE
#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_BASE (43410000)

#endif 

#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_FACTOR (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_GENERAL_PVT_FACTOR
#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_FACTOR (53504)

#endif 

#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_CORES (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_GENERAL_NOF_CORES
#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_CORES (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_GENERAL_ADAPTER_LIB_VER (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_GENERAL_ADAPTER_LIB_VER
#define DNXF_DATA_MAX_DEVICE_GENERAL_ADAPTER_LIB_VER (5)

#endif 

#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_MESH_TOPOLOGY_LINKS_DATA (1)

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_ALL_BLOCKS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_ALL_BLOCKS
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_ALL_BLOCKS (128)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FMAC (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FMAC
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FMAC (48)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FMAC (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FMAC
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FMAC (4)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FSRD (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FSRD
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FSRD (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FSRD (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FSRD
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FSRD (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCH (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCH
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCH (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCH (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCH
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCH (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DCH_LINK_GROUPS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DCH_LINK_GROUPS
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DCH_LINK_GROUPS (3)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCH (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCH
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCH (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_CCH (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_CCH
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_CCH (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCQ (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCQ
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCQ (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_RTP (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_RTP
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_RTP (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_RTP (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_RTP
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_RTP (192)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_OCCG (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_OCCG
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_OCCG (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_ECI (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_ECI
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_ECI (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CMIC (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CMIC
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CMIC (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMACH (1)

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMACL (1)

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_LCM (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_LCM
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_LCM (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MCT (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MCT
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MCT (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_QRH (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_QRH
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_QRH (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCML (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCML
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCML (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCML (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCML
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCML (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_LCM (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_LCM
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_LCM (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_QRH (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_QRH
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_QRH (24)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DTM_FIFOS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DTM_FIFOS
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DTM_FIFOS (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FSRD (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FSRD
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FSRD (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_PHY_CORE (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_PHY_CORE
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_PHY_CORE (8)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_FMACS_IN_FSRD (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_FMACS_IN_FSRD
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_FMACS_IN_FSRD (2)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_PCU (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_PCU
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_PCU (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCML (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCML
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCML (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DFL (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DFL
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DFL (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DTM (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DTM
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DTM (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_PADS (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_PADS
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_PADS (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DFL_FBC (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DFL_FBC
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DFL_FBC (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DTL (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DTL
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DTL (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY_WRAP (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY_WRAP
#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY_WRAP (1)

#endif 

#define DNXF_DATA_MAX_DEVICE_VTMON_VOL_FACTOR (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_VTMON_VOL_FACTOR
#define DNXF_DATA_MAX_DEVICE_VTMON_VOL_FACTOR (950)

#endif 

#define DNXF_DATA_MAX_DEVICE_VTMON_VOL_MULTIPLE (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_VTMON_VOL_MULTIPLE
#define DNXF_DATA_MAX_DEVICE_VTMON_VOL_MULTIPLE (5)

#endif 

#define DNXF_DATA_MAX_DEVICE_VTMON_VOL_DIVISOR (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_VTMON_VOL_DIVISOR
#define DNXF_DATA_MAX_DEVICE_VTMON_VOL_DIVISOR (4096)

#endif 

#define DNXF_DATA_MAX_DEVICE_OTP_NOF_WORDS_IN_ROW (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_OTP_NOF_WORDS_IN_ROW
#define DNXF_DATA_MAX_DEVICE_OTP_NOF_WORDS_IN_ROW (2)

#endif 

#define DNXF_DATA_MAX_DEVICE_OTP_READ_TIMEOUT (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_DEVICE_OTP_READ_TIMEOUT
#define DNXF_DATA_MAX_DEVICE_OTP_READ_TIMEOUT (100000)

#endif 




#endif 

