
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNXF_DATA_MAX_MODULE_TESTING_H_

#define _DNXF_DATA_MAX_MODULE_TESTING_H_




#ifndef BCM_DNXF_SUPPORT
#error "This file is for use by DNXF family only!"
#endif


#define DNXF_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF
#define DNXF_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF (305419896)

#endif 

#define DNXF_DATA_MAX_MODULE_TESTING_UNSUPPORTED_UNSUPPORTED_DEF (1)

#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D3 (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D3
#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D3 (1)

#endif 

#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D1 (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D1
#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D1 (10)

#endif 

#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_SAME_VALUE (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_SAME_VALUE
#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_SAME_VALUE (10)

#endif 

#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_D1_UNDEFINED (1)

#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_D3_UNDEFINED (1)
#ifdef BCM_DNXF1_SUPPORT

#undef DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_D3_UNDEFINED
#define DNXF_DATA_MAX_MODULE_TESTING_MAX_TEST_D3_UNDEFINED (1)

#endif 




#endif 

