/*------------------------------------------------------------------------------
 * 
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *  Broadcom Corporation
 *  Proprietary and Confidential information
 *  All rights reserved
 *  This source file is the property of Broadcom Corporation, and
 *  may not be copied or distributed in any isomorphic form without the
 *  prior written consent of Broadcom Corporation.
 *------------------------------------------------------------------------------
 *  Description: Defines for the Speed Table, AM Table, and UM Table access APIs
 *----------------------------------------------------------------------------*/

#ifndef _TBHMOD_SPEED_CTRL_DEFINES_H_
#define _TBHMOD_SPEED_CTRL_DEFINES_H_

/*-------- Defines for table dimensions --------*/
#define SPD_CTRL_SPD_ID_TBL_SIZE 64
#define SPD_CTRL_AM_TBL_SIZE 64
#define SPD_CTRL_UM_TBL_SIZE 64
#define SPD_CTRL_SPD_ID_TBL_ENTRY_WIDTH 150
#define SPD_CTRL_AM_TBL_ENTRY_WIDTH 73
#define SPD_CTRL_UM_TBL_ENTRY_WIDTH 48

/*-------- Defines for fields of Speed ID Table --------*/
#define SPD_ID_TBL_AM_TABLE_INDEX_OFFSET 0
#define SPD_ID_TBL_AM_TABLE_INDEX_WIDTH 6
#define SPD_ID_TBL_AM_TABLE_INDEX_MASK ((1 << SPD_ID_TBL_AM_TABLE_INDEX_WIDTH) - 1)
#define SPD_ID_TBL_FEC_ARCH_OFFSET 6
#define SPD_ID_TBL_FEC_ARCH_WIDTH 3
#define SPD_ID_TBL_FEC_ARCH_MASK ((1 << SPD_ID_TBL_FEC_ARCH_WIDTH) - 1)
#define SPD_ID_TBL_SYMBOL_INTERLEAVE_OFFSET 9
#define SPD_ID_TBL_SYMBOL_INTERLEAVE_WIDTH 1
#define SPD_ID_TBL_SYMBOL_INTERLEAVE_MASK ((1 << SPD_ID_TBL_SYMBOL_INTERLEAVE_WIDTH) - 1)
#define SPD_ID_TBL_TC_XOR_CONTROL_OFFSET 10
#define SPD_ID_TBL_TC_XOR_CONTROL_WIDTH 1
#define SPD_ID_TBL_TC_XOR_CONTROL_MASK ((1 << SPD_ID_TBL_TC_XOR_CONTROL_WIDTH) - 1)
#define SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_OFFSET 11 
#define SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH 2
#define SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_MASK ((1 << SPD_ID_TBL_RS_FEC_SYNC_HEADER_MODE_WIDTH) - 1)
#define SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_OFFSET 13 
#define SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH 4
#define SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_MASK ((1 << SPD_ID_TBL_RS_FEC_CWM_NIBBLE_MATCH_COUNT_WIDTH) - 1)
#define SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_OFFSET 17
#define SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_WIDTH 2
#define SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_MASK ((1 << SPD_ID_TBL_BASE_R_FEC_SYNC_HEADER_MODE_WIDTH) - 1)
#define SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_OFFSET 19
#define SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH 2
#define SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_MASK ((1 << SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_WINDOW_MODE_WIDTH) - 1)
#define SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_OFFSET 21
#define SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH 14
#define SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_MASK ((1 << SPD_ID_TBL_RS_FEC_SYMBOL_ERROR_COUNT_THRESHOLD_WIDTH) - 1)
#define SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_OFFSET 35
#define SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH 8
#define SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_MASK ((1 << SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_2XN_WIDTH) - 1)
#define SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_OFFSET 43
#define SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH 8
#define SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_MASK ((1 << SPD_ID_TBL_DESKEW_FORWARDING_THRESHOLD_1XN_WIDTH) - 1)
#define SPD_ID_TBL_BIT_MUX_MODE_OFFSET 51
#define SPD_ID_TBL_BIT_MUX_MODE_WIDTH 2
#define SPD_ID_TBL_BIT_MUX_MODE_MASK ((1 << SPD_ID_TBL_BIT_MUX_MODE_WIDTH) - 1)
#define SPD_ID_TBL_NUM_LANES_OFFSET 53
#define SPD_ID_TBL_NUM_LANES_WIDTH 3
#define SPD_ID_TBL_NUM_LANES_MASK ((1 << SPD_ID_TBL_NUM_LANES_WIDTH) - 1)
#define SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_OFFSET 56
#define SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH 8
#define SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_MASK ((1 << SPD_ID_TBL_DESKEW_WINDOW_WITHOUT_RS_FEC_WIDTH) - 1)
#define SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_OFFSET 64
#define SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH 8
#define SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_MASK ((1 << SPD_ID_TBL_DESKEW_WINDOW_WITH_RS_FEC_WIDTH) - 1)
#define SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_OFFSET 72
#define SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH 1
#define SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_MASK ((1 << SPD_ID_TBL_BER_FSM_DISABLE_WITH_RS_FEC_WIDTH) - 1)
#define SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_OFFSET 73
#define SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH 1
#define SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_MASK ((1 << SPD_ID_TBL_BER_FSM_DISABLE_WITHOUT_RS_FEC_WIDTH) - 1)
#define SPD_ID_TBL_BER_WINDOW_MODE_OFFSET 74
#define SPD_ID_TBL_BER_WINDOW_MODE_WIDTH 2
#define SPD_ID_TBL_BER_WINDOW_MODE_MASK ((1 << SPD_ID_TBL_BER_WINDOW_MODE_WIDTH) - 1)
#define SPD_ID_TBL_BER_TRIGGER_COUNT_OFFSET 76
#define SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH 1
#define SPD_ID_TBL_BER_TRIGGER_COUNT_MASK ((1 << SPD_ID_TBL_BER_TRIGGER_COUNT_WIDTH) - 1)
#define SPD_ID_TBL_CREDIT_QUOTIENT_OFFSET 77
#define SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH 7
#define SPD_ID_TBL_CREDIT_QUOTIENT_MASK ((1 << SPD_ID_TBL_CREDIT_QUOTIENT_WIDTH) - 1)
#define SPD_ID_TBL_CREDIT_REMAINDER_OFFSET 84
#define SPD_ID_TBL_CREDIT_REMAINDER_WIDTH 10
#define SPD_ID_TBL_CREDIT_REMAINDER_MASK ((1 << SPD_ID_TBL_CREDIT_REMAINDER_WIDTH) - 1)
#define SPD_ID_TBL_CREDIT_DIVISOR_OFFSET 94
#define SPD_ID_TBL_CREDIT_DIVISOR_WIDTH 10
#define SPD_ID_TBL_CREDIT_DIVISOR_MASK ((1 << SPD_ID_TBL_CREDIT_DIVISOR_WIDTH) - 1)
#define SPD_ID_TBL_USE_CL49_BLOCK_SYNC_OFFSET 104
#define SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH 1
#define SPD_ID_TBL_USE_CL49_BLOCK_SYNC_MASK ((1 << SPD_ID_TBL_USE_CL49_BLOCK_SYNC_WIDTH) - 1)
#define SPD_ID_TBL_SCR_MODE_OFFSET 105
#define SPD_ID_TBL_SCR_MODE_WIDTH 2
#define SPD_ID_TBL_SCR_MODE_MASK ((1 << SPD_ID_TBL_SCR_MODE_WIDTH) - 1)
#define SPD_ID_TBL_CODEC_MODE_OFFSET 107
#define SPD_ID_TBL_CODEC_MODE_WIDTH 2
#define SPD_ID_TBL_CODEC_MODE_MASK ((1 << SPD_ID_TBL_CODEC_MODE_WIDTH) - 1)
#define SPD_ID_TBL_TRAINING_EN_OFFSET 109
#define SPD_ID_TBL_TRAINING_EN_WIDTH 1
#define SPD_ID_TBL_TRAINING_EN_MASK ((1 << SPD_ID_TBL_TRAINING_EN_WIDTH) - 1)
#define SPD_ID_TBL_AN_TIMER_SELECT_OFFSET 110
#define SPD_ID_TBL_AN_TIMER_SELECT_WIDTH 1
#define SPD_ID_TBL_AN_TIMER_SELECT_MASK ((1 << SPD_ID_TBL_AN_TIMER_SELECT_WIDTH) - 1)
#define SPD_ID_TBL_PMD_PAM4_MODE_OFFSET 111
#define SPD_ID_TBL_PMD_PAM4_MODE_WIDTH 3
#define SPD_ID_TBL_PMD_PAM4_MODE_MASK ((1 << SPD_ID_TBL_PMD_PAM4_MODE_WIDTH) - 1)
#define SPD_ID_TBL_PMD_OSR_MODE_OFFSET 114
#define SPD_ID_TBL_PMD_OSR_MODE_WIDTH 4
#define SPD_ID_TBL_PMD_OSR_MODE_MASK ((1 << SPD_ID_TBL_PMD_OSR_MODE_WIDTH) - 1)
#define SPD_ID_TBL_T_PMA_WATERMARK_OFFSET 118
#define SPD_ID_TBL_T_PMA_WATERMARK_WIDTH 4
#define SPD_ID_TBL_T_PMA_WATERMARK_MASK ((1 << SPD_ID_TBL_T_PMA_WATERMARK_WIDTH) - 1)
#define SPD_ID_TBL_L_TPMA_WATERMARK_OFFSET 122
#define SPD_ID_TBL_L_TPMA_WATERMARK_WIDTH 3
#define SPD_ID_TBL_L_TPMA_WATERMARK_MASK ((1 << SPD_ID_TBL_L_TPMA_WATERMARK_WIDTH) - 1)
#define SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_OFFSET 125
#define SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH 8
#define SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_MASK ((1 << SPD_ID_TBL_LOOP_BLOCK_COUNT_FOR_TS_WIDTH) - 1)
#define SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_OFFSET 133
#define SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH 14 
#define SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_MASK ((1 << SPD_ID_TBL_LOOP_BIT_COUNT_FOR_TS_WIDTH) - 1)
#define SPD_ID_TBL_AM_LOCK_FSM_MODE_OFFSET 147
#define SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH 1
#define SPD_ID_TBL_AM_LOCK_FSM_MODE_MASK ((1 << SPD_ID_TBL_AM_LOCK_FSM_MODE_WIDTH) - 1)
#define SPD_ID_TBL_T_PMA_START_MODE_OFFSET 148
#define SPD_ID_TBL_T_PMA_START_MODE_WIDTH 1
#define SPD_ID_TBL_T_PMA_START_MODE_MASK ((1 << SPD_ID_TBL_T_PMA_START_MODE_WIDTH) - 1)
#define SPD_ID_TBL_HI_SER_ENABLE_OFFSET 149
#define SPD_ID_TBL_HI_SER_ENABLE_WIDTH 1
#define SPD_ID_TBL_HI_SER_ENABLE_MASK ((1 << SPD_ID_TBL_HI_SER_ENABLE_WIDTH) - 1)

/*-------- Defines for fields of AM Table --------*/
#define AM_TBL_AM_SPACING_CREDITS_OFFSET 65
#define AM_TBL_AM_SPACING_CREDITS_WIDTH 8
#define AM_TBL_AM_SPACING_CREDITS_MASK ((1 << AM_TBL_AM_SPACING_CREDITS_WIDTH) - 1)
#define AM_TBL_AM_SPACING_NO_RS_OFFSET 57
#define AM_TBL_AM_SPACING_NO_RS_WIDTH 8
#define AM_TBL_AM_SPACING_NO_RS_MASK ((1 << AM_TBL_AM_SPACING_NO_RS_WIDTH) - 1)
#define AM_TBL_AM_SPACING_RS_OFFSET 48
#define AM_TBL_AM_SPACING_RS_WIDTH 9
#define AM_TBL_AM_SPACING_RS_MASK ((1 << AM_TBL_AM_SPACING_RS_WIDTH) - 1)
#define AM_TBL_USE_FIXED_OFFSET 44
#define AM_TBL_USE_FIXED_WIDTH 4
#define AM_TBL_USE_FIXED_MASK ((1 << AM_TBL_USE_FIXED_WIDTH) - 1)
#define AM_TBL_CM_OFFSET 20
#define AM_TBL_CM_WIDTH 24
#define AM_TBL_CM_MASK ((1 << AM_TBL_CM_WIDTH) - 1)
#define AM_TBL_UM_TABLE_INDEX_OFFSET 14
#define AM_TBL_UM_TABLE_INDEX_WIDTH 6
#define AM_TBL_UM_TABLE_INDEX_MASK ((1 << AM_TBL_UM_TABLE_INDEX_WIDTH) - 1)
#define AM_TBL_UM_TABLE_COUNT_OFFSET 9
#define AM_TBL_UM_TABLE_COUNT_WIDTH 5
#define AM_TBL_UM_TABLE_COUNT_MASK ((1 << AM_TBL_UM_TABLE_COUNT_WIDTH) - 1)
#define AM_TBL_PAD_MODE_OFFSET 7
#define AM_TBL_PAD_MODE_WIDTH 2
#define AM_TBL_PAD_MODE_MASK ((1 << AM_TBL_PAD_MODE_WIDTH) - 1)
#define AM_TBL_AM_SIZE_OFFSET 3
#define AM_TBL_AM_SIZE_WIDTH 4
#define AM_TBL_AM_SIZE_MASK ((1 << AM_TBL_AM_SIZE_WIDTH) - 1)
#define AM_TBL_AM_COMPRESSION_MODE_OFFSET 0
#define AM_TBL_AM_COMPRESSION_MODE_WIDTH 3
#define AM_TBL_AM_COMPRESSION_MODE_MASK ((1 << AM_TBL_AM_COMPRESSION_MODE_WIDTH) - 1)

/*-------- Defines for fields of UM Table --------*/
#define UM_TBL_UM_OFFSET 24
#define UM_TBL_UM_WIDTH 24
#define UM_TBL_UM_MASK ((1 << UM_TBL_UM_WIDTH) - 1)
#define UM_TBL_CM_PAD_OFFSET 16
#define UM_TBL_CM_PAD_WIDTH 8
#define UM_TBL_CM_PAD_MASK ((1 << UM_TBL_CM_PAD_WIDTH) - 1)
#define UM_TBL_UM_PAD_OFFSET 8
#define UM_TBL_UM_PAD_WIDTH 8
#define UM_TBL_UM_PAD_MASK ((1 << UM_TBL_UM_PAD_WIDTH) - 1)
#define UM_TBL_CM_CONTROL_OFFSET 0
#define UM_TBL_CM_CONTROL_WIDTH 8
#define UM_TBL_CM_CONTROL_MASK ((1 << UM_TBL_CM_CONTROL_WIDTH) - 1)


#endif  /* _TBHMOD_SPEED_CTRL_DEFINES_H_ */

