# -*- Makefile -*-
# $Id: Makefile,v 1.1 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/cint

include ${SDK}/make/Make.config

CFGFLAGS += -I$(SDK)/src/appl/cint

lib = libdiagcint
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
