#
# $Id: Makefile,v 1.4 2016/10/10
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/flow/porting
include ${SDK}/make/Make.config

#subdirs = 

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxflowporting

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend