# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#
# Makefile for BCM Tomahawk driver Library
#

LOCALDIR = src/bcm/esw/tomahawk2

include ${SDK}/make/Make.config

lib = libtomahawk2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
