# $Id$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.

#LOCALDIR = src/soc/ces

#include ${SDK}/make/Make.config

#subdirs = nemo_driver
#subdirs += clsbuilder
#subdirs += sal

#include ${SDK}/make/Make.subdirs
