# $Id: Makefile,v 1.2 2011/08/21 07:21:11 bhanup Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
LOCALDIR = src/soc/dpp/SAND/Management

include ${SDK}/make/Make.config

lib = libbcm_dpp_sand_mgmt

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
