#
# $Id: Makefile,v 1.1 2011/05/06 22:14:22 raphy Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for phy/wcmod/src subdirectory
#
LOCALDIR = src/soc/phy/wcmod/src

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/src/soc/phy/wcmod/include
INCDIR += -I${SDK}/src/soc/phy

lib = libsoc_wcmod
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
