# $Id: Makefile 2016/07/02 11:20:00 msivaram Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw/techsupport/cos

include ${SDK}/make/Make.config

lib = libtscos

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
