/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 *
 * Default PHY chip support for SDK.
 */

#ifndef PHYMOD_CUSTOM_CHIP_CONFIG_H
#define PHYMOD_CUSTOM_CHIP_CONFIG_H

#ifndef USER_DEFINED_PHYMOD_CHIPS
#define PHYMOD_EAGLE_SUPPORT
#define PHYMOD_FALCON_SUPPORT
#define PHYMOD_FALCON16_SUPPORT
#define PHYMOD_MERLIN16_SUPPORT
#define PHYMOD_QSGMIIE_SUPPORT
#define PHYMOD_TSCE_SUPPORT
#define PHYMOD_TSCF_SUPPORT
#define PHYMOD_TSCF16_SUPPORT
#define PHYMOD_TSCE16_SUPPORT
#define PHYMOD_VIPER_SUPPORT
#define PHYMOD_FURIA_SUPPORT
#define PHYMOD_SESTO_SUPPORT
#define PHYMOD_QUADRA28_SUPPORT
#define PHYMOD_QTCE_SUPPORT
#define PHYMOD_HURACAN_SUPPORT
#define PHYMOD_MADURA_SUPPORT
#define PHYMOD_DINO_SUPPORT
#define PHYMOD_PHY8806X_SUPPORT
#define PHYMOD_TSCE_DPLL_SUPPORT
#define PHYMOD_EAGLE_DPLL_SUPPORT
#define PHYMOD_BLACKHAWK_SUPPORT
#define PHYMOD_TSCBH_SUPPORT
#define PHYMOD_TSCF_GEN3_SUPPORT
#define PHYMOD_FALCON_DPLL_SUPPORT
#define PHYMOD_QTCE16_SUPPORT
#define PHYMOD_NULL_SUPPORT
#define PHYMOD_TSCBH_GEN2_SUPPORT
#define PHYMOD_MERLIN7_SUPPORT
#define PHYMOD_TSCE7_SUPPORT
#define PHYMOD_TSCF16_GEN3_SUPPORT
#define PHYMOD_FALCON16_V1L4P1_SUPPORT
#define PHYMOD_TSCBH_FLEXE_SUPPORT
#define PHYMOD_TSCBH_GEN3_SUPPORT
#define PHYMOD_BLACKHAWK7_V1L8P1_SUPPORT
#define PHYMOD_TSCO_SUPPORT
#define PHYMOD_OSPREY7_V2L8P1_SUPPORT
#define PHYMOD_BLACKHAWK7_L8P2_SUPPORT
#define PHYMOD_TSCO_DPLL_SUPPORT
#define PHYMOD_OSPREY7_V2L8P2_SUPPORT
#define PHYMOD_TSCBH_FE_GEN2_SUPPORT
#define PHYMOD_BLACKHAWK7_L2P2_SUPPORT
#define PHYMOD_TSCBH_SUB10G_SUPPORT
#endif /* USER_DEFINED_PHYMOD_CHIPS */

#endif /* PHYMOD_CUSTOM_CHIP_CONFIG_H */
