#
# $Id: Makefile,v 1.4 2012/03/08 10:43:54 assafz Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for portlib subdirectory
#

LOCALDIR = src/soc/cprimod

include ${SDK}/make/Make.config

subdirs := cpms
include ${SDK}/make/Make.subdirs

lib = libsoc_cprimod

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
