#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

include $(SDK)/make/libname.mk

ifndef IO_SYSTEM
IO_SYSTEM = posix
endif

SUBDIRS := $(IO_SYSTEM)
include $(SDK)/make/subdir.mk

include $(SDK)/make/lib.mk
