/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:       bcm_xmod_arg_len.c
 */

#include "bcm_xmod_api.h"

const xmod_api_length_t bcm_xmod_ethernet_cmds_arg_len_tbl[XMOD_ETHERNET_CMDS_COUNT] = {
/* XMOD_PHY_FIRMWARE_LANE_CONFIG_GET   0x00 */   { 0,                                          0 },
/* XMOD_PHY_FIRMWARE_LANE_CONFIG_SET   0x01 */   { 0,                                          0 },
/* NA                                  0x02 */   { 0,                                          0 },
/* XMOD_PHY_INIT                       0x03 */   { 0,                                          0 },
/* NA                                  0x04 */   { 0,                                          0 },
/* XMOD_PHY_RX_RESTART                 0x05 */   { 0,                                          0 },
/* XMOD_PHY_POLARITY_GET               0x06 */   { 0,                                          0 },
/* XMOD_PHY_POLARITY_SET               0x07 */   { 0,                                          0 },
/* XMOD_PHY_TX_GET                     0x08 */   { 0,                                          0 },
/* XMOD_PHY_TX_SET                     0x09 */   { 0,                                          0 },
/* XMOD_PHY_MEDIA_TYPE_TX_GET          0x0a */   { 0,                                          0 },
/* NA                                  0x0b */   { 0,                                          0 },
/* XMOD_PHY_TX_OVERRIDE_GET            0x0c */   { 0,                                          0 },
/* XMOD_PHY_TX_OVERRIDE_SET            0x0d */   { 0,                                          0 },
/* NA                                  0x0e */   { 0,                                          0 },
/* NA                                  0x0f */   { 0,                                          0 },
/* XMOD_PHY_RX_GET                     0x10 */   { 0,                                          0 },
/* XMOD_PHY_RX_SET                     0x11 */   { 0,                                          0 },
/* XMOD_PHY_RESET_GET                  0x12 */   { 0,                                          0 },
/* XMOD_PHY_RESET_SET                  0x13 */   { 0,                                          0 },
/* XMOD_PHY_POWER_GET                  0x14 */   { 0,                                          0 },
/* XMOD_PHY_POWER_SET                  0x15 */   { 0,                                          0 },
/* XMOD_PHY_TX_LANE_CONTROL_GET        0x16 */   { 0,                                          0 },
/* XMOD_PHY_TX_LANE_CONTROL_SET        0x17 */   { 0,                                          0 },
/* XMOD_PHY_RX_LANE_CONTROL_GET        0x18 */   { 0,                                          0 },
/* XMOD_PHY_RX_LANE_CONTROL_SET        0x19 */   { 0,                                          0 },
/* XMOD_PHY_FEC_ENABLE_GET             0x1a */   { 0,                                          0 },
/* XMOD_PHY_FEC_ENABLE_SET             0x1b */   { 0,                                          0 },
/* XMOD_PHY_INTERFACE_CONFIG_GET       0x1c */   { 0,                                          0 },
/* XMOD_PHY_INTERFACE_CONFIG_SET       0x1d */   { 0,                                          0 },
/* XMOD_PHY_CL72_GET                   0x1e */   { 0,                                          0 },
/* XMOD_PHY_CL72_SET                   0x1f */   { 0,                                          0 },
/* XMOD_PHY_CL72_STATUS_GET            0x20 */   { 0,                                          0 },
/* NA                                  0x21 */   { 0,                                          0 },
/* XMOD_PHY_AUTONEG_ABILITY_GET        0x22 */   { 0,                                          0 },
/* XMOD_PHY_AUTONEG_ABILITY_SET        0x23 */   { 0,                                          0 },
/* XMOD_PHY_AUTONEG_REMOTE_ABILITY_GET 0x24 */   { 0,                                          0 },
/* NA                                  0x25 */   { 0,                                          0 },
/* XMOD_PHY_AUTONEG_GET                0x26 */   { 0,                                          0 },
/* XMOD_PHY_AUTONEG_SET                0x27 */   { 0,                                          0 },
/* XMOD_PHY_AUTONEG_STATUS_GET         0x28 */   { 0,                                          0 },
/* NA                                  0x29 */   { 0,                                          0 },
/* XMOD_PHY_LOOPBACK_GET               0x2a */   { 0,                                          0 },
/* XMOD_PHY_LOOPBACK_SET               0x2b */   { 0,                                          0 },
/* XMOD_PHY_RX_PMD_LOCKED_GET          0x2c */   { 0,                                          0 },
/* NA                                  0x2d */   { 0,                                          0 },
/* XMOD_PHY_LINK_STATUS_GET            0x2e */   { 0,                                          0 },
/* NA                                  0x2f */   { 0,                                          0 },
/* XMOD_PHY_STATUS_DUMP                0x30 */   { 0,                                          0 },
/* NA                                  0x31 */   { 0,                                          0 },
/* XMOD_PHY_PCS_USERSPEED_GET          0x32 */   { 0,                                          0 },
/* XMOD_PHY_PCS_USERSPEED_SET          0x33 */   { 0,                                          0 },
/* NA                                  0x34 */   { 0,                                          0 },
/* XMOD_PORT_INIT                      0x35 */   { 0,                                          0 },
/* NA                                  0x36 */   { 0,                                          0 },
/* XMOD_PHY_AN_TRY_ENABLE              0x37 */   { 0,                                          0 },
/* NA                                  0x38 */   { 0,                                          0 },
/* XMOD_PE_INIT                        0x39 */   { XMOD_PE_INIT_IN_LEN,                        XMOD_PE_INIT_OUT_LEN },
/* XMOD_PE_STATUS_GET                  0x3a */   { XMOD_PE_STATUS_GET_IN_LEN,                  XMOD_PE_STATUS_GET_OUT_LEN },
/* NA                                  0x3b */   { 0,                                          0 },
/* XMOD_PE_PORT_STATS_GET              0x3c */   { XMOD_PE_PORT_STATS_GET_IN_LEN,              XMOD_PE_PORT_STATS_GET_OUT_LEN },
/* NA                                  0x3d */   { 0,                                          0 },
/* NA                                  0x3e */   { 0,                                          0 },
/* XMOD_PE_TAGID_SET                   0x3f */   { XMOD_PE_TAGID_SET_IN_LEN,                   XMOD_PE_TAGID_SET_OUT_LEN },
/* XMOD_PE_FW_VER_GET                  0x40 */   { XMOD_PE_FW_VER_GET_IN_LEN,                  XMOD_PE_FW_VER_GET_OUT_LEN },
/* NA                                  0x41 */   { 0,                                          0 },
};

