# -*- Makefile -*-
# $Id: Makefile,v 1.3 2005/01/17 19:53:08 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for StrataXGS SDK and diagnostics
#

include $(SDK)/make/Make.config

ifeq ($(HOSTTYPE),i386-linux)
subdirs= user
endif

include $(SDK)/make/Make.subdirs

include $(SDK)/make/Make.depend

