# -*- Makefile -*-
# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#

include ${SDK}/make/Make.config

subdirs= shared bcm-diag-proxy

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
