# $Id: $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# Makefile for Hurricane4 flexport common library

LOCALDIR = src/soc/esw/hurricane4/flexport

include ${SDK}/make/Make.config

lib = libsoc_hurricane4_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
