# $Id: Makefile 2016/10/12 11:55:00 patild Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw/techsupport/pstat

include ${SDK}/make/Make.config

lib = libtspstat

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
