

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_FC_H_

#define _DNX_DATA_MAX_FC_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_FC_GENERAL_NOF_GLB_RSC (14)


#define DNX_DATA_MAX_FC_GENERAL_NOF_GEN_BMPS (64)


#define DNX_DATA_MAX_FC_GENERAL_GEN_BMP_FIRST_ID (1)


#define DNX_DATA_MAX_FC_GENERAL_NOF_AF_NIF_INDICATIONS (144)


#define DNX_DATA_MAX_FC_GENERAL_NOF_CAL_LLFCS (148)


#define DNX_DATA_MAX_FC_GENERAL_NOF_ENTRIES_QMLF (32767)


#define DNX_DATA_MAX_FC_GENERAL_NOF_BITS_IN_PFC_STATUS_SELECT (4)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_PFC (0)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_NIF_LLFC (1)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_PORT_2_PRIO (2)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_PORT_4_PRIO (3)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_PORT_8_PRIO (4)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_PFC_GENERIC_BMP (7)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_RX_DEST_EMPTY (6)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_VSQ_A_B_C (0)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_VSQ_D (1)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_LLFC_VSQ (2)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_PFC_VSQ (3)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_GLB_RSC (4)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_NIF_LLFC (6)


#define DNX_DATA_MAX_FC_CALENDAR_COMMON_TX_SRC_EMPTY (7)


#define DNX_DATA_MAX_FC_COE_NOF_COE_CAL_INSTANCES (2)


#define DNX_DATA_MAX_FC_COE_NOF_SUPPORTED_VLAN_IDS (4096)


#define DNX_DATA_MAX_FC_COE_NOF_COE_VID_MASK_WIDTH (10)


#define DNX_DATA_MAX_FC_COE_NOF_COE_VID_RIGHT_SHIFT_WIDTH (4)


#define DNX_DATA_MAX_FC_COE_MAX_COE_TICKS (1048575)


#define DNX_DATA_MAX_FC_COE_FC_SUPPORT  (1)


#define DNX_DATA_MAX_FC_OOB_NOF_OOB_IDS (2)


#define DNX_DATA_MAX_FC_INBAND_NOF_INBAND_INTLKN_CAL_INSTANCES (16)




#endif 

