

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_QOS_H_

#define _DNX_DATA_MAX_QOS_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROFILES (1024)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_OPCODE_PROFILES (256)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_PROFILES (4)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_POLICER_PROFILES (4)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_VLAN_PCP_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PROFILES (32)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_POLICER_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_MPLS_PHP_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_OPCODE_PROFILES (32)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PHP_OPCODE_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_TTL_PIPE_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROPAGATION_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_OPCODE_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_NETWORK_QOS_PIPE_PROFILES (64)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_COS_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_PRIORITY (7)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EXP (7)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DSCP (255)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_CFI (1)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_TC (7)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DP (3)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_ECN (3)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EGRESS_POLICER_OFFSET (7)


#define DNX_DATA_MAX_QOS_QOS_MAX_INT_MAP_ID (255)


#define DNX_DATA_MAX_QOS_QOS_MAX_EGRESS_VAR (255)


#define DNX_DATA_MAX_QOS_QOS_ECN_BITS_WIDTH (3)


#define DNX_DATA_MAX_QOS_QOS_EEI_MPLS_TTL_PROFILE (30)


#define DNX_DATA_MAX_QOS_FEATURE_PHB_RM_FFC_BITS_WIDTH (23)




#endif 

