
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_NIF_H_

#define _DNX_DATA_MAX_NIF_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_NIF_GLOBAL_NOF_LCPLLS (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_NOF_LCPLLS
#define DNX_DATA_MAX_NIF_GLOBAL_NOF_LCPLLS (2)


#define DNX_DATA_MAX_NIF_GLOBAL_NOF_NIF_INTERFACES_PER_CORE (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_NOF_NIF_INTERFACES_PER_CORE
#define DNX_DATA_MAX_NIF_GLOBAL_NOF_NIF_INTERFACES_PER_CORE (386)


#define DNX_DATA_MAX_NIF_GLOBAL_NIF_INTERFACE_ID_TO_UNIT_ID_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_NIF_INTERFACE_ID_TO_UNIT_ID_GRANULARITY
#define DNX_DATA_MAX_NIF_GLOBAL_NIF_INTERFACE_ID_TO_UNIT_ID_GRANULARITY (8)


#define DNX_DATA_MAX_NIF_GLOBAL_NOF_NIF_UNITS_PER_CORE (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_NOF_NIF_UNITS_PER_CORE
#define DNX_DATA_MAX_NIF_GLOBAL_NOF_NIF_UNITS_PER_CORE (18)


#define DNX_DATA_MAX_NIF_GLOBAL_REASSEMBLER_FIFO_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_REASSEMBLER_FIFO_THRESHOLD
#define DNX_DATA_MAX_NIF_GLOBAL_REASSEMBLER_FIFO_THRESHOLD (90)


#define DNX_DATA_MAX_NIF_GLOBAL_TOTAL_DATA_CAPACITY (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_TOTAL_DATA_CAPACITY
#define DNX_DATA_MAX_NIF_GLOBAL_TOTAL_DATA_CAPACITY (1600000)


#define DNX_DATA_MAX_NIF_GLOBAL_SINGLE_MGMT_PORT_CAPACITY (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_SINGLE_MGMT_PORT_CAPACITY
#define DNX_DATA_MAX_NIF_GLOBAL_SINGLE_MGMT_PORT_CAPACITY (25000)


#define DNX_DATA_MAX_NIF_GLOBAL_MAX_NOF_LANES_PER_PORT (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_MAX_NOF_LANES_PER_PORT
#define DNX_DATA_MAX_NIF_GLOBAL_MAX_NOF_LANES_PER_PORT (24)


#define DNX_DATA_MAX_NIF_GLOBAL_GHAO_SPEED_LIMIT (1)

#undef DNX_DATA_MAX_NIF_GLOBAL_GHAO_SPEED_LIMIT
#define DNX_DATA_MAX_NIF_GLOBAL_GHAO_SPEED_LIMIT (1200000)


#define DNX_DATA_MAX_NIF_PHYS_NOF_PHYS  (1)

#undef DNX_DATA_MAX_NIF_PHYS_NOF_PHYS
#define DNX_DATA_MAX_NIF_PHYS_NOF_PHYS  (144)


#define DNX_DATA_MAX_NIF_PHYS_MAX_PHYS_IN_CORE (1)

#undef DNX_DATA_MAX_NIF_PHYS_MAX_PHYS_IN_CORE
#define DNX_DATA_MAX_NIF_PHYS_MAX_PHYS_IN_CORE (128)


#define DNX_DATA_MAX_NIF_PHYS_PM8X50_GEN (1)

#undef DNX_DATA_MAX_NIF_PHYS_PM8X50_GEN
#define DNX_DATA_MAX_NIF_PHYS_PM8X50_GEN (2)


#define DNX_DATA_MAX_NIF_PHYS_IS_PAM4_SPEED_SUPPORTED (1)

#undef DNX_DATA_MAX_NIF_PHYS_IS_PAM4_SPEED_SUPPORTED
#define DNX_DATA_MAX_NIF_PHYS_IS_PAM4_SPEED_SUPPORTED (1)


#define DNX_DATA_MAX_NIF_PHYS_FIRST_MGMT_PHY (1)

#define DNX_DATA_MAX_NIF_PHYS_NOF_MGMT_PHYS (1)

#define DNX_DATA_MAX_NIF_PHYS_TXPI_SDM_SCHEME (1)

#undef DNX_DATA_MAX_NIF_PHYS_TXPI_SDM_SCHEME
#define DNX_DATA_MAX_NIF_PHYS_TXPI_SDM_SCHEME (1)


#define DNX_DATA_MAX_NIF_ILKN_ILU_NOF   (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILU_NOF
#define DNX_DATA_MAX_NIF_ILKN_ILU_NOF   (8)


#define DNX_DATA_MAX_NIF_ILKN_ILKN_UNIT_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILKN_UNIT_NOF
#define DNX_DATA_MAX_NIF_ILKN_ILKN_UNIT_NOF (8)


#define DNX_DATA_MAX_NIF_ILKN_ILKN_UNIT_IF_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILKN_UNIT_IF_NOF
#define DNX_DATA_MAX_NIF_ILKN_ILKN_UNIT_IF_NOF (2)


#define DNX_DATA_MAX_NIF_ILKN_ILKN_IF_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILKN_IF_NOF
#define DNX_DATA_MAX_NIF_ILKN_ILKN_IF_NOF (16)


#define DNX_DATA_MAX_NIF_ILKN_FEC_UNITS_PER_CORE_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_FEC_UNITS_PER_CORE_NOF
#define DNX_DATA_MAX_NIF_ILKN_FEC_UNITS_PER_CORE_NOF (16)


#define DNX_DATA_MAX_NIF_ILKN_NOF_LANES_PER_FEC_UNIT (1)

#undef DNX_DATA_MAX_NIF_ILKN_NOF_LANES_PER_FEC_UNIT
#define DNX_DATA_MAX_NIF_ILKN_NOF_LANES_PER_FEC_UNIT (2)


#define DNX_DATA_MAX_NIF_ILKN_LANES_MAX_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_LANES_MAX_NOF
#define DNX_DATA_MAX_NIF_ILKN_LANES_MAX_NOF (24)


#define DNX_DATA_MAX_NIF_ILKN_LANES_MAX_NOF_USING_FEC (1)

#undef DNX_DATA_MAX_NIF_ILKN_LANES_MAX_NOF_USING_FEC
#define DNX_DATA_MAX_NIF_ILKN_LANES_MAX_NOF_USING_FEC (24)


#define DNX_DATA_MAX_NIF_ILKN_LANES_ALLOWED_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_LANES_ALLOWED_NOF
#define DNX_DATA_MAX_NIF_ILKN_LANES_ALLOWED_NOF (24)


#define DNX_DATA_MAX_NIF_ILKN_ILKN_OVER_ETH_PMS_MAX (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILKN_OVER_ETH_PMS_MAX
#define DNX_DATA_MAX_NIF_ILKN_ILKN_OVER_ETH_PMS_MAX (6)


#define DNX_DATA_MAX_NIF_ILKN_SEGMENTS_MAX_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_SEGMENTS_MAX_NOF
#define DNX_DATA_MAX_NIF_ILKN_SEGMENTS_MAX_NOF (8)


#define DNX_DATA_MAX_NIF_ILKN_SEGMENTS_HALF_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_SEGMENTS_HALF_NOF
#define DNX_DATA_MAX_NIF_ILKN_SEGMENTS_HALF_NOF (4)


#define DNX_DATA_MAX_NIF_ILKN_PMS_NOF   (1)

#undef DNX_DATA_MAX_NIF_ILKN_PMS_NOF
#define DNX_DATA_MAX_NIF_ILKN_PMS_NOF   (6)


#define DNX_DATA_MAX_NIF_ILKN_FMAC_BUS_SIZE (1)

#undef DNX_DATA_MAX_NIF_ILKN_FMAC_BUS_SIZE
#define DNX_DATA_MAX_NIF_ILKN_FMAC_BUS_SIZE (70)


#define DNX_DATA_MAX_NIF_ILKN_ILKN_RX_HRF_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILKN_RX_HRF_NOF
#define DNX_DATA_MAX_NIF_ILKN_ILKN_RX_HRF_NOF (4)


#define DNX_DATA_MAX_NIF_ILKN_ILKN_TX_HRF_NOF (1)

#undef DNX_DATA_MAX_NIF_ILKN_ILKN_TX_HRF_NOF
#define DNX_DATA_MAX_NIF_ILKN_ILKN_TX_HRF_NOF (2)


#define DNX_DATA_MAX_NIF_ILKN_DATA_RX_HRF_SIZE (1)

#undef DNX_DATA_MAX_NIF_ILKN_DATA_RX_HRF_SIZE
#define DNX_DATA_MAX_NIF_ILKN_DATA_RX_HRF_SIZE (2048)


#define DNX_DATA_MAX_NIF_ILKN_TDM_RX_HRF_SIZE (1)

#undef DNX_DATA_MAX_NIF_ILKN_TDM_RX_HRF_SIZE
#define DNX_DATA_MAX_NIF_ILKN_TDM_RX_HRF_SIZE (256)


#define DNX_DATA_MAX_NIF_ILKN_TX_HRF_CREDITS (1)

#undef DNX_DATA_MAX_NIF_ILKN_TX_HRF_CREDITS
#define DNX_DATA_MAX_NIF_ILKN_TX_HRF_CREDITS (192)


#define DNX_DATA_MAX_NIF_ILKN_NOF_RX_HRF_PER_PORT (1)

#undef DNX_DATA_MAX_NIF_ILKN_NOF_RX_HRF_PER_PORT
#define DNX_DATA_MAX_NIF_ILKN_NOF_RX_HRF_PER_PORT (2)


#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_HIGH_ELK (1)

#undef DNX_DATA_MAX_NIF_ILKN_WATERMARK_HIGH_ELK
#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_HIGH_ELK (3)


#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_LOW_ELK (1)

#undef DNX_DATA_MAX_NIF_ILKN_WATERMARK_LOW_ELK
#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_LOW_ELK (4)


#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_HIGH_DATA (1)

#undef DNX_DATA_MAX_NIF_ILKN_WATERMARK_HIGH_DATA
#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_HIGH_DATA (11)


#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_LOW_DATA (1)

#undef DNX_DATA_MAX_NIF_ILKN_WATERMARK_LOW_DATA
#define DNX_DATA_MAX_NIF_ILKN_WATERMARK_LOW_DATA (12)


#define DNX_DATA_MAX_NIF_ILKN_PAD_SIZE  (1)

#undef DNX_DATA_MAX_NIF_ILKN_PAD_SIZE
#define DNX_DATA_MAX_NIF_ILKN_PAD_SIZE  (60)


#define DNX_DATA_MAX_NIF_ILKN_BURST_MAX_RANGE_MAX (1)

#undef DNX_DATA_MAX_NIF_ILKN_BURST_MAX_RANGE_MAX
#define DNX_DATA_MAX_NIF_ILKN_BURST_MAX_RANGE_MAX (512)


#define DNX_DATA_MAX_NIF_ILKN_BURST_MIN (1)

#undef DNX_DATA_MAX_NIF_ILKN_BURST_MIN
#define DNX_DATA_MAX_NIF_ILKN_BURST_MIN (64)


#define DNX_DATA_MAX_NIF_ILKN_BURST_SHORT (1)

#undef DNX_DATA_MAX_NIF_ILKN_BURST_SHORT
#define DNX_DATA_MAX_NIF_ILKN_BURST_SHORT (64)


#define DNX_DATA_MAX_NIF_ILKN_BURST_MIN_RANGE_MAX (1)

#undef DNX_DATA_MAX_NIF_ILKN_BURST_MIN_RANGE_MAX
#define DNX_DATA_MAX_NIF_ILKN_BURST_MIN_RANGE_MAX (256)


#define DNX_DATA_MAX_NIF_ETH_CDU_NOF    (1)

#undef DNX_DATA_MAX_NIF_ETH_CDU_NOF
#define DNX_DATA_MAX_NIF_ETH_CDU_NOF    (18)


#define DNX_DATA_MAX_NIF_ETH_CLU_NOF    (1)

#undef DNX_DATA_MAX_NIF_ETH_CLU_NOF
#define DNX_DATA_MAX_NIF_ETH_CLU_NOF    (6)


#define DNX_DATA_MAX_NIF_ETH_NBU_NOF    (1)

#undef DNX_DATA_MAX_NIF_ETH_NBU_NOF
#define DNX_DATA_MAX_NIF_ETH_NBU_NOF    (0)


#define DNX_DATA_MAX_NIF_ETH_MGU_NOF    (1)

#undef DNX_DATA_MAX_NIF_ETH_MGU_NOF
#define DNX_DATA_MAX_NIF_ETH_MGU_NOF    (0)


#define DNX_DATA_MAX_NIF_ETH_CDUM_NOF   (1)

#undef DNX_DATA_MAX_NIF_ETH_CDUM_NOF
#define DNX_DATA_MAX_NIF_ETH_CDUM_NOF   (2)


#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_CDU (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_CDU
#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_CDU (1)


#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_CLU (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_CLU
#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_CLU (4)


#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_NBU (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_NBU
#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_NBU (0)


#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_MGU (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_MGU
#define DNX_DATA_MAX_NIF_ETH_NOF_PMS_IN_MGU (0)


#define DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_ETHU_PMS_IN_DEVICE (1)

#undef DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_ETHU_PMS_IN_DEVICE
#define DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_ETHU_PMS_IN_DEVICE (28)


#define DNX_DATA_MAX_NIF_ETH_NOF_CDU_LANES_IN_PM (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_CDU_LANES_IN_PM
#define DNX_DATA_MAX_NIF_ETH_NOF_CDU_LANES_IN_PM (8)


#define DNX_DATA_MAX_NIF_ETH_NOF_CLU_LANES_IN_PM (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_CLU_LANES_IN_PM
#define DNX_DATA_MAX_NIF_ETH_NOF_CLU_LANES_IN_PM (4)


#define DNX_DATA_MAX_NIF_ETH_NOF_CDU_PMS (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_CDU_PMS
#define DNX_DATA_MAX_NIF_ETH_NOF_CDU_PMS (18)


#define DNX_DATA_MAX_NIF_ETH_NOF_CLU_PMS (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_CLU_PMS
#define DNX_DATA_MAX_NIF_ETH_NOF_CLU_PMS (24)


#define DNX_DATA_MAX_NIF_ETH_NOF_NBU_LANES_IN_PM (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_NBU_LANES_IN_PM
#define DNX_DATA_MAX_NIF_ETH_NOF_NBU_LANES_IN_PM (0)


#define DNX_DATA_MAX_NIF_ETH_NOF_MGU_LANES_IN_PM (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_MGU_LANES_IN_PM
#define DNX_DATA_MAX_NIF_ETH_NOF_MGU_LANES_IN_PM (0)


#define DNX_DATA_MAX_NIF_ETH_NOF_NBU_PMS (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_NBU_PMS
#define DNX_DATA_MAX_NIF_ETH_NOF_NBU_PMS (0)


#define DNX_DATA_MAX_NIF_ETH_NOF_MGU_PMS (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_MGU_PMS
#define DNX_DATA_MAX_NIF_ETH_NOF_MGU_PMS (0)


#define DNX_DATA_MAX_NIF_ETH_ETHU_NOF   (1)

#undef DNX_DATA_MAX_NIF_ETH_ETHU_NOF
#define DNX_DATA_MAX_NIF_ETH_ETHU_NOF   (18)


#define DNX_DATA_MAX_NIF_ETH_CDU_NOF_PER_CORE (1)

#undef DNX_DATA_MAX_NIF_ETH_CDU_NOF_PER_CORE
#define DNX_DATA_MAX_NIF_ETH_CDU_NOF_PER_CORE (9)


#define DNX_DATA_MAX_NIF_ETH_CLU_NOF_PER_CORE (1)

#undef DNX_DATA_MAX_NIF_ETH_CLU_NOF_PER_CORE
#define DNX_DATA_MAX_NIF_ETH_CLU_NOF_PER_CORE (6)


#define DNX_DATA_MAX_NIF_ETH_MAX_ETHU_NOF_PER_CORE (1)

#undef DNX_DATA_MAX_NIF_ETH_MAX_ETHU_NOF_PER_CORE
#define DNX_DATA_MAX_NIF_ETH_MAX_ETHU_NOF_PER_CORE (10)


#define DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_CDU (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_CDU
#define DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_CDU (8)


#define DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_CLU (1)

#undef DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_CLU
#define DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_CLU (16)


#define DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_NBU (1)

#define DNX_DATA_MAX_NIF_ETH_NOF_LANES_IN_MGU (1)

#define DNX_DATA_MAX_NIF_ETH_MAX_NOF_LANES_IN_ETHU (1)

#undef DNX_DATA_MAX_NIF_ETH_MAX_NOF_LANES_IN_ETHU
#define DNX_DATA_MAX_NIF_ETH_MAX_NOF_LANES_IN_ETHU (16)


#define DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_CDU_LANES_IN_DEVICE (1)

#undef DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_CDU_LANES_IN_DEVICE
#define DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_CDU_LANES_IN_DEVICE (144)


#define DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_NBU_LANES_IN_DEVICE (1)

#undef DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_NBU_LANES_IN_DEVICE
#define DNX_DATA_MAX_NIF_ETH_TOTAL_NOF_NBU_LANES_IN_DEVICE (0)


#define DNX_DATA_MAX_NIF_ETH_CDU_MAC_MODE_CONFIG_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_CDU_MAC_MODE_CONFIG_NOF
#define DNX_DATA_MAX_NIF_ETH_CDU_MAC_MODE_CONFIG_NOF (2)


#define DNX_DATA_MAX_NIF_ETH_NBU_MAC_MODE_CONFIG_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_NBU_MAC_MODE_CONFIG_NOF
#define DNX_DATA_MAX_NIF_ETH_NBU_MAC_MODE_CONFIG_NOF (0)


#define DNX_DATA_MAX_NIF_ETH_MAC_MODE_CONFIG_LANES_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_MAC_MODE_CONFIG_LANES_NOF
#define DNX_DATA_MAX_NIF_ETH_MAC_MODE_CONFIG_LANES_NOF (4)


#define DNX_DATA_MAX_NIF_ETH_CDU_MAC_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_CDU_MAC_NOF
#define DNX_DATA_MAX_NIF_ETH_CDU_MAC_NOF (2)


#define DNX_DATA_MAX_NIF_ETH_NBU_MAC_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_NBU_MAC_NOF
#define DNX_DATA_MAX_NIF_ETH_NBU_MAC_NOF (0)


#define DNX_DATA_MAX_NIF_ETH_MAC_LANES_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_MAC_LANES_NOF
#define DNX_DATA_MAX_NIF_ETH_MAC_LANES_NOF (8)


#define DNX_DATA_MAX_NIF_ETH_ETHU_LOGICAL_FIFO_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_ETHU_LOGICAL_FIFO_NOF
#define DNX_DATA_MAX_NIF_ETH_ETHU_LOGICAL_FIFO_NOF (16)


#define DNX_DATA_MAX_NIF_ETH_CDU_MEMORY_ENTRIES_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_CDU_MEMORY_ENTRIES_NOF
#define DNX_DATA_MAX_NIF_ETH_CDU_MEMORY_ENTRIES_NOF (1024)


#define DNX_DATA_MAX_NIF_ETH_CLU_MEMORY_ENTRIES_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_CLU_MEMORY_ENTRIES_NOF
#define DNX_DATA_MAX_NIF_ETH_CLU_MEMORY_ENTRIES_NOF (1024)


#define DNX_DATA_MAX_NIF_ETH_NBU_MEMORY_ENTRIES_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_NBU_MEMORY_ENTRIES_NOF
#define DNX_DATA_MAX_NIF_ETH_NBU_MEMORY_ENTRIES_NOF (1024)


#define DNX_DATA_MAX_NIF_ETH_MGU_MEMORY_ENTRIES_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_MGU_MEMORY_ENTRIES_NOF
#define DNX_DATA_MAX_NIF_ETH_MGU_MEMORY_ENTRIES_NOF (1024)


#define DNX_DATA_MAX_NIF_ETH_PRIORITY_GROUP_NOF_ENTRIES_MIN (1)

#undef DNX_DATA_MAX_NIF_ETH_PRIORITY_GROUP_NOF_ENTRIES_MIN
#define DNX_DATA_MAX_NIF_ETH_PRIORITY_GROUP_NOF_ENTRIES_MIN (4)


#define DNX_DATA_MAX_NIF_ETH_PRIORITY_GROUPS_NOF (1)

#undef DNX_DATA_MAX_NIF_ETH_PRIORITY_GROUPS_NOF
#define DNX_DATA_MAX_NIF_ETH_PRIORITY_GROUPS_NOF (3)


#define DNX_DATA_MAX_NIF_ETH_NOF_RMCS_PER_PRIORITY_GROUP (1)

#define DNX_DATA_MAX_NIF_ETH_PAD_SIZE_MIN (1)

#undef DNX_DATA_MAX_NIF_ETH_PAD_SIZE_MIN
#define DNX_DATA_MAX_NIF_ETH_PAD_SIZE_MIN (64)


#define DNX_DATA_MAX_NIF_ETH_PAD_SIZE_MAX (1)

#undef DNX_DATA_MAX_NIF_ETH_PAD_SIZE_MAX
#define DNX_DATA_MAX_NIF_ETH_PAD_SIZE_MAX (96)


#define DNX_DATA_MAX_NIF_ETH_PACKET_SIZE_MAX (1)

#undef DNX_DATA_MAX_NIF_ETH_PACKET_SIZE_MAX
#define DNX_DATA_MAX_NIF_ETH_PACKET_SIZE_MAX (10000)


#define DNX_DATA_MAX_NIF_ETH_AN_MAX_NOF_ABILITIES (1)

#undef DNX_DATA_MAX_NIF_ETH_AN_MAX_NOF_ABILITIES
#define DNX_DATA_MAX_NIF_ETH_AN_MAX_NOF_ABILITIES (20)


#define DNX_DATA_MAX_NIF_ETH_PHY_MAP_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_ETH_PHY_MAP_GRANULARITY
#define DNX_DATA_MAX_NIF_ETH_PHY_MAP_GRANULARITY (8)


#define DNX_DATA_MAX_NIF_ETH_VCO_FACTOR_FOR_53P125_RATE (1)

#define DNX_DATA_MAX_NIF_ETH_VCO_FACTOR_FOR_51P5625_RATE (1)

#define DNX_DATA_MAX_NIF_ETH_IS_400G_SUPPORTED (1)

#undef DNX_DATA_MAX_NIF_ETH_IS_400G_SUPPORTED
#define DNX_DATA_MAX_NIF_ETH_IS_400G_SUPPORTED (1)


#define DNX_DATA_MAX_NIF_ETH_IS_800G_SUPPORTED (1)

#define DNX_DATA_MAX_NIF_FRAMER_NOF_UNITS (1)

#undef DNX_DATA_MAX_NIF_FRAMER_NOF_UNITS
#define DNX_DATA_MAX_NIF_FRAMER_NOF_UNITS (1)


#define DNX_DATA_MAX_NIF_FRAMER_B66SWITCH_BACKUP_CHANNELS (1)

#undef DNX_DATA_MAX_NIF_FRAMER_B66SWITCH_BACKUP_CHANNELS
#define DNX_DATA_MAX_NIF_FRAMER_B66SWITCH_BACKUP_CHANNELS (2)


#define DNX_DATA_MAX_NIF_FRAMER_GEN     (1)

#undef DNX_DATA_MAX_NIF_FRAMER_GEN
#define DNX_DATA_MAX_NIF_FRAMER_GEN     (2)


#define DNX_DATA_MAX_NIF_FRAMER_NOF_MGMT_CHANNELS (1)

#undef DNX_DATA_MAX_NIF_FRAMER_NOF_MGMT_CHANNELS
#define DNX_DATA_MAX_NIF_FRAMER_NOF_MGMT_CHANNELS (4)


#define DNX_DATA_MAX_NIF_FRAMER_CLOCK_MHZ (1)

#undef DNX_DATA_MAX_NIF_FRAMER_CLOCK_MHZ
#define DNX_DATA_MAX_NIF_FRAMER_CLOCK_MHZ (1152)


#define DNX_DATA_MAX_NIF_FRAMER_PTP_CHANNEL_MAX_BANDWIDTH (1)

#undef DNX_DATA_MAX_NIF_FRAMER_PTP_CHANNEL_MAX_BANDWIDTH
#define DNX_DATA_MAX_NIF_FRAMER_PTP_CHANNEL_MAX_BANDWIDTH (10000)


#define DNX_DATA_MAX_NIF_FRAMER_OAM_CHANNEL_MAX_BANDWIDTH (1)

#undef DNX_DATA_MAX_NIF_FRAMER_OAM_CHANNEL_MAX_BANDWIDTH
#define DNX_DATA_MAX_NIF_FRAMER_OAM_CHANNEL_MAX_BANDWIDTH (25000)


#define DNX_DATA_MAX_NIF_FRAMER_NOF_MAC1_CHANNELS (1)

#undef DNX_DATA_MAX_NIF_FRAMER_NOF_MAC1_CHANNELS
#define DNX_DATA_MAX_NIF_FRAMER_NOF_MAC1_CHANNELS (320)


#define DNX_DATA_MAX_NIF_FRAMER_NOF_MAC2_CHANNELS (1)

#undef DNX_DATA_MAX_NIF_FRAMER_NOF_MAC2_CHANNELS
#define DNX_DATA_MAX_NIF_FRAMER_NOF_MAC2_CHANNELS (80)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_NORMAL_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_NORMAL_CLIENTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_NORMAL_CLIENTS (320)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SPECIAL_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SPECIAL_CLIENTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SPECIAL_CLIENTS (2)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_CLIENTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_CLIENTS (320)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_CHANNEL_BASE (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_CHANNEL_BASE
#define DNX_DATA_MAX_NIF_MAC_CLIENT_CHANNEL_BASE (160)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_MAX_NOF_SLOTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_MAX_NOF_SLOTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_MAX_NOF_SLOTS (1700)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_LOGICAL_FIFOS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_LOGICAL_FIFOS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_LOGICAL_FIFOS (128)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_CLIENT_CHANNEL (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_CLIENT_CHANNEL
#define DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_CLIENT_CHANNEL (80)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_CLIENT_CHANNEL (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_CLIENT_CHANNEL
#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_CLIENT_CHANNEL (81)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_TX_CAL_SLOT (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_TX_CAL_SLOT
#define DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_TX_CAL_SLOT (0)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_TX_CAL_SLOT (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_TX_CAL_SLOT
#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_TX_CAL_SLOT (40)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_PRIORITY_GROUPS_NOF (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_PRIORITY_GROUPS_NOF
#define DNX_DATA_MAX_NIF_MAC_CLIENT_PRIORITY_GROUPS_NOF (3)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_CHANNEL_MAX_BANDWIDTH (1)

#define DNX_DATA_MAX_NIF_MAC_CLIENT_OAM_CHANNEL_MAX_BANDWIDTH (1)

#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_MEM_ENTRIES_PER_SLOT (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_MEM_ENTRIES_PER_SLOT
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_MEM_ENTRIES_PER_SLOT (128)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_OAM_FIFO_ENTRIES_IN_SB_RX (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_OAM_FIFO_ENTRIES_IN_SB_RX
#define DNX_DATA_MAX_NIF_MAC_CLIENT_PTP_OAM_FIFO_ENTRIES_IN_SB_RX (4)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_AVERAGE_IPG_FOR_L1 (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_AVERAGE_IPG_FOR_L1
#define DNX_DATA_MAX_NIF_MAC_CLIENT_AVERAGE_IPG_FOR_L1 (88)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_MAC_TX_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_MAC_TX_THRESHOLD
#define DNX_DATA_MAX_NIF_MAC_CLIENT_MAC_TX_THRESHOLD (4)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_RMC_CAL_NOF_SLOTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_RMC_CAL_NOF_SLOTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_RMC_CAL_NOF_SLOTS (128)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_MAC_TIMESLOTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_MAC_TIMESLOTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_MAC_TIMESLOTS (320)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_TX_AVERAGE_IPG_MAX (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_TX_AVERAGE_IPG_MAX
#define DNX_DATA_MAX_NIF_MAC_CLIENT_TX_AVERAGE_IPG_MAX (63)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_TX_THRESHOLD_MAX (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_TX_THRESHOLD_MAX
#define DNX_DATA_MAX_NIF_MAC_CLIENT_TX_THRESHOLD_MAX (15)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_TX_FIFO_CELL_CNT_MAX (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_TX_FIFO_CELL_CNT_MAX
#define DNX_DATA_MAX_NIF_MAC_CLIENT_TX_FIFO_CELL_CNT_MAX (4095)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_SB_FIFO_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_SB_FIFO_GRANULARITY
#define DNX_DATA_MAX_NIF_MAC_CLIENT_SB_FIFO_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_SB_CAL_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_SB_CAL_GRANULARITY
#define DNX_DATA_MAX_NIF_MAC_CLIENT_SB_CAL_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SB_FIFOS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SB_FIFOS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SB_FIFOS (640)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SB_CAL_SLOTS (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SB_CAL_SLOTS
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_SB_CAL_SLOTS (6800)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_UNITS_PER_SB_TX_FIFO (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_UNITS_PER_SB_TX_FIFO
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_UNITS_PER_SB_TX_FIFO (4)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_UNITS_PER_SB_RX_FIFO (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_UNITS_PER_SB_RX_FIFO
#define DNX_DATA_MAX_NIF_MAC_CLIENT_NOF_UNITS_PER_SB_RX_FIFO (8)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_TINYMAC_CLOCK_MHZ (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_TINYMAC_CLOCK_MHZ
#define DNX_DATA_MAX_NIF_MAC_CLIENT_TINYMAC_CLOCK_MHZ (1700)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_SB_TX_INIT_CREDIT_FOR_5G (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_SB_TX_INIT_CREDIT_FOR_5G
#define DNX_DATA_MAX_NIF_MAC_CLIENT_SB_TX_INIT_CREDIT_FOR_5G (3)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_ASYNC_FIFO_DELAY_CYCLES (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_ASYNC_FIFO_DELAY_CYCLES
#define DNX_DATA_MAX_NIF_MAC_CLIENT_ASYNC_FIFO_DELAY_CYCLES (260)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_PIPE_DELAY_CYCLES (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_PIPE_DELAY_CYCLES
#define DNX_DATA_MAX_NIF_MAC_CLIENT_PIPE_DELAY_CYCLES (20)


#define DNX_DATA_MAX_NIF_MAC_CLIENT_MAC_PAD_SIZE (1)

#undef DNX_DATA_MAX_NIF_MAC_CLIENT_MAC_PAD_SIZE
#define DNX_DATA_MAX_NIF_MAC_CLIENT_MAC_PAD_SIZE (64)


#define DNX_DATA_MAX_NIF_SAR_CLIENT_NOF_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_SAR_CLIENT_NOF_CLIENTS
#define DNX_DATA_MAX_NIF_SAR_CLIENT_NOF_CLIENTS (320)


#define DNX_DATA_MAX_NIF_SAR_CLIENT_ILKN_BURST_SIZE_IN_FEU (1)

#undef DNX_DATA_MAX_NIF_SAR_CLIENT_ILKN_BURST_SIZE_IN_FEU
#define DNX_DATA_MAX_NIF_SAR_CLIENT_ILKN_BURST_SIZE_IN_FEU (244)


#define DNX_DATA_MAX_NIF_SAR_CLIENT_NOF_SAR_TIMESLOTS (1)

#undef DNX_DATA_MAX_NIF_SAR_CLIENT_NOF_SAR_TIMESLOTS
#define DNX_DATA_MAX_NIF_SAR_CLIENT_NOF_SAR_TIMESLOTS (320)


#define DNX_DATA_MAX_NIF_SAR_CLIENT_CHANNEL_BASE (1)

#undef DNX_DATA_MAX_NIF_SAR_CLIENT_CHANNEL_BASE
#define DNX_DATA_MAX_NIF_SAR_CLIENT_CHANNEL_BASE (80)


#define DNX_DATA_MAX_NIF_SAR_CLIENT_SAR_JITTER_TOLERANCE_MAX_LEVEL (1)

#undef DNX_DATA_MAX_NIF_SAR_CLIENT_SAR_JITTER_TOLERANCE_MAX_LEVEL
#define DNX_DATA_MAX_NIF_SAR_CLIENT_SAR_JITTER_TOLERANCE_MAX_LEVEL (7)


#define DNX_DATA_MAX_NIF_SAR_CLIENT_CAL_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_SAR_CLIENT_CAL_GRANULARITY
#define DNX_DATA_MAX_NIF_SAR_CLIENT_CAL_GRANULARITY (250)


#define DNX_DATA_MAX_NIF_FLEXE_FEU_NOF  (1)

#undef DNX_DATA_MAX_NIF_FLEXE_FEU_NOF
#define DNX_DATA_MAX_NIF_FLEXE_FEU_NOF  (1)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_CLIENTS
#define DNX_DATA_MAX_NIF_FLEXE_NOF_CLIENTS (320)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_GROUPS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_GROUPS
#define DNX_DATA_MAX_NIF_FLEXE_NOF_GROUPS (16)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_GROUP_ID (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_GROUP_ID
#define DNX_DATA_MAX_NIF_FLEXE_MAX_GROUP_ID (1048574)


#define DNX_DATA_MAX_NIF_FLEXE_MIN_GROUP_ID (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MIN_GROUP_ID
#define DNX_DATA_MAX_NIF_FLEXE_MIN_GROUP_ID (0)


#define DNX_DATA_MAX_NIF_FLEXE_NB_TX_DELAY (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NB_TX_DELAY
#define DNX_DATA_MAX_NIF_FLEXE_NB_TX_DELAY (6)


#define DNX_DATA_MAX_NIF_FLEXE_NB_TX_FIFO_TH_FOR_FIRST_READ (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NB_TX_FIFO_TH_FOR_FIRST_READ
#define DNX_DATA_MAX_NIF_FLEXE_NB_TX_FIFO_TH_FOR_FIRST_READ (25)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_PCS  (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_PCS
#define DNX_DATA_MAX_NIF_FLEXE_NOF_PCS  (16)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_PHY_SPEEDS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_PHY_SPEEDS
#define DNX_DATA_MAX_NIF_FLEXE_NOF_PHY_SPEEDS (4)


#define DNX_DATA_MAX_NIF_FLEXE_PHY_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_FLEXE_PHY_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_FLEXE_PHY_SPEED_GRANULARITY (50000)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_FLEXE_CORE_SPEED (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_FLEXE_CORE_SPEED
#define DNX_DATA_MAX_NIF_FLEXE_MAX_FLEXE_CORE_SPEED (1600000)


#define DNX_DATA_MAX_NIF_FLEXE_FLEXE_CORE_CLOCK_SOURCE_PM (1)

#undef DNX_DATA_MAX_NIF_FLEXE_FLEXE_CORE_CLOCK_SOURCE_PM
#define DNX_DATA_MAX_NIF_FLEXE_FLEXE_CORE_CLOCK_SOURCE_PM (0)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_NOF_SLOTS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_NOF_SLOTS
#define DNX_DATA_MAX_NIF_FLEXE_MAX_NOF_SLOTS (960)


#define DNX_DATA_MAX_NIF_FLEXE_MIN_CLIENT_ID (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MIN_CLIENT_ID
#define DNX_DATA_MAX_NIF_FLEXE_MIN_CLIENT_ID (1)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_CLIENT_ID (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_CLIENT_ID
#define DNX_DATA_MAX_NIF_FLEXE_MAX_CLIENT_ID (65534)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_INSTANCES (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_INSTANCES
#define DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_INSTANCES (16)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_LPHYS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_LPHYS
#define DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_LPHYS (32)


#define DNX_DATA_MAX_NIF_FLEXE_DISTRIBUTED_ILU_ID (1)

#undef DNX_DATA_MAX_NIF_FLEXE_DISTRIBUTED_ILU_ID
#define DNX_DATA_MAX_NIF_FLEXE_DISTRIBUTED_ILU_ID (1)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_NIF_RATE_CENTRALIZED (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_NIF_RATE_CENTRALIZED
#define DNX_DATA_MAX_NIF_FLEXE_MAX_NIF_RATE_CENTRALIZED (1220000)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_NIF_RATE_DISTRIBUTED (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_NIF_RATE_DISTRIBUTED
#define DNX_DATA_MAX_NIF_FLEXE_MAX_NIF_RATE_DISTRIBUTED (420000)


#define DNX_DATA_MAX_NIF_FLEXE_MAX_ILU_RATE_DISTRIBUTED (1)

#undef DNX_DATA_MAX_NIF_FLEXE_MAX_ILU_RATE_DISTRIBUTED
#define DNX_DATA_MAX_NIF_FLEXE_MAX_ILU_RATE_DISTRIBUTED (618744)


#define DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_CORE_PORTS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_CORE_PORTS
#define DNX_DATA_MAX_NIF_FLEXE_NOF_FLEXE_CORE_PORTS (64)


#define DNX_DATA_MAX_NIF_FLEXE_NB_CAL_NOF_SLOTS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NB_CAL_NOF_SLOTS
#define DNX_DATA_MAX_NIF_FLEXE_NB_CAL_NOF_SLOTS (340)


#define DNX_DATA_MAX_NIF_FLEXE_NB_CAL_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NB_CAL_GRANULARITY
#define DNX_DATA_MAX_NIF_FLEXE_NB_CAL_GRANULARITY (50000)


#define DNX_DATA_MAX_NIF_FLEXE_NON_5G_SLOT_BW (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NON_5G_SLOT_BW
#define DNX_DATA_MAX_NIF_FLEXE_NON_5G_SLOT_BW (800000)


#define DNX_DATA_MAX_NIF_FLEXE_NB_CAL_SLOT_NOF_BITS (1)

#undef DNX_DATA_MAX_NIF_FLEXE_NB_CAL_SLOT_NOF_BITS
#define DNX_DATA_MAX_NIF_FLEXE_NB_CAL_SLOT_NOF_BITS (7)


#define DNX_DATA_MAX_NIF_PRD_NOF_CONTROL_FRAMES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_CONTROL_FRAMES
#define DNX_DATA_MAX_NIF_PRD_NOF_CONTROL_FRAMES (4)


#define DNX_DATA_MAX_NIF_PRD_NOF_ETHER_TYPE_CODES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_ETHER_TYPE_CODES
#define DNX_DATA_MAX_NIF_PRD_NOF_ETHER_TYPE_CODES (16)


#define DNX_DATA_MAX_NIF_PRD_NOF_TCAM_ENTRIES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_TCAM_ENTRIES
#define DNX_DATA_MAX_NIF_PRD_NOF_TCAM_ENTRIES (32)


#define DNX_DATA_MAX_NIF_PRD_TCAM_KEY_OFFSET_SIZE (1)

#undef DNX_DATA_MAX_NIF_PRD_TCAM_KEY_OFFSET_SIZE
#define DNX_DATA_MAX_NIF_PRD_TCAM_KEY_OFFSET_SIZE (7)


#define DNX_DATA_MAX_NIF_PRD_NOF_MPLS_SPECIAL_LABELS (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_MPLS_SPECIAL_LABELS
#define DNX_DATA_MAX_NIF_PRD_NOF_MPLS_SPECIAL_LABELS (4)


#define DNX_DATA_MAX_NIF_PRD_NOF_PRIORITIES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_PRIORITIES
#define DNX_DATA_MAX_NIF_PRD_NOF_PRIORITIES (4)


#define DNX_DATA_MAX_NIF_PRD_CUSTOM_ETHER_TYPE_CODE_MIN (1)

#undef DNX_DATA_MAX_NIF_PRD_CUSTOM_ETHER_TYPE_CODE_MIN
#define DNX_DATA_MAX_NIF_PRD_CUSTOM_ETHER_TYPE_CODE_MIN (1)


#define DNX_DATA_MAX_NIF_PRD_CUSTOM_ETHER_TYPE_CODE_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_CUSTOM_ETHER_TYPE_CODE_MAX
#define DNX_DATA_MAX_NIF_PRD_CUSTOM_ETHER_TYPE_CODE_MAX (6)


#define DNX_DATA_MAX_NIF_PRD_ETHER_TYPE_CODE_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_ETHER_TYPE_CODE_MAX
#define DNX_DATA_MAX_NIF_PRD_ETHER_TYPE_CODE_MAX (15)


#define DNX_DATA_MAX_NIF_PRD_ETHER_TYPE_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_ETHER_TYPE_MAX
#define DNX_DATA_MAX_NIF_PRD_ETHER_TYPE_MAX (65535)


#define DNX_DATA_MAX_NIF_PRD_RMC_THRESHOLD_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_RMC_THRESHOLD_MAX
#define DNX_DATA_MAX_NIF_PRD_RMC_THRESHOLD_MAX (65535)


#define DNX_DATA_MAX_NIF_PRD_CDU_RMC_THRESHOLD_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_CDU_RMC_THRESHOLD_MAX
#define DNX_DATA_MAX_NIF_PRD_CDU_RMC_THRESHOLD_MAX (65535)


#define DNX_DATA_MAX_NIF_PRD_HRF_THRESHOLD_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_HRF_THRESHOLD_MAX
#define DNX_DATA_MAX_NIF_PRD_HRF_THRESHOLD_MAX (8191)


#define DNX_DATA_MAX_NIF_PRD_MPLS_SPECIAL_LABEL_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_MPLS_SPECIAL_LABEL_MAX
#define DNX_DATA_MAX_NIF_PRD_MPLS_SPECIAL_LABEL_MAX (15)


#define DNX_DATA_MAX_NIF_PRD_FLEX_KEY_OFFSET_KEY_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_FLEX_KEY_OFFSET_KEY_MAX
#define DNX_DATA_MAX_NIF_PRD_FLEX_KEY_OFFSET_KEY_MAX (127)


#define DNX_DATA_MAX_NIF_PRD_FLEX_KEY_OFFSET_RESULT_MAX (1)

#undef DNX_DATA_MAX_NIF_PRD_FLEX_KEY_OFFSET_RESULT_MAX
#define DNX_DATA_MAX_NIF_PRD_FLEX_KEY_OFFSET_RESULT_MAX (255)


#define DNX_DATA_MAX_NIF_PRD_TPID_MAX   (1)

#undef DNX_DATA_MAX_NIF_PRD_TPID_MAX
#define DNX_DATA_MAX_NIF_PRD_TPID_MAX   (65535)


#define DNX_DATA_MAX_NIF_PRD_NOF_CLU_PORT_PROFILES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_CLU_PORT_PROFILES
#define DNX_DATA_MAX_NIF_PRD_NOF_CLU_PORT_PROFILES (4)


#define DNX_DATA_MAX_NIF_PRD_NOF_FRAMER_PORT_PROFILES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_FRAMER_PORT_PROFILES
#define DNX_DATA_MAX_NIF_PRD_NOF_FRAMER_PORT_PROFILES (8)


#define DNX_DATA_MAX_NIF_PRD_NOF_OFR_PORT_PROFILES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_OFR_PORT_PROFILES
#define DNX_DATA_MAX_NIF_PRD_NOF_OFR_PORT_PROFILES (8)


#define DNX_DATA_MAX_NIF_PRD_RMC_FIFO_2_THRESHOLD_RESOLUTION (1)

#undef DNX_DATA_MAX_NIF_PRD_RMC_FIFO_2_THRESHOLD_RESOLUTION
#define DNX_DATA_MAX_NIF_PRD_RMC_FIFO_2_THRESHOLD_RESOLUTION (16)


#define DNX_DATA_MAX_NIF_PRD_NOF_OFR_NIF_INTERFACES (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_OFR_NIF_INTERFACES
#define DNX_DATA_MAX_NIF_PRD_NOF_OFR_NIF_INTERFACES (384)


#define DNX_DATA_MAX_NIF_PRD_NOF_PRD_COUNTERS (1)

#undef DNX_DATA_MAX_NIF_PRD_NOF_PRD_COUNTERS
#define DNX_DATA_MAX_NIF_PRD_NOF_PRD_COUNTERS (144)


#define DNX_DATA_MAX_NIF_PORTMOD_PM_TYPES_NOF (1)

#undef DNX_DATA_MAX_NIF_PORTMOD_PM_TYPES_NOF
#define DNX_DATA_MAX_NIF_PORTMOD_PM_TYPES_NOF (4)


#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_ETHU_BIT (1)

#undef DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_ETHU_BIT
#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_ETHU_BIT (100000)


#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_ILU_BIT (1)

#undef DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_ILU_BIT
#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_ILU_BIT (150000)


#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_CDU_RMC_BIT (1)

#undef DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_CDU_RMC_BIT
#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_CDU_RMC_BIT (100000)


#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_CLU_RMC_BIT (1)

#undef DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_CLU_RMC_BIT
#define DNX_DATA_MAX_NIF_SCHEDULER_RATE_PER_CLU_RMC_BIT (25000)


#define DNX_DATA_MAX_NIF_SCHEDULER_NOF_WEIGHT_BITS (1)

#undef DNX_DATA_MAX_NIF_SCHEDULER_NOF_WEIGHT_BITS
#define DNX_DATA_MAX_NIF_SCHEDULER_NOF_WEIGHT_BITS (4)


#define DNX_DATA_MAX_NIF_SCHEDULER_NOF_RMC_BITS (1)

#undef DNX_DATA_MAX_NIF_SCHEDULER_NOF_RMC_BITS
#define DNX_DATA_MAX_NIF_SCHEDULER_NOF_RMC_BITS (4)


#define DNX_DATA_MAX_NIF_SCHEDULER_DYNAMIC_SCHEDULING_RATE_RESOLUTION (1)

#define DNX_DATA_MAX_NIF_SCHEDULER_RMC_MAP_TABLE_NOF_ENTRIES (1)

#define DNX_DATA_MAX_NIF_SCHEDULER_RMC_MAP_TABLE_ENTRY_RESOLUTION (1)

#define DNX_DATA_MAX_NIF_DBAL_CDU_RX_RMC_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_CDU_RX_RMC_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_CDU_RX_RMC_ENTRY_SIZE (12)


#define DNX_DATA_MAX_NIF_DBAL_CLU_RX_RMC_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_CLU_RX_RMC_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_CLU_RX_RMC_ENTRY_SIZE (10)


#define DNX_DATA_MAX_NIF_DBAL_CDU_TX_START_THRESHOLD_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_CDU_TX_START_THRESHOLD_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_CDU_TX_START_THRESHOLD_ENTRY_SIZE (15)


#define DNX_DATA_MAX_NIF_DBAL_CLU_TX_START_THRESHOLD_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_CLU_TX_START_THRESHOLD_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_CLU_TX_START_THRESHOLD_ENTRY_SIZE (14)


#define DNX_DATA_MAX_NIF_DBAL_NBU_TX_START_THRESHOLD_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_NBU_TX_START_THRESHOLD_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_NBU_TX_START_THRESHOLD_ENTRY_SIZE (0)


#define DNX_DATA_MAX_NIF_DBAL_MGU_TX_START_THRESHOLD_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_MGU_TX_START_THRESHOLD_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_MGU_TX_START_THRESHOLD_ENTRY_SIZE (0)


#define DNX_DATA_MAX_NIF_DBAL_NBU_TX_THRESHOLD_AFTER_OVF_ENTRY_SIZE (1)

#define DNX_DATA_MAX_NIF_DBAL_MGU_TX_THRESHOLD_AFTER_OVF_ENTRY_SIZE (1)

#define DNX_DATA_MAX_NIF_DBAL_NBU_RX_FIFO_SRSTN_ENTRY_SIZE (1)

#define DNX_DATA_MAX_NIF_DBAL_MGU_RX_FIFO_SRSTN_ENTRY_SIZE (1)

#define DNX_DATA_MAX_NIF_DBAL_ILU_BURST_MIN_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_ILU_BURST_MIN_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_ILU_BURST_MIN_ENTRY_SIZE (2)


#define DNX_DATA_MAX_NIF_DBAL_ETHU_RX_RMC_COUNTER_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_ETHU_RX_RMC_COUNTER_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_ETHU_RX_RMC_COUNTER_ENTRY_SIZE (15)


#define DNX_DATA_MAX_NIF_DBAL_CDU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_CDU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_CDU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE (14)


#define DNX_DATA_MAX_NIF_DBAL_CLU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_CLU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE
#define DNX_DATA_MAX_NIF_DBAL_CLU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE (14)


#define DNX_DATA_MAX_NIF_DBAL_NBU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE (1)

#define DNX_DATA_MAX_NIF_DBAL_MGU_LANE_FIFO_LEVEL_AND_OCCUPANCY_ENTRY_SIZE (1)

#define DNX_DATA_MAX_NIF_DBAL_SCH_CNT_DEC_THRESHOLD_BIT_SIZE (1)

#undef DNX_DATA_MAX_NIF_DBAL_SCH_CNT_DEC_THRESHOLD_BIT_SIZE
#define DNX_DATA_MAX_NIF_DBAL_SCH_CNT_DEC_THRESHOLD_BIT_SIZE (15)


#define DNX_DATA_MAX_NIF_DBAL_TX_CREDITS_BITS (1)

#undef DNX_DATA_MAX_NIF_DBAL_TX_CREDITS_BITS
#define DNX_DATA_MAX_NIF_DBAL_TX_CREDITS_BITS (8)


#define DNX_DATA_MAX_NIF_DBAL_NOF_RX_FIFO_COUNTERS (1)

#undef DNX_DATA_MAX_NIF_DBAL_NOF_RX_FIFO_COUNTERS
#define DNX_DATA_MAX_NIF_DBAL_NOF_RX_FIFO_COUNTERS (8)


#define DNX_DATA_MAX_NIF_DBAL_NOF_TX_FIFO_COUNTERS (1)

#undef DNX_DATA_MAX_NIF_DBAL_NOF_TX_FIFO_COUNTERS
#define DNX_DATA_MAX_NIF_DBAL_NOF_TX_FIFO_COUNTERS (8)


#define DNX_DATA_MAX_NIF_ARB_NOF_CONTEXTS (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_CONTEXTS
#define DNX_DATA_MAX_NIF_ARB_NOF_CONTEXTS (384)


#define DNX_DATA_MAX_NIF_ARB_NOF_RX_QPMS (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_RX_QPMS
#define DNX_DATA_MAX_NIF_ARB_NOF_RX_QPMS (2)


#define DNX_DATA_MAX_NIF_ARB_NOF_RX_PPMS_IN_QPM (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_RX_PPMS_IN_QPM
#define DNX_DATA_MAX_NIF_ARB_NOF_RX_PPMS_IN_QPM (4)


#define DNX_DATA_MAX_NIF_ARB_NOF_LANES_IN_QPM (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_LANES_IN_QPM
#define DNX_DATA_MAX_NIF_ARB_NOF_LANES_IN_QPM (32)


#define DNX_DATA_MAX_NIF_ARB_NOF_MAP_DESTINATIONS (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_MAP_DESTINATIONS
#define DNX_DATA_MAX_NIF_ARB_NOF_MAP_DESTINATIONS (3)


#define DNX_DATA_MAX_NIF_ARB_MAX_CALENDAR_LENGTH (1)

#undef DNX_DATA_MAX_NIF_ARB_MAX_CALENDAR_LENGTH
#define DNX_DATA_MAX_NIF_ARB_MAX_CALENDAR_LENGTH (6800)


#define DNX_DATA_MAX_NIF_ARB_NOF_RX_SOURCES (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_RX_SOURCES
#define DNX_DATA_MAX_NIF_ARB_NOF_RX_SOURCES (3)


#define DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_NOF_MODES (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_NOF_MODES
#define DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_NOF_MODES (9)


#define DNX_DATA_MAX_NIF_ARB_RX_QPM_CALENDAR_LENGTH (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_QPM_CALENDAR_LENGTH
#define DNX_DATA_MAX_NIF_ARB_RX_QPM_CALENDAR_LENGTH (340)


#define DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_LENGTH (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_LENGTH
#define DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_LENGTH (6800)


#define DNX_DATA_MAX_NIF_ARB_CDPM_CALENDAR_LENGTH (1)

#undef DNX_DATA_MAX_NIF_ARB_CDPM_CALENDAR_LENGTH
#define DNX_DATA_MAX_NIF_ARB_CDPM_CALENDAR_LENGTH (80)


#define DNX_DATA_MAX_NIF_ARB_TMAC_CALENDAR_LENGTH (1)

#undef DNX_DATA_MAX_NIF_ARB_TMAC_CALENDAR_LENGTH
#define DNX_DATA_MAX_NIF_ARB_TMAC_CALENDAR_LENGTH (6800)


#define DNX_DATA_MAX_NIF_ARB_RX_QPM_CALENDAR_NOF_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_QPM_CALENDAR_NOF_CLIENTS
#define DNX_DATA_MAX_NIF_ARB_RX_QPM_CALENDAR_NOF_CLIENTS (32)


#define DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_NOF_CLIENTS (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_NOF_CLIENTS
#define DNX_DATA_MAX_NIF_ARB_RX_SCH_CALENDAR_NOF_CLIENTS (384)


#define DNX_DATA_MAX_NIF_ARB_RX_QPM_PORT_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_QPM_PORT_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_ARB_RX_QPM_PORT_SPEED_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_ARB_RX_SCH_PORT_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_SCH_PORT_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_ARB_RX_SCH_PORT_SPEED_GRANULARITY (250)


#define DNX_DATA_MAX_NIF_ARB_TX_ETH_PORT_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_ARB_TX_ETH_PORT_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_ARB_TX_ETH_PORT_SPEED_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_ARB_TX_TMAC_PORT_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_ARB_TX_TMAC_PORT_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_ARB_TX_TMAC_PORT_SPEED_GRANULARITY (250)


#define DNX_DATA_MAX_NIF_ARB_TX_TMAC_NOF_SECTIONS (1)

#undef DNX_DATA_MAX_NIF_ARB_TX_TMAC_NOF_SECTIONS
#define DNX_DATA_MAX_NIF_ARB_TX_TMAC_NOF_SECTIONS (680)


#define DNX_DATA_MAX_NIF_ARB_TX_TMAC_LINK_LIST_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_ARB_TX_TMAC_LINK_LIST_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_ARB_TX_TMAC_LINK_LIST_SPEED_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_ARB_NOF_ENTRIES_IN_MEMORY_ROW_FOR_RX_CALENDAR (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_ENTRIES_IN_MEMORY_ROW_FOR_RX_CALENDAR
#define DNX_DATA_MAX_NIF_ARB_NOF_ENTRIES_IN_MEMORY_ROW_FOR_RX_CALENDAR (20)


#define DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_RX_CALENDAR (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_RX_CALENDAR
#define DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_RX_CALENDAR (4)


#define DNX_DATA_MAX_NIF_ARB_NOF_ENTRIES_IN_TMAC_CALENDAR (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_ENTRIES_IN_TMAC_CALENDAR
#define DNX_DATA_MAX_NIF_ARB_NOF_ENTRIES_IN_TMAC_CALENDAR (10)


#define DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_TMAC_CALENDAR (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_TMAC_CALENDAR
#define DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_TMAC_CALENDAR (9)


#define DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_PPM_CALENDAR (1)

#undef DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_PPM_CALENDAR
#define DNX_DATA_MAX_NIF_ARB_NOF_BIT_PER_ENTRY_IN_PPM_CALENDAR (4)


#define DNX_DATA_MAX_NIF_ARB_MIN_PORT_SPEED_FOR_LINK_LIST_SECTION (1)

#undef DNX_DATA_MAX_NIF_ARB_MIN_PORT_SPEED_FOR_LINK_LIST_SECTION
#define DNX_DATA_MAX_NIF_ARB_MIN_PORT_SPEED_FOR_LINK_LIST_SECTION (3000)


#define DNX_DATA_MAX_NIF_ARB_LINK_LIST_SECTIONS_DENOMINATOR (1)

#undef DNX_DATA_MAX_NIF_ARB_LINK_LIST_SECTIONS_DENOMINATOR
#define DNX_DATA_MAX_NIF_ARB_LINK_LIST_SECTIONS_DENOMINATOR (10000)


#define DNX_DATA_MAX_NIF_ARB_HIGH_START_TX_SPEED_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_ARB_HIGH_START_TX_SPEED_THRESHOLD
#define DNX_DATA_MAX_NIF_ARB_HIGH_START_TX_SPEED_THRESHOLD (800000)


#define DNX_DATA_MAX_NIF_ARB_LOW_START_TX_SPEED_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_ARB_LOW_START_TX_SPEED_THRESHOLD
#define DNX_DATA_MAX_NIF_ARB_LOW_START_TX_SPEED_THRESHOLD (3000)


#define DNX_DATA_MAX_NIF_ARB_HIGH_START_TX_SPEED_VALUE (1)

#undef DNX_DATA_MAX_NIF_ARB_HIGH_START_TX_SPEED_VALUE
#define DNX_DATA_MAX_NIF_ARB_HIGH_START_TX_SPEED_VALUE (10)


#define DNX_DATA_MAX_NIF_ARB_MIDDLE_START_TX_SPEED_VALUE (1)

#undef DNX_DATA_MAX_NIF_ARB_MIDDLE_START_TX_SPEED_VALUE
#define DNX_DATA_MAX_NIF_ARB_MIDDLE_START_TX_SPEED_VALUE (5)


#define DNX_DATA_MAX_NIF_ARB_LOW_START_TX_SPEED_VALUE (1)

#undef DNX_DATA_MAX_NIF_ARB_LOW_START_TX_SPEED_VALUE
#define DNX_DATA_MAX_NIF_ARB_LOW_START_TX_SPEED_VALUE (3)


#define DNX_DATA_MAX_NIF_ARB_MAX_VALUE_FOR_TX_START_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_ARB_MAX_VALUE_FOR_TX_START_THRESHOLD
#define DNX_DATA_MAX_NIF_ARB_MAX_VALUE_FOR_TX_START_THRESHOLD (255)


#define DNX_DATA_MAX_NIF_ARB_RX_PM_DEFAULT_MIN_PKT_SIZE (1)

#undef DNX_DATA_MAX_NIF_ARB_RX_PM_DEFAULT_MIN_PKT_SIZE
#define DNX_DATA_MAX_NIF_ARB_RX_PM_DEFAULT_MIN_PKT_SIZE (60)


#define DNX_DATA_MAX_NIF_OFR_NOF_CONTEXTS (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_CONTEXTS
#define DNX_DATA_MAX_NIF_OFR_NOF_CONTEXTS (384)


#define DNX_DATA_MAX_NIF_OFR_NOF_RMC_PER_PRIORITY_GROUP (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_RMC_PER_PRIORITY_GROUP
#define DNX_DATA_MAX_NIF_OFR_NOF_RMC_PER_PRIORITY_GROUP (384)


#define DNX_DATA_MAX_NIF_OFR_NOF_TOTAL_RMCS (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_TOTAL_RMCS
#define DNX_DATA_MAX_NIF_OFR_NOF_TOTAL_RMCS (768)


#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEM_SECTIONS_PER_GROUP (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_RX_MEM_SECTIONS_PER_GROUP
#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEM_SECTIONS_PER_GROUP (160)


#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_GROUPS (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_GROUPS
#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_GROUPS (4)


#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_SECTIONS (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_SECTIONS
#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_SECTIONS (640)


#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_ENTRIES_PER_SECTION (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_ENTRIES_PER_SECTION
#define DNX_DATA_MAX_NIF_OFR_NOF_RX_MEMORY_ENTRIES_PER_SECTION (4)


#define DNX_DATA_MAX_NIF_OFR_RX_MEMORY_LINK_LIST_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_OFR_RX_MEMORY_LINK_LIST_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_OFR_RX_MEMORY_LINK_LIST_SPEED_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_OFR_RX_SCH_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_OFR_RX_SCH_GRANULARITY
#define DNX_DATA_MAX_NIF_OFR_RX_SCH_GRANULARITY (250)


#define DNX_DATA_MAX_NIF_OFR_NOF_BYTES_PER_MEMORY_SECTION (1)

#undef DNX_DATA_MAX_NIF_OFR_NOF_BYTES_PER_MEMORY_SECTION
#define DNX_DATA_MAX_NIF_OFR_NOF_BYTES_PER_MEMORY_SECTION (64)


#define DNX_DATA_MAX_NIF_OFT_CALENDAR_LENGTH (1)

#undef DNX_DATA_MAX_NIF_OFT_CALENDAR_LENGTH
#define DNX_DATA_MAX_NIF_OFT_CALENDAR_LENGTH (6800)


#define DNX_DATA_MAX_NIF_OFT_NOF_SECTIONS (1)

#undef DNX_DATA_MAX_NIF_OFT_NOF_SECTIONS
#define DNX_DATA_MAX_NIF_OFT_NOF_SECTIONS (640)


#define DNX_DATA_MAX_NIF_OFT_NOF_INTERNAL_CALENDAR_ENTRIES (1)

#undef DNX_DATA_MAX_NIF_OFT_NOF_INTERNAL_CALENDAR_ENTRIES
#define DNX_DATA_MAX_NIF_OFT_NOF_INTERNAL_CALENDAR_ENTRIES (16)


#define DNX_DATA_MAX_NIF_OFT_NOF_BIT_PER_INTERNAL_ENTRY_IN_CALENDAR (1)

#undef DNX_DATA_MAX_NIF_OFT_NOF_BIT_PER_INTERNAL_ENTRY_IN_CALENDAR
#define DNX_DATA_MAX_NIF_OFT_NOF_BIT_PER_INTERNAL_ENTRY_IN_CALENDAR (9)


#define DNX_DATA_MAX_NIF_OFT_NOF_CONTEXTS (1)

#undef DNX_DATA_MAX_NIF_OFT_NOF_CONTEXTS
#define DNX_DATA_MAX_NIF_OFT_NOF_CONTEXTS (384)


#define DNX_DATA_MAX_NIF_OFT_PORT_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_OFT_PORT_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_OFT_PORT_SPEED_GRANULARITY (5000)


#define DNX_DATA_MAX_NIF_OFT_CALENDAR_SPEED_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_OFT_CALENDAR_SPEED_GRANULARITY
#define DNX_DATA_MAX_NIF_OFT_CALENDAR_SPEED_GRANULARITY (250)


#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_DEGRADE_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_DEGRADE_THRESHOLD
#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_DEGRADE_THRESHOLD (-5)


#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_DEGRADE_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_DEGRADE_THRESHOLD
#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_DEGRADE_THRESHOLD (-13)


#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_FAIL_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_FAIL_THRESHOLD
#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_FAIL_THRESHOLD (-5)


#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_FAIL_THRESHOLD (1)

#undef DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_FAIL_THRESHOLD
#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_FAIL_THRESHOLD (-13)


#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_INTERVAL (1)

#undef DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_INTERVAL
#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MAX_INTERVAL (600000000)


#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_INTERVAL (1)

#undef DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_INTERVAL
#define DNX_DATA_MAX_NIF_SIGNAL_QUALITY_MIN_INTERVAL (500000)


#define DNX_DATA_MAX_NIF_OTN_NOF_UNITS  (1)

#undef DNX_DATA_MAX_NIF_OTN_NOF_UNITS
#define DNX_DATA_MAX_NIF_OTN_NOF_UNITS  (1)


#define DNX_DATA_MAX_NIF_OTN_NOF_LANES  (1)

#undef DNX_DATA_MAX_NIF_OTN_NOF_LANES
#define DNX_DATA_MAX_NIF_OTN_NOF_LANES  (64)


#define DNX_DATA_MAX_NIF_OTN_NOF_GROUPS (1)

#undef DNX_DATA_MAX_NIF_OTN_NOF_GROUPS
#define DNX_DATA_MAX_NIF_OTN_NOF_GROUPS (8)


#define DNX_DATA_MAX_NIF_OTN_NOF_LANES_PER_GROUP (1)

#undef DNX_DATA_MAX_NIF_OTN_NOF_LANES_PER_GROUP
#define DNX_DATA_MAX_NIF_OTN_NOF_LANES_PER_GROUP (8)


#define DNX_DATA_MAX_NIF_FLR_MAX_TICK_UNIT (1)

#undef DNX_DATA_MAX_NIF_FLR_MAX_TICK_UNIT
#define DNX_DATA_MAX_NIF_FLR_MAX_TICK_UNIT (65535)


#define DNX_DATA_MAX_NIF_FLR_MAX_TICK_COUNT (1)

#undef DNX_DATA_MAX_NIF_FLR_MAX_TICK_COUNT
#define DNX_DATA_MAX_NIF_FLR_MAX_TICK_COUNT (1023)


#define DNX_DATA_MAX_NIF_FLR_TIMER_GRANULARITY (1)

#undef DNX_DATA_MAX_NIF_FLR_TIMER_GRANULARITY
#define DNX_DATA_MAX_NIF_FLR_TIMER_GRANULARITY (40)





#endif 

