
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_METER_H_

#define _DNX_DATA_MAX_METER_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_METER_PROFILE_LARGE_BUCKET_MODE_EXP_ADD (1)

#undef DNX_DATA_MAX_METER_PROFILE_LARGE_BUCKET_MODE_EXP_ADD
#define DNX_DATA_MAX_METER_PROFILE_LARGE_BUCKET_MODE_EXP_ADD (6)


#define DNX_DATA_MAX_METER_PROFILE_MAX_REGULAR_BUCKET_MODE_BURST (1)

#undef DNX_DATA_MAX_METER_PROFILE_MAX_REGULAR_BUCKET_MODE_BURST
#define DNX_DATA_MAX_METER_PROFILE_MAX_REGULAR_BUCKET_MODE_BURST (4161536)


#define DNX_DATA_MAX_METER_PROFILE_REV_EXP_MIN (1)

#undef DNX_DATA_MAX_METER_PROFILE_REV_EXP_MIN
#define DNX_DATA_MAX_METER_PROFILE_REV_EXP_MIN (0)


#define DNX_DATA_MAX_METER_PROFILE_REV_EXP_MAX (1)

#undef DNX_DATA_MAX_METER_PROFILE_REV_EXP_MAX
#define DNX_DATA_MAX_METER_PROFILE_REV_EXP_MAX (31)


#define DNX_DATA_MAX_METER_PROFILE_BURST_SIZE_MIN (1)

#undef DNX_DATA_MAX_METER_PROFILE_BURST_SIZE_MIN
#define DNX_DATA_MAX_METER_PROFILE_BURST_SIZE_MIN (1)


#define DNX_DATA_MAX_METER_PROFILE_NOF_VALID_GLOBAL_METERS (1)

#undef DNX_DATA_MAX_METER_PROFILE_NOF_VALID_GLOBAL_METERS
#define DNX_DATA_MAX_METER_PROFILE_NOF_VALID_GLOBAL_METERS (5)


#define DNX_DATA_MAX_METER_PROFILE_NOF_DP_COMMAND_MAX (1)

#undef DNX_DATA_MAX_METER_PROFILE_NOF_DP_COMMAND_MAX
#define DNX_DATA_MAX_METER_PROFILE_NOF_DP_COMMAND_MAX (16)


#define DNX_DATA_MAX_METER_PROFILE_GLOBAL_ENGINE_HW_STAT_DATABASE_ID (1)

#undef DNX_DATA_MAX_METER_PROFILE_GLOBAL_ENGINE_HW_STAT_DATABASE_ID
#define DNX_DATA_MAX_METER_PROFILE_GLOBAL_ENGINE_HW_STAT_DATABASE_ID (3)


#define DNX_DATA_MAX_METER_PROFILE_IR_MANT_NOF_BITS (1)

#undef DNX_DATA_MAX_METER_PROFILE_IR_MANT_NOF_BITS
#define DNX_DATA_MAX_METER_PROFILE_IR_MANT_NOF_BITS (10)


#define DNX_DATA_MAX_METER_METER_DB_NOF_INGRESS_DB (1)

#undef DNX_DATA_MAX_METER_METER_DB_NOF_INGRESS_DB
#define DNX_DATA_MAX_METER_METER_DB_NOF_INGRESS_DB (3)


#define DNX_DATA_MAX_METER_METER_DB_NOF_EGRESS_DB (1)

#undef DNX_DATA_MAX_METER_METER_DB_NOF_EGRESS_DB
#define DNX_DATA_MAX_METER_METER_DB_NOF_EGRESS_DB (2)


#define DNX_DATA_MAX_METER_METER_DB_NOF_METERS_ID_IN_GROUP (1)

#undef DNX_DATA_MAX_METER_METER_DB_NOF_METERS_ID_IN_GROUP
#define DNX_DATA_MAX_METER_METER_DB_NOF_METERS_ID_IN_GROUP (4)


#define DNX_DATA_MAX_METER_MEM_MGMT_ADRRESS_RANGE_RESOLUTION (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_ADRRESS_RANGE_RESOLUTION
#define DNX_DATA_MAX_METER_MEM_MGMT_ADRRESS_RANGE_RESOLUTION (8192)


#define DNX_DATA_MAX_METER_MEM_MGMT_OBJECT_STAT_POINTER_BASE_RESOLUTION (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_OBJECT_STAT_POINTER_BASE_RESOLUTION
#define DNX_DATA_MAX_METER_MEM_MGMT_OBJECT_STAT_POINTER_BASE_RESOLUTION (16384)


#define DNX_DATA_MAX_METER_MEM_MGMT_BASE_BIG_ENGINE_FOR_METER (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_BASE_BIG_ENGINE_FOR_METER
#define DNX_DATA_MAX_METER_MEM_MGMT_BASE_BIG_ENGINE_FOR_METER (16)


#define DNX_DATA_MAX_METER_MEM_MGMT_BASE_MID_ENGINE_FOR_METER (1)

#define DNX_DATA_MAX_METER_MEM_MGMT_INGRESS_SINGLE_BUCKET_ENGINE (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_INGRESS_SINGLE_BUCKET_ENGINE
#define DNX_DATA_MAX_METER_MEM_MGMT_INGRESS_SINGLE_BUCKET_ENGINE (0)


#define DNX_DATA_MAX_METER_MEM_MGMT_EGRESS_SINGLE_BUCKET_ENGINE (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_EGRESS_SINGLE_BUCKET_ENGINE
#define DNX_DATA_MAX_METER_MEM_MGMT_EGRESS_SINGLE_BUCKET_ENGINE (1)


#define DNX_DATA_MAX_METER_MEM_MGMT_METER_POINTER_SIZE (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_METER_POINTER_SIZE
#define DNX_DATA_MAX_METER_MEM_MGMT_METER_POINTER_SIZE (20)


#define DNX_DATA_MAX_METER_MEM_MGMT_METER_POINTER_MAP_SIZE (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_METER_POINTER_MAP_SIZE
#define DNX_DATA_MAX_METER_MEM_MGMT_METER_POINTER_MAP_SIZE (10)


#define DNX_DATA_MAX_METER_MEM_MGMT_INVALID_BANK_ID (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_INVALID_BANK_ID
#define DNX_DATA_MAX_METER_MEM_MGMT_INVALID_BANK_ID (63)


#define DNX_DATA_MAX_METER_MEM_MGMT_DEFAULT_BANK_ID (1)

#define DNX_DATA_MAX_METER_MEM_MGMT_PTR_MAP_TABLE_RESOLUTION (1)

#undef DNX_DATA_MAX_METER_MEM_MGMT_PTR_MAP_TABLE_RESOLUTION
#define DNX_DATA_MAX_METER_MEM_MGMT_PTR_MAP_TABLE_RESOLUTION (4096)


#define DNX_DATA_MAX_METER_EXPANSION_MAX_SIZE (1)

#undef DNX_DATA_MAX_METER_EXPANSION_MAX_SIZE
#define DNX_DATA_MAX_METER_EXPANSION_MAX_SIZE (7)





#endif 

