
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_EGR_QUEUING_V1_H_

#define _DNX_DATA_MAX_EGR_QUEUING_V1_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_NOF_EGR_INTERFACES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_NOF_CHANNELIZED_EGR_INTERFACES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_CPU_INTERFACE_NOF_CHANNELS (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_CPU_NOF_TCS (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_RCY_INTERFACE_NOF_CHANNELS (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_NOF_IPC_BUS_INTERFACES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_NOF_EGR_QUEUES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_NOF_EGR_PRIORITIES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_PS_QUEUE_RESOLUTION (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_RCY_RESERVED_QUEUE (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_NOF_QUEUE_PAIRS (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_TOTAL_NOF_EGR_QUEUES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SCHEDULING_NOF_INTERFACE_CALENDAR_SLOTS (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_DEFAULT_MAX_BURST (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_MAX_BURST_VALUE (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_QUEUE_MAX_BURST_VALUE (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_MAX_INTERFACE_CREDITS_VALUE (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_MAX_PORT_CREDITS_VALUE (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_SLOTS_PER_CLOCK (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_CREDITS_PER_BIT (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_CREDITS_PER_PACKET (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_CALCAL_CHANNELIZED_ENTRIES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_CALCAL_NON_CHANNELIZED_ENTRIES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_CALCAL_LENGTH (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_NOF_PORT_SHAPER_ENTRIES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_PORT_CAL_UNUSED_ENTRY (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_PORT_SHAPER_START_ENTRY (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_NOF_QUEUE_SHAPER_ENTRIES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_NOF_CIR_SHAPER_ENTRIES (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_RCY_MIRROR_MULTIPLIER (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_RCY_MIRROR_MAX_BURST_VALUE (1)

#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_MAX_RCY_MIRROR_CREDIT_VALUE (1)




#endif 

