
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_TUNNEL_H_

#define _DNX_DATA_MAX_TUNNEL_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_TUNNEL_UDP_NOF_UDP_PORTS_PROFILES (1)

#undef DNX_DATA_MAX_TUNNEL_UDP_NOF_UDP_PORTS_PROFILES
#define DNX_DATA_MAX_TUNNEL_UDP_NOF_UDP_PORTS_PROFILES (8)


#define DNX_DATA_MAX_TUNNEL_UDP_FIRST_UDP_PORTS_PROFILE (1)

#undef DNX_DATA_MAX_TUNNEL_UDP_FIRST_UDP_PORTS_PROFILE
#define DNX_DATA_MAX_TUNNEL_UDP_FIRST_UDP_PORTS_PROFILE (1)


#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_UDP_TUNNEL_TYPE (1)

#undef DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_UDP_TUNNEL_TYPE
#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_UDP_TUNNEL_TYPE (0)


#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GRE_TUNNEL_TYPE (1)

#undef DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GRE_TUNNEL_TYPE
#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GRE_TUNNEL_TYPE (0)


#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GENEVE_TUNNEL_TYPE_SUPPORTED (1)

#undef DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GENEVE_TUNNEL_TYPE_SUPPORTED
#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GENEVE_TUNNEL_TYPE_SUPPORTED (1)


#define DNX_DATA_MAX_TUNNEL_ROO_TERMINATE_ONLY_8B_IN_IP_AT_TERM_BLOCK_USING_PMF (1)

#undef DNX_DATA_MAX_TUNNEL_ROO_TERMINATE_ONLY_8B_IN_IP_AT_TERM_BLOCK_USING_PMF
#define DNX_DATA_MAX_TUNNEL_ROO_TERMINATE_ONLY_8B_IN_IP_AT_TERM_BLOCK_USING_PMF (1)


#define DNX_DATA_MAX_TUNNEL_FEATURE_TUNNEL_ROUTE_DISABLE (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_TUNNEL_ROUTE_DISABLE
#define DNX_DATA_MAX_TUNNEL_FEATURE_TUNNEL_ROUTE_DISABLE (1)


#define DNX_DATA_MAX_TUNNEL_FEATURE_DEDICATED_FODO_TO_VNI_TABLE (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_DEDICATED_FODO_TO_VNI_TABLE
#define DNX_DATA_MAX_TUNNEL_FEATURE_DEDICATED_FODO_TO_VNI_TABLE (0)


#define DNX_DATA_MAX_TUNNEL_FEATURE_DIP_IDX_TYPE_IS_LIF_FIELD (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_DIP_IDX_TYPE_IS_LIF_FIELD
#define DNX_DATA_MAX_TUNNEL_FEATURE_DIP_IDX_TYPE_IS_LIF_FIELD (0)


#define DNX_DATA_MAX_TUNNEL_FEATURE_FODO_TO_VNI_ENTRY_CREATED_BY_VLAN_API (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_FODO_TO_VNI_ENTRY_CREATED_BY_VLAN_API
#define DNX_DATA_MAX_TUNNEL_FEATURE_FODO_TO_VNI_ENTRY_CREATED_BY_VLAN_API (1)


#define DNX_DATA_MAX_TUNNEL_FEATURE_HAS_FLOW_GPORT_TO_TUNNEL_TYPE (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_HAS_FLOW_GPORT_TO_TUNNEL_TYPE
#define DNX_DATA_MAX_TUNNEL_FEATURE_HAS_FLOW_GPORT_TO_TUNNEL_TYPE (0)


#define DNX_DATA_MAX_TUNNEL_FEATURE_SUPPORT_LEARN_MODE_ASYNC_LIF_AND_FEC (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_SUPPORT_LEARN_MODE_ASYNC_LIF_AND_FEC
#define DNX_DATA_MAX_TUNNEL_FEATURE_SUPPORT_LEARN_MODE_ASYNC_LIF_AND_FEC (1)


#define DNX_DATA_MAX_TUNNEL_FEATURE_L3_FODO_RESULT_TYPE_SUPPORTED (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_L3_FODO_RESULT_TYPE_SUPPORTED
#define DNX_DATA_MAX_TUNNEL_FEATURE_L3_FODO_RESULT_TYPE_SUPPORTED (1)


#define DNX_DATA_MAX_TUNNEL_FEATURE_UDP_TUNNEL_NAT (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_UDP_TUNNEL_NAT
#define DNX_DATA_MAX_TUNNEL_FEATURE_UDP_TUNNEL_NAT (1)


#define DNX_DATA_MAX_TUNNEL_FEATURE_SHORT_NETWORK_DOMAIN (1)

#undef DNX_DATA_MAX_TUNNEL_FEATURE_SHORT_NETWORK_DOMAIN
#define DNX_DATA_MAX_TUNNEL_FEATURE_SHORT_NETWORK_DOMAIN (0)





#endif 

