
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_PORT_H_

#define _DNX_DATA_MAX_PORT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_PORT_STATIC_ADD_DEFAULT_SPEED_FOR_SPECIAL_IF (1)

#undef DNX_DATA_MAX_PORT_STATIC_ADD_DEFAULT_SPEED_FOR_SPECIAL_IF
#define DNX_DATA_MAX_PORT_STATIC_ADD_DEFAULT_SPEED_FOR_SPECIAL_IF (10000)


#define DNX_DATA_MAX_PORT_GENERAL_ERP_PP_DSP (1)

#undef DNX_DATA_MAX_PORT_GENERAL_ERP_PP_DSP
#define DNX_DATA_MAX_PORT_GENERAL_ERP_PP_DSP (255)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_CHANNELS (1)

#undef DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_CHANNELS
#define DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_CHANNELS (256)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_MIRROR_CHANNELS (1)

#undef DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_MIRROR_CHANNELS
#define DNX_DATA_MAX_PORT_GENERAL_MAX_NOF_MIRROR_CHANNELS (400)


#define DNX_DATA_MAX_PORT_GENERAL_FABRIC_PHYS_OFFSET (1)

#undef DNX_DATA_MAX_PORT_GENERAL_FABRIC_PHYS_OFFSET
#define DNX_DATA_MAX_PORT_GENERAL_FABRIC_PHYS_OFFSET (144)


#define DNX_DATA_MAX_PORT_GENERAL_PP_DSP_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_PP_DSP_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_PP_DSP_SIZE (10)


#define DNX_DATA_MAX_PORT_GENERAL_INGRESS_VLAN_DOMAIN_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_INGRESS_VLAN_DOMAIN_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_INGRESS_VLAN_DOMAIN_SIZE (11)


#define DNX_DATA_MAX_PORT_GENERAL_VLAN_DOMAIN_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_VLAN_DOMAIN_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_VLAN_DOMAIN_SIZE (11)


#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_SIZE (21)


#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_OFFSET_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_OFFSET_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_OFFSET_SIZE (6)


#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_WIDTH_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_WIDTH_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_WIDTH_SIZE (6)


#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_INPUT_OFFSET_SIZE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_INPUT_OFFSET_SIZE
#define DNX_DATA_MAX_PORT_GENERAL_FFC_INSTRUCTION_INPUT_OFFSET_SIZE (9)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP (1)

#define DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP_BEFORE (1)

#undef DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP_BEFORE
#define DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP_BEFORE (64)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP_AFTER (1)

#undef DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP_AFTER
#define DNX_DATA_MAX_PORT_GENERAL_MAX_FIRST_HEADER_SIZE_TO_SKIP_AFTER (64)


#define DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_WIDTH_START_OFFSET (1)

#undef DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_WIDTH_START_OFFSET
#define DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_WIDTH_START_OFFSET (6)


#define DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_START_INPUT_OFFSET (1)

#undef DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_START_INPUT_OFFSET
#define DNX_DATA_MAX_PORT_GENERAL_PRT_FFC_START_INPUT_OFFSET (12)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_PHYS_PER_PM (1)

#undef DNX_DATA_MAX_PORT_GENERAL_MAX_PHYS_PER_PM
#define DNX_DATA_MAX_PORT_GENERAL_MAX_PHYS_PER_PM (8)


#define DNX_DATA_MAX_PORT_GENERAL_MAX_CORE_ACCESS_PER_PORT (1)

#undef DNX_DATA_MAX_PORT_GENERAL_MAX_CORE_ACCESS_PER_PORT
#define DNX_DATA_MAX_PORT_GENERAL_MAX_CORE_ACCESS_PER_PORT (6)





#endif 

