
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ECGM_H_

#define _DNX_DATA_MAX_ECGM_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_ECGM_GENERAL_ECGM_IS_SUPPORTED (1)

#undef DNX_DATA_MAX_ECGM_GENERAL_ECGM_IS_SUPPORTED
#define DNX_DATA_MAX_ECGM_GENERAL_ECGM_IS_SUPPORTED (1)


#define DNX_DATA_MAX_ECGM_GENERAL_MAX_FADT_REFERENCES (1)

#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_SP (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_SP
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_SP (2)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_INTERFACE_PROFILES (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_INTERFACE_PROFILES
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_INTERFACE_PROFILES (8)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_PORT_PROFILES (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_PORT_PROFILES
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_PORT_PROFILES (16)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS (76000)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS_NOF_BITS (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS_NOF_BITS
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_PDS_NOF_BITS (17)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS (32000)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS_NOF_BITS (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS_NOF_BITS
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_TOTAL_DBS_NOF_BITS (15)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_RESERVED_DBS_PER_SP_NOF_BITS (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_RESERVED_DBS_PER_SP_NOF_BITS
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_RESERVED_DBS_PER_SP_NOF_BITS (17)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_ALPHA_VALUE (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_ALPHA_VALUE
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_ALPHA_VALUE (7)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MIN_ALPHA_VALUE (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_MIN_ALPHA_VALUE
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MIN_ALPHA_VALUE (-7)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_CORE_BANDWIDTH_MBPS (1)

#undef DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_CORE_BANDWIDTH_MBPS
#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MAX_CORE_BANDWIDTH_MBPS (4000000)


#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MC_RCY_RESERVED_INTERFACE_TH_IDS (1)

#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_MC_RCY_RESERVED_PORT_TH_IDS (1)

#define DNX_DATA_MAX_ECGM_CORE_RESOURCES_NOF_TC_DP_ADMISSION_PROFILES (1)

#define DNX_DATA_MAX_ECGM_PORT_RESOURCES_MAX_NOF_PORTS (1)

#undef DNX_DATA_MAX_ECGM_PORT_RESOURCES_MAX_NOF_PORTS
#define DNX_DATA_MAX_ECGM_PORT_RESOURCES_MAX_NOF_PORTS (160)


#define DNX_DATA_MAX_ECGM_INFO_FC_Q_PAIR_VECTOR_SELECT_NOF_BITS (1)

#undef DNX_DATA_MAX_ECGM_INFO_FC_Q_PAIR_VECTOR_SELECT_NOF_BITS
#define DNX_DATA_MAX_ECGM_INFO_FC_Q_PAIR_VECTOR_SELECT_NOF_BITS (3)


#define DNX_DATA_MAX_ECGM_INFO_FC_Q_PAIR_VECTOR_NOF_PRESENTED (1)

#undef DNX_DATA_MAX_ECGM_INFO_FC_Q_PAIR_VECTOR_NOF_PRESENTED
#define DNX_DATA_MAX_ECGM_INFO_FC_Q_PAIR_VECTOR_NOF_PRESENTED (256)


#define DNX_DATA_MAX_ECGM_INFO_FC_EGR_IF_VECTOR_SELECT_NOF_BITS (1)

#undef DNX_DATA_MAX_ECGM_INFO_FC_EGR_IF_VECTOR_SELECT_NOF_BITS
#define DNX_DATA_MAX_ECGM_INFO_FC_EGR_IF_VECTOR_SELECT_NOF_BITS (2)


#define DNX_DATA_MAX_ECGM_INFO_FC_EGR_IF_VECTOR_NOF_PRESENTED (1)

#undef DNX_DATA_MAX_ECGM_INFO_FC_EGR_IF_VECTOR_NOF_PRESENTED
#define DNX_DATA_MAX_ECGM_INFO_FC_EGR_IF_VECTOR_NOF_PRESENTED (136)


#define DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_RQP (1)

#undef DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_RQP
#define DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_RQP (11)


#define DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_PQP (1)

#undef DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_PQP
#define DNX_DATA_MAX_ECGM_INFO_NOF_DROPPED_REASONS_PQP (16)


#define DNX_DATA_MAX_ECGM_INFO_NOF_BITS_IN_PD_COUNT (1)

#undef DNX_DATA_MAX_ECGM_INFO_NOF_BITS_IN_PD_COUNT
#define DNX_DATA_MAX_ECGM_INFO_NOF_BITS_IN_PD_COUNT (16)





#endif 

