
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_CRPS_H_

#define _DNX_DATA_MAX_CRPS_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_ENGINES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_ENGINES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_ENGINES (34)


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_MID_ENGINES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_MID_ENGINES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_MID_ENGINES (8)


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_BIG_ENGINES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_BIG_ENGINES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_BIG_ENGINES (18)


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_DATABASES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_DATABASES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_DATABASES (34)


#define DNX_DATA_MAX_CRPS_ENGINE_DATA_MAPPING_TABLE_SIZE (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_DATA_MAPPING_TABLE_SIZE
#define DNX_DATA_MAX_CRPS_ENGINE_DATA_MAPPING_TABLE_SIZE (1024)


#define DNX_DATA_MAX_CRPS_ENGINE_MAX_COUNTER_SET_SIZE (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_MAX_COUNTER_SET_SIZE
#define DNX_DATA_MAX_CRPS_ENGINE_MAX_COUNTER_SET_SIZE (32)


#define DNX_DATA_MAX_CRPS_ENGINE_OAM_COUNTER_SET_SIZE (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_OAM_COUNTER_SET_SIZE
#define DNX_DATA_MAX_CRPS_ENGINE_OAM_COUNTER_SET_SIZE (1)


#define DNX_DATA_MAX_CRPS_ENGINE_MAX_NOF_COUNTER_SETS (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_MAX_NOF_COUNTER_SETS
#define DNX_DATA_MAX_CRPS_ENGINE_MAX_NOF_COUNTER_SETS (1)


#define DNX_DATA_MAX_CRPS_ENGINE_LAST_ADDRESS_NOF_BITS (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_LAST_ADDRESS_NOF_BITS
#define DNX_DATA_MAX_CRPS_ENGINE_LAST_ADDRESS_NOF_BITS (16)


#define DNX_DATA_MAX_CRPS_ENGINE_COUNTER_FORMAT_NOF_BITS (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_COUNTER_FORMAT_NOF_BITS
#define DNX_DATA_MAX_CRPS_ENGINE_COUNTER_FORMAT_NOF_BITS (2)


#define DNX_DATA_MAX_CRPS_ENGINE_COUNTER_MODE_NOF_BITS (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_COUNTER_MODE_NOF_BITS
#define DNX_DATA_MAX_CRPS_ENGINE_COUNTER_MODE_NOF_BITS (4)


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_SMALL_METER_SHARED_ENGINES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_SMALL_METER_SHARED_ENGINES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_SMALL_METER_SHARED_ENGINES (2)


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_MID_METER_SHARED_ENGINES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_MID_METER_SHARED_ENGINES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_MID_METER_SHARED_ENGINES (0)


#define DNX_DATA_MAX_CRPS_ENGINE_NOF_BIG_METER_SHARED_ENGINES (1)

#undef DNX_DATA_MAX_CRPS_ENGINE_NOF_BIG_METER_SHARED_ENGINES
#define DNX_DATA_MAX_CRPS_ENGINE_NOF_BIG_METER_SHARED_ENGINES (18)


#define DNX_DATA_MAX_CRPS_EVICTION_COUNTERS_FIFO_DEPTH (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_COUNTERS_FIFO_DEPTH
#define DNX_DATA_MAX_CRPS_EVICTION_COUNTERS_FIFO_DEPTH (16384)


#define DNX_DATA_MAX_CRPS_EVICTION_NOF_COUNTERS_FIFO (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_NOF_COUNTERS_FIFO
#define DNX_DATA_MAX_CRPS_EVICTION_NOF_COUNTERS_FIFO (2)


#define DNX_DATA_MAX_CRPS_EVICTION_DMA_RECORD_ENTRY_NOF_BITS (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_DMA_RECORD_ENTRY_NOF_BITS
#define DNX_DATA_MAX_CRPS_EVICTION_DMA_RECORD_ENTRY_NOF_BITS (120)


#define DNX_DATA_MAX_CRPS_EVICTION_BUBBLE_BEFORE_REQUEST_TIMEOUT (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_BUBBLE_BEFORE_REQUEST_TIMEOUT
#define DNX_DATA_MAX_CRPS_EVICTION_BUBBLE_BEFORE_REQUEST_TIMEOUT (500)


#define DNX_DATA_MAX_CRPS_EVICTION_BUBBLE_AFTER_REQUEST_TIMEOUT (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_BUBBLE_AFTER_REQUEST_TIMEOUT
#define DNX_DATA_MAX_CRPS_EVICTION_BUBBLE_AFTER_REQUEST_TIMEOUT (500)


#define DNX_DATA_MAX_CRPS_EVICTION_SEQ_ADDRESS_NOF_BITS (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_SEQ_ADDRESS_NOF_BITS
#define DNX_DATA_MAX_CRPS_EVICTION_SEQ_ADDRESS_NOF_BITS (17)


#define DNX_DATA_MAX_CRPS_EVICTION_NOF_EVICTION_DESTINATION_TYPES (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_NOF_EVICTION_DESTINATION_TYPES
#define DNX_DATA_MAX_CRPS_EVICTION_NOF_EVICTION_DESTINATION_TYPES (2)


#define DNX_DATA_MAX_CRPS_EVICTION_NOF_CRPS_NETWORK_CHANNELS (1)

#undef DNX_DATA_MAX_CRPS_EVICTION_NOF_CRPS_NETWORK_CHANNELS
#define DNX_DATA_MAX_CRPS_EVICTION_NOF_CRPS_NETWORK_CHANNELS (8)


#define DNX_DATA_MAX_CRPS_EXPANSION_EXPANSION_SIZE (1)

#undef DNX_DATA_MAX_CRPS_EXPANSION_EXPANSION_SIZE
#define DNX_DATA_MAX_CRPS_EXPANSION_EXPANSION_SIZE (10)


#define DNX_DATA_MAX_CRPS_LATENCY_ETPP_COMMAND_ID (1)

#undef DNX_DATA_MAX_CRPS_LATENCY_ETPP_COMMAND_ID
#define DNX_DATA_MAX_CRPS_LATENCY_ETPP_COMMAND_ID (5)


#define DNX_DATA_MAX_CRPS_LATENCY_EPP_COMMAND_ID (1)

#undef DNX_DATA_MAX_CRPS_LATENCY_EPP_COMMAND_ID
#define DNX_DATA_MAX_CRPS_LATENCY_EPP_COMMAND_ID (-1)


#define DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_PORT_OFFSET (1)

#undef DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_PORT_OFFSET
#define DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_PORT_OFFSET (0)


#define DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_TC_OFFSET (1)

#undef DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_TC_OFFSET
#define DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_TC_OFFSET (8)


#define DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_MULTICAST_OFFSET (1)

#undef DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_MULTICAST_OFFSET
#define DNX_DATA_MAX_CRPS_LATENCY_STAT_ID_MULTICAST_OFFSET (11)


#define DNX_DATA_MAX_CRPS_STATE_COUNTERS_MAX_WIDE_STATE_COUNTERS_SIZE (1)

#undef DNX_DATA_MAX_CRPS_STATE_COUNTERS_MAX_WIDE_STATE_COUNTERS_SIZE
#define DNX_DATA_MAX_CRPS_STATE_COUNTERS_MAX_WIDE_STATE_COUNTERS_SIZE (0)


#define DNX_DATA_MAX_CRPS_STATE_COUNTERS_MAX_NARROW_STATE_COUNTERS_SIZE (1)

#undef DNX_DATA_MAX_CRPS_STATE_COUNTERS_MAX_NARROW_STATE_COUNTERS_SIZE
#define DNX_DATA_MAX_CRPS_STATE_COUNTERS_MAX_NARROW_STATE_COUNTERS_SIZE (0)


#define DNX_DATA_MAX_CRPS_STATE_COUNTERS_STATE_COUNTER_DATA_SIZE_PER_FULL_COUNTER (1)

#undef DNX_DATA_MAX_CRPS_STATE_COUNTERS_STATE_COUNTER_DATA_SIZE_PER_FULL_COUNTER
#define DNX_DATA_MAX_CRPS_STATE_COUNTERS_STATE_COUNTER_DATA_SIZE_PER_FULL_COUNTER (0)





#endif 

