
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_REGRESSION_H_

#define _DNX_DATA_MAX_REGRESSION_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_EXT_LOOPS (1)

#undef DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_EXT_LOOPS
#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_EXT_LOOPS (23)


#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_P2P_LINKS (1)

#undef DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_P2P_LINKS
#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_P2P_LINKS (2)


#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_FORCE_ER (1)

#undef DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_FORCE_ER
#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_FORCE_ER (1)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_CGM_VOQ_PROFILES (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_CGM_VOQ_PROFILES
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_CGM_VOQ_PROFILES (10)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QQST_TABLE (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QQST_TABLE
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QQST_TABLE (16)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QDCT_TABLE (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QDCT_TABLE
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QDCT_TABLE (16)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE (5)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE_2 (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE_2
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE_2 (4)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_IVSI (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_IVSI
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_IVSI (9)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EVSI (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EVSI
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EVSI (25)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_GLEM (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_GLEM
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_GLEM (16372)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EXEM_1 (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EXEM_1
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EXEM_1 (10142)


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_FEC_1 (1)

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_FEC_1
#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_FEC_1 (0)





#endif 

