
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_DEVICE_H_

#define _DNX_DATA_MAX_DEVICE_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_SYSTEM_PORTS (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_SYSTEM_PORTS
#define DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_SYSTEM_PORTS (32768)


#define DNX_DATA_MAX_DEVICE_GENERAL_INVALID_SYSTEM_PORT (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_INVALID_SYSTEM_PORT
#define DNX_DATA_MAX_DEVICE_GENERAL_INVALID_SYSTEM_PORT (32767)


#define DNX_DATA_MAX_DEVICE_GENERAL_FMQ_SYSTEM_PORT (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_FMQ_SYSTEM_PORT
#define DNX_DATA_MAX_DEVICE_GENERAL_FMQ_SYSTEM_PORT (32766)


#define DNX_DATA_MAX_DEVICE_GENERAL_INVALID_FAP_ID (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_INVALID_FAP_ID
#define DNX_DATA_MAX_DEVICE_GENERAL_INVALID_FAP_ID (2047)


#define DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_FAPS (1)

#define DNX_DATA_MAX_DEVICE_GENERAL_FAP_IDS_PER_CORE_BITS (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_FAP_IDS_PER_CORE_BITS
#define DNX_DATA_MAX_DEVICE_GENERAL_FAP_IDS_PER_CORE_BITS (2)


#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES
#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES (2)


#define DNX_DATA_MAX_DEVICE_GENERAL_VALID_CORES_BITMAP (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_VALID_CORES_BITMAP
#define DNX_DATA_MAX_DEVICE_GENERAL_VALID_CORES_BITMAP (3)


#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES_FOR_TRAFFIC (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES_FOR_TRAFFIC
#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES_FOR_TRAFFIC (2)


#define DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_LAYER_PROTOCOLS (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_LAYER_PROTOCOLS
#define DNX_DATA_MAX_DEVICE_GENERAL_MAX_NOF_LAYER_PROTOCOLS (32)


#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_IPCS (1)

#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORE_GROUPS (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORE_GROUPS
#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORE_GROUPS (1)


#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES_PER_CORE_GROUP (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES_PER_CORE_GROUP
#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_CORES_PER_CORE_GROUP (2)


#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_AVS_STATUS_BITS (1)

#undef DNX_DATA_MAX_DEVICE_GENERAL_NOF_AVS_STATUS_BITS
#define DNX_DATA_MAX_DEVICE_GENERAL_NOF_AVS_STATUS_BITS (8)


#define DNX_DATA_MAX_DEVICE_OTP_NOF_WORDS_IN_ROW (1)

#undef DNX_DATA_MAX_DEVICE_OTP_NOF_WORDS_IN_ROW
#define DNX_DATA_MAX_DEVICE_OTP_NOF_WORDS_IN_ROW (2)


#define DNX_DATA_MAX_DEVICE_OTP_READ_TIMEOUT (1)

#undef DNX_DATA_MAX_DEVICE_OTP_READ_TIMEOUT
#define DNX_DATA_MAX_DEVICE_OTP_READ_TIMEOUT (100000)





#endif 

