
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_TSN_H_

#define _DNX_DATA_MAX_TSN_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_TIME (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_TIME
#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_TIME (128)


#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_ATTEMPTS (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_ATTEMPTS
#define DNX_DATA_MAX_TSN_PREEMPTION_VERIFY_MAX_ATTEMPTS (8)


#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_TX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_TX
#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_TX (512)


#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_TX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_TX
#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_TX (64)


#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_RX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_RX
#define DNX_DATA_MAX_TSN_PREEMPTION_NON_FINAL_FRAG_SIZE_RX (256)


#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_RX (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_RX
#define DNX_DATA_MAX_TSN_PREEMPTION_FINAL_FRAG_SIZE_RX (64)


#define DNX_DATA_MAX_TSN_PREEMPTION_FRAG_SIZE_BYTES_IN_HW_UNIT (1)

#undef DNX_DATA_MAX_TSN_PREEMPTION_FRAG_SIZE_BYTES_IN_HW_UNIT
#define DNX_DATA_MAX_TSN_PREEMPTION_FRAG_SIZE_BYTES_IN_HW_UNIT (8)


#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_NS (1)

#undef DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_NS
#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_NS (1000)


#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_MIN_NS (1)

#undef DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_MIN_NS
#define DNX_DATA_MAX_TSN_TIME_TICK_PERIOD_MIN_NS (400)


#define DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_NOF_BITS (1)

#undef DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_NOF_BITS
#define DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_NOF_BITS (48)


#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_NOF_BITS (1)

#undef DNX_DATA_MAX_TSN_TIME_TAS_TOD_NOF_BITS
#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_NOF_BITS (48)


#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_SOURCE (1)

#undef DNX_DATA_MAX_TSN_TIME_TAS_TOD_SOURCE
#define DNX_DATA_MAX_TSN_TIME_TAS_TOD_SOURCE (1)


#define DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_MAX_DIFF (1)

#undef DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_MAX_DIFF
#define DNX_DATA_MAX_TSN_TIME_TSN_COUNTER_MAX_DIFF (10000)


#define DNX_DATA_MAX_TSN_TAF_MAX_TIME_INTERVALS_ENTRIES (1)

#undef DNX_DATA_MAX_TSN_TAF_MAX_TIME_INTERVALS_ENTRIES
#define DNX_DATA_MAX_TSN_TAF_MAX_TIME_INTERVALS_ENTRIES (128)


#define DNX_DATA_MAX_TSN_TAF_NOF_GATES  (1)

#undef DNX_DATA_MAX_TSN_TAF_NOF_GATES
#define DNX_DATA_MAX_TSN_TAF_NOF_GATES  (256)


#define DNX_DATA_MAX_TSN_TAF_MAX_PROFILES_PER_GATE (1)

#undef DNX_DATA_MAX_TSN_TAF_MAX_PROFILES_PER_GATE
#define DNX_DATA_MAX_TSN_TAF_MAX_PROFILES_PER_GATE (2)


#define DNX_DATA_MAX_TSN_TAF_GATE_CONTROL_LIST_NOF_ENTRIES (1)

#undef DNX_DATA_MAX_TSN_TAF_GATE_CONTROL_LIST_NOF_ENTRIES
#define DNX_DATA_MAX_TSN_TAF_GATE_CONTROL_LIST_NOF_ENTRIES (16384)


#define DNX_DATA_MAX_TSN_TAF_TAF_ADMISSION_PROFILE (1)

#undef DNX_DATA_MAX_TSN_TAF_TAF_ADMISSION_PROFILE
#define DNX_DATA_MAX_TSN_TAF_TAF_ADMISSION_PROFILE (2)


#define DNX_DATA_MAX_TSN_TAS_MAX_TIME_INTERVALS_ENTRIES (1)

#undef DNX_DATA_MAX_TSN_TAS_MAX_TIME_INTERVALS_ENTRIES
#define DNX_DATA_MAX_TSN_TAS_MAX_TIME_INTERVALS_ENTRIES (128)


#define DNX_DATA_MAX_TSN_TAS_NOF_TAS_PORTS (1)

#undef DNX_DATA_MAX_TSN_TAS_NOF_TAS_PORTS
#define DNX_DATA_MAX_TSN_TAS_NOF_TAS_PORTS (64)


#define DNX_DATA_MAX_TSN_TAS_MAX_PROFILES_PER_PORT (1)

#undef DNX_DATA_MAX_TSN_TAS_MAX_PROFILES_PER_PORT
#define DNX_DATA_MAX_TSN_TAS_MAX_PROFILES_PER_PORT (2)


#define DNX_DATA_MAX_TSN_CQF_MAX_TIME_INTERVALS_ENTRIES (1)

#undef DNX_DATA_MAX_TSN_CQF_MAX_TIME_INTERVALS_ENTRIES
#define DNX_DATA_MAX_TSN_CQF_MAX_TIME_INTERVALS_ENTRIES (12)


#define DNX_DATA_MAX_TSN_CQF_NOF_CQF_PORTS (1)

#undef DNX_DATA_MAX_TSN_CQF_NOF_CQF_PORTS
#define DNX_DATA_MAX_TSN_CQF_NOF_CQF_PORTS (64)


#define DNX_DATA_MAX_TSN_CQF_TIME_MARGIN (1)

#undef DNX_DATA_MAX_TSN_CQF_TIME_MARGIN
#define DNX_DATA_MAX_TSN_CQF_TIME_MARGIN (50000000)


#define DNX_DATA_MAX_TSN_TSN_THREAD_WAKEUP_INTERVAL_NSEC (1)

#undef DNX_DATA_MAX_TSN_TSN_THREAD_WAKEUP_INTERVAL_NSEC
#define DNX_DATA_MAX_TSN_TSN_THREAD_WAKEUP_INTERVAL_NSEC (1100000000)


#define DNX_DATA_MAX_TSN_TSN_THREAD_MAX_PROCESS_TIME_NSEC (1)

#undef DNX_DATA_MAX_TSN_TSN_THREAD_MAX_PROCESS_TIME_NSEC
#define DNX_DATA_MAX_TSN_TSN_THREAD_MAX_PROCESS_TIME_NSEC (900000000)


#define DNX_DATA_MAX_TSN_TSN_THREAD_GROUP_WINDOW_LENGTH_NSEC (1)

#undef DNX_DATA_MAX_TSN_TSN_THREAD_GROUP_WINDOW_LENGTH_NSEC
#define DNX_DATA_MAX_TSN_TSN_THREAD_GROUP_WINDOW_LENGTH_NSEC (900000000)





#endif 

