
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_PVT_H_

#define _DNX_DATA_MAX_PVT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_PVT_GENERAL_NOF_PVT_MONITORS (1)

#undef DNX_DATA_MAX_PVT_GENERAL_NOF_PVT_MONITORS
#define DNX_DATA_MAX_PVT_GENERAL_NOF_PVT_MONITORS (9)


#define DNX_DATA_MAX_PVT_GENERAL_PVT_BASE (1)

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_BASE
#define DNX_DATA_MAX_PVT_GENERAL_PVT_BASE (43410000)


#define DNX_DATA_MAX_PVT_GENERAL_PVT_FACTOR (1)

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_FACTOR
#define DNX_DATA_MAX_PVT_GENERAL_PVT_FACTOR (53504)


#define DNX_DATA_MAX_PVT_GENERAL_PVT_OFFSET (1)

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_OFFSET
#define DNX_DATA_MAX_PVT_GENERAL_PVT_OFFSET (2159740)


#define DNX_DATA_MAX_PVT_GENERAL_NOF_MAIN_MONITORS (1)

#define DNX_DATA_MAX_PVT_GENERAL_PVT_MON_CONTROL_SEL_NOF_BITS (1)

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_MON_CONTROL_SEL_NOF_BITS
#define DNX_DATA_MAX_PVT_GENERAL_PVT_MON_CONTROL_SEL_NOF_BITS (5)


#define DNX_DATA_MAX_PVT_GENERAL_THERMAL_DATA_NOF_BITS (1)

#undef DNX_DATA_MAX_PVT_GENERAL_THERMAL_DATA_NOF_BITS
#define DNX_DATA_MAX_PVT_GENERAL_THERMAL_DATA_NOF_BITS (11)


#define DNX_DATA_MAX_PVT_GENERAL_VOL_SEL (1)

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_SEL
#define DNX_DATA_MAX_PVT_GENERAL_VOL_SEL (10)


#define DNX_DATA_MAX_PVT_GENERAL_VOL_FACTOR (1)

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_FACTOR
#define DNX_DATA_MAX_PVT_GENERAL_VOL_FACTOR (1020)


#define DNX_DATA_MAX_PVT_GENERAL_VOL_MULTIPLE (1)

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_MULTIPLE
#define DNX_DATA_MAX_PVT_GENERAL_VOL_MULTIPLE (5)


#define DNX_DATA_MAX_PVT_GENERAL_VOL_DIVISOR (1)

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_DIVISOR
#define DNX_DATA_MAX_PVT_GENERAL_VOL_DIVISOR (4096)





#endif 

