
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_INGR_CONGESTION_H_

#define _DNX_DATA_MAX_INGR_CONGESTION_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_THRESHOLD_GRANULARITY (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_THRESHOLD_GRANULARITY
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_THRESHOLD_GRANULARITY (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WORDS_RESOLUTION (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_WORDS_RESOLUTION
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WORDS_RESOLUTION (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_BYTES_THRESHOLD_GRANULARITY (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_BYTES_THRESHOLD_GRANULARITY
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_BYTES_THRESHOLD_GRANULARITY (256)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_DROPPED_REASONS_CGM (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_DROPPED_REASONS_CGM
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_DROPPED_REASONS_CGM (33)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_MAX_GAIN (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_MAX_GAIN
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_MAX_GAIN (31)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_GRANULARITY (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_GRANULARITY
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_WRED_GRANULARITY (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_PDS_IN_PDB (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_PDS_IN_PDB
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_NOF_PDS_IN_PDB (4)


#define DNX_DATA_MAX_INGR_CONGESTION_INFO_MAX_JUMBO_PACKET_SIZE (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INFO_MAX_JUMBO_PACKET_SIZE
#define DNX_DATA_MAX_INGR_CONGESTION_INFO_MAX_JUMBO_PACKET_SIZE (10000)


#define DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MIN (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MIN
#define DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MIN (-8)


#define DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MAX (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MAX
#define DNX_DATA_MAX_INGR_CONGESTION_DRAM_BOUND_FADT_ALPHA_MAX (7)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_RATE_CLASS (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_RATE_CLASS
#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_RATE_CLASS (64)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_RATE_CLASS_NOF_BITS (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VOQ_RATE_CLASS_NOF_BITS
#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_RATE_CLASS_NOF_BITS (6)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_COMPENSATION_PROFILES (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_COMPENSATION_PROFILES
#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_NOF_COMPENSATION_PROFILES (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_DEFAULT_COMPENSATION (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VOQ_DEFAULT_COMPENSATION
#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_DEFAULT_COMPENSATION (24)


#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_VOQ_CONGESTION_NOTIFICATION_FIFO_SIZE (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VOQ_VOQ_CONGESTION_NOTIFICATION_FIFO_SIZE
#define DNX_DATA_MAX_INGR_CONGESTION_VOQ_VOQ_CONGESTION_NOTIFICATION_FIFO_SIZE (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_RATE_CLASS_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_RATE_CLASS_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_RATE_CLASS_NOF (16)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_RATE_CLASS_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_RATE_CLASS_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_RATE_CLASS_NOF (4)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_A_NOF (4)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_B_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_B_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_B_NOF (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_C_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_C_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_C_NOF (128)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_D_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_D_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_D_NOF (256)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_NOF (147)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_HW_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_HW_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_HW_NOF (148)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_NOF (1024)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_HW_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_HW_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_HW_NOF (1024)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_POOL_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_POOL_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_POOL_NOF (2)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_CONNECTION_CLASS_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_CONNECTION_CLASS_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_CONNECTION_CLASS_NOF (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_TC_PG_PROFILE_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_TC_PG_PROFILE_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_TC_PG_PROFILE_NOF (16)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_CONGESTION_NOTIFICATION_FIFO_SIZE (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_CONGESTION_NOTIFICATION_FIFO_SIZE
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_E_CONGESTION_NOTIFICATION_FIFO_SIZE (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_CONGESTION_NOTIFICATION_FIFO_SIZE (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_CONGESTION_NOTIFICATION_FIFO_SIZE
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_VSQ_F_CONGESTION_NOTIFICATION_FIFO_SIZE (32)


#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_OVERSUBSCRIPTION_BUBBLE_WIDTH (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_VSQ_OVERSUBSCRIPTION_BUBBLE_WIDTH
#define DNX_DATA_MAX_INGR_CONGESTION_VSQ_OVERSUBSCRIPTION_BUBBLE_WIDTH (16)


#define DNX_DATA_MAX_INGR_CONGESTION_INIT_FIFO_SIZE (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_INIT_FIFO_SIZE
#define DNX_DATA_MAX_INGR_CONGESTION_INIT_FIFO_SIZE (256)


#define DNX_DATA_MAX_INGR_CONGESTION_DBAL_ADMISSION_TEST_NOF (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_DBAL_ADMISSION_TEST_NOF
#define DNX_DATA_MAX_INGR_CONGESTION_DBAL_ADMISSION_TEST_NOF (40)


#define DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_NOF_GROUPS (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_NOF_GROUPS
#define DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_NOF_GROUPS (8)


#define DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_AGING_CLOCKS_RESOLUTION (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_AGING_CLOCKS_RESOLUTION
#define DNX_DATA_MAX_INGR_CONGESTION_MIRROR_ON_DROP_AGING_CLOCKS_RESOLUTION (1024)


#define DNX_DATA_MAX_INGR_CONGESTION_SRAM_BUFFER_NOF_DROP_PROFILES (1)

#undef DNX_DATA_MAX_INGR_CONGESTION_SRAM_BUFFER_NOF_DROP_PROFILES
#define DNX_DATA_MAX_INGR_CONGESTION_SRAM_BUFFER_NOF_DROP_PROFILES (4)





#endif 

