
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_DEBUG_H_

#define _DNX_DATA_MAX_DEBUG_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_DEBUG_KLEAP_FWD1_GEN_DATA_SIZE (1)

#undef DNX_DATA_MAX_DEBUG_KLEAP_FWD1_GEN_DATA_SIZE
#define DNX_DATA_MAX_DEBUG_KLEAP_FWD1_GEN_DATA_SIZE (2748)


#define DNX_DATA_MAX_DEBUG_KLEAP_FWD2_GEN_DATA_SIZE (1)

#undef DNX_DATA_MAX_DEBUG_KLEAP_FWD2_GEN_DATA_SIZE
#define DNX_DATA_MAX_DEBUG_KLEAP_FWD2_GEN_DATA_SIZE (3180)


#define DNX_DATA_MAX_DEBUG_GENERAL_GLOBAL_VISIBILITY (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_GLOBAL_VISIBILITY
#define DNX_DATA_MAX_DEBUG_GENERAL_GLOBAL_VISIBILITY (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_HAS_ETPP_VISIBILITY_ENABLER (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_HAS_ETPP_VISIBILITY_ENABLER
#define DNX_DATA_MAX_DEBUG_GENERAL_HAS_ETPP_VISIBILITY_ENABLER (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_HAS_PERIODIC_VISIBILITY (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_HAS_PERIODIC_VISIBILITY
#define DNX_DATA_MAX_DEBUG_GENERAL_HAS_PERIODIC_VISIBILITY (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_ETPP_EOP_AND_SOP_DEC_ABOVE_THRESHOLD (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_ETPP_EOP_AND_SOP_DEC_ABOVE_THRESHOLD
#define DNX_DATA_MAX_DEBUG_GENERAL_ETPP_EOP_AND_SOP_DEC_ABOVE_THRESHOLD (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_EGRESS_PORT_MC_VISIBILITY (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_EGRESS_PORT_MC_VISIBILITY
#define DNX_DATA_MAX_DEBUG_GENERAL_EGRESS_PORT_MC_VISIBILITY (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_PMF_DEBUG_SIGNALS (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_PMF_DEBUG_SIGNALS
#define DNX_DATA_MAX_DEBUG_GENERAL_PMF_DEBUG_SIGNALS (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_FER_DEBUG_SIGNALS (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_FER_DEBUG_SIGNALS
#define DNX_DATA_MAX_DEBUG_GENERAL_FER_DEBUG_SIGNALS (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_EES_DATA_DEVICE_DEBUG_SIGNALS (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_EES_DATA_DEVICE_DEBUG_SIGNALS
#define DNX_DATA_MAX_DEBUG_GENERAL_EES_DATA_DEVICE_DEBUG_SIGNALS (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_LBP_DEBUG_SIGNALS_REGISTER_BASED (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_LBP_DEBUG_SIGNALS_REGISTER_BASED
#define DNX_DATA_MAX_DEBUG_GENERAL_LBP_DEBUG_SIGNALS_REGISTER_BASED (1)


#define DNX_DATA_MAX_DEBUG_GENERAL_SIGNAL_VERSION (1)

#undef DNX_DATA_MAX_DEBUG_GENERAL_SIGNAL_VERSION
#define DNX_DATA_MAX_DEBUG_GENERAL_SIGNAL_VERSION (1)





#endif 

