
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ESEM_H_

#define _DNX_DATA_MAX_ESEM_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES (3)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS (4)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE (1)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE (16)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION (60)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_PORT_SVTAG (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_PORT_SVTAG
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_PORT_SVTAG (61)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES (6)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS (6)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS (64)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD (2)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4 (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4 (0)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE (52)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION (60)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_ARP_PLUS_AC (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_ARP_PLUS_AC
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_ARP_PLUS_AC (60)


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_PREDEFINE_ALLOCATIONS (1)

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_PREDEFINE_ALLOCATIONS
#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_PREDEFINE_ALLOCATIONS (0)


#define DNX_DATA_MAX_ESEM_FEATURE_ESEM_NAME_SPACE_NOF_BITS (1)

#undef DNX_DATA_MAX_ESEM_FEATURE_ESEM_NAME_SPACE_NOF_BITS
#define DNX_DATA_MAX_ESEM_FEATURE_ESEM_NAME_SPACE_NOF_BITS (11)





#endif 

