
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_PORT_PP_H_

#define _DNX_DATA_MAX_PORT_PP_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_INGRESS_LLVP_PROFILES (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_NOF_INGRESS_LLVP_PROFILES
#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_INGRESS_LLVP_PROFILES (8)


#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_LLVP_PROFILES (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_LLVP_PROFILES
#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_LLVP_PROFILES (8)


#define DNX_DATA_MAX_PORT_PP_GENERAL_DEFAULT_INGRESS_NATIVE_AC_LLVP_PROFILE_ID (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_DEFAULT_INGRESS_NATIVE_AC_LLVP_PROFILE_ID
#define DNX_DATA_MAX_PORT_PP_GENERAL_DEFAULT_INGRESS_NATIVE_AC_LLVP_PROFILE_ID (0)


#define DNX_DATA_MAX_PORT_PP_GENERAL_DEFAULT_EGRESS_NATIVE_AC_LLVP_PROFILE_ID (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_DEFAULT_EGRESS_NATIVE_AC_LLVP_PROFILE_ID
#define DNX_DATA_MAX_PORT_PP_GENERAL_DEFAULT_EGRESS_NATIVE_AC_LLVP_PROFILE_ID (0)


#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_SIT_PROFILE (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_SIT_PROFILE
#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_SIT_PROFILE (8)


#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_ACCEPTABLE_FRAME_TYPE_PROFILE (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_ACCEPTABLE_FRAME_TYPE_PROFILE
#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_EGRESS_ACCEPTABLE_FRAME_TYPE_PROFILE (4)


#define DNX_DATA_MAX_PORT_PP_GENERAL_SIT_INNER_ETH_ADDITIONAL_TAG (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_SIT_INNER_ETH_ADDITIONAL_TAG
#define DNX_DATA_MAX_PORT_PP_GENERAL_SIT_INNER_ETH_ADDITIONAL_TAG (1)


#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_VIRTUAL_PORT_TCAM_ENTRIES (1)

#undef DNX_DATA_MAX_PORT_PP_GENERAL_NOF_VIRTUAL_PORT_TCAM_ENTRIES
#define DNX_DATA_MAX_PORT_PP_GENERAL_NOF_VIRTUAL_PORT_TCAM_ENTRIES (512)





#endif 

