
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_MDB_H_

#define _DNX_DATA_MAX_MDB_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_MDB_GLOBAL_UTILIZATION_API_NOF_DBS (1)

#undef DNX_DATA_MAX_MDB_GLOBAL_UTILIZATION_API_NOF_DBS
#define DNX_DATA_MAX_MDB_GLOBAL_UTILIZATION_API_NOF_DBS (17)


#define DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES (1)

#undef DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES
#define DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES (20)


#define DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES_PLUS_EM_OVF_OR_EEDB_BANK (1)

#undef DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES_PLUS_EM_OVF_OR_EEDB_BANK
#define DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES_PLUS_EM_OVF_OR_EEDB_BANK (21)


#define DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES_PLUS_DATA_WIDTH (1)

#undef DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES_PLUS_DATA_WIDTH
#define DNX_DATA_MAX_MDB_DH_TOTAL_NOF_MACROES_PLUS_DATA_WIDTH (21)


#define DNX_DATA_MAX_MDB_DH_MAX_NOF_CLUSTER_INTERFACES (1)

#undef DNX_DATA_MAX_MDB_DH_MAX_NOF_CLUSTER_INTERFACES
#define DNX_DATA_MAX_MDB_DH_MAX_NOF_CLUSTER_INTERFACES (11)


#define DNX_DATA_MAX_MDB_DH_MAX_NOF_CLUSTERS (1)

#undef DNX_DATA_MAX_MDB_DH_MAX_NOF_CLUSTERS
#define DNX_DATA_MAX_MDB_DH_MAX_NOF_CLUSTERS (8)


#define DNX_DATA_MAX_MDB_DH_MAX_NOF_DB_CLUSTERS (1)

#undef DNX_DATA_MAX_MDB_DH_MAX_NOF_DB_CLUSTERS
#define DNX_DATA_MAX_MDB_DH_MAX_NOF_DB_CLUSTERS (100)


#define DNX_DATA_MAX_MDB_DH_NOF_BUCKET_CLUSTERS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_BUCKET_CLUSTERS
#define DNX_DATA_MAX_MDB_DH_NOF_BUCKET_CLUSTERS (4)


#define DNX_DATA_MAX_MDB_DH_NOF_BUCKETS_IN_MACRO (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_BUCKETS_IN_MACRO
#define DNX_DATA_MAX_MDB_DH_NOF_BUCKETS_IN_MACRO (2)


#define DNX_DATA_MAX_MDB_DH_NOF_PAIR_CLUSTERS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_PAIR_CLUSTERS
#define DNX_DATA_MAX_MDB_DH_NOF_PAIR_CLUSTERS (2)


#define DNX_DATA_MAX_MDB_DH_NOF_DATA_ROWS_PER_HITBIT_ROW (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_DATA_ROWS_PER_HITBIT_ROW
#define DNX_DATA_MAX_MDB_DH_NOF_DATA_ROWS_PER_HITBIT_ROW (4)


#define DNX_DATA_MAX_MDB_DH_NOF_DDHA_BLOCKS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_DDHA_BLOCKS
#define DNX_DATA_MAX_MDB_DH_NOF_DDHA_BLOCKS (4)


#define DNX_DATA_MAX_MDB_DH_NOF_DDHB_BLOCKS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_DDHB_BLOCKS
#define DNX_DATA_MAX_MDB_DH_NOF_DDHB_BLOCKS (4)


#define DNX_DATA_MAX_MDB_DH_NOF_DHC_BLOCKS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_DHC_BLOCKS
#define DNX_DATA_MAX_MDB_DH_NOF_DHC_BLOCKS (8)


#define DNX_DATA_MAX_MDB_DH_NOF_DDHC_BLOCKS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_DDHC_BLOCKS
#define DNX_DATA_MAX_MDB_DH_NOF_DDHC_BLOCKS (0)


#define DNX_DATA_MAX_MDB_DH_NOF_DDHX_BLOCKS (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_DDHX_BLOCKS
#define DNX_DATA_MAX_MDB_DH_NOF_DDHX_BLOCKS (0)


#define DNX_DATA_MAX_MDB_DH_CLUSTER_ROW_WIDTH_BITS (1)

#undef DNX_DATA_MAX_MDB_DH_CLUSTER_ROW_WIDTH_BITS
#define DNX_DATA_MAX_MDB_DH_CLUSTER_ROW_WIDTH_BITS (120)


#define DNX_DATA_MAX_MDB_DH_CLUSTER_ROW_WIDTH_UINT32 (1)

#undef DNX_DATA_MAX_MDB_DH_CLUSTER_ROW_WIDTH_UINT32
#define DNX_DATA_MAX_MDB_DH_CLUSTER_ROW_WIDTH_UINT32 (4)


#define DNX_DATA_MAX_MDB_DH_DATA_OUT_GRANULARITY (1)

#undef DNX_DATA_MAX_MDB_DH_DATA_OUT_GRANULARITY
#define DNX_DATA_MAX_MDB_DH_DATA_OUT_GRANULARITY (30)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_BB_CONNECTED (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_BB_CONNECTED
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_BB_CONNECTED (16)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_240_120 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_240_120
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_240_120 (16)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_480_ODD (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_480_ODD
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_480_ODD (5)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_480 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_480
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_480 (4)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_360_120 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_360_120
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_360_120 (16)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_360 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_360
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_360 (16)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_240_240 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_240_240
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_240_240 (3)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_120_240 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_120_240
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_120_240 (1)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_240_120_120 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_240_120_120
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_240_120_120 (2)


#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_120_120_120 (1)

#undef DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_120_120_120
#define DNX_DATA_MAX_MDB_DH_BPU_SETUP_SIZE_120_120_120_120 (0)


#define DNX_DATA_MAX_MDB_DH_NOF_FEC_MACRO_TYPES (1)

#undef DNX_DATA_MAX_MDB_DH_NOF_FEC_MACRO_TYPES
#define DNX_DATA_MAX_MDB_DH_NOF_FEC_MACRO_TYPES (2)


#define DNX_DATA_MAX_MDB_PDBS_MAX_NOF_INTERFACE_DHS (1)

#undef DNX_DATA_MAX_MDB_PDBS_MAX_NOF_INTERFACE_DHS
#define DNX_DATA_MAX_MDB_PDBS_MAX_NOF_INTERFACE_DHS (12)


#define DNX_DATA_MAX_MDB_PDBS_MESH_MODE_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_PDBS_MESH_MODE_SUPPORT
#define DNX_DATA_MAX_MDB_PDBS_MESH_MODE_SUPPORT (1)


#define DNX_DATA_MAX_MDB_PDBS_MAX_KEY_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_MAX_KEY_SIZE
#define DNX_DATA_MAX_MDB_PDBS_MAX_KEY_SIZE (160)


#define DNX_DATA_MAX_MDB_PDBS_MAX_PAYLOAD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_MAX_PAYLOAD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_MAX_PAYLOAD_SIZE (180)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_1_ARRAY_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_1_ARRAY_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_1_ARRAY_SIZE (64)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_2_ARRAY_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_2_ARRAY_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_2_ARRAY_SIZE (64)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_3_ARRAY_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_3_ARRAY_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_9_MDB_ITEM_3_ARRAY_SIZE (64)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_40_MDB_ITEM_0_ARRAY_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_40_MDB_ITEM_0_ARRAY_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_40_MDB_ITEM_0_ARRAY_SIZE (128)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (74)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_MACT_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_MACT_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_MACT_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (3)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_KAPS_DYNAMIC_MEMORY_ACCESS_SBC_MEMORY_ACCESS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_KAPS_DYNAMIC_MEMORY_ACCESS_SBC_MEMORY_ACCESS_FIELD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_KAPS_DYNAMIC_MEMORY_ACCESS_SBC_MEMORY_ACCESS_FIELD_SIZE (22)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DDHB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DDHB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DDHB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (24)


#define DNX_DATA_MAX_MDB_PDBS_MDB_NOF_PROFILES (1)

#undef DNX_DATA_MAX_MDB_PDBS_MDB_NOF_PROFILES
#define DNX_DATA_MAX_MDB_PDBS_MDB_NOF_PROFILES (7)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_KAPS_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_KAPS_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_KAPS_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (22)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DDHA_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DDHA_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE
#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDB_DDHA_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (24)


#define DNX_DATA_MAX_MDB_PDBS_TABLE_DDHA_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#define DNX_DATA_MAX_MDB_PDBS_TABLE_DDHAB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDBA_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDBB_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#define DNX_DATA_MAX_MDB_PDBS_TABLE_MDBK_DYNAMIC_MEMORY_ACCESS_MEMORY_ACCESS_FIELD_SIZE (1)

#define DNX_DATA_MAX_MDB_EM_AGE_ROW_SIZE_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_AGE_ROW_SIZE_BITS
#define DNX_DATA_MAX_MDB_EM_AGE_ROW_SIZE_BITS (128)


#define DNX_DATA_MAX_MDB_EM_AGE_OVFCAM_ROW_SIZE_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_AGE_OVFCAM_ROW_SIZE_BITS
#define DNX_DATA_MAX_MDB_EM_AGE_OVFCAM_ROW_SIZE_BITS (32)


#define DNX_DATA_MAX_MDB_EM_OVF_CAM_MAX_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_OVF_CAM_MAX_SIZE
#define DNX_DATA_MAX_MDB_EM_OVF_CAM_MAX_SIZE (8)


#define DNX_DATA_MAX_MDB_EM_AGE_SUPPORT_PER_ENTRY_SIZE_RATIO (1)

#undef DNX_DATA_MAX_MDB_EM_AGE_SUPPORT_PER_ENTRY_SIZE_RATIO
#define DNX_DATA_MAX_MDB_EM_AGE_SUPPORT_PER_ENTRY_SIZE_RATIO (1)


#define DNX_DATA_MAX_MDB_EM_FLUSH_TCAM_RULE_COUNTER_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_FLUSH_TCAM_RULE_COUNTER_SUPPORT
#define DNX_DATA_MAX_MDB_EM_FLUSH_TCAM_RULE_COUNTER_SUPPORT (1)


#define DNX_DATA_MAX_MDB_EM_NOF_AGING_PROFILES (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_AGING_PROFILES
#define DNX_DATA_MAX_MDB_EM_NOF_AGING_PROFILES (8)


#define DNX_DATA_MAX_MDB_EM_AGING_PROFILES_SIZE_IN_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_AGING_PROFILES_SIZE_IN_BITS
#define DNX_DATA_MAX_MDB_EM_AGING_PROFILES_SIZE_IN_BITS (3)


#define DNX_DATA_MAX_MDB_EM_MAX_TID_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_MAX_TID_SIZE
#define DNX_DATA_MAX_MDB_EM_MAX_TID_SIZE (6)


#define DNX_DATA_MAX_MDB_EM_MAX_NOF_TIDS (1)

#undef DNX_DATA_MAX_MDB_EM_MAX_NOF_TIDS
#define DNX_DATA_MAX_MDB_EM_MAX_NOF_TIDS (64)


#define DNX_DATA_MAX_MDB_EM_FLUSH_SUPPORT_TIDS (1)

#undef DNX_DATA_MAX_MDB_EM_FLUSH_SUPPORT_TIDS
#define DNX_DATA_MAX_MDB_EM_FLUSH_SUPPORT_TIDS (64)


#define DNX_DATA_MAX_MDB_EM_FLUSH_MAX_SUPPORTED_KEY (1)

#undef DNX_DATA_MAX_MDB_EM_FLUSH_MAX_SUPPORTED_KEY
#define DNX_DATA_MAX_MDB_EM_FLUSH_MAX_SUPPORTED_KEY (80)


#define DNX_DATA_MAX_MDB_EM_FLUSH_MAX_SUPPORTED_KEY_PLUS_PAYLOAD (1)

#undef DNX_DATA_MAX_MDB_EM_FLUSH_MAX_SUPPORTED_KEY_PLUS_PAYLOAD
#define DNX_DATA_MAX_MDB_EM_FLUSH_MAX_SUPPORTED_KEY_PLUS_PAYLOAD (144)


#define DNX_DATA_MAX_MDB_EM_DH_120_ENTRY_ENCODING_NOF_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_DH_120_ENTRY_ENCODING_NOF_BITS
#define DNX_DATA_MAX_MDB_EM_DH_120_ENTRY_ENCODING_NOF_BITS (2)


#define DNX_DATA_MAX_MDB_EM_DH_240_ENTRY_ENCODING_NOF_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_DH_240_ENTRY_ENCODING_NOF_BITS
#define DNX_DATA_MAX_MDB_EM_DH_240_ENTRY_ENCODING_NOF_BITS (4)


#define DNX_DATA_MAX_MDB_EM_FORMAT_GRANULARITY (1)

#undef DNX_DATA_MAX_MDB_EM_FORMAT_GRANULARITY
#define DNX_DATA_MAX_MDB_EM_FORMAT_GRANULARITY (30)


#define DNX_DATA_MAX_MDB_EM_MAX_NOF_VMV_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_MAX_NOF_VMV_SIZE
#define DNX_DATA_MAX_MDB_EM_MAX_NOF_VMV_SIZE (6)


#define DNX_DATA_MAX_MDB_EM_VMV_NOF_VALUES (1)

#undef DNX_DATA_MAX_MDB_EM_VMV_NOF_VALUES
#define DNX_DATA_MAX_MDB_EM_VMV_NOF_VALUES (64)


#define DNX_DATA_MAX_MDB_EM_NOF_VMV_SIZE_NOF_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_VMV_SIZE_NOF_BITS
#define DNX_DATA_MAX_MDB_EM_NOF_VMV_SIZE_NOF_BITS (3)


#define DNX_DATA_MAX_MDB_EM_ESEM_NOF_VMV_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_ESEM_NOF_VMV_SIZE
#define DNX_DATA_MAX_MDB_EM_ESEM_NOF_VMV_SIZE (4)


#define DNX_DATA_MAX_MDB_EM_GLEM_NOF_VMV_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_GLEM_NOF_VMV_SIZE
#define DNX_DATA_MAX_MDB_EM_GLEM_NOF_VMV_SIZE (1)


#define DNX_DATA_MAX_MDB_EM_MACT_NOF_VMV_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_MACT_NOF_VMV_SIZE
#define DNX_DATA_MAX_MDB_EM_MACT_NOF_VMV_SIZE (3)


#define DNX_DATA_MAX_MDB_EM_MACT_MAX_PAYLOAD_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_MACT_MAX_PAYLOAD_SIZE
#define DNX_DATA_MAX_MDB_EM_MACT_MAX_PAYLOAD_SIZE (64)


#define DNX_DATA_MAX_MDB_EM_SHIFT_VMV_MAX_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_SHIFT_VMV_MAX_SIZE
#define DNX_DATA_MAX_MDB_EM_SHIFT_VMV_MAX_SIZE (3)


#define DNX_DATA_MAX_MDB_EM_SHIFT_VMV_MAX_REGS_PER_TABLE (1)

#undef DNX_DATA_MAX_MDB_EM_SHIFT_VMV_MAX_REGS_PER_TABLE
#define DNX_DATA_MAX_MDB_EM_SHIFT_VMV_MAX_REGS_PER_TABLE (4)


#define DNX_DATA_MAX_MDB_EM_MIN_NOF_APP_ID_BITS (1)

#undef DNX_DATA_MAX_MDB_EM_MIN_NOF_APP_ID_BITS
#define DNX_DATA_MAX_MDB_EM_MIN_NOF_APP_ID_BITS (2)


#define DNX_DATA_MAX_MDB_EM_MAX_NOF_SPN_SIZES (1)

#undef DNX_DATA_MAX_MDB_EM_MAX_NOF_SPN_SIZES
#define DNX_DATA_MAX_MDB_EM_MAX_NOF_SPN_SIZES (8)


#define DNX_DATA_MAX_MDB_EM_NOF_LFSR_SIZES (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_LFSR_SIZES
#define DNX_DATA_MAX_MDB_EM_NOF_LFSR_SIZES (4)


#define DNX_DATA_MAX_MDB_EM_NOF_FORMATS (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_FORMATS
#define DNX_DATA_MAX_MDB_EM_NOF_FORMATS (32)


#define DNX_DATA_MAX_MDB_EM_DEFRAGMENTATION_PRIORITY_SUPPORTED (1)

#undef DNX_DATA_MAX_MDB_EM_DEFRAGMENTATION_PRIORITY_SUPPORTED
#define DNX_DATA_MAX_MDB_EM_DEFRAGMENTATION_PRIORITY_SUPPORTED (1)


#define DNX_DATA_MAX_MDB_EM_DISABLE_CUCKOO_LOOP_DETECTION_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_DISABLE_CUCKOO_LOOP_DETECTION_SUPPORT
#define DNX_DATA_MAX_MDB_EM_DISABLE_CUCKOO_LOOP_DETECTION_SUPPORT (1)


#define DNX_DATA_MAX_MDB_EM_DISABLE_CUCKOO_HIT_BIT_SYNC (1)

#undef DNX_DATA_MAX_MDB_EM_DISABLE_CUCKOO_HIT_BIT_SYNC
#define DNX_DATA_MAX_MDB_EM_DISABLE_CUCKOO_HIT_BIT_SYNC (1)


#define DNX_DATA_MAX_MDB_EM_AGE_PROFILE_PER_RATIO_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_AGE_PROFILE_PER_RATIO_SUPPORT
#define DNX_DATA_MAX_MDB_EM_AGE_PROFILE_PER_RATIO_SUPPORT (1)


#define DNX_DATA_MAX_MDB_EM_FLEX_MAG_SUPPORTED (1)

#undef DNX_DATA_MAX_MDB_EM_FLEX_MAG_SUPPORTED
#define DNX_DATA_MAX_MDB_EM_FLEX_MAG_SUPPORTED (1)


#define DNX_DATA_MAX_MDB_EM_FLEX_FULLY_SUPPORTED (1)

#undef DNX_DATA_MAX_MDB_EM_FLEX_FULLY_SUPPORTED
#define DNX_DATA_MAX_MDB_EM_FLEX_FULLY_SUPPORTED (1)


#define DNX_DATA_MAX_MDB_EM_STEP_TABLE_MAX_SIZE (1)

#undef DNX_DATA_MAX_MDB_EM_STEP_TABLE_MAX_SIZE
#define DNX_DATA_MAX_MDB_EM_STEP_TABLE_MAX_SIZE (2048)


#define DNX_DATA_MAX_MDB_EM_NOF_ENCODING_VALUES (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_ENCODING_VALUES
#define DNX_DATA_MAX_MDB_EM_NOF_ENCODING_VALUES (8)


#define DNX_DATA_MAX_MDB_EM_NOF_ENCODING_TYPES (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_ENCODING_TYPES
#define DNX_DATA_MAX_MDB_EM_NOF_ENCODING_TYPES (4)


#define DNX_DATA_MAX_MDB_EM_EXTRA_VMV_SHIFT_REGISTERS (1)

#undef DNX_DATA_MAX_MDB_EM_EXTRA_VMV_SHIFT_REGISTERS
#define DNX_DATA_MAX_MDB_EM_EXTRA_VMV_SHIFT_REGISTERS (1)


#define DNX_DATA_MAX_MDB_EM_SCAN_BANK_PARTICIPATE_IN_CUCKOO_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_SCAN_BANK_PARTICIPATE_IN_CUCKOO_SUPPORT
#define DNX_DATA_MAX_MDB_EM_SCAN_BANK_PARTICIPATE_IN_CUCKOO_SUPPORT (0)


#define DNX_DATA_MAX_MDB_EM_SCAN_BANK_PARTICIPATE_IN_CUCKOO_PARTIAL_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_SCAN_BANK_PARTICIPATE_IN_CUCKOO_PARTIAL_SUPPORT
#define DNX_DATA_MAX_MDB_EM_SCAN_BANK_PARTICIPATE_IN_CUCKOO_PARTIAL_SUPPORT (1)


#define DNX_DATA_MAX_MDB_EM_SBUS_ERROR_CODE_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_SBUS_ERROR_CODE_SUPPORT
#define DNX_DATA_MAX_MDB_EM_SBUS_ERROR_CODE_SUPPORT (1)


#define DNX_DATA_MAX_MDB_EM_NOF_EMP_TABLES (1)

#undef DNX_DATA_MAX_MDB_EM_NOF_EMP_TABLES
#define DNX_DATA_MAX_MDB_EM_NOF_EMP_TABLES (3)


#define DNX_DATA_MAX_MDB_EM_DEFRAG_INTERRUPT_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_DEFRAG_INTERRUPT_SUPPORT
#define DNX_DATA_MAX_MDB_EM_DEFRAG_INTERRUPT_SUPPORT (0)


#define DNX_DATA_MAX_MDB_EM_GLEM_BYPASS_OPTION_SUPPORT (1)

#undef DNX_DATA_MAX_MDB_EM_GLEM_BYPASS_OPTION_SUPPORT
#define DNX_DATA_MAX_MDB_EM_GLEM_BYPASS_OPTION_SUPPORT (1)


#define DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_MAX_BITS (1)

#undef DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_MAX_BITS
#define DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_MAX_BITS (20)


#define DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_MAX_BITS_SUPPORT_SINGLE_MACRO_B_GRANULARITY_FEC_ALLOC (1)

#undef DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_MAX_BITS_SUPPORT_SINGLE_MACRO_B_GRANULARITY_FEC_ALLOC
#define DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_MAX_BITS_SUPPORT_SINGLE_MACRO_B_GRANULARITY_FEC_ALLOC (19)


#define DNX_DATA_MAX_MDB_DIRECT_VSI_PHYSICAL_ADDRESS_MAX_BITS (1)

#undef DNX_DATA_MAX_MDB_DIRECT_VSI_PHYSICAL_ADDRESS_MAX_BITS
#define DNX_DATA_MAX_MDB_DIRECT_VSI_PHYSICAL_ADDRESS_MAX_BITS (18)


#define DNX_DATA_MAX_MDB_DIRECT_FEC_ROW_WIDTH (1)

#undef DNX_DATA_MAX_MDB_DIRECT_FEC_ROW_WIDTH
#define DNX_DATA_MAX_MDB_DIRECT_FEC_ROW_WIDTH (240)


#define DNX_DATA_MAX_MDB_DIRECT_FEC_ADDRESS_MAPPING_BITS (1)

#undef DNX_DATA_MAX_MDB_DIRECT_FEC_ADDRESS_MAPPING_BITS
#define DNX_DATA_MAX_MDB_DIRECT_FEC_ADDRESS_MAPPING_BITS (5)


#define DNX_DATA_MAX_MDB_DIRECT_FEC_ADDRESS_MAPPING_BITS_RELEVANT (1)

#undef DNX_DATA_MAX_MDB_DIRECT_FEC_ADDRESS_MAPPING_BITS_RELEVANT
#define DNX_DATA_MAX_MDB_DIRECT_FEC_ADDRESS_MAPPING_BITS_RELEVANT (2)


#define DNX_DATA_MAX_MDB_DIRECT_FEC_MAX_CLUSTER_PAIRS (1)

#undef DNX_DATA_MAX_MDB_DIRECT_FEC_MAX_CLUSTER_PAIRS
#define DNX_DATA_MAX_MDB_DIRECT_FEC_MAX_CLUSTER_PAIRS (16)


#define DNX_DATA_MAX_MDB_DIRECT_MAX_PAYLOAD_SIZE (1)

#undef DNX_DATA_MAX_MDB_DIRECT_MAX_PAYLOAD_SIZE
#define DNX_DATA_MAX_MDB_DIRECT_MAX_PAYLOAD_SIZE (180)


#define DNX_DATA_MAX_MDB_DIRECT_NOF_FECS_IN_SUPER_FEC (1)

#undef DNX_DATA_MAX_MDB_DIRECT_NOF_FECS_IN_SUPER_FEC
#define DNX_DATA_MAX_MDB_DIRECT_NOF_FECS_IN_SUPER_FEC (2)


#define DNX_DATA_MAX_MDB_DIRECT_NOF_FEC_ECMP_HIERARCHIES (1)

#undef DNX_DATA_MAX_MDB_DIRECT_NOF_FEC_ECMP_HIERARCHIES
#define DNX_DATA_MAX_MDB_DIRECT_NOF_FEC_ECMP_HIERARCHIES (3)


#define DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_OVF_ENABLE_VAL (1)

#undef DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_OVF_ENABLE_VAL
#define DNX_DATA_MAX_MDB_DIRECT_PHYSICAL_ADDRESS_OVF_ENABLE_VAL (1)


#define DNX_DATA_MAX_MDB_DIRECT_NOF_FEC_DBS (1)

#undef DNX_DATA_MAX_MDB_DIRECT_NOF_FEC_DBS
#define DNX_DATA_MAX_MDB_DIRECT_NOF_FEC_DBS (3)


#define DNX_DATA_MAX_MDB_EEDB_PHASE_MAP_BITS (1)

#undef DNX_DATA_MAX_MDB_EEDB_PHASE_MAP_BITS
#define DNX_DATA_MAX_MDB_EEDB_PHASE_MAP_BITS (7)


#define DNX_DATA_MAX_MDB_EEDB_PHASE_MAP_ARRAY_SIZE (1)

#undef DNX_DATA_MAX_MDB_EEDB_PHASE_MAP_ARRAY_SIZE
#define DNX_DATA_MAX_MDB_EEDB_PHASE_MAP_ARRAY_SIZE (128)


#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASE_PER_MAG (1)

#undef DNX_DATA_MAX_MDB_EEDB_NOF_PHASE_PER_MAG
#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASE_PER_MAG (2)


#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASES (1)

#undef DNX_DATA_MAX_MDB_EEDB_NOF_PHASES
#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASES (8)


#define DNX_DATA_MAX_MDB_EEDB_NOF_EEDB_MAGS (1)

#undef DNX_DATA_MAX_MDB_EEDB_NOF_EEDB_MAGS
#define DNX_DATA_MAX_MDB_EEDB_NOF_EEDB_MAGS (4)


#define DNX_DATA_MAX_MDB_EEDB_NOF_EEDB_BANKS (1)

#undef DNX_DATA_MAX_MDB_EEDB_NOF_EEDB_BANKS
#define DNX_DATA_MAX_MDB_EEDB_NOF_EEDB_BANKS (64)


#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASES_PER_EEDB_BANK (1)

#undef DNX_DATA_MAX_MDB_EEDB_NOF_PHASES_PER_EEDB_BANK
#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASES_PER_EEDB_BANK (3)


#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASES_PER_EEDB_BANK_SIZE (1)

#undef DNX_DATA_MAX_MDB_EEDB_NOF_PHASES_PER_EEDB_BANK_SIZE
#define DNX_DATA_MAX_MDB_EEDB_NOF_PHASES_PER_EEDB_BANK_SIZE (2)


#define DNX_DATA_MAX_MDB_EEDB_PHASE_BANK_SELECT_DEFAULT (1)

#undef DNX_DATA_MAX_MDB_EEDB_PHASE_BANK_SELECT_DEFAULT
#define DNX_DATA_MAX_MDB_EEDB_PHASE_BANK_SELECT_DEFAULT (0)


#define DNX_DATA_MAX_MDB_EEDB_ENTRY_FORMAT_BITS (1)

#undef DNX_DATA_MAX_MDB_EEDB_ENTRY_FORMAT_BITS
#define DNX_DATA_MAX_MDB_EEDB_ENTRY_FORMAT_BITS (7)


#define DNX_DATA_MAX_MDB_EEDB_ENTRY_FORMAT_ENCODING_BITS (1)

#undef DNX_DATA_MAX_MDB_EEDB_ENTRY_FORMAT_ENCODING_BITS
#define DNX_DATA_MAX_MDB_EEDB_ENTRY_FORMAT_ENCODING_BITS (2)


#define DNX_DATA_MAX_MDB_EEDB_BANK_ID_BITS (1)

#undef DNX_DATA_MAX_MDB_EEDB_BANK_ID_BITS
#define DNX_DATA_MAX_MDB_EEDB_BANK_ID_BITS (6)


#define DNX_DATA_MAX_MDB_KAPS_NOF_DBS   (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_DBS
#define DNX_DATA_MAX_MDB_KAPS_NOF_DBS   (2)


#define DNX_DATA_MAX_MDB_KAPS_NOF_SMALL_BBS (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_SMALL_BBS
#define DNX_DATA_MAX_MDB_KAPS_NOF_SMALL_BBS (16)


#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_RPB_MAX (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_RPB_MAX
#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_RPB_MAX (2048)


#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_ADS_MAX (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_ADS_MAX
#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_ADS_MAX (1024)


#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_BB_MAX (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_BB_MAX
#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_BB_MAX (512)


#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_RPB_HITBITS_MAX (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_RPB_HITBITS_MAX
#define DNX_DATA_MAX_MDB_KAPS_NOF_ROWS_IN_SMALL_RPB_HITBITS_MAX (64)


#define DNX_DATA_MAX_MDB_KAPS_NOF_BIG_BBS_BLK_IDS (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_BIG_BBS_BLK_IDS
#define DNX_DATA_MAX_MDB_KAPS_NOF_BIG_BBS_BLK_IDS (14)


#define DNX_DATA_MAX_MDB_KAPS_NOF_BYTES_IN_HITBIT_ROW (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_BYTES_IN_HITBIT_ROW
#define DNX_DATA_MAX_MDB_KAPS_NOF_BYTES_IN_HITBIT_ROW (2)


#define DNX_DATA_MAX_MDB_KAPS_KEY_LSN_BITS (1)

#undef DNX_DATA_MAX_MDB_KAPS_KEY_LSN_BITS
#define DNX_DATA_MAX_MDB_KAPS_KEY_LSN_BITS (4)


#define DNX_DATA_MAX_MDB_KAPS_KEY_PREFIX_LENGTH (1)

#undef DNX_DATA_MAX_MDB_KAPS_KEY_PREFIX_LENGTH
#define DNX_DATA_MAX_MDB_KAPS_KEY_PREFIX_LENGTH (6)


#define DNX_DATA_MAX_MDB_KAPS_MAX_PREFIX_IN_BB_ROW (1)

#undef DNX_DATA_MAX_MDB_KAPS_MAX_PREFIX_IN_BB_ROW
#define DNX_DATA_MAX_MDB_KAPS_MAX_PREFIX_IN_BB_ROW (16)


#define DNX_DATA_MAX_MDB_KAPS_KEY_WIDTH_IN_BITS (1)

#undef DNX_DATA_MAX_MDB_KAPS_KEY_WIDTH_IN_BITS
#define DNX_DATA_MAX_MDB_KAPS_KEY_WIDTH_IN_BITS (160)


#define DNX_DATA_MAX_MDB_KAPS_BB_BYTE_WIDTH (1)

#undef DNX_DATA_MAX_MDB_KAPS_BB_BYTE_WIDTH
#define DNX_DATA_MAX_MDB_KAPS_BB_BYTE_WIDTH (60)


#define DNX_DATA_MAX_MDB_KAPS_RPB_BYTE_WIDTH (1)

#undef DNX_DATA_MAX_MDB_KAPS_RPB_BYTE_WIDTH
#define DNX_DATA_MAX_MDB_KAPS_RPB_BYTE_WIDTH (21)


#define DNX_DATA_MAX_MDB_KAPS_ADS_BYTE_WIDTH (1)

#undef DNX_DATA_MAX_MDB_KAPS_ADS_BYTE_WIDTH
#define DNX_DATA_MAX_MDB_KAPS_ADS_BYTE_WIDTH (16)


#define DNX_DATA_MAX_MDB_KAPS_DIRECT_BYTE_WIDTH (1)

#undef DNX_DATA_MAX_MDB_KAPS_DIRECT_BYTE_WIDTH
#define DNX_DATA_MAX_MDB_KAPS_DIRECT_BYTE_WIDTH (15)


#define DNX_DATA_MAX_MDB_KAPS_RPB_VALID_BITS (1)

#undef DNX_DATA_MAX_MDB_KAPS_RPB_VALID_BITS
#define DNX_DATA_MAX_MDB_KAPS_RPB_VALID_BITS (2)


#define DNX_DATA_MAX_MDB_KAPS_MAX_FMT   (1)

#undef DNX_DATA_MAX_MDB_KAPS_MAX_FMT
#define DNX_DATA_MAX_MDB_KAPS_MAX_FMT   (15)


#define DNX_DATA_MAX_MDB_KAPS_NOF_APP_IDS (1)

#undef DNX_DATA_MAX_MDB_KAPS_NOF_APP_IDS
#define DNX_DATA_MAX_MDB_KAPS_NOF_APP_IDS (64)


#define DNX_DATA_MAX_MDB_KAPS_MAX_NOF_RESULT_TYPES (1)

#undef DNX_DATA_MAX_MDB_KAPS_MAX_NOF_RESULT_TYPES
#define DNX_DATA_MAX_MDB_KAPS_MAX_NOF_RESULT_TYPES (1)





#endif 

