
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_PP_H_

#define _DNX_DATA_MAX_PP_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_PP_STAGES_IS_VTT5_SUPPORTED (1)

#undef DNX_DATA_MAX_PP_STAGES_IS_VTT5_SUPPORTED
#define DNX_DATA_MAX_PP_STAGES_IS_VTT5_SUPPORTED (1)


#define DNX_DATA_MAX_PP_STAGES_IS_ERPP_SUPPORTED (1)

#undef DNX_DATA_MAX_PP_STAGES_IS_ERPP_SUPPORTED
#define DNX_DATA_MAX_PP_STAGES_IS_ERPP_SUPPORTED (1)


#define DNX_DATA_MAX_PP_PEM_NOF_PEM_BITS (1)

#undef DNX_DATA_MAX_PP_PEM_NOF_PEM_BITS
#define DNX_DATA_MAX_PP_PEM_NOF_PEM_BITS (3)


#define DNX_DATA_MAX_PP_PEM_NOF_PEM_BLOCKS_PER_CORE (1)

#undef DNX_DATA_MAX_PP_PEM_NOF_PEM_BLOCKS_PER_CORE
#define DNX_DATA_MAX_PP_PEM_NOF_PEM_BLOCKS_PER_CORE (4)


#define DNX_DATA_MAX_PP_ETPP_ETPS_TYPE_SIZE_BITS (1)

#undef DNX_DATA_MAX_PP_ETPP_ETPS_TYPE_SIZE_BITS
#define DNX_DATA_MAX_PP_ETPP_ETPS_TYPE_SIZE_BITS (7)


#define DNX_DATA_MAX_PP_ETPP_NOF_ADDITIONAL_HEADERS_PROFILES (1)

#undef DNX_DATA_MAX_PP_ETPP_NOF_ADDITIONAL_HEADERS_PROFILES
#define DNX_DATA_MAX_PP_ETPP_NOF_ADDITIONAL_HEADERS_PROFILES (32)


#define DNX_DATA_MAX_PP_ETPP_NOF_ADDITIONAL_HEADERS_PROFILES_MAPS (1)

#undef DNX_DATA_MAX_PP_ETPP_NOF_ADDITIONAL_HEADERS_PROFILES_MAPS
#define DNX_DATA_MAX_PP_ETPP_NOF_ADDITIONAL_HEADERS_PROFILES_MAPS (256)


#define DNX_DATA_MAX_PP_ETPP_DYNAMIC_ADDITIONAL_HEADERS_PROFILE (1)

#undef DNX_DATA_MAX_PP_ETPP_DYNAMIC_ADDITIONAL_HEADERS_PROFILE
#define DNX_DATA_MAX_PP_ETPP_DYNAMIC_ADDITIONAL_HEADERS_PROFILE (1)


#define DNX_DATA_MAX_PP_DEBUG_PACKET_HEADER_DATA (1)

#undef DNX_DATA_MAX_PP_DEBUG_PACKET_HEADER_DATA
#define DNX_DATA_MAX_PP_DEBUG_PACKET_HEADER_DATA (512)


#define DNX_DATA_MAX_PP_DEBUG_PTC_SIZE  (1)

#undef DNX_DATA_MAX_PP_DEBUG_PTC_SIZE
#define DNX_DATA_MAX_PP_DEBUG_PTC_SIZE  (10)


#define DNX_DATA_MAX_PP_DEBUG_VALID_BYTES (1)

#undef DNX_DATA_MAX_PP_DEBUG_VALID_BYTES
#define DNX_DATA_MAX_PP_DEBUG_VALID_BYTES (9)


#define DNX_DATA_MAX_PP_DEBUG_TIME_STAMP (1)

#undef DNX_DATA_MAX_PP_DEBUG_TIME_STAMP
#define DNX_DATA_MAX_PP_DEBUG_TIME_STAMP (34)





#endif 

