
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_MODULE_TESTING_H_

#define _DNX_DATA_MAX_MODULE_TESTING_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF (1)

#undef DNX_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF
#define DNX_DATA_MAX_MODULE_TESTING_UNSUPPORTED_SUPPORTED_DEF (305419896)


#define DNX_DATA_MAX_MODULE_TESTING_UNSUPPORTED_UNSUPPORTED_DEF (1)

#define DNX_DATA_MAX_MODULE_TESTING_STANDARD_SUBMODULE_STANDARD_DEFINE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_STANDARD_SUBMODULE_STANDARD_DEFINE
#define DNX_DATA_MAX_MODULE_TESTING_STANDARD_SUBMODULE_STANDARD_DEFINE (2)



#define DNX_DATA_MAX_MODULE_TESTING_STANDARD_SUBMODULE_DEFINE_FAMILY_DNX2 (2)

#define DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_SIGNED (1)

#undef DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_SIGNED
#define DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_SIGNED (-1)


#define DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_UNSIGNED (1)

#undef DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_UNSIGNED
#define DNX_DATA_MAX_MODULE_TESTING_TYPES_DEF_UNSIGNED (4294967295)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_CORES (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_CORES
#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_CORES (2)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_ADD_CORES (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_ADD_CORES
#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_ADD_CORES (3)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_MUL_CORES (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_MUL_CORES
#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_MUL_CORES (6)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_DIV_CORES (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_DIV_CORES
#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_DIV_CORES (1)


#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_OP_CORES (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_OP_CORES
#define DNX_DATA_MAX_MODULE_TESTING_DATA_POINTERS_OP_CORES (7)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_VRF_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DBAL_VRF_FIELD_SIZE
#define DNX_DATA_MAX_MODULE_TESTING_DBAL_VRF_FIELD_SIZE (17)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_FIELD_DEFINE_EXAMPLE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DBAL_FIELD_DEFINE_EXAMPLE
#define DNX_DATA_MAX_MODULE_TESTING_DBAL_FIELD_DEFINE_EXAMPLE (2)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_MAX_VAL (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_MAX_VAL
#define DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_MAX_VAL (5)


#define DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_FIELD_SIZE
#define DNX_DATA_MAX_MODULE_TESTING_DBAL_RES_FIELD_SIZE (4)


#define DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_FIELD_SIZE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_FIELD_SIZE
#define DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_FIELD_SIZE (17)


#define DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_LARGE_NOF_ELEMENTS (1)

#undef DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_LARGE_NOF_ELEMENTS
#define DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_LARGE_NOF_ELEMENTS (3000000)


#define DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_DEFAULT_MEMORY_SIZE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_DEFAULT_MEMORY_SIZE
#define DNX_DATA_MAX_MODULE_TESTING_EXAMPLE_TESTS_DEFAULT_MEMORY_SIZE (10000)



#define DNX_DATA_MAX_MODULE_TESTING_SUBMODULE_FAMILY_DNX2_DNX2_SUBMODULE_DEFINE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_SUBMODULE_FAMILY_DNX2_DNX2_SUBMODULE_DEFINE
#define DNX_DATA_MAX_MODULE_TESTING_SUBMODULE_FAMILY_DNX2_DNX2_SUBMODULE_DEFINE (2)



#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IFDEF (1)
#ifdef INCLUDE_XFLOW_MACSEC


#undef DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IFDEF
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IFDEF (1)



#endif 
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IFNDEF (1)
#ifndef INCLUDE_XFLOW_MACSEC


#undef DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IFNDEF
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IFNDEF (1)



#endif 
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IF (1)
#if defined(INCLUDE_XFLOW_MACSEC)


#undef DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IF
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_STANDARD_DEFINE_IF (1)



#endif 
#ifdef INCLUDE_XFLOW_MACSEC

#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_FLAGS_DEFINE_NO_FLAGS (1)

#undef DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_FLAGS_DEFINE_NO_FLAGS
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_FLAGS_DEFINE_NO_FLAGS (1)


#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_FLAGS_DEFINE_FLAGS (1)
#ifdef BCM_WARM_BOOT_SUPPORT


#undef DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_FLAGS_DEFINE_FLAGS
#define DNX_DATA_MAX_MODULE_TESTING_COMPILE_FLAGS_SUBMODULE_FLAGS_DEFINE_FLAGS (1)



#endif 

#endif 
#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D3 (1)

#undef DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D3
#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D3 (2)


#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D2 (1)

#undef DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D2
#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_GREATER_D2 (20)


#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_SAME_VALUE (1)

#undef DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_SAME_VALUE
#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_SAME_VALUE (10)


#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_D2_UNDEFINED (1)

#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_D3_UNDEFINED (1)

#undef DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_D3_UNDEFINED
#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_D3_UNDEFINED (2)



#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_DNX2_EXCLUSIVE (2)

#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_COMPILE_FLAGS (1)
#ifdef INCLUDE_XFLOW_MACSEC


#undef DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_COMPILE_FLAGS
#define DNX_DATA_MAX_MODULE_TESTING_MAX_TEST_COMPILE_FLAGS (2)



#endif 



#endif 

