#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/field/map/auto_generated

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/shared

lib = libbcm_dnxfieldmap_auto_generated

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

