# $Id: Makefile,v 1.3 2007/05/02 23:41:26 aung Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC COMMON driver Library
#
LOCALDIR = src/soc/common

include ${SDK}/make/Make.config

lib = libsoccommon

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
