#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

include $(SDK)/make/libname.mk

ifdef YAML
SUBDIRS := libyaml
else
SUBDIRS := null
endif

include $(SDK)/make/subdir.mk

include $(SDK)/make/lib.mk
