
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#ifndef MDB_GLOBAL_H_INCLUDED

#define MDB_GLOBAL_H_INCLUDED

#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif


typedef enum
{
    
    MDB_MACRO_A,
    
    MDB_MACRO_B,
    
    MDB_EEDB_BANK,
    
    MDB_NOF_MACRO_TYPES
} mdb_macro_types_e;


typedef enum
{
    MDB_EEDB_MEM_TYPE_DATA_CLUSTER,
    MDB_EEDB_MEM_TYPE_DATA_BANK,
    MDB_EEDB_MEM_TYPE_LL,

    MDB_NOF_EEDB_MEM_TYPES
} mdb_eedb_mem_type_e;


typedef enum
{
    MDB_PHYSICAL_TABLE_ISEM_1,
    MDB_PHYSICAL_TABLE_ISEM_2,
    MDB_PHYSICAL_TABLE_ISEM_3,
    MDB_PHYSICAL_TABLE_INLIF_1,
    MDB_PHYSICAL_TABLE_INLIF_2,
    MDB_PHYSICAL_TABLE_INLIF_3,
    MDB_PHYSICAL_TABLE_IVSI,
    MDB_PHYSICAL_TABLE_LEM,
    MDB_PHYSICAL_TABLE_ADS_1,
    MDB_PHYSICAL_TABLE_ADS_2,
    MDB_PHYSICAL_TABLE_BIG_KAPS_BB_1,
    MDB_PHYSICAL_TABLE_BIG_KAPS_BB_2,
    MDB_PHYSICAL_TABLE_IOEM_0,
    MDB_PHYSICAL_TABLE_IOEM_1,
    MDB_PHYSICAL_TABLE_EOEM_0,
    MDB_PHYSICAL_TABLE_EOEM_1,
    MDB_PHYSICAL_TABLE_MAP,
    MDB_PHYSICAL_TABLE_FEC_1,
    MDB_PHYSICAL_TABLE_FEC_2,
    MDB_PHYSICAL_TABLE_FEC_3,
    MDB_PHYSICAL_TABLE_MC_ID,
    MDB_PHYSICAL_TABLE_GLEM_0,
    MDB_PHYSICAL_TABLE_GLEM_1,
    MDB_PHYSICAL_TABLE_EEDB_1_LL,
    MDB_PHYSICAL_TABLE_EEDB_1_DATA,
    MDB_PHYSICAL_TABLE_EEDB_2_LL,
    MDB_PHYSICAL_TABLE_EEDB_2_DATA,
    MDB_PHYSICAL_TABLE_EEDB_1_2_DATA,
    MDB_PHYSICAL_TABLE_EEDB_3_LL,
    MDB_PHYSICAL_TABLE_EEDB_3_DATA,
    MDB_PHYSICAL_TABLE_EEDB_4_LL,
    MDB_PHYSICAL_TABLE_EEDB_4_DATA,
    MDB_PHYSICAL_TABLE_EEDB_3_4_DATA,
    MDB_PHYSICAL_TABLE_EEDB_5_LL,
    MDB_PHYSICAL_TABLE_EEDB_5_DATA,
    MDB_PHYSICAL_TABLE_EEDB_6_LL,
    MDB_PHYSICAL_TABLE_EEDB_6_DATA,
    MDB_PHYSICAL_TABLE_EEDB_5_6_DATA,
    MDB_PHYSICAL_TABLE_EEDB_7_LL,
    MDB_PHYSICAL_TABLE_EEDB_7_DATA,
    MDB_PHYSICAL_TABLE_EEDB_8_LL,
    MDB_PHYSICAL_TABLE_EEDB_8_DATA,
    MDB_PHYSICAL_TABLE_EEDB_7_8_DATA,
    MDB_PHYSICAL_TABLE_ESEM,
    MDB_PHYSICAL_TABLE_EVSI,
    MDB_PHYSICAL_TABLE_EXEM_1,
    MDB_PHYSICAL_TABLE_EXEM_2,
    MDB_PHYSICAL_TABLE_EXEM_3,
    MDB_PHYSICAL_TABLE_EXEM_4,
    MDB_PHYSICAL_TABLE_RMEP,

    MDB_NOF_PHYSICAL_TABLES,
} mdb_physical_table_e;


#endif 
