#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id: $
LOCALDIR = src/appl/diag/phymod

include ${SDK}/make/Make.config

lib = libdiag_phymod

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
