
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_L3_H_

#define _DNX_DATA_MAX_L3_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_L3_EGR_POINTED_FIRST_EGR_POINTED_ID (1)


#define DNX_DATA_MAX_L3_FEC_NOF_FECS    (786432)


#define DNX_DATA_MAX_L3_FEC_FIRST_VALID_FEC_ECMP_ID (1)


#define DNX_DATA_MAX_L3_FEC_MAX_FEC_ID_FOR_SINGLE_DHB_CLUSTER_PAIR_GRANULARITY (524287)


#define DNX_DATA_MAX_L3_FEC_MAX_FEC_ID_FOR_DOUBLE_DHB_CLUSTER_PAIR_GRANULARITY (786431)


#define DNX_DATA_MAX_L3_FEC_MAX_DEFAULT_FEC (131071)


#define DNX_DATA_MAX_L3_FEC_BANK_SIZE   (26214)


#define DNX_DATA_MAX_L3_FEC_BANK_SIZE_ROUND_UP (26216)


#define DNX_DATA_MAX_L3_FEC_MAX_NOF_SUPER_FECS_PER_BANK (13108)


#define DNX_DATA_MAX_L3_FEC_NOF_PHYSICAL_FECS_PER_BANK (8192)


#define DNX_DATA_MAX_L3_FEC_BANK_NOF_PHYSICAL_ROWS (8192)


#define DNX_DATA_MAX_L3_FEC_SUPER_FEC_SIZE (150)


#define DNX_DATA_MAX_L3_FEC_MAX_NOF_BANKS (30)


#define DNX_DATA_MAX_L3_FEC_FIRST_BANK_WITHOUT_ID_ALLOC (4)


#define DNX_DATA_MAX_L3_FEC_FIRST_SHARED_BANK (3)


#define DNX_DATA_MAX_L3_FEC_MAX_SUPER_FEC_ID (393215)


#define DNX_DATA_MAX_L3_FEC_NOF_FEC_DIRECTIONS (1)


#define DNX_DATA_MAX_L3_FEC_FEC_Z_MAX_FEC_ID (0)


#define DNX_DATA_MAX_L3_FEC_NOF_DPC_FEC_DB (0)


#define DNX_DATA_MAX_L3_FEC_NOF_FEC_DBS_ALL_CORES (3)


#define DNX_DATA_MAX_L3_FEC_NOF_FEC_RESULT_TYPES (7)


#define DNX_DATA_MAX_L3_FER_MDB_GRANULARITY_RATIO (2)


#define DNX_DATA_MAX_L3_FER_NOF_FER_SORT_TO_MDB_TABLE_MUXES (0)


#define DNX_DATA_MAX_L3_FER_MAX_NOF_SORTING_BLOCKS_PER_FEC_DB (0)


#define DNX_DATA_MAX_L3_SOURCE_ADDRESS_SOURCE_ADDRESS_TABLE_SIZE (256)


#define DNX_DATA_MAX_L3_SOURCE_ADDRESS_CUSTOM_SA_USE_DUAL_HOMING (1)


#define DNX_DATA_MAX_L3_VRF_NOF_VRF     (65536)


#define DNX_DATA_MAX_L3_VRF_NOF_VRF_IPV6 (16384)


#define DNX_DATA_MAX_L3_ROUTING_ENABLERS_ROUTING_ENABLE_VECTOR_LENGTH (64)


#define DNX_DATA_MAX_L3_ROUTING_ENABLERS_ROUTING_ENABLE_ACTION_SUPPORT (0)


#define DNX_DATA_MAX_L3_ROUTING_ENABLERS_ROUTING_ENABLE_ACTION_PROFILE_SIZE (0)


#define DNX_DATA_MAX_L3_ROUTING_ENABLERS_ROUTING_ENABLE_INDICATION_NOF_BITS_PER_LAYER (1)


#define DNX_DATA_MAX_L3_ROUTING_ENABLERS_ROUTING_ENABLE_NOF_PROFILES_PER_LAYER (2)


#define DNX_DATA_MAX_L3_ROUTING_ENABLERS_ROUTING_ENABLED_ACTION_PROFILE_ID (0)


#define DNX_DATA_MAX_L3_RIF_MAX_NOF_RIFS (131072)


#define DNX_DATA_MAX_L3_FWD_FLP_FRAGMENT_SUPPORT (1)


#define DNX_DATA_MAX_L3_FWD_MAX_MC_GROUP_LPM (131071)


#define DNX_DATA_MAX_L3_FWD_MAX_MC_GROUP_EM (524287)


#define DNX_DATA_MAX_L3_FWD_NOF_MY_MAC_PREFIXES (64)


#define DNX_DATA_MAX_L3_FWD_COMPRESSED_SIP_SVL_SIZE (16)


#define DNX_DATA_MAX_L3_FWD_NOF_COMPRESSED_SVL_SIP (65536)


#define DNX_DATA_MAX_L3_FWD_LPM_STRENGTH_PROFILES_SUPPORT (1)


#define DNX_DATA_MAX_L3_FWD_NOF_LPM_STRENGTH_PROFILES (8)


#define DNX_DATA_MAX_L3_FWD_COMPRESSED_SIP_IVL_SIZE (13)


#define DNX_DATA_MAX_L3_FWD_NOF_COMPRESSED_IVL_SIP (8192)


#define DNX_DATA_MAX_L3_ECMP_GROUP_SIZE_MULTIPLY_AND_DIVIDE_NOF_BITS (11)


#define DNX_DATA_MAX_L3_ECMP_GROUP_SIZE_CONSISTENT_NOF_BITS (8)


#define DNX_DATA_MAX_L3_ECMP_GROUP_SIZE_NOF_BITS (11)


#define DNX_DATA_MAX_L3_ECMP_MAX_GROUP_SIZE (2048)


#define DNX_DATA_MAX_L3_ECMP_NOF_ECMP_BASIC_MODE (32768)


#define DNX_DATA_MAX_L3_ECMP_TOTAL_NOF_ECMP (40960)


#define DNX_DATA_MAX_L3_ECMP_MAX_ECMP_BASIC_MODE (32767)


#define DNX_DATA_MAX_L3_ECMP_MAX_ECMP_EXTENDED_MODE (40959)


#define DNX_DATA_MAX_L3_ECMP_NOF_EXTENDED_ECMP_PER_FAILOVER_BANK (512)


#define DNX_DATA_MAX_L3_ECMP_NOF_FAILOVER_BANKS_PER_EXTENDED_ECMP_BANK (4)


#define DNX_DATA_MAX_L3_ECMP_NOF_GROUP_PROFILES_PER_HIERARCHY (1024)


#define DNX_DATA_MAX_L3_ECMP_MEMBER_TABLE_NOF_ROWS_SIZE_IN_BITS (13)


#define DNX_DATA_MAX_L3_ECMP_MEMBER_TABLE_ADDRESS_SIZE_IN_BITS (9)


#define DNX_DATA_MAX_L3_ECMP_ECMP_BANK_SIZE (2048)


#define DNX_DATA_MAX_L3_ECMP_NOF_ECMP_BANKS_BASIC (16)


#define DNX_DATA_MAX_L3_ECMP_NOF_ECMP_BANKS_EXTENDED (4)


#define DNX_DATA_MAX_L3_ECMP_NOF_ECMP   (40960)


#define DNX_DATA_MAX_L3_ECMP_PROFILE_ID_SIZE (10)


#define DNX_DATA_MAX_L3_ECMP_PROFILE_ID_OFFSET (0)


#define DNX_DATA_MAX_L3_ECMP_TUNNEL_PRIORITY_SUPPORT (1)


#define DNX_DATA_MAX_L3_ECMP_NOF_TUNNEL_PRIORITY_MAP_PROFILES (4)


#define DNX_DATA_MAX_L3_ECMP_TUNNEL_PRIORITY_FIELD_WIDTH (5)


#define DNX_DATA_MAX_L3_ECMP_TUNNEL_PRIORITY_INDEX_FIELD_WIDTH (3)


#define DNX_DATA_MAX_L3_ECMP_CONSISTENT_MEM_ROW_SIZE_IN_BITS (32)


#define DNX_DATA_MAX_L3_ECMP_CONSISTENT_BANK_SIZE_IN_BITS (8192)


#define DNX_DATA_MAX_L3_ECMP_ECMP_SMALL_CONSISTENT_GROUP_NOF_ENTRIES (128)


#define DNX_DATA_MAX_L3_ECMP_ECMP_SMALL_CONSISTENT_GROUP_ENTRY_SIZE_IN_BITS (4)


#define DNX_DATA_MAX_L3_ECMP_NOF_CONSISTENT_RESOURCES (512)


#define DNX_DATA_MAX_L3_VIP_ECMP_NOF_VIP_ECMP (4096)


#define DNX_DATA_MAX_L3_VIP_ECMP_MAX_VIP_ECMP_TABLE_SIZE (16384)


#define DNX_DATA_MAX_L3_WCMP_GROUP_SIZE_NOF_BITS (0)


#define DNX_DATA_MAX_L3_WCMP_MAX_MEMBER_WEIGHT (0)


#define DNX_DATA_MAX_L3_WCMP_MEMBER_WEIGHT_QUANT_FACTOR (0)


#define DNX_DATA_MAX_L3_SOURCE_ADDRESS_ETHERNET_NOF_MYMAC_PREFIXES (64)


#define DNX_DATA_MAX_L3_VRRP_NOF_PROTOCOL_GROUPS (4)


#define DNX_DATA_MAX_L3_VRRP_NOF_TCAM_ENTRIES (32)


#define DNX_DATA_MAX_L3_VRRP_NOF_VSI_TCAM_ENTRIES (16)


#define DNX_DATA_MAX_L3_VRRP_NOF_TCAM_ENTRIES_USED_BY_EXEM (4)


#define DNX_DATA_MAX_L3_VRRP_EXEM_VRID_IPV4_TCAM_INDEX (16)


#define DNX_DATA_MAX_L3_VRRP_EXEM_VRID_IPV6_TCAM_INDEX (17)


#define DNX_DATA_MAX_L3_VRRP_EXEM_DEFAULT_TCAM_INDEX (18)


#define DNX_DATA_MAX_L3_VRRP_EXEM_DEFAULT_TCAM_INDEX_MSB (19)


#define DNX_DATA_MAX_L3_VRRP_VRRP_DEFAULT_NUM_ENTRIES (12)


#define DNX_DATA_MAX_L3_VRRP_IS_MULTIPLE_MY_MAC_DA_TABLE_PER_MSB_BIT (1)


#define DNX_DATA_MAX_L3_VRRP_IS_MAPPED_PP_PORT_USED (1)


#define DNX_DATA_MAX_L3_VRRP_NOF_DBS    (2)




#endif 

