
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_EGR_QUEUING_V1_H_

#define _DNX_DATA_MAX_EGR_QUEUING_V1_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_NOF_EGR_INTERFACES (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_INTERFACES_NOF_CHANNELIZED_EGR_INTERFACES (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_NOF_EGR_QUEUES (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_NOF_EGR_PRIORITIES (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_PS_QUEUE_RESOLUTION (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_RCY_RESERVED_QUEUE (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_NOF_QUEUE_PAIRS (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_EGRESS_QUEUES_TOTAL_NOF_EGR_QUEUES (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_SCHEDULING_NOF_INTERFACE_CALENDAR_SLOTS (0)


#define DNX_DATA_MAX_EGR_QUEUING_V1_SHAPING_DEFAULT_MAX_BURST (0)




#endif 

