
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __DNX_ALGO_FIELD_ACTION_LAYOUT_H__
#define __DNX_ALGO_FIELD_ACTION_LAYOUT_H__

#include <include/soc/dnxc/swstate/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int dnx_algo_field_action_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(DNX_ALGO_FIELD_ACTION_MODULE_ID, 0),
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__FIELD_GROUP,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__PLACE_IN_FG,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__MASK_IS_ALLOC,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__FES_STATE__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__PRIORITY,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF2__CONTEXT_STATE__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__FIELD_GROUP,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__PLACE_IN_FG,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__MASK_IS_ALLOC,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__FES_STATE__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__PRIORITY,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__IPMF3__CONTEXT_STATE__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__FIELD_GROUP,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__PLACE_IN_FG,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__MASK_IS_ALLOC,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__FES_STATE__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__PRIORITY,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__EPMF__CONTEXT_STATE__LAST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__FIRST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__FIRST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__FIRST - 1,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__IS_PRIORITY_POSITION,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__LAST,
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__LAST_SUB = DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW__FEM__LAST - 1,
    
    DNX_SW_STATE_DNX_ALGO_FIELD_ACTION_SW_NOF_PARAMS,
} dnxc_sw_state_layout_dnx_algo_field_action_node_id_e;

#endif 
