
/*
 * 
 This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 
 Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef DBAL_DEFINES_HW_ENTITY_GROUPS_H_INCLUDED

#define DBAL_DEFINES_HW_ENTITY_GROUPS_H_INCLUDED


typedef enum
{
    DBAL_HW_ENTITY_GROUP_EMPTY,
    
    DBAL_HW_ENTITY_GROUP_CDBM_PARSER_SOFT_STAGE_TCAM,
    
    DBAL_HW_ENTITY_GROUP_CDBM_RX_RMC_PRD_THRESHOLDS,
    
    DBAL_HW_ENTITY_GROUP_CDB_PARSER_SOFT_STAGE_TCAM,
    
    DBAL_HW_ENTITY_GROUP_CDB_RX_RMC_PRD_THRESHOLDS,
    DBAL_HW_ENTITY_GROUP_CDUM_MAC_RESET,
    
    DBAL_HW_ENTITY_GROUP_CDUM_PARSER_SOFT_STAGE_TCAM,
    
    DBAL_HW_ENTITY_GROUP_CDUM_RX_FIFO_RANGE_RMC,
    
    DBAL_HW_ENTITY_GROUP_CDUM_RX_PORT_MAP_TO_RMC,
    
    DBAL_HW_ENTITY_GROUP_CDUM_RX_RMC_MAP,
    
    DBAL_HW_ENTITY_GROUP_CDUM_RX_RMC_PRD_THRESHOLDS,
    DBAL_HW_ENTITY_GROUP_CDU_MAC_RESET,
    
    DBAL_HW_ENTITY_GROUP_CDU_PARSER_SOFT_STAGE_TCAM,
    
    DBAL_HW_ENTITY_GROUP_CDU_RX_FIFO_RANGE_RMC,
    
    DBAL_HW_ENTITY_GROUP_CDU_RX_PORT_MAP_TO_RMC,
    
    DBAL_HW_ENTITY_GROUP_CDU_RX_RMC_MAP,
    
    DBAL_HW_ENTITY_GROUP_CDU_RX_RMC_PRD_THRESHOLDS,
    
    DBAL_HW_ENTITY_GROUP_CFG_STAT_METADATA_CURRENT_PROTOCOL_TYPE,
    
    DBAL_HW_ENTITY_GROUP_CLU_PARSER_SOFT_STAGE_TCAM,
    DBAL_HW_ENTITY_GROUP_CLU_PM_RESET,
    
    DBAL_HW_ENTITY_GROUP_CLU_RX_FIFO_RANGE_RMC,
    
    DBAL_HW_ENTITY_GROUP_CLU_RX_PORT_MAP_TO_PARSER_PROFILE,
    
    DBAL_HW_ENTITY_GROUP_CLU_RX_PORT_MAP_TO_RMC,
    
    DBAL_HW_ENTITY_GROUP_CLU_RX_RMC_MAP,
    
    DBAL_HW_ENTITY_GROUP_CLU_RX_RMC_PRD_THRESHOLDS,
    
    DBAL_HW_ENTITY_GROUP_ECI_FAP_GLOBAL_SYS_HEADER_CFG,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_ACCEPTABLE_FRAME_TYPE_TABLE,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_CFG_FHEI_MODEL,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_CFG_FHEI_UPPER_LAYER_TYPE_MAP,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_CFG_INLIF_DP_PROFILE_MAP,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_CFG_INLIF_PROFILE_MAPPED_IN_JERICHO_MODE,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_DEVICE_CFG_PARSER_ENABLERS,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_FHEI_MPLS_COMMAND,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_FHEI_MPLS_UPPER_LAYER_PROTOCOL_TO_PES_MAPPING_TABLE,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_FWD_LAYER_ADDITIONAL_INFO_TO_IP_MC_ELIGIBLE_MAPPING,
    DBAL_HW_ENTITY_GROUP_EGRESS_INGRESS_TRAPPED_BY_FHEI,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_IVEC_TABLE,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_JERICHO_COMPATIBLE_REGISTERS,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_LIF_EXTENSION_FORMAT_CFG,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_PARSING_START_TYPE_MAPPING_TABLE,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_PCP_DEI_DP_MAPPING_TABLE,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_PPH_BASE_FIELDS_CG_2,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_SYSTEM_HEADERS_CG_1,
    
    DBAL_HW_ENTITY_GROUP_EGRESS_UTILITY_REGS,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ADDITIONAL_HEADERS_MAP_TABLE_0,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ADDITIONAL_HEADERS_MAP_TABLE_1,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ADDITIONAL_HEADERS_MAP_TABLE_2,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ADDITIONAL_HEADERS_PROFILE_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ARR_PREFIX_GROUP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_FWD_MAP_PROTOCOL_QOS,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_LAYER_PROTOCOL_IPV4,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_LAYER_PROTOCOL_IPV6,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_LAYER_PROTOCOL_MPLS,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_MAP_FWD_LAYER_PROTOCOL,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_MAP_REMARK_PROFILE_QOS_DP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_MAP_REMARK_PROFILE_QOS_VAR,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_MPLS_CONTROL_WORD,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_PIPE_MAPPED_TTL_VARIABLE_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_REMARK_PROTOCOL_PROFILE,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CFG_TTL_MODEL_PIPE_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_CURRENT_NEXT_PROTOCOL_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_DEFAULT_SVTAG,
    DBAL_HW_ENTITY_GROUP_ETPP_ENC_DEVICE_CONFIGS,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ENC_QOS_VAR_TYPE_MAPPING,
    
    DBAL_HW_ENTITY_GROUP_ETPP_ETHERNET_FWD_CODE,
    
    DBAL_HW_ENTITY_GROUP_ETPP_FORWARD_CODE_IPV4_OR_IPV6,
    
    DBAL_HW_ENTITY_GROUP_ETPP_LAYER_NWK_QOS_TABLE,
    
    DBAL_HW_ENTITY_GROUP_ETPP_MTU_MAP_TABLE,
    
    DBAL_HW_ENTITY_GROUP_ETPP_NEW_QOS_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_NWK_QOS_IDX_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_PROTOCOL_TYPE_COMPRESSED_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_QOS_DP_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_QOS_MODEL_MAPPING_TABLE,
    
    DBAL_HW_ENTITY_GROUP_ETPP_SIT_PROFILE_MAP_TABLE,
    DBAL_HW_ENTITY_GROUP_ETPP_SOURCE_ADRS_MAP,
    
    DBAL_HW_ENTITY_GROUP_ETPP_VLAN_EDIT_PROFILE_MAP_TABLE,
    
    DBAL_HW_ENTITY_GROUP_ETTP_MAIN_HEADER_MAP_TABLE,
    
    DBAL_HW_ENTITY_GROUP_FABRIC_DTQ_BASE_ADDRESS,
    
    DBAL_HW_ENTITY_GROUP_FABRIC_MESH_TOPOLOGY_LINKS_STATUS_INFO,
    
    DBAL_HW_ENTITY_GROUP_FEU_PARSER_SOFT_STAGE_TCAM,
    
    DBAL_HW_ENTITY_GROUP_GLOBAL_TPID_0_1_REGS,
    
    DBAL_HW_ENTITY_GROUP_GLOBAL_TPID_2_3_REGS,
    
    DBAL_HW_ENTITY_GROUP_GLOBAL_TPID_4_5_REGS,
    
    DBAL_HW_ENTITY_GROUP_GLOBAL_TPID_6_REGS,
    
    DBAL_HW_ENTITY_GROUP_ILU_PARSER_SOFT_STAGE_TCAM,
    
    DBAL_HW_ENTITY_GROUP_ILU_RX_HRF_PRD_THRESHOLDS,
    
    DBAL_HW_ENTITY_GROUP_INDIRECT_FORCE_BUBBLE_IGNORE_PULSE_WIDTH,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CFG_PROTOCOL_IS_ETH,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CFG_PROTOCOL_IS_IPV4,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CFG_PROTOCOL_IS_IPV6,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CFG_PROTOCOL_IS_MAC_IN_MAC,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CFG_PROTOCOL_IS_MPLS,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CS_INLIF_PROFILE_MAP_LSB,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_CS_INLIF_PROFILE_MAP_MSB,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_ETHERNET_TRAPS,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_ETHERNET_TRAP_ACTION_PROFILE_VECTOR,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_FWD_DOMAIN_CS_PROFILE_MAP,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_INITIAL_PCP_DEI_MAP_TYPE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_ITPP_GENERAL_CFG,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_LEARN_KEY_CONTEXT,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_LIF_PROFILE_ATTRIBUTES_1,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_LIF_TRAPS,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_LLVP_CLASSIFICATION_GROUP,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_MAP_PORT_TO_LEARN_LIF_VEC,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_MAP_PORT_TO_LEARN_LIF_VEC_HIGH,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_MAP_PORT_TO_LEARN_LIF_VEC_LOW,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_MAP_PORT_TO_MEMBERSHIP_IF_VEC,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_MAP_VRID_TO_IP_VERSION,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_MPLS_SPECIAL_LABEL_ATTRIBUTES,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_STATISTICS_INFO,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_STAT_OBJ_PROFILE_ATTR,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_TERMINATION_PROFILE_TABLE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VD_TO_VLAN_CLASSIFICATION_PROFILE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VLAN_EDIT_COMMAND_TABLE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VLAN_EDIT_PCP_DEI_MAP,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VLAN_MEMBERSHIP_IF_ATTR,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VLAN_MEMBERSHIP_TABLE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VRID_MY_MAC_MAPPING,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VRID_MY_MAC_TCAM,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VSI_PROFILE_ATTRIBUTES_0,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VSI_PROFILE_ATTRIBUTES_1,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_ACTION_PROFILE_ACCEPTABLE_FRAME_TYPES,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_ETHERNET_TERMINATION_ACTION,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_MPLS_LABEL_RANGE_PROFILE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_MPLS_LABEL_RANGE_TABLE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_QOS_PROPAG_PROFILE_MAPPING,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_SPECIAL_LABELS_PROFILE,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_SPECIAL_LABEL_VALUES,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_TRAP_STRENGTHS_3,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_TRAP_STRENGTHS_4,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_TRAP_STRENGTHS_5,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_TRAP_STRENGTHS_6,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_TRAP_STRENGTHS_7,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_TRAP_STRENGTHS_8,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_VLAN_DOMAIN_ATTRIBUTES,
    
    DBAL_HW_ENTITY_GROUP_INGRESS_VTT_VLAN_RANGE_COMPRESSION_TABLE,
    
    DBAL_HW_ENTITY_GROUP_ITPP_MAPPING_FWD_INFO_TO_EN_TERM,
    
    DBAL_HW_ENTITY_GROUP_ITPP_SNIFF_SYS_HEADER_INFO,
    
    DBAL_HW_ENTITY_GROUP_MACSEC_ISEC_MGMTRULE_CFG_DA_TYPE,
    
    DBAL_HW_ENTITY_GROUP_MAPPING_QUEUE_TYPE_TO_SNIFF_PACKET,
    
    DBAL_HW_ENTITY_GROUP_MAP_STATISTIC_OBJECT_TABLE,
    
    DBAL_HW_ENTITY_GROUP_OAMP_PE_GEN_MEM,
    
    DBAL_HW_ENTITY_GROUP_OAMP_PE_PROG_TCAM,
    
    DBAL_HW_ENTITY_GROUP_SCH_IF_CALENDAR,
    
    DBAL_HW_ENTITY_GROUP_TDM_EGRESS_CONFIGURATION,
    
    DBAL_HW_ENTITY_GROUP_VTT_MPLS_PREPROCESSING_BOS_OR_TTL_TRAP,
    DBAL_NOF_HW_ENTITY_GROUPS
} dbal_hw_entity_group_e;


#endif 
