# $Id: Makefile,v 1.1 2011/10/25 21:07:56 srajesh Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id: Makefile,v 1.1 2011/10/25 21:07:56 sanjayg Exp $
# Makefile for Katana2 SOC driver Library
#

LOCALDIR = src/soc/esw/saber2

include ${SDK}/make/Make.config

lib = libsoc_saber2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

