# $Id$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM Firebolt6 driver Library
#

LOCALDIR = src/bcm/esw/firebolt6

include ${SDK}/make/Make.config

lib = libfirebolt6

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
