/*! \file bcmdrd_custom_config.h
 *
 * This config file defines all compilation-time specifications for
 * the SDKLT BCMDRD.
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef __BCMDRD_CUSTOM_CONFIG_H__
#define __BCMDRD_CUSTOM_CONFIG_H__

#ifdef  BCMDRD_CONFIG_INCLUDE_BCM56880
#define BCMDRD_CONFIG_INCLUDE_BCM56881 BCMDRD_CONFIG_INCLUDE_BCM56880
#define BCMDRD_CONFIG_INCLUDE_BCM56883 BCMDRD_CONFIG_INCLUDE_BCM56880
#endif

#ifdef  BCMDRD_CONFIG_INCLUDE_BCM56990
#define BCMDRD_CONFIG_INCLUDE_BCM56991 BCMDRD_CONFIG_INCLUDE_BCM56990
#endif

#ifdef  BCMDRD_CONFIG_INCLUDE_BCM56990_Ax
#define BCMDRD_CONFIG_INCLUDE_BCM56991_Ax BCMDRD_CONFIG_INCLUDE_BCM56990_Ax
#endif

#ifdef  BCMDRD_CONFIG_INCLUDE_BCM56990_Bx
#define BCMDRD_CONFIG_INCLUDE_BCM56991_Bx BCMDRD_CONFIG_INCLUDE_BCM56990_Bx
#endif

#ifdef  BCMDRD_CONFIG_INCLUDE_BCM56996
#define BCMDRD_CONFIG_INCLUDE_BCM56997 BCMDRD_CONFIG_INCLUDE_BCM56996
#endif

#ifdef  BCMDRD_CONFIG_INCLUDE_BCM56780
#define BCMDRD_CONFIG_INCLUDE_BCM56782 BCMDRD_CONFIG_INCLUDE_BCM56780
#define BCMDRD_CONFIG_INCLUDE_BCM56784 BCMDRD_CONFIG_INCLUDE_BCM56780
#define BCMDRD_CONFIG_INCLUDE_BCM56786 BCMDRD_CONFIG_INCLUDE_BCM56780
#define BCMDRD_CONFIG_INCLUDE_BCM56788 BCMDRD_CONFIG_INCLUDE_BCM56780
#endif

#endif /* __BCMDRD_CUSTOM_CONFIG_H__ */
