# $Id: Makefile,v 1.1 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
# 

LOCALDIR = src/appl/cpudb

include ${SDK}/make/Make.config

lib = libcpudb

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
