# $Id: Makefile,v 1.1 2004/02/24 07:46:30 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# 

LOCALDIR = src/appl/stktask

include ${SDK}/make/Make.config

lib = libstktask

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
