# $Id: Makefile,v 1.1.8.2 2013/04/03 06:44:49 ako Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# Makefile for Greyhound SOC driver Library
#

LOCALDIR = src/soc/esw/greyhound

include ${SDK}/make/Make.config

lib = libsoc_greyhound

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

