
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_VLAN_H_

#define _DNX_DATA_MAX_VLAN_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_TAG_FORMATS (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_TAG_FORMATS
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_TAG_FORMATS (32)


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_INGRESS_VLAN_EDIT_PROFILES (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_INGRESS_VLAN_EDIT_PROFILES
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_INGRESS_VLAN_EDIT_PROFILES (64)


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_EGRESS_VLAN_EDIT_PROFILES (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_EGRESS_VLAN_EDIT_PROFILES
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_EGRESS_VLAN_EDIT_PROFILES (64)


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_RANGE_ENTRIES (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_RANGE_ENTRIES
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_RANGE_ENTRIES (32)


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_RANGES_PER_ENTRY (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_RANGES_PER_ENTRY
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_NOF_VLAN_RANGES_PER_ENTRY (32)


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_EGRESS_TPID_OUTER_PACKET_INDEX (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_EGRESS_TPID_OUTER_PACKET_INDEX
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_EGRESS_TPID_OUTER_PACKET_INDEX (14)


#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_EGRESS_TPID_INNER_PACKET_INDEX (1)

#undef DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_EGRESS_TPID_INNER_PACKET_INDEX
#define DNX_DATA_MAX_VLAN_VLAN_TRANSLATE_EGRESS_TPID_INNER_PACKET_INDEX (15)





#endif 

