
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_QOS_H_

#define _DNX_DATA_MAX_QOS_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROFILES (1024)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_OPCODE_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_OPCODE_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_OPCODE_PROFILES (256)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_PROFILES (4)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_POLICER_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_POLICER_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_POLICER_PROFILES (4)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_VLAN_PCP_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_VLAN_PCP_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_VLAN_PCP_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PROFILES (32)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_POLICER_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_POLICER_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_POLICER_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_MPLS_PHP_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_MPLS_PHP_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_MPLS_PHP_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_OPCODE_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_OPCODE_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_OPCODE_PROFILES (32)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PHP_OPCODE_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PHP_OPCODE_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_PHP_OPCODE_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_TTL_PIPE_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_TTL_PIPE_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_TTL_PIPE_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROPAGATION_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROPAGATION_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_PROPAGATION_PROFILES (8)


#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_OPCODE_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_OPCODE_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_INGRESS_ECN_OPCODE_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_NETWORK_QOS_PIPE_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_NETWORK_QOS_PIPE_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_NETWORK_QOS_PIPE_PROFILES (64)


#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_COS_PROFILES (1)

#undef DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_COS_PROFILES
#define DNX_DATA_MAX_QOS_QOS_NOF_EGRESS_COS_PROFILES (16)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_PRIORITY (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_PRIORITY
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_PRIORITY (7)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EXP (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EXP
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EXP (7)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DSCP (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DSCP
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DSCP (255)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_CFI (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_CFI
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_CFI (1)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_TC (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_TC
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_TC (7)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DP (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DP
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_DP (3)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_ECN (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_ECN
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_ECN (3)


#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EGRESS_POLICER_OFFSET (1)

#undef DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EGRESS_POLICER_OFFSET
#define DNX_DATA_MAX_QOS_QOS_PACKET_MAX_EGRESS_POLICER_OFFSET (7)


#define DNX_DATA_MAX_QOS_QOS_MAX_INT_MAP_ID (1)

#undef DNX_DATA_MAX_QOS_QOS_MAX_INT_MAP_ID
#define DNX_DATA_MAX_QOS_QOS_MAX_INT_MAP_ID (255)


#define DNX_DATA_MAX_QOS_QOS_MAX_EGRESS_VAR (1)

#undef DNX_DATA_MAX_QOS_QOS_MAX_EGRESS_VAR
#define DNX_DATA_MAX_QOS_QOS_MAX_EGRESS_VAR (255)


#define DNX_DATA_MAX_QOS_QOS_ECN_BITS_WIDTH (1)

#undef DNX_DATA_MAX_QOS_QOS_ECN_BITS_WIDTH
#define DNX_DATA_MAX_QOS_QOS_ECN_BITS_WIDTH (3)


#define DNX_DATA_MAX_QOS_QOS_EEI_MPLS_TTL_PROFILE (1)

#undef DNX_DATA_MAX_QOS_QOS_EEI_MPLS_TTL_PROFILE
#define DNX_DATA_MAX_QOS_QOS_EEI_MPLS_TTL_PROFILE (30)


#define DNX_DATA_MAX_QOS_FEATURE_PHB_RM_FFC_BITS_WIDTH (1)

#undef DNX_DATA_MAX_QOS_FEATURE_PHB_RM_FFC_BITS_WIDTH
#define DNX_DATA_MAX_QOS_FEATURE_PHB_RM_FFC_BITS_WIDTH (23)





#endif 

