
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_STACK_H_

#define _DNX_DATA_MAX_STACK_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX family only!"
#endif


#define DNX_DATA_MAX_STACK_GENERAL_NOF_TM_DOMAINS_MAX (1)

#undef DNX_DATA_MAX_STACK_GENERAL_NOF_TM_DOMAINS_MAX
#define DNX_DATA_MAX_STACK_GENERAL_NOF_TM_DOMAINS_MAX (13)


#define DNX_DATA_MAX_STACK_GENERAL_DEST_PORT_BASE_QUEUE_MIN (1)

#undef DNX_DATA_MAX_STACK_GENERAL_DEST_PORT_BASE_QUEUE_MIN
#define DNX_DATA_MAX_STACK_GENERAL_DEST_PORT_BASE_QUEUE_MIN (262080)


#define DNX_DATA_MAX_STACK_GENERAL_DEST_PORT_BASE_QUEUE_MAX (1)

#undef DNX_DATA_MAX_STACK_GENERAL_DEST_PORT_BASE_QUEUE_MAX
#define DNX_DATA_MAX_STACK_GENERAL_DEST_PORT_BASE_QUEUE_MAX (262143)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_MIN (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_MIN
#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_MIN (0)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_MAX (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_MAX
#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_MAX (256)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_ALL (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_ALL
#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_TRUNK_RESOLVE_ENTRY_ALL (268435455)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_MIN (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_MIN
#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_MIN (0)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_MAX (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_MAX
#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_MAX (4)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_ALL (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_ALL
#define DNX_DATA_MAX_STACK_GENERAL_LAG_STACK_FEC_RESOLVE_ENTRY_ALL (268435455)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_DOMAIN_MIN (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_DOMAIN_MIN
#define DNX_DATA_MAX_STACK_GENERAL_LAG_DOMAIN_MIN (0)


#define DNX_DATA_MAX_STACK_GENERAL_LAG_DOMAIN_MAX (1)

#undef DNX_DATA_MAX_STACK_GENERAL_LAG_DOMAIN_MAX
#define DNX_DATA_MAX_STACK_GENERAL_LAG_DOMAIN_MAX (64)


#define DNX_DATA_MAX_STACK_GENERAL_TRUNK_ENTRY_PER_TMD_BIT_NUM (1)

#undef DNX_DATA_MAX_STACK_GENERAL_TRUNK_ENTRY_PER_TMD_BIT_NUM
#define DNX_DATA_MAX_STACK_GENERAL_TRUNK_ENTRY_PER_TMD_BIT_NUM (8)





#endif 

