# $Id: Makefile,v 1.2 2011/08/21 07:19:53 bhanup Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/dnx/time

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxtime

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
