#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/init

include ${SDK}/make/Make.config

lib = libbcm_dnxinit

subdirs = auto_generated


include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

