# $Id: Makefile,v 1.2 2004/03/09 00:36:44 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/customer

include ${SDK}/make/Make.config

lib = libcustomer

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
