# 
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
# Makefile for Tomahawk2 SOC driver Library
#

LOCALDIR = src/soc/esw/tomahawk2

include ${SDK}/make/Make.config

SUBDIR_TOMAHAWK2_FLEXPORT = flexport

subdirs := $(SUBDIR_TOMAHAWK2_FLEXPORT)

lib = libsoc_tomahawk2

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

