
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_MACSEC_H_

#define _DNX_DATA_MAX_MACSEC_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif


#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_NOF
#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_NOF (10)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_IN_CORE_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_IN_CORE_NOF
#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_IN_CORE_NOF (5)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_PORTS_IN_MACSEC_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_PORTS_IN_MACSEC_NOF
#define DNX_DATA_MAX_MACSEC_GENERAL_PORTS_IN_MACSEC_NOF (32)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOF
#define DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOF (4)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOT_ZERO_VERIFY (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOT_ZERO_VERIFY
#define DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOT_ZERO_VERIFY (1)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_TX_THRESHOLD (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_TX_THRESHOLD
#define DNX_DATA_MAX_MACSEC_GENERAL_TX_THRESHOLD (3)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_MAX_DEPTH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_MAX_DEPTH
#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_MAX_DEPTH (3232)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_HW_DEPTH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_HW_DEPTH
#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_HW_DEPTH (4096)

#endif 

#define DNX_DATA_MAX_MACSEC_GENERAL_ASSOCIATION_NUMBER_FULL_RANGE_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_GENERAL_ASSOCIATION_NUMBER_FULL_RANGE_NOF
#define DNX_DATA_MAX_MACSEC_GENERAL_ASSOCIATION_NUMBER_FULL_RANGE_NOF (4)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_FLOW_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_FLOW_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_FLOW_NOF (1536)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_POLICY_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_POLICY_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_POLICY_NOF (1024)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_SECURE_ASSOC_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_SECURE_ASSOC_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_SECURE_ASSOC_NOF (2048)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_UDF_NOF_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_UDF_NOF_BITS
#define DNX_DATA_MAX_MACSEC_INGRESS_UDF_NOF_BITS (440)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_MGMT_RULE_EXACT_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_MGMT_RULE_EXACT_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_MGMT_RULE_EXACT_NOF (8)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_TPID_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_TPID_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_TPID_NOF (5)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_CPU_FLEX_MAP_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_CPU_FLEX_MAP_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_CPU_FLEX_MAP_NOF (16)

#endif 

#define DNX_DATA_MAX_MACSEC_INGRESS_SC_TCAM_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_INGRESS_SC_TCAM_NOF
#define DNX_DATA_MAX_MACSEC_INGRESS_SC_TCAM_NOF (1280)

#endif 

#define DNX_DATA_MAX_MACSEC_EGRESS_SECURE_ASSOC_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_EGRESS_SECURE_ASSOC_NOF
#define DNX_DATA_MAX_MACSEC_EGRESS_SECURE_ASSOC_NOF (1024)

#endif 

#define DNX_DATA_MAX_MACSEC_EGRESS_SOFT_EXPIRY_THRESHOLD_PROFILES_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_EGRESS_SOFT_EXPIRY_THRESHOLD_PROFILES_NOF
#define DNX_DATA_MAX_MACSEC_EGRESS_SOFT_EXPIRY_THRESHOLD_PROFILES_NOF (4)

#endif 

#define DNX_DATA_MAX_MACSEC_EGRESS_AN_BIT_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_EGRESS_AN_BIT_NOF
#define DNX_DATA_MAX_MACSEC_EGRESS_AN_BIT_NOF (2)

#endif 

#define DNX_DATA_MAX_MACSEC_WRAPPER_MACSEC_ARB_PORTS_NOF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_WRAPPER_MACSEC_ARB_PORTS_NOF
#define DNX_DATA_MAX_MACSEC_WRAPPER_MACSEC_ARB_PORTS_NOF (384)

#endif 

#define DNX_DATA_MAX_MACSEC_WRAPPER_PER_PORT_SPEED_MAX_MBPS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_WRAPPER_PER_PORT_SPEED_MAX_MBPS
#define DNX_DATA_MAX_MACSEC_WRAPPER_PER_PORT_SPEED_MAX_MBPS (400000)

#endif 

#define DNX_DATA_MAX_MACSEC_WRAPPER_WRAPPER_SPEED_MAX_MBPS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_WRAPPER_WRAPPER_SPEED_MAX_MBPS
#define DNX_DATA_MAX_MACSEC_WRAPPER_WRAPPER_SPEED_MAX_MBPS (800000)

#endif 

#define DNX_DATA_MAX_MACSEC_WRAPPER_FRAMER_PORTS_OFFSET (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_MACSEC_WRAPPER_FRAMER_PORTS_OFFSET
#define DNX_DATA_MAX_MACSEC_WRAPPER_FRAMER_PORTS_OFFSET (64)

#endif 




#endif 

