
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_SYNCE_H_

#define _DNX_DATA_MAX_SYNCE_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_PLLS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_NOF_PLLS

#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_PLLS (2)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_NIF_DIV_MIN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_NIF_DIV_MIN

#define DNX_DATA_MAX_SYNCE_GENERAL_NIF_DIV_MIN (2)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_NIF_DIV_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_NIF_DIV_MAX

#define DNX_DATA_MAX_SYNCE_GENERAL_NIF_DIV_MAX (2)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_FABRIC_DIV_MIN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_FABRIC_DIV_MIN

#define DNX_DATA_MAX_SYNCE_GENERAL_FABRIC_DIV_MIN (2)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_FABRIC_DIV_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_FABRIC_DIV_MAX

#define DNX_DATA_MAX_SYNCE_GENERAL_FABRIC_DIV_MAX (16)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_CLK_BLOCKS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_NOF_CLK_BLOCKS

#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_CLK_BLOCKS (18)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_FABRIC_CLK_BLOCKS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_NOF_FABRIC_CLK_BLOCKS

#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_FABRIC_CLK_BLOCKS (24)

#endif 


#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_MAS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_SYNCE_GENERAL_NOF_MAS

#define DNX_DATA_MAX_SYNCE_GENERAL_NOF_MAS (2)

#endif 




#endif 

