
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_FAILOVER_H_

#define _DNX_DATA_MAX_FAILOVER_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_EGRESS_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_EGRESS_SIZE

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_EGRESS_SIZE (131072)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_INGRESS_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_INGRESS_SIZE

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_INGRESS_SIZE (16384)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_INGRESS_MC_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_INGRESS_MC_SIZE

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_INGRESS_MC_SIZE (0)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_SIZE

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_SIZE (262144)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_EGR_NO_PROTECTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_EGR_NO_PROTECTION

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_EGR_NO_PROTECTION (0)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_ING_NO_PROTECTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_ING_NO_PROTECTION

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_ING_NO_PROTECTION (0)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_ING_MC_NO_PROTECTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_ING_MC_NO_PROTECTION

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_ING_MC_NO_PROTECTION (0)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_NO_PROTECTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_NO_PROTECTION

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_NO_PROTECTION (262143)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_FACILITY_PROTECTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_FACILITY_PROTECTION

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_FACILITY_PROTECTION (262142)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_NOF_FEC_PATH_SELECT_BANKS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_NOF_FEC_PATH_SELECT_BANKS

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_NOF_FEC_PATH_SELECT_BANKS (16)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_NOF_FEC_PATH_SELECT_BANKS_IN_HW (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_NOF_FEC_PATH_SELECT_BANKS_IN_HW

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_NOF_FEC_PATH_SELECT_BANKS_IN_HW (16)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_BANK_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_BANK_SIZE

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_FEC_BANK_SIZE (16384)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_IN_LIF_PROTECTION_POINTER_NOF_MSB (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_IN_LIF_PROTECTION_POINTER_NOF_MSB

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_IN_LIF_PROTECTION_POINTER_NOF_MSB (2)

#endif 


#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_IN_LIF_PROTECTION_POINTER_NOF_LSB (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_FAILOVER_PATH_SELECT_IN_LIF_PROTECTION_POINTER_NOF_LSB

#define DNX_DATA_MAX_FAILOVER_PATH_SELECT_IN_LIF_PROTECTION_POINTER_NOF_LSB (12)

#endif 




#endif 

