
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_TUNNEL_H_

#define _DNX_DATA_MAX_TUNNEL_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_TUNNEL_UDP_NOF_UDP_PORTS_PROFILES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_UDP_NOF_UDP_PORTS_PROFILES

#define DNX_DATA_MAX_TUNNEL_UDP_NOF_UDP_PORTS_PROFILES (8)

#endif 


#define DNX_DATA_MAX_TUNNEL_UDP_FIRST_UDP_PORTS_PROFILE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_UDP_FIRST_UDP_PORTS_PROFILE

#define DNX_DATA_MAX_TUNNEL_UDP_FIRST_UDP_PORTS_PROFILE (1)

#endif 


#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_UDP_TUNNEL_TYPE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_UDP_TUNNEL_TYPE

#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_UDP_TUNNEL_TYPE (0)

#endif 


#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GENEVE_TUNNEL_TYPE_SUPPORTED (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GENEVE_TUNNEL_TYPE_SUPPORTED

#define DNX_DATA_MAX_TUNNEL_TUNNEL_TYPE_GENEVE_TUNNEL_TYPE_SUPPORTED (1)

#endif 


#define DNX_DATA_MAX_TUNNEL_TCAM_TABLE_HAS_RAW_UDP_TUNNEL_TYPE_IS_2ND_PASS_KEY_FIELDS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_TCAM_TABLE_HAS_RAW_UDP_TUNNEL_TYPE_IS_2ND_PASS_KEY_FIELDS

#define DNX_DATA_MAX_TUNNEL_TCAM_TABLE_HAS_RAW_UDP_TUNNEL_TYPE_IS_2ND_PASS_KEY_FIELDS (0)

#endif 


#define DNX_DATA_MAX_TUNNEL_FEATURE_TUNNEL_ROUTE_DISABLE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_FEATURE_TUNNEL_ROUTE_DISABLE

#define DNX_DATA_MAX_TUNNEL_FEATURE_TUNNEL_ROUTE_DISABLE (1)

#endif 


#define DNX_DATA_MAX_TUNNEL_FEATURE_DEDICATED_FODO_TO_VNI_TABLE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_FEATURE_DEDICATED_FODO_TO_VNI_TABLE

#define DNX_DATA_MAX_TUNNEL_FEATURE_DEDICATED_FODO_TO_VNI_TABLE (0)

#endif 


#define DNX_DATA_MAX_TUNNEL_FEATURE_DIP_IDX_TYPE_IS_LIF_FIELD (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_FEATURE_DIP_IDX_TYPE_IS_LIF_FIELD

#define DNX_DATA_MAX_TUNNEL_FEATURE_DIP_IDX_TYPE_IS_LIF_FIELD (0)

#endif 


#define DNX_DATA_MAX_TUNNEL_FEATURE_FODO_TO_VNI_ENTRY_CREATED_BY_VLAN_API (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_FEATURE_FODO_TO_VNI_ENTRY_CREATED_BY_VLAN_API

#define DNX_DATA_MAX_TUNNEL_FEATURE_FODO_TO_VNI_ENTRY_CREATED_BY_VLAN_API (1)

#endif 


#define DNX_DATA_MAX_TUNNEL_FEATURE_HAS_FLOW_GPORT_TO_TUNNEL_TYPE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_TUNNEL_FEATURE_HAS_FLOW_GPORT_TO_TUNNEL_TYPE

#define DNX_DATA_MAX_TUNNEL_FEATURE_HAS_FLOW_GPORT_TO_TUNNEL_TYPE (0)

#endif 




#endif 

