
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_PVT_H_

#define _DNX_DATA_MAX_PVT_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_PVT_GENERAL_NOF_PVT_MONITORS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_NOF_PVT_MONITORS

#define DNX_DATA_MAX_PVT_GENERAL_NOF_PVT_MONITORS (9)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_PVT_BASE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_BASE

#define DNX_DATA_MAX_PVT_GENERAL_PVT_BASE (43410000)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_PVT_FACTOR (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_FACTOR

#define DNX_DATA_MAX_PVT_GENERAL_PVT_FACTOR (53504)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_PVT_MON_CONTROL_SEL_NOF_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_PVT_MON_CONTROL_SEL_NOF_BITS

#define DNX_DATA_MAX_PVT_GENERAL_PVT_MON_CONTROL_SEL_NOF_BITS (5)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_THERMAL_DATA_NOF_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_THERMAL_DATA_NOF_BITS

#define DNX_DATA_MAX_PVT_GENERAL_THERMAL_DATA_NOF_BITS (11)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_VOL_SEL (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_SEL

#define DNX_DATA_MAX_PVT_GENERAL_VOL_SEL (10)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_VOL_FACTOR (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_FACTOR

#define DNX_DATA_MAX_PVT_GENERAL_VOL_FACTOR (1020)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_VOL_MULTIPLE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_MULTIPLE

#define DNX_DATA_MAX_PVT_GENERAL_VOL_MULTIPLE (5)

#endif 


#define DNX_DATA_MAX_PVT_GENERAL_VOL_DIVISOR (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_PVT_GENERAL_VOL_DIVISOR

#define DNX_DATA_MAX_PVT_GENERAL_VOL_DIVISOR (4096)

#endif 




#endif 

