
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_IQS_H_

#define _DNX_DATA_MAX_IQS_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_IQS_CREDIT_MAX_CREDIT_BALANCE_THRESHOLD (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_MAX_CREDIT_BALANCE_THRESHOLD

#define DNX_DATA_MAX_IQS_CREDIT_MAX_CREDIT_BALANCE_THRESHOLD (131071)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_MAX_WORTH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_MAX_WORTH

#define DNX_DATA_MAX_IQS_CREDIT_MAX_WORTH (65535)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_BACK_MIN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_BACK_MIN

#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_BACK_MIN (0)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_BACK_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_BACK_MAX

#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_BACK_MAX (262143)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_EMPTY_MIN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_EMPTY_MIN

#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_EMPTY_MIN (-131071)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_EMPTY_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_EMPTY_MAX

#define DNX_DATA_MAX_IQS_CREDIT_SATISIFIED_EMPTY_MAX (131071)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MIN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MIN

#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MIN (-262143)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MAX

#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MAX (262143)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MULT_MIN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MULT_MIN

#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MULT_MIN (16)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MULT_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MULT_MAX

#define DNX_DATA_MAX_IQS_CREDIT_HUNGRY_MULT_MAX (4096)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_NOF_BW_LEVELS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_NOF_BW_LEVELS

#define DNX_DATA_MAX_IQS_CREDIT_NOF_BW_LEVELS (4)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_CREDIT_FC_ON_TH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_CREDIT_FC_ON_TH

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_CREDIT_FC_ON_TH (30)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_CREDIT_FC_OFF_TH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_CREDIT_FC_OFF_TH

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_CREDIT_FC_OFF_TH (20)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_BYTE_FC_ON_TH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_BYTE_FC_ON_TH

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_BYTE_FC_ON_TH (1000)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_BYTE_FC_OFF_TH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_BYTE_FC_OFF_TH

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_BYTE_FC_OFF_TH (800)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_EIR_CREDIT_FC_TH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_EIR_CREDIT_FC_TH

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_EIR_CREDIT_FC_TH (8191)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_EIR_BYTE_FC_TH (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_EIR_BYTE_FC_TH

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_EIR_BYTE_FC_TH (2097151)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_NOF_BE_CLASSES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_NOF_BE_CLASSES

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_NOF_BE_CLASSES (3)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_MAX_BE_WEIGHT (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_MAX_BE_WEIGHT

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_MAX_BE_WEIGHT (31)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_MAX_BURST_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_MAX_BURST_MAX

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_MAX_BURST_MAX (63)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_SHP_CRDT_RATE_MLTP (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_SHP_CRDT_RATE_MLTP

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_SHP_CRDT_RATE_MLTP (8)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_FMQ_SHP_CRDT_RATE_DELTA (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_FMQ_SHP_CRDT_RATE_DELTA

#define DNX_DATA_MAX_IQS_CREDIT_FMQ_SHP_CRDT_RATE_DELTA (7)

#endif 


#define DNX_DATA_MAX_IQS_CREDIT_MAX_RATE_PROFILE_PRESET_GBPS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_CREDIT_MAX_RATE_PROFILE_PRESET_GBPS

#define DNX_DATA_MAX_IQS_CREDIT_MAX_RATE_PROFILE_PRESET_GBPS (4096)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_LOW_DELAY_DEQ_BYTES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_LOW_DELAY_DEQ_BYTES

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_LOW_DELAY_DEQ_BYTES (16)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_CREDIT_BALANCE_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_CREDIT_BALANCE_MAX

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_CREDIT_BALANCE_MAX (131072)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_CREDIT_BALANCE_RESOLUTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_CREDIT_BALANCE_RESOLUTION

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_CREDIT_BALANCE_RESOLUTION (4096)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_S2D_CREDIT_BALANCE_MAX (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_S2D_CREDIT_BALANCE_MAX

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_S2D_CREDIT_BALANCE_MAX (2097152)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_S2D_CREDIT_BALANCE_RESOLUTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_S2D_CREDIT_BALANCE_RESOLUTION

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_S2D_CREDIT_BALANCE_RESOLUTION (65536)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_SRAM_TO_FABRIC_CREDIT_LFSR_THR (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_SRAM_TO_FABRIC_CREDIT_LFSR_THR

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_SRAM_TO_FABRIC_CREDIT_LFSR_THR (112)

#endif 


#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_SRAM_TO_FABRIC_CREDIT_LFSR_MASK (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DEQ_DEFAULT_SRAM_TO_FABRIC_CREDIT_LFSR_MASK

#define DNX_DATA_MAX_IQS_DEQ_DEFAULT_SRAM_TO_FABRIC_CREDIT_LFSR_MASK (3)

#endif 


#define DNX_DATA_MAX_IQS_DQCQ_MAX_NOF_CONTEXTS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DQCQ_MAX_NOF_CONTEXTS

#define DNX_DATA_MAX_IQS_DQCQ_MAX_NOF_CONTEXTS (5)

#endif 


#define DNX_DATA_MAX_IQS_DQCQ_NOF_PRIORITIES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DQCQ_NOF_PRIORITIES

#define DNX_DATA_MAX_IQS_DQCQ_NOF_PRIORITIES (8)

#endif 


#define DNX_DATA_MAX_IQS_DBAL_IPT_COUNTERS_NOF_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_DBAL_IPT_COUNTERS_NOF_BITS

#define DNX_DATA_MAX_IQS_DBAL_IPT_COUNTERS_NOF_BITS (32)

#endif 


#define DNX_DATA_MAX_IQS_FLUSH_BYTES_UNITS_TO_SEND (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_IQS_FLUSH_BYTES_UNITS_TO_SEND

#define DNX_DATA_MAX_IQS_FLUSH_BYTES_UNITS_TO_SEND (128)

#endif 




#endif 

