
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ESB_H_

#define _DNX_DATA_MAX_ESB_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_ESB_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_ESB_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_ESB_QUEUES (459)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ETH_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ETH_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ETH_QUEUES (128)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_ETH_LP_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_ETH_LP_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_ETH_LP_QUEUES (64)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ILKN_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ILKN_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_NIF_ILKN_QUEUES (16)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_ILKN_TDM_OR_LP_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_ILKN_TDM_OR_LP_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_ILKN_TDM_OR_LP_QUEUES (4)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_FLEXE_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_FLEXE_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_FLEXE_QUEUES (320)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_SPECIAL_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_SPECIAL_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_SPECIAL_QUEUES (10)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_RESERVED_QUEUES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_RESERVED_QUEUES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_RESERVED_QUEUES (2)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_FPC (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_FPC

#define DNX_DATA_MAX_ESB_GENERAL_NOF_FPC (4)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_BUFFERS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_BUFFERS

#define DNX_DATA_MAX_ESB_GENERAL_TOTAL_NOF_BUFFERS (8192)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_LEN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_LEN

#define DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_LEN (12288)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_WINDOW_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_WINDOW_SIZE

#define DNX_DATA_MAX_ESB_GENERAL_MUX_CAL_WINDOW_SIZE (64)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NIF_CREDITS_RESOLUTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NIF_CREDITS_RESOLUTION

#define DNX_DATA_MAX_ESB_GENERAL_NIF_CREDITS_RESOLUTION (48)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NIF_CREDITS_RATE_RESOLUTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NIF_CREDITS_RATE_RESOLUTION

#define DNX_DATA_MAX_ESB_GENERAL_NIF_CREDITS_RATE_RESOLUTION (50000)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_FPC_PTR_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_FPC_PTR_SIZE

#define DNX_DATA_MAX_ESB_GENERAL_FPC_PTR_SIZE (11)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_BUFFERS_PER_FPC (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_BUFFERS_PER_FPC

#define DNX_DATA_MAX_ESB_GENERAL_NOF_BUFFERS_PER_FPC (2048)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_L1_MUX_CAL_RES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_L1_MUX_CAL_RES

#define DNX_DATA_MAX_ESB_GENERAL_L1_MUX_CAL_RES (5000)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_TM_EGR_QUEUING_MUX_CAL_RES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_TM_EGR_QUEUING_MUX_CAL_RES

#define DNX_DATA_MAX_ESB_GENERAL_TM_EGR_QUEUING_MUX_CAL_RES (7500)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_FLEXE_QUEUE_ID_BASE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_FLEXE_QUEUE_ID_BASE

#define DNX_DATA_MAX_ESB_GENERAL_FLEXE_QUEUE_ID_BASE (128)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_ILKN_QUEUE_ID_BASE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_ILKN_QUEUE_ID_BASE

#define DNX_DATA_MAX_ESB_GENERAL_ILKN_QUEUE_ID_BASE (384)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_ILKN_TDM_OR_LP_QUEUE_ID_BASE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_ILKN_TDM_OR_LP_QUEUE_ID_BASE

#define DNX_DATA_MAX_ESB_GENERAL_ILKN_TDM_OR_LP_QUEUE_ID_BASE (456)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_ETH_LP_QUEUE_ID_BASE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_ETH_LP_QUEUE_ID_BASE

#define DNX_DATA_MAX_ESB_GENERAL_ETH_LP_QUEUE_ID_BASE (392)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_NOF_EGR_TXI_INTERFACES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_NOF_EGR_TXI_INTERFACES

#define DNX_DATA_MAX_ESB_GENERAL_NOF_EGR_TXI_INTERFACES (464)

#endif 


#define DNX_DATA_MAX_ESB_GENERAL_MAX_QUEUE_TO_MAP_TO_NIF (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_GENERAL_MAX_QUEUE_TO_MAP_TO_NIF

#define DNX_DATA_MAX_ESB_GENERAL_MAX_QUEUE_TO_MAP_TO_NIF (458)

#endif 


#define DNX_DATA_MAX_ESB_DBAL_PM_INTERNAL_PORT_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_DBAL_PM_INTERNAL_PORT_SIZE

#define DNX_DATA_MAX_ESB_DBAL_PM_INTERNAL_PORT_SIZE (7)

#endif 


#define DNX_DATA_MAX_ESB_DBAL_COUNTER_CONFIG_MASK_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_DBAL_COUNTER_CONFIG_MASK_SIZE

#define DNX_DATA_MAX_ESB_DBAL_COUNTER_CONFIG_MASK_SIZE (9)

#endif 


#define DNX_DATA_MAX_ESB_DBAL_CREDIT_SIZE_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_DBAL_CREDIT_SIZE_BITS

#define DNX_DATA_MAX_ESB_DBAL_CREDIT_SIZE_BITS (15)

#endif 


#define DNX_DATA_MAX_ESB_DBAL_TXI_IRDY_THRESH_SIZE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESB_DBAL_TXI_IRDY_THRESH_SIZE

#define DNX_DATA_MAX_ESB_DBAL_TXI_IRDY_THRESH_SIZE (15)

#endif 




#endif 

