
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_UTILEX_H_

#define _DNX_DATA_MAX_UTILEX_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_DSS_PER_CORE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_DSS_PER_CORE

#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_DSS_PER_CORE (500)

#endif 


#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_HASHS_PER_CORE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_HASHS_PER_CORE

#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_HASHS_PER_CORE (200)

#endif 


#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_LISTS_PER_CORE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_LISTS_PER_CORE

#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_LISTS_PER_CORE (200)

#endif 


#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_MULTIS_PER_CORE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_MULTIS_PER_CORE

#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_MULTIS_PER_CORE (200)

#endif 


#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_RES_TAG_BITMAPS_PER_CORE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_RES_TAG_BITMAPS_PER_CORE

#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_RES_TAG_BITMAPS_PER_CORE (800)

#endif 


#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_DEFRAGMENTED_CHUNKS_PER_CORE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_DEFRAGMENTED_CHUNKS_PER_CORE

#define DNX_DATA_MAX_UTILEX_COMMON_MAX_NOF_DEFRAGMENTED_CHUNKS_PER_CORE (4)

#endif 




#endif 

