
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_ESEM_H_

#define _DNX_DATA_MAX_ESEM_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_ACCESSES (3)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_APP_DI_ID_SIZE_IN_BITS (4)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NO_ACTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NO_ACTION

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NO_ACTION (0)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_NATIVE (1)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_AC (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_AC

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_DEFAULT_AC (8)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_SFLOW_SAMPLE_INTERFACE (16)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_IP_TUNNEL_NO_ACTION (60)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_ESEM_CMD_DEFAULT_PROFILES (5)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS_SIZE_IN_BITS (6)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_NOF_CMDS (64)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_MIN_SIZE_FOR_ESEM_CMD (2)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4 (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_GRE_ANY_IPV4 (0)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_VXLAN_GPE (52)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_ARR_PREFIX_IP_TUNNEL_NO_ACTION (60)

#endif 


#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_PREDEFINE_ALLOCATIONS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_PREDEFINE_ALLOCATIONS

#define DNX_DATA_MAX_ESEM_ACCESS_CMD_ESEM_CMD_PREDEFINE_ALLOCATIONS (0)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_NATIVE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_NATIVE

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_NATIVE (12)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_AC (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_AC

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_AC (13)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_SFLOW_SAMPLE_INTERFACE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_SFLOW_SAMPLE_INTERFACE

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_SFLOW_SAMPLE_INTERFACE (14)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_DUAL_HOMING (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_DUAL_HOMING

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_DEFAULT_DUAL_HOMING (15)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_VXLAN (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_VXLAN

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_VXLAN (11)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_PROFILES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_PROFILES

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_PROFILES (16)

#endif 


#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_ALLOCABLE_PROFILES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_ALLOCABLE_PROFILES

#define DNX_DATA_MAX_ESEM_DEFAULT_RESULT_PROFILE_NOF_ALLOCABLE_PROFILES (8)

#endif 




#endif 

