
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_REGRESSION_H_

#define _DNX_DATA_MAX_REGRESSION_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_EXT_LOOPS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_EXT_LOOPS

#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_EXT_LOOPS (23)

#endif 


#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_P2P_LINKS (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_P2P_LINKS

#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_P2P_LINKS (2)

#endif 


#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_FORCE_ER (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_FORCE_ER

#define DNX_DATA_MAX_REGRESSION_DVAPI_TOPOLOGY_NOF_PM_FORCE_ER (1)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_CGM_VOQ_PROFILES (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_CGM_VOQ_PROFILES

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_CGM_VOQ_PROFILES (10)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QQST_TABLE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QQST_TABLE

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QQST_TABLE (8)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QDCT_TABLE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QDCT_TABLE

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ECGM_QDCT_TABLE (8)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE (5)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE_2 (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE_2

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_ERPP_PER_PP_PORT_TABLE_2 (4)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_IVSI (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_IVSI

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_IVSI (9)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EVSI (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EVSI

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EVSI (25)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_GLEM (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_GLEM

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_GLEM (16372)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EXEM_1 (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EXEM_1

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_EXEM_1 (10142)

#endif 


#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_FEC_1 (1)
#ifdef BCM_DNX2_SUPPORT

#undef DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_FEC_1

#define DNX_DATA_MAX_REGRESSION_SER_PARAMETERS_MDB_FEC_1 (0)

#endif 




#endif 

