# $Id: Makefile,v 1.1 2008/01/22 19:05:15 gskul Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/triumph2

include ${SDK}/make/Make.config

lib = libtriumph2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
