/* 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
*/

#ifndef __SOC_PPC_API_TRAP_MGMT_INCLUDED__

#define __SOC_PPC_API_TRAP_MGMT_INCLUDED__




#include <soc/dpp/SAND/Utils/sand_header.h>

#include <soc/dpp/SAND/Management/sand_general_macros.h>
#include <soc/dpp/SAND/Management/sand_error_code.h>

#include <soc/dpp/PPC/ppc_api_general.h>
#include <soc/dpp/PPC/ppc_api_frwrd_mact.h>
#include <soc/dpp/TMC/tmc_api_packet.h>






#define  SOC_PPC_TRAP_ACTION_PKT_DISCARD_ID (0xffffffff)

#define  SOC_PPC_TRAP_ACTION_PKT_CPU_ID (0xffffffff - 1)

#define  SOC_PPC_TRAP_ACTION_PKT_DISCARD_AND_LEARN_ID (0xffffffff - 2)

#define  SOC_PPC_TRAP_EG_NO_ACTION       (0xffffffff)

#define  SOC_PPC_TRAP_EVENT_BUFF_MAX_SIZE (5)


#define SOC_PPC_TRAP_CODE_NOF_USER_DEFINED_SNOOPS_FOR_TM   (16)


#define SOC_PPC_TRAP_CODE_USER_DEFINED_DROP_TRAP   \
            (SOC_PPC_TRAP_CODE_USER_DEFINED_LAST - 0 - SOC_PPC_TRAP_CODE_NOF_USER_DEFINED_SNOOPS_FOR_TM) 
#define SOC_PPC_TRAP_CODE_USER_DEFINED_DFLT_TRAP   \
            (SOC_PPC_TRAP_CODE_USER_DEFINED_LAST - 1 - SOC_PPC_TRAP_CODE_NOF_USER_DEFINED_SNOOPS_FOR_TM) 


#define PPC_TRAP_MGMT_SNP_STRENGTH_MAX                  (3)
#define PPC_EG_TRAP_SHIFT_SIZE                          (16)

#define MAX_NUM_OF_CORES_EGRESS_ACTION_PROFILE          (2)










#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX  (0x0<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX  (0x1<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX  (0x2<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX  (0x3<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX  (0x4<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX  (0x5<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX  (0x6<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX  (0x7<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX  (0x8<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX  (0x9<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX  (0xa<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_PMF_PREFIX   (0xb<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX   (0xc<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_IHP_TIMNA_PREFIX (0xd<<4)
#define SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX      ((0xf<<4) | (0x0 << 3))
#define SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_PREFIX     ((0xf<<4) | (0x1 << 3))
#define SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX       (0xe<<4)




typedef enum
{
  
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP0                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP1                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP2                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_SA_DROP3                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_TE_TRANSPLANT                    = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_TE_UNKNOWN_TUNNEL                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_TRANSPLANT                       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PBP_LEARN_SNOOP                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_SA_AUTHENTICATION_FAILED             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_PORT_NOT_PERMITTED                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_UNEXPECTED_VID                       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xa,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_SA_MULTICAST                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xb,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_SA_EQUALS_DA                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xc,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_8021X                                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xd,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE0               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xe,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE1               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR0_PREFIX + 0xf,

  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE2               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ACCEPTABLE_FRAME_TYPE3               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_MY_ARP                               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ARP                                  = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_IGMP_MEMBERSHIP_QUERY                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_IGMP_REPORT_LEAVE_MSG                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_IGMP_UNDEFINED                       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ICMPV6_MLD_MC_LISTENER_QUERY         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x7,

  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR1_PREFIX + 0x8, 
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP0                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 0,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP1                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 1,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP2                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 2,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP3                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 3,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP4                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 4,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP5                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 5,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP6                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 6,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_TRAP7                    = SOC_PPC_TRAP_CODE_INTERNAL_LLR_RESERVED_MC_PREFIX + 7,

  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ICMPV6_MLD_REPORT_DONE_MSG           = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_ICMPV6_MLD_UNDEFINED                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_DHCP_SERVER                          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_DHCP_CLIENT                          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_DHCPV6_SERVER                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_DHCPV6_CLIENT                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP0                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP1                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP2                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_LLR_GENERAL_TRAP3                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_LLR2_PREFIX + 0x9,

    
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_PORT_NOT_VLAN_MEMBER                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_HEADER_SIZE_ERR                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_B_MAC_AND_LEARN_NULL              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_B_DA_UNKNOWN_I_SID                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_IP_DISABLE                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_MPLS_DISABLE              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_ARP                       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_MAC_AND_UNKNOWN_L3                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_IP_COMP_MC_INVALID_IP                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_VERSION                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_INVALID_TTL                    = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xa,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_CHBH                           = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xb,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_NO_REVERSE_FEC                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xc,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_CITE                           = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xd,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_ILLEGAL_INNER_MC               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xe,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_DISABLE_BRIDGE_IF_DESIGNTAED   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT0_PREFIX + 0xf,

  
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_INVALID_LIF_ENTRY                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_UNEXPECTED_BOS                    = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_UNEXPECTED_NO_BOS                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_TTL_0                             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_TTL_1                             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_CONTROL_WORD_TRAP                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_CONTROL_WORD_DROP                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_STP_STATE_BLOCK                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_STP_STATE_LEARN                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_ILLEGEL_PFC                            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_IPV4_TUNNEL_TERMINATION_AND_FRAGMENTED = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xA,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_ETHER_IP_VERSION_ERROR                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xB,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_PROTECTION_PATH_INVALID                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xC,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_TRILL_NO_ADJACENT                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xD,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MPLS_TERMINATION_ERR                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xE,
  SOC_PPC_TRAP_CODE_INTERNAL_VTT_MY_B_MAC_MC_CONTINUE                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT1_PREFIX + 0xF,

  
  SOC_PPC_TRAP_CODE_INTERNAL_MPLS_ILLEGAL_LABEL                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_INNER_IP_COMP_MC_INVALID_IP_0              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_INNER_ETHERNET_MY_MAC_IP_DISABLED          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_VTT2_PREFIX + 0x8,

  
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_L2CP_PEER                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_L2CP_DROP                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_FL_IGMP_MEMBERSHIP_QUERY         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_FL_IGMP_REPORT_LEAVE_MSG         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_FL_IGMP_UNDEFINED                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_FL_ICMPV6_MLD_MC_LISTENER_QUERY  = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_FL_ICMPV6_MLD_REPORT_DONE        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ETH_FL_ICMPV6_MLD_UNDEFINED          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_VERSION_ERROR                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_CHECKSUM_ERROR                  = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_HEADER_LENGTH_ERROR             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xa,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_TOTAL_LENGTH_ERROR              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xb,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_TTL0                            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xc,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_HAS_OPTIONS                     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xd,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_TTL1                            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xe,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_SIP_EQUAL_DIP                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP0_PREFIX + 0xf,

  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_DIP_ZERO                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV4_SIP_IS_MC                       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_VERSION_ERROR                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_HOP_COUNT0                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_HOP_COUNT1                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_UNSPECIFIED_DESTINATION         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_LOOPBACK_ADDRESS                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_MULTICAST_SOURCE                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_NEXT_HEADER_NULL                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_UNSPECIFIED_SOURCE              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_LINK_DESTINATION          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xa,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_SITE_DESTINATION          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xb,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_LINK_SOURCE               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xc,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_LOCAL_SITE_SOURCE               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xd,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_IPV4_COMPATIBLE_DESTINATION     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xe,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_IPV4_MAPPED_DESTINATION         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP1_PREFIX + 0xf,

  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IPV6_MULTICAST_DESTINATION           = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_TTL0                            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_TTL1                            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TCP_SN_FLAGS_ZERO                    = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TCP_SN_ZERO_FLAGS_SET                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TCP_SYN_FIN                          = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TCP_EQUAL_PORTS                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TCP_FRAGMENT_INCOMPLETE_HEADER       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TCP_FRAGMENT_OFFSET_LT8              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_UDP_EQUAL_PORTS                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ICMP_DATA_GT_576                     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xa,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ICMP_FRAGMENTED                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xb,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_DROP0                             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xc,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_DROP1                             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xd,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_DROP2                             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xe,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_DROP3                             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP2_PREFIX + 0xf,

  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND0                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND1                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND2                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SA_NOT_FOUND3                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x3,

  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_UNKNOWN_LABEL                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_P2P_MISCONFIGURATION                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ARP                                  = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_FCF                                  = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x7,

  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX                     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP3_PREFIX + 0x8, 
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP0                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 0,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP1                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 1,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP2                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 2,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP3                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 3,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP4                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 4,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP5                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 5,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP6                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 6,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_TRAP7                      = SOC_PPC_TRAP_CODE_INTERNAL_FLP_IEEE_1588_PREFIX + 7,

  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ELK_ERROR                            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_ELK_REJECTED                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_LEVEL                                = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x2, 
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_SAME_INTERFACE                       = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TRILL_UNKNOWN_UC                     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_TRILL_UNKNOWN_MC                     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_UC_LOOSE_RPF_FAIL                    = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_DEFAULT_UCV6                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x7,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_DEFAULT_MCV6                         = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x8,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_P2P_NO_BOS                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0x9,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_CONTROL_WORD_TRAP               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xa,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_CONTROL_WORD_DROP               = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xb,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PASSIVE                              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xc, 
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_MPLS_P2P_MPLSX4                      = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xd,
  SOC_PPC_TRAP_CODE_INTERNAL_FLP_FABRIC_PROVIDED_SECURITY             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FLP4_PREFIX + 0xe,


  
  SOC_PPC_TRAP_CODE_INTERNAL_PMF_GENERAL                              = SOC_PPC_TRAP_CODE_INTERNAL_IHP_PMF_PREFIX + 0x0,


  
  SOC_PPC_TRAP_CODE_INTERNAL_FER_FACILITY_INVALID                     = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_FER_FEC_ENTRY_ACCESSED                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_FER_UC_STRICT_RPF_FAIL                   = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_FER_MC_EXPLICIT_RPF_FAIL                 = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_FER_MC_USE_SIP_AS_IS_RPF_FAIL            = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_FER_SIP_TRANSPLANT_DETECTION             = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_FER_ICMP_REDIRECT                        = SOC_PPC_TRAP_CODE_INTERNAL_IHP_FER_PREFIX  + 0x6,



  
  SOC_PPC_TRAP_CODE_INTERNAL_USER_OAMP                                = SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_USER_ETHERNET_OAM_ACCELERATED            = SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_USER_MPLS_OAM_ACCELERATED                = SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_USER_BFD_IP_OAM_TUNNEL_ACCELERATED       = SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_USER_BFD_PWE_OAM_ACCELERATED             = SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_USER_ETHERNET_OAM_UP_ACCELERATED         = SOC_PPC_TRAP_CODE_INTERNAL_USER_PREFIX     + 0x5,

  
  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_TRAP_VTT_VT                        =  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_TRAP_VTT_TT                        =  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_TRAP_FLP                           =  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_TRAP_PMF_1ST_PASS                  =  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_TRAP_PMF_2ND_PASS                  =  SOC_PPC_TRAP_CODE_INTERNAL_BLOCK_PREFIX + 0x4,
  
  
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_ETH_OAM                         =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x0,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_Y1731_O_MPLSTP                  =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x1,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_Y1731_O_PWE                     =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x2,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_BFD_O_IPV4                      =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x3,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_BFD_O_MPLS                      =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x4,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_BFD_O_PWE                       =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x5,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_BFDCC_O_MPLSTP                  =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x6,
  SOC_PPC_TRAP_CODE_INTERNAL_OAM_BFDCV_O_MPLSTP                  =  SOC_PPC_TRAP_CODE_INTERNAL_OAM_PREFIX + 0x7



} SOC_PPC_TRAP_CODE_INTERNAL;



typedef enum
{
  
  SOC_PPC_TRAP_MGMT_FTMH_DEST_EXT_MODE_NEVER,
  
  SOC_PPC_TRAP_MGMT_FTMH_DEST_EXT_MODE_MC,
  
  SOC_PPC_TRAP_MGMT_FTMH_DEST_EXT_MODE_ALWAYS
} SOC_PPC_TRAP_MGMT_FTMH_DEST_EXT_MODE;

typedef enum
{
  
  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_NORMAL,
  
  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_TRAP,
  
  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_SNOOP,
  
  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_IN_MIRROR,
  
  SOC_PPC_NOF_TRAP_MGMT_PKT_FRWRD_TYPES
} SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE;

typedef enum
{
  
  SOC_PPC_TRAP_SNOOP_ACTION_SIZE_64B = 0,
  
  SOC_PPC_TRAP_SNOOP_ACTION_SIZE_128B = 1,
  
  SOC_PPC_TRAP_SNOOP_ACTION_SIZE_FULL_PACKET = 2,
  
  SOC_PPC_NOF_TRAP_SNOOP_ACTION_SIZES = 3
}SOC_PPC_TRAP_SNOOP_ACTION_SIZE;

typedef enum
{
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_NONE = 0,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DEST = 0x1,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_TC = 0x2,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DP = 0x4,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_POLICER = 0x8,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_FRWRD_OFFSET = 0x10,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_CUD = 0x20,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DP_METER_CMD = 0x40,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_ALL = (int)0xFFFFFFFF,
  
  SOC_PPC_NOF_TRAP_ACTION_PROFILE_OVERWRITES_PB = 8,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DEST_EEI = 0x80,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DEST_OUTLIF = 0x100,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_FRWRD_TYPE = 0x200,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_DA_TYPE = 0x400,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_METER_0 = 0x800,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_METER_1 = 0x1000,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_COUNTER_0 = 0x2000,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_COUNTER_1 = 0x4000,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_PP_DSP = 0x8000,
  
  SOC_PPC_TRAP_ACTION_PROFILE_USE_ARR = 0x10000,
  
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_COS_PROFILE = 0x20000,
  
 SOC_PPC_NOF_TRAP_ACTION_PROFILE_OVERWRITES_ARAD = 21
}SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE;

typedef enum
{
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_NONE = 0,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_AGED_OUT = 1,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_LEARN = 2,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_TRANSPLANT = 3,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_REFRESH = 4,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_ACK = 5,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_RETRIEVE = 6,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_LIMIT_EXCEED = 7,
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE_CPU_REQ_FAIL = 8,
  
  SOC_PPC_NOF_TRAP_MACT_EVENT_TYPES = 9
}SOC_PPC_TRAP_MACT_EVENT_TYPE;


typedef enum
{
  
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_0,  
  
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_1,  
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_2, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_3, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_4, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_5, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_6, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_7, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_8, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_9, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_10, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_11, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_12, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_13, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_14, 
   
  SOC_PPC_TRAP_CODE_ETPP_FIELD_SNOOP_15, 
   
  SOC_PPC_TRAP_CODE_ETPP_OUT_VPORT_DISCARD,  
   
  SOC_PPC_TRAP_CODE_ETPP_STP_STATE_FAIL,  
   
  SOC_PPC_TRAP_CODE_ETPP_PROTECTION_PATH_UNEXPECTED,  
   
  SOC_PPC_TRAP_CODE_ETPP_VPORT_LOOKUP_FAIL, 
     
  SOC_PPC_TRAP_CODE_ETPP_MTU_FILTER,
  
  SOC_PPC_TRAP_CODE_ETPP_ACC_FRAME_TYPE,
  
  SOC_PPC_TRAP_CODE_ETPP_SPLIT_HORIZON,
  
  SOC_PPC_TRAP_CODE_ETPP_PORT_NOT_VLAN_MEMBER,
  
  SOC_PPC_NOF_TRAP_ETPP_TYPES_ARAD

}SOC_PPC_TRAP_ETPP_TYPE;




typedef enum
{
  
  SOC_PPC_TRAP_EG_TYPE_NONE = 0x0,
  
  SOC_PPC_TRAP_EG_TYPE_NO_VSI_TRANSLATION = 0x1,
  
  SOC_PPC_TRAP_EG_TYPE_VSI_MEMBERSHIP = 0x2,
  
  SOC_PPC_TRAP_EG_TYPE_ACC_FRM = 0x4,
  
  SOC_PPC_TRAP_EG_TYPE_HAIR_PIN = 0x8,
  
  SOC_PPC_TRAP_EG_TYPE_UNKNOWN_DA = 0x10,
  
  SOC_PPC_TRAP_EG_TYPE_SPLIT_HORIZON = 0x20,
  
  SOC_PPC_TRAP_EG_TYPE_PRIVATE_VLAN = 0x40,
  
  SOC_PPC_TRAP_EG_TYPE_TTL_SCOPE = 0x80,
  
  SOC_PPC_TRAP_EG_TYPE_MTU_VIOLATION = 0x100,
  
  SOC_PPC_TRAP_EG_TYPE_TRILL_TTL_0 = 0x200,
  
  SOC_PPC_TRAP_EG_TYPE_TRILL_SAME_INTERFACE = 0x400,
  
  SOC_PPC_TRAP_EG_TYPE_TRILL_BOUNCE_BACK = 0x800,
  
  SOC_PPC_TRAP_EG_TYPE_DSS_STACKING	= 0x1000,
  
  SOC_PPC_TRAP_EG_TYPE_LAG_MULTICAST = 0x2000,
  
  SOC_PPC_TRAP_EG_TYPE_EXCLUDE_SRC = 0x4000,
  
  SOC_PPC_TRAP_EG_TYPE_CFM_TRAP = 0x8000,
  
  SOC_PPC_TRAP_EG_TYPE_ALL = (int)0xFFFFFFFF,
  
  SOC_PPC_NOF_TRAP_EG_TYPES_PB = 15,
  
  SOC_PPC_TRAP_EG_TYPE_INVALID_OUT_PORT = (1 << PPC_EG_TRAP_SHIFT_SIZE), 
  
  SOC_PPC_TRAP_EG_TYPE_CNM_PACKET = (2 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_VERSION_ERROR  = (3 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_CHECKSUM_ERROR = (4 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_HEADER_LENGTH_ERROR = (5 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_TOTAL_LENGTH_ERROR = (6 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IP_TTL0 = (7 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IP_HAS_OPTIONS = (8 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IP_TTL1 = (9 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_SIP_EQUAL_DIP = (10 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_DIP_ZERO = (11 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV4_SIP_IS_MC = (12 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_UNSPECIFIED_DESTINATION = (13 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_LOOPBACK_ADDRESS = (14 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_MULTICAST_SOURCE = (15 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_UNSPECIFIED_SOURCE = (16 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_LINK_DESTINATION = (17 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_SITE_DESTINATION = (18 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_LINK_SOURCE = (19 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_LOCAL_SITE_SOURCE = (20 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_IPV4_COMPATIBLE_DESTINATION = (21 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_IPV4_MAPPED_DESTINATION = (22 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_MULTICAST_DESTINATION = (23 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_IPV6_HOP_BY_HOP  = (24 << PPC_EG_TRAP_SHIFT_SIZE),
  
  SOC_PPC_TRAP_EG_TYPE_HIGHEST_ARAD  = SOC_PPC_TRAP_EG_TYPE_IPV6_HOP_BY_HOP,

  SOC_PPC_NOF_TRAP_EG_TYPES_ARAD = 39
  
}SOC_PPC_TRAP_EG_TYPE;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  SOC_PPC_TRAP_MGMT_FTMH_DEST_EXT_MODE dest_ext_mode;
  
  uint8 lb_ext_en;
  
  uint8 internal_eep_ext;
  
  uint8 stacking_enabled;
  
  uint8 tdm_enabled;
  
  uint32 user_header_size;
  
  SOC_TMC_PKT_PACKET_RECV_MODE recv_mode;
} SOC_PPC_TRAP_MGMT_PACKET_PARSE_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint8 is_oam_dest;
  
  SOC_PPC_FRWRD_DECISION_INFO frwrd_dest;
  
  uint8 add_vsi;
  
  uint32 vsi_shift;

} SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 counter_select;
  
  uint32 counter_id;

} SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 meter_select;
  
  uint32 meter_id;
  
  uint32 meter_command;

} SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 ethernet_police_id;

} SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  SOC_SAND_PP_TC tc;
  
  SOC_SAND_PP_DP dp;
} SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint8 enable_learning;
  
  uint8 is_trap;
  
  uint8 is_control;
  
  uint32 frwrd_offset_index;
  
  SOC_TMC_PKT_FRWRD_TYPE frwrd_type;
  
  int32 frwrd_offset_bytes_fix;
  
  SOC_SAND_PP_ETHERNET_DA_TYPE da_type;

} SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 strength;
  
  uint32 tunnel_termination_strength;
  
  uint32 bitmap_mask;
  
  SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO dest_info;
  
  SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO cos_info;
  
  SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO count_info;
  
  SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO meter_info;
  
  SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO policing_info;
  
  SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO processing_info;

} SOC_PPC_TRAP_FRWRD_ACTION_PROFILE_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 strength;
  
  uint32 tunnel_termination_strength;
   
  uint32 snoop_cmnd;

} SOC_PPC_TRAP_SNOOP_ACTION_PROFILE_INFO;

 
typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR

  
  uint32 cud;

  
  uint8 dsp_ptr;

  
  uint8 cos_profile;

  
  uint8 mirror_profile;

} SOC_PPC_TRAP_EG_ACTION_HDR_DATA;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 bitmap_mask;
  
  SOC_PPC_TM_PORT out_tm_port;
   
  SOC_PPC_TM_PORT out_tm_port_arr[MAX_NUM_OF_CORES_EGRESS_ACTION_PROFILE];
  
  SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO cos_info;
  
  uint32 cud;

  
  SOC_PPC_TRAP_EG_ACTION_HDR_DATA header_data;

  
  SOC_PPC_TRAP_EG_ACTION_HDR_DATA header_data_arr[MAX_NUM_OF_CORES_EGRESS_ACTION_PROFILE];

} SOC_PPC_TRAP_EG_ACTION_PROFILE_INFO;


typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  uint32 mirror_cmd;
  
  uint32 mirror_strength;
  
  uint32 mirror_enable;
  
  uint32 fwd_strength;
  
  uint32 fwd_enable;

} SOC_PPC_TRAP_ETPP_INFO;



typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR
  
  SOC_PPC_TRAP_MACT_EVENT_TYPE type;
  
  SOC_PPC_FRWRD_MACT_ENTRY_KEY key;
  
  SOC_PPC_FRWRD_MACT_ENTRY_VALUE val;
  
  uint8 is_part_of_lag;

} SOC_PPC_TRAP_MACT_EVENT_INFO;

typedef struct
{
  SOC_SAND_MAGIC_NUM_VAR

  
  
   SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE frwrd_type;
  
   uint8 is_trapped;
  
   uint8 is_punted;
    
   uint8 is_hw_trap_code;
  
  SOC_PPC_TRAP_CODE cpu_trap_code;
  
  uint32 cpu_trap_qualifier;
  
  uint32 snoop_cmnd;
  
  uint32 src_sys_port;
  
  uint32 size_in_bytes;
  
  uint32 ntwrk_header_ptr;
  
  uint32 user_header_ptr[2];
  uint32 internal_inlif_inrif;
  
  uint32 in_ac;
  
  uint32 rif;
  
  uint32 vrf;
  
  uint32 otm_port;
  
  uint32 outlif_mcid;
  
  uint32 lb_key;
  
  uint32 dsp_ext;
  
  uint32 stacking_ext;

  
  uint32 tc;
  
  uint32 dp;
   
  uint32 internal_fwd_code;
  
  uint32 internal_unknown_addr;

  

  uint32 internal_fwd_hdr_offset;

  
  uint32    oam_type;
  uint32    oam_offset;
  uint32    oam_sub_type;
  uint32    mep_type;
  uint32    oam_tp_cmd;
  uint32    oam_ts_encaps;
  uint64    oam_data;
  uint8     ext_mac_1588;    

  
  uint8		tdm_pkt_size; 
  uint8		tdm_type; 
  uint16	tdm_dest_fap_id; 
  uint8		tdm_otm_port;	 
  uint32	tdm_mc_id;	 

} SOC_PPC_TRAP_PACKET_INFO;










void SOC_PPC_TRAP_MGMT_PACKET_PARSE_INFO_clear(
        SOC_SAND_OUT SOC_PPC_TRAP_MGMT_PACKET_PARSE_INFO *info
     );

void
  SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO *info
  );

void
  SOC_PPC_TRAP_EG_ACTION_HDR_DATA_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_EG_ACTION_HDR_DATA *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO *info
  );

void
  SOC_PPC_TRAP_FRWRD_ACTION_PROFILE_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_FRWRD_ACTION_PROFILE_INFO *info
  );

void
  SOC_PPC_TRAP_ETPP_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_ETPP_INFO *info
  );

void
  SOC_PPC_TRAP_SNOOP_ACTION_PROFILE_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_SNOOP_ACTION_PROFILE_INFO *info
  );

void
  SOC_PPC_TRAP_EG_ACTION_PROFILE_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_EG_ACTION_PROFILE_INFO *info
  );

void
  SOC_PPC_TRAP_MACT_EVENT_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_MACT_EVENT_INFO *info
  );

void
  SOC_PPC_TRAP_PACKET_INFO_clear(
    SOC_SAND_OUT SOC_PPC_TRAP_PACKET_INFO *info
  );

#if SOC_PPC_DEBUG_IS_LVL1

const char*
  SOC_PPC_TRAP_SNOOP_ACTION_SIZE_to_string(
    SOC_SAND_IN  SOC_PPC_TRAP_SNOOP_ACTION_SIZE enum_val
  );

const char*
  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE_to_string(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_OVERWRITE enum_val
  );

const char*
  SOC_PPC_TRAP_MACT_EVENT_TYPE_to_string(
    SOC_SAND_IN  SOC_PPC_TRAP_MACT_EVENT_TYPE enum_val
  );

const char*
  SOC_PPC_TRAP_CODE_to_api_string(
    SOC_SAND_IN  SOC_PPC_TRAP_CODE enum_val
   );

const char*
  SOC_PPC_TRAP_CODE_to_string(
    SOC_SAND_IN  SOC_PPC_TRAP_CODE enum_val
  );

const char*
  SOC_PPC_TRAP_EG_TYPE_to_string(
    SOC_SAND_IN  SOC_PPC_TRAP_EG_TYPE enum_val
  );

const char*
  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE_to_string(
    SOC_SAND_IN  SOC_PPC_TRAP_MGMT_PKT_FRWRD_TYPE enum_val
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_DEST_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_COUNT_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_METER_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_POLICE_INFO *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_COS_INFO *info
  );

void
  SOC_PPC_TRAP_EG_ACTION_HDR_DATA_print(
    SOC_SAND_IN  SOC_PPC_TRAP_EG_ACTION_HDR_DATA *info
  );

void
  SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_ACTION_PROFILE_PROCESS_INFO *info
  );

void
  SOC_PPC_TRAP_FRWRD_ACTION_PROFILE_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_FRWRD_ACTION_PROFILE_INFO *info
  );

void
  SOC_PPC_TRAP_SNOOP_ACTION_PROFILE_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_SNOOP_ACTION_PROFILE_INFO *info
  );

void
  SOC_PPC_TRAP_EG_ACTION_PROFILE_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_EG_ACTION_PROFILE_INFO *info
  );

void
  SOC_PPC_TRAP_MACT_EVENT_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_MACT_EVENT_INFO *info
  );

void
  SOC_PPC_TRAP_PACKET_INFO_print(
    SOC_SAND_IN  SOC_PPC_TRAP_PACKET_INFO *info
  );

#endif 



#include <soc/dpp/SAND/Utils/sand_footer.h>


#endif

