# $Id: Makefile 2017/20/02 10:55:00 patild Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw/techsupport/rsvd4

include ${SDK}/make/Make.config

lib = libtsrsvd4

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
