/*! \file bcm56990_b0_fp_ing_action_conflict.c
 *
 *  IFP action conflict check function for Tomahawk-4 B0(56990_B0).
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <shr/shr_error.h>
#include <shr/shr_debug.h>
#include <bcmfp/bcmfp_internal.h>
#include <bcmfp/chip/bcm56990_b0_fp.h>
#include <bcmltd/chip/bcmltd_id.h>

#define BSL_LOG_MODULE BSL_LS_BCMFP_DEV

int
bcmfp_bcm56990_b0_ingress_action_cfg_conflict_check(int unit,
                                                    bcmfp_action_t action1,
                                                    bcmfp_action_t action)
{
    uint32_t fid = 0;

    switch (action1) {
        case FP_ING_POLICY_TEMPLATEt_ACTION_NEW_HIGIG_EHf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_DVPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_PORTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_TRUNKf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_MODULEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_PORTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_TRUNKf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_UC_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_BROADCAST_PKTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_ADD_PORTS_BROADCASTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_REMOVE_PORTS_BROADCASTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_VLAN_BROADCASTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_VLAN_BROADCAST_FP_INGf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_L2_MC_GROUP_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_L3_MC_NHOP_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_DELAYED_REDIRECT_ENABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_DELAYED_DROP_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_DVPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_PORTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_TRUNKf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_MODULEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_PORTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_TRUNKf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_NHOPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_UC_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_BROADCAST_PKTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_ADD_PORTS_BROADCASTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_REMOVE_PORTS_BROADCASTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_VLAN_BROADCASTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_VLAN_BROADCAST_FP_INGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_L2_MC_GROUP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_L3_MC_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_HIGIG_EHf;
            BCMFP_ACTIONS_CONFLICT(fid );
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DELAYED_REDIRECT_ENABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DELAYED_DROP_ENABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_ADD_REDIRECT_DATA_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_REMOVE_REDIRECT_DATA_IDf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_ADD_REDIRECT_DATA_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_REMOVE_REDIRECT_DATA_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_NHOPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMP_RESET_OVERLAY_NHOP_IDf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_DVPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_PORTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_TRUNKf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_MODULEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_PORTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_UNMODIFIED_REDIRECT_TO_TRUNKf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_NHOPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_UC_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_BROADCAST_PKTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_ADD_PORTS_BROADCASTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_REMOVE_PORTS_BROADCASTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_VLAN_BROADCASTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_PORTS_VLAN_BROADCAST_FP_INGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_L2_MC_GROUP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_L3_MC_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_HIGIG_EHf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_CLASS_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_NHOPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_CLASS_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;

        case FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_CLASS_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_CLASS_IDf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_CLASS_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_NHOPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_ECMP_RESET_OVERLAY_NHOP_IDf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDS_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_FP_ING_CLASS_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_BFD_SEESSION_IDXf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_NHOPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_REDIRECT_TO_ECMP_RESET_OVERLAY_NHOP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_TO_CPUf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_SWITCH_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_SWITCH_TO_CPU_REINSATEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_AND_SWITCH_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_TO_CPU_WITH_TIMESTAMPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_TO_CPUf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_SWITCH_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_SWITCH_TO_CPU_REINSATEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_AND_SWITCH_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_TO_CPU_WITH_TIMESTAMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_COPY_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_TO_CPUf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_SWITCH_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_SWITCH_TO_CPU_REINSATEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_AND_SWITCH_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_TO_CPU_WITH_TIMESTAMPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_TO_CPUf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_SWITCH_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_SWITCH_TO_CPU_REINSATEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_AND_SWITCH_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_TO_CPU_WITH_TIMESTAMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_COPY_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_TO_CPUf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_SWITCH_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_SWITCH_TO_CPU_REINSATEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_AND_SWITCH_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_TO_CPU_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_TO_CPU_WITH_TIMESTAMPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_TO_CPUf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_SWITCH_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_SWITCH_TO_CPU_REINSATEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_AND_SWITCH_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_TO_CPU_WITH_TIMESTAMPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_COPY_TO_CPU_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_DROPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_DROP_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_DROP_CANCELf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_DROPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_DROPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_DROP_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_DROP_CANCELf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_DROPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_DROPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_DROP_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_DROP_CANCELf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_DROPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_HIGIG_CLASS_ID_SELECTf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_NEW_CLASSIFICATION_TAGf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_SWITCH_TO_L3UCf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_L3_SWITCH_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_CLASS_ID_SELECTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_CHANGE_PKT_L2_FIELDSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_OUTER_DOT1P_TO_INNER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_OUTER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_OUTER_DOT1P_TO_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_DOT1P_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_PRESERVE_DOT1Pf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_OUTER_DOT1P_TO_INNER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_OUTER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_OUTER_DOT1P_TO_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_DOT1P_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_PRESERVE_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_OUTER_DOT1P_TO_INNER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_OUTER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_OUTER_DOT1P_TO_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_DOT1P_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_PRESERVE_DOT1Pf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_OUTER_DOT1P_TO_INNER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_OUTER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_OUTER_DOT1P_TO_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_DOT1P_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_PRESERVE_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_OUTER_DOT1P_TO_INNER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_OUTER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_OUTER_DOT1P_TO_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_DOT1P_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_PRESERVE_DOT1Pf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_OUTER_DOT1P_TO_INNER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_OUTER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_OUTER_DOT1P_TO_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_DOT1P_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_PRESERVE_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_INTPRI_TO_INNER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_INTPRIf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_INTPRI_TO_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_INTPRI_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_FP_ING_COS_Q_INT_PRI_MAP_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_UC_COSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_MC_COSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_COSf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_INTPRI_TO_INNER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_INTPRIf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_INTPRI_TO_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_INTPRI_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_FP_ING_COS_Q_INT_PRI_MAP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_UC_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_MC_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_INTPRI_TO_INNER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_INTPRIf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_INTPRI_TO_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_INTPRI_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_FP_ING_COS_Q_INT_PRI_MAP_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_UC_COSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_MC_COSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_COSf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_INTPRI_TO_INNER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_INTPRIf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_INTPRI_TO_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_INTPRI_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_FP_ING_COS_Q_INT_PRI_MAP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_UC_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_MC_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_INTPRI_TO_INNER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_INTPRIf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_INTPRI_TO_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_INTPRI_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_FP_ING_COS_Q_INT_PRI_MAP_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_UC_COSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_MC_COSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_COSf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_INTPRI_TO_INNER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_INTPRIf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_INTPRI_TO_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_INTPRI_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_FP_ING_COS_Q_INT_PRI_MAP_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_UC_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_MC_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_COSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_DSCPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_DSCP_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_R_PRESERVE_DSCPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_NEW_DSCPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_DSCP_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_R_PRESERVE_DSCPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_DSCPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_DSCP_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_Y_PRESERVE_DSCPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_NEW_DSCPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_DSCP_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_Y_PRESERVE_DSCPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_DSCPf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_DSCP_UPDATES_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_TOSf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_TOS_TO_PRE_FP_ING_OUTER_DOT1Pf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_G_PRESERVE_DSCPf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_DSCPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_NEW_TOSf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_TOS_TO_PRE_FP_ING_OUTER_DOT1Pf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_DSCP_UPDATES_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_G_PRESERVE_DSCPf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_INSTANCE_IDf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_OVERRIDEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_INSTANCE_IDf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_OVERRIDEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_ING_TIMESTAMP_INSERTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_ING_TIMESTAMP_INSERT_CANCELf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_TIMESTAMP_INSERT_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ING_TIMESTAMP_INSERTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_EGR_TIMESTAMP_INSERTf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_EGR_TIMESTAMP_INSERT_CANCELf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_EGR_TIMESTAMP_INSERT_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_EGR_TIMESTAMP_INSERTf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_COLOR_DISABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_COLOR_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_COLOR_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_COLOR_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_LOOKUP_DISABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_LOOKUP_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_LOOKUP_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_LOOKUP_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_QUEUE_DISABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_QUEUE_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_QUEUE_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_ETRAP_QUEUE_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_INBAND_TELEMETRY_ENCAP_DISABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_INBAND_TELEMETRY_ENCAP_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_INBAND_TELEMETRY_ENCAP_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_INBAND_TELEMETRY_ENCAP_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_DLB_ECMP_MONITOR_DISABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_DLB_ECMP_MONITOR_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DLB_ECMP_MONITOR_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DLB_ECMP_MONITOR_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_ON_DROP_TM_ENABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_ON_DROP_TM_DISABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_ON_DROP_TM_ENABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_MIRROR_ON_DROP_TM_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_DYNAMIC_ECMP_CANCELf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_DYNAMIC_ECMP_ENABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DYNAMIC_ECMP_CANCELf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DYNAMIC_ECMP_ENABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        case FP_ING_POLICY_TEMPLATEt_ACTION_DCN_ENABLEf:
        case FP_ING_POLICY_TEMPLATEt_ACTION_DCN_DISABLEf:
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DCN_ENABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            fid = FP_ING_POLICY_TEMPLATEt_ACTION_DCN_DISABLEf;
            BCMFP_ACTIONS_CONFLICT(fid);
            break;
        default:
            break;
    }
    return SHR_E_NONE;
}
