# $Id: $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for streamlined packet I/O drivers
#

include ${SDK}/make/Make.config

subdirs := hmi main
include ${SDK}/make/Make.subdirs
