# $Id: Makefile,v 1.0 2016/04/18 yiwenz Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for flexflow Library
#

LOCALDIR = src/bcm/esw/flexflow

include ${SDK}/make/Make.config

lib = libflexflow

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
