#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id: Makefile,v 1.4 2011/10/24 06:32:12 assaf Exp $
LOCALDIR = src/appl/diag/dfe

include ${SDK}/make/Make.config

lib = libdiag_dfe

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
