#
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dnx/drv

include ${SDK}/make/Make.config

lib = libsoc_dnxdrv


INCDIR += -I${SDK}/include/soc/dnx


include ${SDK}/make/Make.subdirs


include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
