#
# $Id: Makefile,v 1.4 2017/10/04 10:43:54 sk019289 Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/bcm/dnx/algo/vlan

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/bcm_int/dnx/algo/vlan

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxalgovlan

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
