#
#   $Id: Makefile,v 1.2.648.1 2012/04/19 02:19:58 vinodhkc Exp $
# 
# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for i2c subdirectory
#
CFLAGS += -g
LOCALDIR = src/soc/i2c

include ${SDK}/make/Make.config

lib = libsoc_i2c
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
