# $Id: Makefile,v 1.1 2004/02/24 07:46:20 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Build LED processor tools
# Build example code
#
.KEEP_STATE:

all:
	$(MAKE) -C tools all
	$(MAKE) -C example all

clean:
	$(MAKE) -C tools clean
	$(MAKE) -C example clean

clobber:
	$(MAKE) -C tools clobber
	$(MAKE) -C example clobber
