#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/bcm/ltsw/xgs

include ${SDK}/make/Make.config

lib = libltsw_xgs

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

