# $Id: Makefile,v 1.1 2004/03/13 02:19:21 miyarn Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/firebolt

include ${SDK}/make/Make.config

lib = libfirebolt

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
