/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by stub_gen from npl path and template files
 * for device bcm56880_a0 and variant dna_4_6_6.
 *
 * Tool: $SDK/INTERNAL/fltg/variant_stub/stub_gen
 *
 * Edits to this file will be lost when it is regenerated.
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#include <bcma/tecsup/bcma_tecsup_builtin.h>

bcma_tecsup_builtin_cmd_t *
bcm56880_a0_dna_4_6_6_bcma_tecsup_category_list_get(int unit)
{
    return NULL;
}

bcma_tecsup_builtin_feature_t *
bcm56880_a0_dna_4_6_6_bcma_tecsup_feature_list_get(int unit)
{
    return NULL;
}
