#
# BCM56880 128x50g port configuration.
#
# configuration yaml file
#   device:
#       <unit>:
#           <table>:
#               ?
#                   <key_fld_1>: <value>
#                   <key_fld_2>: <value>
#                   ...
#                   <key_fld_n>: <value>
#               :
#                   <data_fld_1>: <value>
#                   <data_fld_2>: <value>
#                   ...
#                   <data_fld_n>: <value>
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

---
device:
    0:
        PC_PORT_PHYS_MAP:
            ?
                # CPU port
                PORT_ID: 0
            :
                PC_PHYS_PORT_ID: 0
            ?
                PORT_ID: 1
            :
                PC_PHYS_PORT_ID: 1
            ?
                PORT_ID: 2
            :
                PC_PHYS_PORT_ID: 2
            ?
                PORT_ID: 3
            :
                PC_PHYS_PORT_ID: 3
            ?
                PORT_ID: 4
            :
                PC_PHYS_PORT_ID: 4
            ?
                PORT_ID: 5
            :
                PC_PHYS_PORT_ID: 5
            ?
                PORT_ID: 6
            :
                PC_PHYS_PORT_ID: 6
            ?
                PORT_ID: 7
            :
                PC_PHYS_PORT_ID: 7
            ?
                PORT_ID: 8
            :
                PC_PHYS_PORT_ID: 8
            ?
                PORT_ID: 9
            :
                PC_PHYS_PORT_ID: 17
            ?
                PORT_ID: 10
            :
                PC_PHYS_PORT_ID: 18
            ?
                PORT_ID: 11
            :
                PC_PHYS_PORT_ID: 19
            ?
                PORT_ID: 12
            :
                PC_PHYS_PORT_ID: 20
            ?
                PORT_ID: 13
            :
                PC_PHYS_PORT_ID: 21
            ?
                PORT_ID: 14
            :
                PC_PHYS_PORT_ID: 22
            ?
                PORT_ID: 15
            :
                PC_PHYS_PORT_ID: 23
            ?
                PORT_ID: 16
            :
                PC_PHYS_PORT_ID: 24
            ?
                PORT_ID: 20     # Pipe1
            :
                PC_PHYS_PORT_ID: 33
            ?
                PORT_ID: 21
            :
                PC_PHYS_PORT_ID: 34
            ?
                PORT_ID: 22
            :
                PC_PHYS_PORT_ID: 35
            ?
                PORT_ID: 23
            :
                PC_PHYS_PORT_ID: 36
            ?
                PORT_ID: 24     # Pipe1
            :
                PC_PHYS_PORT_ID: 37
            ?
                PORT_ID: 25
            :
                PC_PHYS_PORT_ID: 38
            ?
                PORT_ID: 26
            :
                PC_PHYS_PORT_ID: 39
            ?
                PORT_ID: 27
            :
                PC_PHYS_PORT_ID: 40
            ?
                PORT_ID: 28     # Pipe1
            :
                PC_PHYS_PORT_ID: 49
            ?
                PORT_ID: 29
            :
                PC_PHYS_PORT_ID: 50
            ?
                PORT_ID: 30
            :
                PC_PHYS_PORT_ID: 51
            ?
                PORT_ID: 31
            :
                PC_PHYS_PORT_ID: 52
            ?
                PORT_ID: 32     # Pipe1
            :
                PC_PHYS_PORT_ID: 53
            ?
                PORT_ID: 33
            :
                PC_PHYS_PORT_ID: 54
            ?
                PORT_ID: 34
            :
                PC_PHYS_PORT_ID: 55
            ?
                PORT_ID: 35
            :
                PC_PHYS_PORT_ID: 56
            ?
                PORT_ID: 40     # Pipe2
            :
                PC_PHYS_PORT_ID: 65
            ?
                PORT_ID: 41
            :
                PC_PHYS_PORT_ID: 66
            ?
                PORT_ID: 42
            :
                PC_PHYS_PORT_ID: 67
            ?
                PORT_ID: 43
            :
                PC_PHYS_PORT_ID: 68
            ?
                PORT_ID: 44     # Pipe2
            :
                PC_PHYS_PORT_ID: 69
            ?
                PORT_ID: 45
            :
                PC_PHYS_PORT_ID: 70
            ?
                PORT_ID: 46
            :
                PC_PHYS_PORT_ID: 71
            ?
                PORT_ID: 47
            :
                PC_PHYS_PORT_ID: 72
            ?
                PORT_ID: 48     # Pipe2
            :
                PC_PHYS_PORT_ID: 81
            ?
                PORT_ID: 49
            :
                PC_PHYS_PORT_ID: 82
            ?
                PORT_ID: 50
            :
                PC_PHYS_PORT_ID: 83
            ?
                PORT_ID: 51
            :
                PC_PHYS_PORT_ID: 84
            ?
                PORT_ID: 52     # Pipe2
            :
                PC_PHYS_PORT_ID: 85
            ?
                PORT_ID: 53
            :
                PC_PHYS_PORT_ID: 86
            ?
                PORT_ID: 54
            :
                PC_PHYS_PORT_ID: 87
            ?
                PORT_ID: 55
            :
                PC_PHYS_PORT_ID: 88
            ?
                PORT_ID: 60     # Pipe3
            :
                PC_PHYS_PORT_ID: 97
            ?
                PORT_ID: 61
            :
                PC_PHYS_PORT_ID: 98
            ?
                PORT_ID: 62
            :
                PC_PHYS_PORT_ID: 99
            ?
                PORT_ID: 63
            :
                PC_PHYS_PORT_ID: 100
            ?
                PORT_ID: 64     # Pipe3
            :
                PC_PHYS_PORT_ID: 101
            ?
                PORT_ID: 65
            :
                PC_PHYS_PORT_ID: 102
            ?
                PORT_ID: 66
            :
                PC_PHYS_PORT_ID: 103
            ?
                PORT_ID: 67
            :
                PC_PHYS_PORT_ID: 104
            ?
                PORT_ID: 68     # Pipe3
            :
                PC_PHYS_PORT_ID: 113
            ?
                PORT_ID: 69
            :
                PC_PHYS_PORT_ID: 114
            ?
                PORT_ID: 70
            :
                PC_PHYS_PORT_ID: 115
            ?
                PORT_ID: 71
            :
                PC_PHYS_PORT_ID: 116
            ?
                PORT_ID: 72     # Pipe3
            :
                PC_PHYS_PORT_ID: 117
            ?
                PORT_ID: 73
            :
                PC_PHYS_PORT_ID: 118
            ?
                PORT_ID: 74
            :
                PC_PHYS_PORT_ID: 119
            ?
                PORT_ID: 75
            :
                PC_PHYS_PORT_ID: 120
            ?
                PORT_ID: 80     # Pipe4
            :
                PC_PHYS_PORT_ID: 129
            ?
                PORT_ID: 81
            :
                PC_PHYS_PORT_ID: 130
            ?
                PORT_ID: 82
            :
                PC_PHYS_PORT_ID: 131
            ?
                PORT_ID: 83
            :
                PC_PHYS_PORT_ID: 132
            ?
                PORT_ID: 84     # Pipe4
            :
                PC_PHYS_PORT_ID: 133
            ?
                PORT_ID: 85
            :
                PC_PHYS_PORT_ID: 134
            ?
                PORT_ID: 86
            :
                PC_PHYS_PORT_ID: 135
            ?
                PORT_ID: 87
            :
                PC_PHYS_PORT_ID: 136
            ?
                PORT_ID: 88     # Pipe4
            :
                PC_PHYS_PORT_ID: 145
            ?
                PORT_ID: 89
            :
                PC_PHYS_PORT_ID: 146
            ?
                PORT_ID: 90
            :
                PC_PHYS_PORT_ID: 147
            ?
                PORT_ID: 91
            :
                PC_PHYS_PORT_ID: 148
            ?
                PORT_ID: 92     # Pipe4
            :
                PC_PHYS_PORT_ID: 149
            ?
                PORT_ID: 93
            :
                PC_PHYS_PORT_ID: 150
            ?
                PORT_ID: 94
            :
                PC_PHYS_PORT_ID: 151
            ?
                PORT_ID: 95
            :
                PC_PHYS_PORT_ID: 152
            ?
                PORT_ID: 100    # Pipe5
            :
                PC_PHYS_PORT_ID: 161
            ?
                PORT_ID: 101
            :
                PC_PHYS_PORT_ID: 162
            ?
                PORT_ID: 102
            :
                PC_PHYS_PORT_ID: 163
            ?
                PORT_ID: 103
            :
                PC_PHYS_PORT_ID: 164
            ?
                PORT_ID: 104    # Pipe5
            :
                PC_PHYS_PORT_ID: 165
            ?
                PORT_ID: 105
            :
                PC_PHYS_PORT_ID: 166
            ?
                PORT_ID: 106
            :
                PC_PHYS_PORT_ID: 167
            ?
                PORT_ID: 107
            :
                PC_PHYS_PORT_ID: 168
            ?
                PORT_ID: 108    # Pipe5
            :
                PC_PHYS_PORT_ID: 177
            ?
                PORT_ID: 109
            :
                PC_PHYS_PORT_ID: 178
            ?
                PORT_ID: 110
            :
                PC_PHYS_PORT_ID: 179
            ?
                PORT_ID: 111
            :
                PC_PHYS_PORT_ID: 180
            ?
                PORT_ID: 112    # Pipe5
            :
                PC_PHYS_PORT_ID: 181
            ?
                PORT_ID: 113
            :
                PC_PHYS_PORT_ID: 182
            ?
                PORT_ID: 114
            :
                PC_PHYS_PORT_ID: 183
            ?
                PORT_ID: 115
            :
                PC_PHYS_PORT_ID: 184
            ?
                PORT_ID: 120    # Pipe6
            :
                PC_PHYS_PORT_ID: 193
            ?
                PORT_ID: 121
            :
                PC_PHYS_PORT_ID: 194
            ?
                PORT_ID: 122
            :
                PC_PHYS_PORT_ID: 195
            ?
                PORT_ID: 123
            :
                PC_PHYS_PORT_ID: 196
            ?
                PORT_ID: 124    # Pipe6
            :
                PC_PHYS_PORT_ID: 197
            ?
                PORT_ID: 125
            :
                PC_PHYS_PORT_ID: 198
            ?
                PORT_ID: 126
            :
                PC_PHYS_PORT_ID: 199
            ?
                PORT_ID: 127
            :
                PC_PHYS_PORT_ID: 200
            ?
                PORT_ID: 128    # Pipe6
            :
                PC_PHYS_PORT_ID: 209
            ?
                PORT_ID: 129
            :
                PC_PHYS_PORT_ID: 210
            ?
                PORT_ID: 130
            :
                PC_PHYS_PORT_ID: 211
            ?
                PORT_ID: 131
            :
                PC_PHYS_PORT_ID: 212
            ?
                PORT_ID: 132    # Pipe6
            :
                PC_PHYS_PORT_ID: 213
            ?
                PORT_ID: 133
            :
                PC_PHYS_PORT_ID: 214
            ?
                PORT_ID: 134
            :
                PC_PHYS_PORT_ID: 215
            ?
                PORT_ID: 135
            :
                PC_PHYS_PORT_ID: 216
            ?
                PORT_ID: 140    # Pipe7
            :
                PC_PHYS_PORT_ID: 225
            ?
                PORT_ID: 141
            :
                PC_PHYS_PORT_ID: 226
            ?
                PORT_ID: 142
            :
                PC_PHYS_PORT_ID: 227
            ?
                PORT_ID: 143
            :
                PC_PHYS_PORT_ID: 228
            ?
                PORT_ID: 144    # Pipe7
            :
                PC_PHYS_PORT_ID: 229
            ?
                PORT_ID: 145
            :
                PC_PHYS_PORT_ID: 230
            ?
                PORT_ID: 146
            :
                PC_PHYS_PORT_ID: 231
            ?
                PORT_ID: 147
            :
                PC_PHYS_PORT_ID: 232
            ?
                PORT_ID: 148    # Pipe7
            :
                PC_PHYS_PORT_ID: 241
            ?
                PORT_ID: 149
            :
                PC_PHYS_PORT_ID: 242
            ?
                PORT_ID: 150
            :
                PC_PHYS_PORT_ID: 243
            ?
                PORT_ID: 151
            :
                PC_PHYS_PORT_ID: 244
            ?
                PORT_ID: 152    # Pipe7
            :
                PC_PHYS_PORT_ID: 245
            ?
                PORT_ID: 153
            :
                PC_PHYS_PORT_ID: 246
            ?
                PORT_ID: 154
            :
                PC_PHYS_PORT_ID: 247
            ?
                PORT_ID: 155
            :
                PC_PHYS_PORT_ID: 248
            ?
                # Management port 0 (Pipe 1)
                PORT_ID: 38
            :
                PC_PHYS_PORT_ID: 257
            ?
                # Management port 1 (Pipe 3)
                PORT_ID: 78
            :
                PC_PHYS_PORT_ID: 258
            ?
                # Management port 2 (Pipe 5)
                PORT_ID: 118
            :
                PC_PHYS_PORT_ID: 259
            ?
                # Management port 3 (Pipe 7)
                PORT_ID: 158
            :
                PC_PHYS_PORT_ID: 260
...
---
device:
    0:
        PC_PORT:
            ?
                PORT_ID: 0
            :
                &port_mode_10g
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
            ?
                PORT_ID: [[1, 16],
                          [20, 35],
                          [40, 55],
                          [60, 75],
                          [80, 95],
                          [100, 115],
                          [120, 135],
                          [140, 155]]
            :
                &port_mode_50g
                ENABLE: 1
                SPEED: 50000
                NUM_LANES: 1
                FEC_MODE: PC_FEC_RS528
                MAX_FRAME_SIZE: 9416
            ?
                PORT_ID: [38,     # Management port 0 (Pipe 1)
                          78,     # Management port 1 (Pipe 3)
                          118,    # Management port 2 (Pipe 5)
                          158]    # Management port 3 (Pipe 7)
            :
                &port_mode_10g_xfi
                ENABLE: 1
                SPEED: 10000
                NUM_LANES: 1
                MAX_FRAME_SIZE: 9416
...
---
device:
    0:
        # Per pipe flex counter configuration
        CTR_EFLEX_CONFIG:
            CTR_ING_EFLEX_OPERMODE_PIPEUNIQUE: 0
            CTR_EGR_EFLEX_OPERMODE_PIPEUNIQUE: 0
...
