#
# $Id: Makefile,v 1.2 Broadcom SDK $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/appl/dpp/FecAllocation

include ${SDK}/make/Make.config

lib = libappl_dpp_FecAllocaiton

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
