/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */


/*
 * cmicx_sim.h
 *
 * header for the cmic module
 */


#ifndef _CMICX_SIM_H_
#define _CMICX_SIM_H_


/* includes */
#include "../../../include/soc/mcm/cmicx.h"
#include "cmicx_sim_schan.h"
#include "cmicx_sim_sbus_dma.h"
#include "cmicx_sim_packet_dma.h"


/*****************************************************/
/* defines for CMIC pci-available register addresses */
/*****************************************************/

/* general PCID stuff */
#define NUM_PCID_REGISTERS   (NUM_CMICX_REGS+1)  /* +1 because of control reg */
#define MAX_PCID_MEM_VALUES            1000000   /* number of cmicx sim memory
                                                    values able to be stored
                                                    (statically allocated upon
                                                    initialization) */
#define CMICX_MAX_SWITCH_REGISTERS        1000   /* maximum number of switch
                                                    registers that we can/will
                                                    store. */
#define CMICX_MAX_SWITCH_MEMORIES      1000000   /* maximum number of switch
                                                    memory values that we can/
                                                    will store. */
#define CMICX_SIM_PCI_BASE_ADDR     0x03200000
#define CMICX_SIM_CONTROL_REG_ADDR     0xFFFF0

/* schan registers */
#define CMIC_TOP_SBUS_RING_ARB_CTRL_SCHAN_REG_ADDR                CMIC_TOP_SBUS_RING_ARB_CTRL_SCHAN_OFFSET
#define CMIC_TOP_SBUS_TIMEOUT_REG_ADDR                            CMIC_TOP_SBUS_TIMEOUT_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_0_7_REG_ADDR                       CMIC_TOP_SBUS_RING_MAP_0_7_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_8_15_REG_ADDR                      CMIC_TOP_SBUS_RING_MAP_8_15_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_16_23_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_16_23_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_24_31_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_24_31_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_32_39_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_32_39_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_40_47_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_40_47_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_48_55_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_48_55_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_56_63_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_56_63_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_64_71_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_64_71_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_72_79_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_72_79_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_80_87_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_80_87_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_88_95_REG_ADDR                     CMIC_TOP_SBUS_RING_MAP_88_95_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_96_103_REG_ADDR                    CMIC_TOP_SBUS_RING_MAP_96_103_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_104_111_REG_ADDR                   CMIC_TOP_SBUS_RING_MAP_104_111_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_112_119_REG_ADDR                   CMIC_TOP_SBUS_RING_MAP_112_119_OFFSET
#define CMIC_TOP_SBUS_RING_MAP_120_127_REG_ADDR                   CMIC_TOP_SBUS_RING_MAP_120_127_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE0_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x00)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE1_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x04)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE2_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x08)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE3_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x0C)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE4_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x10)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE5_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x14)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE6_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x18)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE7_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x1C)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE8_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x20)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE9_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x24)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE10_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x28)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE11_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x2C)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE12_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x30)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE13_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x34)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE14_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x38)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE15_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x3C)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE16_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x40)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE17_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x44)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE18_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x48)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE19_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x4C)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE20_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x50)
#define CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE21_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH0_MESSAGE_OFFSET + 0x54)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE0_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x00)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE1_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x04)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE2_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x08)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE3_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x0C)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE4_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x10)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE5_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x14)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE6_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x18)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE7_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x1C)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE8_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x20)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE9_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x24)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE10_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x28)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE11_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x2C)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE12_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x30)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE13_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x34)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE14_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x38)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE15_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x3C)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE16_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x40)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE17_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x44)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE18_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x48)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE19_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x4C)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE20_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x50)
#define CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE21_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH1_MESSAGE_OFFSET + 0x54)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE0_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x00)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE1_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x04)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE2_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x08)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE3_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x0C)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE4_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x10)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE5_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x14)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE6_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x18)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE7_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x1C)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE8_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x20)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE9_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x24)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE10_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x28)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE11_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x2C)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE12_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x30)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE13_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x34)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE14_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x38)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE15_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x3C)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE16_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x40)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE17_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x44)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE18_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x48)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE19_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x4C)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE20_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x50)
#define CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE21_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH2_MESSAGE_OFFSET + 0x54)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE0_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x00)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE1_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x04)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE2_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x08)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE3_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x0C)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE4_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x10)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE5_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x14)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE6_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x18)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE7_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x1C)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE8_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x20)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE9_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x24)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE10_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x28)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE11_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x2C)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE12_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x30)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE13_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x34)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE14_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x38)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE15_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x3C)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE16_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x40)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE17_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x44)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE18_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x48)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE19_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x4C)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE20_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x50)
#define CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE21_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH3_MESSAGE_OFFSET + 0x54)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE0_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x00)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE1_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x04)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE2_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x08)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE3_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x0C)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE4_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x10)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE5_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x14)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE6_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x18)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE7_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x1C)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE8_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x20)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE9_REG_ADDR             (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x24)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE10_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x28)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE11_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x2C)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE12_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x30)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE13_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x34)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE14_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x38)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE15_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x3C)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE16_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x40)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE17_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x44)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE18_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x48)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE19_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x4C)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE20_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x50)
#define CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE21_REG_ADDR            (CMIC_COMMON_POOL_SCHAN_CH4_MESSAGE_OFFSET + 0x54)
#define CMIC_COMMON_POOL_SCHAN_CH0_CTRL_REG_ADDR                  CMIC_COMMON_POOL_SCHAN_CH0_CTRL_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH0_ACK_DATA_BEAT_COUNT_REG_ADDR   CMIC_COMMON_POOL_SCHAN_CH0_ACK_DATA_BEAT_COUNT_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH0_ERR_REG_ADDR                   CMIC_COMMON_POOL_SCHAN_CH0_ERR_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH1_CTRL_REG_ADDR                  CMIC_COMMON_POOL_SCHAN_CH1_CTRL_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH1_ACK_DATA_BEAT_COUNT_REG_ADDR   CMIC_COMMON_POOL_SCHAN_CH1_ACK_DATA_BEAT_COUNT_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH1_ERR_REG_ADDR                   CMIC_COMMON_POOL_SCHAN_CH1_ERR_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH2_CTRL_REG_ADDR                  CMIC_COMMON_POOL_SCHAN_CH2_CTRL_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH2_ACK_DATA_BEAT_COUNT_REG_ADDR   CMIC_COMMON_POOL_SCHAN_CH2_ACK_DATA_BEAT_COUNT_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH2_ERR_REG_ADDR                   CMIC_COMMON_POOL_SCHAN_CH2_ERR_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH3_CTRL_REG_ADDR                  CMIC_COMMON_POOL_SCHAN_CH3_CTRL_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH3_ACK_DATA_BEAT_COUNT_REG_ADDR   CMIC_COMMON_POOL_SCHAN_CH3_ACK_DATA_BEAT_COUNT_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH3_ERR_REG_ADDR                   CMIC_COMMON_POOL_SCHAN_CH3_ERR_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH4_CTRL_REG_ADDR                  CMIC_COMMON_POOL_SCHAN_CH4_CTRL_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH4_ACK_DATA_BEAT_COUNT_REG_ADDR   CMIC_COMMON_POOL_SCHAN_CH4_ACK_DATA_BEAT_COUNT_OFFSET
#define CMIC_COMMON_POOL_SCHAN_CH4_ERR_REG_ADDR                   CMIC_COMMON_POOL_SCHAN_CH4_ERR_OFFSET

/* sbus dma registers */
#define CMIC_TOP_SBUS_RING_ARB_CTRL_SBUSDMA_REG_ADDR                               CMIC_TOP_SBUS_RING_ARB_CTRL_SBUSDMA_OFFSET
#define CMIC_CMC0_SHARED_CONFIG_REG_ADDR                                           CMIC_CMC0_SHARED_CONFIG_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CONTROL_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH0_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_REQUEST_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH0_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_COUNT_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH0_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_OPCODE_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH0_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC0_SBUSDMA_CH0_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH0_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH0_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_STATUS_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH0_STATUS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC0_SBUSDMA_CH0_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH0_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH0_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH0_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_TIMER_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH0_TIMER_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_ITER_COUNT_REG_ADDR                                  CMIC_CMC0_SBUSDMA_CH0_ITER_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_TM_CONTROL_0_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH0_TM_CONTROL_0_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_TM_CONTROL_1_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH0_TM_CONTROL_1_OFFSET
#define CMIC_CMC0_SBUSDMA_CH0_TM_CONTROL_2_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH0_TM_CONTROL_2_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CONTROL_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH1_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_REQUEST_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH1_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_COUNT_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH1_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_OPCODE_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH1_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC0_SBUSDMA_CH1_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH1_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH1_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_STATUS_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH1_STATUS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC0_SBUSDMA_CH1_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH1_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH1_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH1_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_TIMER_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH1_TIMER_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_ITER_COUNT_REG_ADDR                                  CMIC_CMC0_SBUSDMA_CH1_ITER_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_TM_CONTROL_0_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH1_TM_CONTROL_0_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_TM_CONTROL_1_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH1_TM_CONTROL_1_OFFSET
#define CMIC_CMC0_SBUSDMA_CH1_TM_CONTROL_2_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH1_TM_CONTROL_2_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CONTROL_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH2_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_REQUEST_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH2_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_COUNT_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH2_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_OPCODE_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH2_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC0_SBUSDMA_CH2_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH2_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH2_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_STATUS_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH2_STATUS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC0_SBUSDMA_CH2_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH2_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH2_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH2_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_TIMER_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH2_TIMER_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_ITER_COUNT_REG_ADDR                                  CMIC_CMC0_SBUSDMA_CH2_ITER_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_TM_CONTROL_0_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH2_TM_CONTROL_0_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_TM_CONTROL_1_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH2_TM_CONTROL_1_OFFSET
#define CMIC_CMC0_SBUSDMA_CH2_TM_CONTROL_2_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH2_TM_CONTROL_2_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CONTROL_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH3_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_REQUEST_REG_ADDR                                     CMIC_CMC0_SBUSDMA_CH3_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_COUNT_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH3_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_OPCODE_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH3_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC0_SBUSDMA_CH3_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH3_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC0_SBUSDMA_CH3_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_STATUS_REG_ADDR                                      CMIC_CMC0_SBUSDMA_CH3_STATUS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC0_SBUSDMA_CH3_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH3_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC0_SBUSDMA_CH3_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC0_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC0_SBUSDMA_CH3_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_TIMER_REG_ADDR                                       CMIC_CMC0_SBUSDMA_CH3_TIMER_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_ITER_COUNT_REG_ADDR                                  CMIC_CMC0_SBUSDMA_CH3_ITER_COUNT_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_TM_CONTROL_0_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH3_TM_CONTROL_0_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_TM_CONTROL_1_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH3_TM_CONTROL_1_OFFSET
#define CMIC_CMC0_SBUSDMA_CH3_TM_CONTROL_2_REG_ADDR                                CMIC_CMC0_SBUSDMA_CH3_TM_CONTROL_2_OFFSET
#define CMIC_CMC1_SHARED_CONFIG_REG_ADDR                                           CMIC_CMC1_SHARED_CONFIG_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CONTROL_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH0_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_REQUEST_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH0_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_COUNT_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH0_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_OPCODE_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH0_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC1_SBUSDMA_CH0_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH0_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH0_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH0_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_STATUS_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH0_STATUS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH0_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC1_SBUSDMA_CH0_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH0_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH0_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH0_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH0_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_TIMER_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH0_TIMER_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_ITER_COUNT_REG_ADDR                                  CMIC_CMC1_SBUSDMA_CH0_ITER_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_TM_CONTROL_0_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH0_TM_CONTROL_0_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_TM_CONTROL_1_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH0_TM_CONTROL_1_OFFSET
#define CMIC_CMC1_SBUSDMA_CH0_TM_CONTROL_2_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH0_TM_CONTROL_2_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CONTROL_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH1_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_REQUEST_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH1_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_COUNT_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH1_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_OPCODE_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH1_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC1_SBUSDMA_CH1_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH1_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH1_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH1_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_STATUS_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH1_STATUS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH1_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC1_SBUSDMA_CH1_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH1_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH1_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH1_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH1_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_TIMER_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH1_TIMER_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_ITER_COUNT_REG_ADDR                                  CMIC_CMC1_SBUSDMA_CH1_ITER_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_TM_CONTROL_0_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH1_TM_CONTROL_0_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_TM_CONTROL_1_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH1_TM_CONTROL_1_OFFSET
#define CMIC_CMC1_SBUSDMA_CH1_TM_CONTROL_2_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH1_TM_CONTROL_2_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CONTROL_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH2_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_REQUEST_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH2_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_COUNT_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH2_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_OPCODE_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH2_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC1_SBUSDMA_CH2_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH2_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH2_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH2_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_STATUS_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH2_STATUS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH2_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC1_SBUSDMA_CH2_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH2_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH2_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH2_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH2_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_TIMER_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH2_TIMER_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_ITER_COUNT_REG_ADDR                                  CMIC_CMC1_SBUSDMA_CH2_ITER_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_TM_CONTROL_0_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH2_TM_CONTROL_0_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_TM_CONTROL_1_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH2_TM_CONTROL_1_OFFSET
#define CMIC_CMC1_SBUSDMA_CH2_TM_CONTROL_2_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH2_TM_CONTROL_2_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CONTROL_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH3_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_REQUEST_REG_ADDR                                     CMIC_CMC1_SBUSDMA_CH3_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_COUNT_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH3_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_OPCODE_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH3_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_SBUS_START_ADDRESS_REG_ADDR                          CMIC_CMC1_SBUSDMA_CH3_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_LO_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_HI_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH3_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_DESC_START_ADDRESS_LO_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH3_DESC_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_DESC_START_ADDRESS_HI_REG_ADDR                       CMIC_CMC1_SBUSDMA_CH3_DESC_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_STATUS_REG_ADDR                                      CMIC_CMC1_SBUSDMA_CH3_STATUS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_LO_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_HI_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH3_CUR_HOSTMEM_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUS_ADDRESS_REG_ADDR                            CMIC_CMC1_SBUSDMA_CH3_CUR_SBUS_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_DESC_ADDRESS_LO_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH3_CUR_DESC_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_DESC_ADDRESS_HI_REG_ADDR                         CMIC_CMC1_SBUSDMA_CH3_CUR_DESC_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_REQUEST_REG_ADDR                  CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_REQUEST_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_OPCODE_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_OPCODE_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_REG_ADDR       CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_SBUS_START_ADDRESS_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_REG_ADDR CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_REG_ADDR CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_HOSTMEM_START_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_COUNT_REG_ADDR                    CMIC_CMC1_SBUSDMA_CH3_CUR_SBUSDMA_CONFIG_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_DEBUG_REG_ADDR                               CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_DEBUG_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_DEBUG_CLR_REG_ADDR                           CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_DEBUG_CLR_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_LO_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_LO_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_HI_REG_ADDR                   CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_ECCERR_ADDRESS_HI_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_ECCERR_CONTROL_REG_ADDR                      CMIC_CMC1_SBUSDMA_CH3_SBUSDMA_ECCERR_CONTROL_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_TIMER_REG_ADDR                                       CMIC_CMC1_SBUSDMA_CH3_TIMER_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_ITER_COUNT_REG_ADDR                                  CMIC_CMC1_SBUSDMA_CH3_ITER_COUNT_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_TM_CONTROL_0_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH3_TM_CONTROL_0_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_TM_CONTROL_1_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH3_TM_CONTROL_1_OFFSET
#define CMIC_CMC1_SBUSDMA_CH3_TM_CONTROL_2_REG_ADDR                                CMIC_CMC1_SBUSDMA_CH3_TM_CONTROL_2_OFFSET

/* packet dma registers */
#define CMIC_TOP_CONFIG_REG_ADDR                                     CMIC_TOP_CONFIG_OFFSET
#define CMIC_TOP_EPINTF_RELEASE_ALL_CREDITS_REG_ADDR                 CMIC_TOP_EPINTF_RELEASE_ALL_CREDITS_OFFSET
#define CMIC_CMC0_SHARED_IRQ_STAT0_REG_ADDR                          CMIC_CMC0_SHARED_IRQ_STAT0_OFFSET
#define CMIC_CMC0_SHARED_IRQ_STAT1_REG_ADDR                          CMIC_CMC0_SHARED_IRQ_STAT1_OFFSET
#define CMIC_CMC0_SHARED_IRQ_STAT_CLR0_REG_ADDR                      CMIC_CMC0_SHARED_IRQ_STAT_CLR0_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH0_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH0_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH0_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH0_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH0_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH0_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH0_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH0_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH0_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH0_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH0_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH0_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH0_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH0_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH0_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH1_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH1_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH1_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH1_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH1_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH1_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH1_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH1_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH1_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH1_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH1_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH1_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH1_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH1_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH1_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH2_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH2_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH2_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH2_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH2_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH2_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH2_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH2_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH2_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH2_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH2_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH2_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH2_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH2_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH2_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH3_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH3_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH3_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH3_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH3_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH3_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH3_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH3_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH3_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH3_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH3_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH3_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH3_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH3_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH3_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH4_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH4_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH4_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH4_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH4_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH4_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH4_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH4_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH4_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH4_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH4_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH4_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH4_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH4_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH4_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH5_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH5_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH5_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH5_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH5_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH5_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH5_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH5_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH5_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH5_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH5_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH5_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH5_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH5_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH5_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH6_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH6_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH6_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH6_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH6_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH6_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH6_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH6_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH6_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH6_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH6_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH6_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH6_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH6_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH6_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_CTRL_REG_ADDR                           CMIC_CMC0_PKTDMA_CH7_CTRL_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH7_DESC_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH7_DESC_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC0_PKTDMA_CH7_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC0_PKTDMA_CH7_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_STAT_REG_ADDR                           CMIC_CMC0_PKTDMA_CH7_STAT_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC0_PKTDMA_CH7_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC0_PKTDMA_CH7_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_INTR_COAL_REG_ADDR                      CMIC_CMC0_PKTDMA_CH7_INTR_COAL_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_CURR_DESC_LO_REG_ADDR                   CMIC_CMC0_PKTDMA_CH7_CURR_DESC_LO_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_CURR_DESC_HI_REG_ADDR                   CMIC_CMC0_PKTDMA_CH7_CURR_DESC_HI_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC0_PKTDMA_CH7_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH7_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC0_PKTDMA_CH7_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC0_PKTDMA_CH7_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_SHARED_IRQ_STAT0_REG_ADDR                          CMIC_CMC1_SHARED_IRQ_STAT0_OFFSET
#define CMIC_CMC1_SHARED_IRQ_STAT1_REG_ADDR                          CMIC_CMC1_SHARED_IRQ_STAT1_OFFSET
#define CMIC_CMC1_SHARED_IRQ_STAT_CLR0_REG_ADDR                      CMIC_CMC1_SHARED_IRQ_STAT_CLR0_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH0_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH0_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH0_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH0_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH0_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH0_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH0_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH0_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH0_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH0_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH0_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH0_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH0_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH0_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH0_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH1_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH1_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH1_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH1_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH1_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH1_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH1_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH1_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH1_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH1_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH1_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH1_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH1_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH1_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH1_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH2_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH2_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH2_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH2_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH2_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH2_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH2_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH2_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH2_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH2_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH2_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH2_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH2_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH2_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH2_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH3_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH3_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH3_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH3_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH3_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH3_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH3_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH3_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH3_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH3_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH3_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH3_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH3_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH3_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH3_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH4_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH4_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH4_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH4_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH4_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH4_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH4_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH4_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH4_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH4_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH4_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH4_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH4_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH4_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH4_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH5_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH5_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH5_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH5_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH5_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH5_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH5_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH5_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH5_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH5_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH5_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH5_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH5_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH5_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH5_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH6_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH6_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH6_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH6_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH6_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH6_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH6_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH6_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH6_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH6_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH6_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH6_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH6_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH6_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH6_PKT_COUNT_TXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_CTRL_REG_ADDR                           CMIC_CMC1_PKTDMA_CH7_CTRL_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_DESC_ADDR_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH7_DESC_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_DESC_ADDR_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH7_DESC_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_DESC_HALT_ADDR_LO_REG_ADDR              CMIC_CMC1_PKTDMA_CH7_DESC_HALT_ADDR_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_DESC_HALT_ADDR_HI_REG_ADDR              CMIC_CMC1_PKTDMA_CH7_DESC_HALT_ADDR_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_STAT_REG_ADDR                           CMIC_CMC1_PKTDMA_CH7_STAT_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_COS_CTRL_RX_0_REG_ADDR                  CMIC_CMC1_PKTDMA_CH7_COS_CTRL_RX_0_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_COS_CTRL_RX_1_REG_ADDR                  CMIC_CMC1_PKTDMA_CH7_COS_CTRL_RX_1_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_INTR_COAL_REG_ADDR                      CMIC_CMC1_PKTDMA_CH7_INTR_COAL_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_CURR_DESC_LO_REG_ADDR                   CMIC_CMC1_PKTDMA_CH7_CURR_DESC_LO_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_CURR_DESC_HI_REG_ADDR                   CMIC_CMC1_PKTDMA_CH7_CURR_DESC_HI_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_RXBUF_THRESHOLD_CONFIG_REG_ADDR         CMIC_CMC1_PKTDMA_CH7_RXBUF_THRESHOLD_CONFIG_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_PKT_COUNT_RXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH7_PKT_COUNT_RXPKT_OFFSET
#define CMIC_CMC1_PKTDMA_CH7_PKT_COUNT_TXPKT_REG_ADDR                CMIC_CMC1_PKTDMA_CH7_PKT_COUNT_TXPKT_OFFSET

/* schan fifo registers */
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE0_REG_ADDR                  0x18C0
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE1_REG_ADDR                  0x18D0
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE2_REG_ADDR                  0x18E0
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE3_REG_ADDR                  0x18F0
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE4_REG_ADDR                  0x1900
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE5_REG_ADDR                  0x1910
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE6_REG_ADDR                  0x1920
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE7_REG_ADDR                  0x1930
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE8_REG_ADDR                  0x1940
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE9_REG_ADDR                  0x1950
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE10_REG_ADDR                 0x1960
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE11_REG_ADDR                 0x1970
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE12_REG_ADDR                 0x1980
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE13_REG_ADDR                 0x1990
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE14_REG_ADDR                 0x19A0
#define CMIC_CMC0_SCHAN_FIFO_BUFF1_MESSAGE15_REG_ADDR                 0x19B0
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE0_REG_ADDR                  0x19C0
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE1_REG_ADDR                  0x19D0
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE2_REG_ADDR                  0x19E0
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE3_REG_ADDR                  0x19F0
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE4_REG_ADDR                  0x1A00
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE5_REG_ADDR                  0x1A10
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE6_REG_ADDR                  0x1A20
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE7_REG_ADDR                  0x1A30
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE8_REG_ADDR                  0x1A40
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE9_REG_ADDR                  0x1A50
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE10_REG_ADDR                 0x1A60
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE11_REG_ADDR                 0x1A70
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE12_REG_ADDR                 0x1A80
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE13_REG_ADDR                 0x1A90
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE14_REG_ADDR                 0x1AA0
#define CMIC_CMC0_SCHAN_FIFO_BUFF2_MESSAGE15_REG_ADDR                 0x1AB0
#define CMIC_CMC0_SCHAN_FIFO_STATUS_BUFF1_REG_ADDR                    0x1AC0
#define CMIC_CMC0_SCHAN_FIFO_STATUS_BUFF2_REG_ADDR                    0x1AD0
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE0_REG_ADDR                  0x18C0
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE1_REG_ADDR                  0x18D0
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE2_REG_ADDR                  0x18E0
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE3_REG_ADDR                  0x18F0
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE4_REG_ADDR                  0x1900
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE5_REG_ADDR                  0x1910
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE6_REG_ADDR                  0x1920
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE7_REG_ADDR                  0x1930
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE8_REG_ADDR                  0x1940
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE9_REG_ADDR                  0x1950
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE10_REG_ADDR                 0x1960
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE11_REG_ADDR                 0x1970
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE12_REG_ADDR                 0x1980
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE13_REG_ADDR                 0x1990
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE14_REG_ADDR                 0x19A0
#define CMIC_CMC1_SCHAN_FIFO_BUFF1_MESSAGE15_REG_ADDR                 0x19B0
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE0_REG_ADDR                  0x19C0
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE1_REG_ADDR                  0x19D0
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE2_REG_ADDR                  0x19E0
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE3_REG_ADDR                  0x19F0
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE4_REG_ADDR                  0x1A00
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE5_REG_ADDR                  0x1A10
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE6_REG_ADDR                  0x1A20
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE7_REG_ADDR                  0x1A30
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE8_REG_ADDR                  0x1A40
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE9_REG_ADDR                  0x1A50
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE10_REG_ADDR                 0x1A60
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE11_REG_ADDR                 0x1A70
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE12_REG_ADDR                 0x1A80
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE13_REG_ADDR                 0x1A90
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE14_REG_ADDR                 0x1AA0
#define CMIC_CMC1_SCHAN_FIFO_BUFF2_MESSAGE15_REG_ADDR                 0x1AB0
#define CMIC_CMC1_SCHAN_FIFO_STATUS_BUFF1_REG_ADDR                    0x1AC0
#define CMIC_CMC1_SCHAN_FIFO_STATUS_BUFF2_REG_ADDR                    0x1AD0


/************************************************************************************/
/* general-purpose macro definitions and other definitions for top-level cmic stuff */
/************************************************************************************/

/* general cmicx sim defines */
#define CMICX_BYTES_PER_WORD                  4

/* defines for cmicx sim constants */
#define CMICX_NUM_CMC                         2
#define CMICX_NUM_PACKET_DMA_PER_CMC          8
#define CMICX_NUM_SBUS_DMA_PER_CMC            4
#define CMICX_NUM_SCHAN_IN_COMMON             5
#define CMIC_CMC_ID_STRING_LENGTH            32

/* bits for cmicx sim control register */
#define CMICX_SIM_CONTROL_REG_PCID_MEM_DUMP_BIT           0
#define CMICX_SIM_CONTROL_REG_SWITCH_REGISTERS_DUMP_BIT   1
#define CMICX_SIM_CONTROL_REG_SWITCH_MEMORIES_DUMP_BIT    2
#define CMICX_SIM_CONTROL_REG_LOG_LEVEL_CUTOFF_SET_BIT   15
#define CMICX_SIM_CONTROL_REG_LOG_LEVEL_CUTOFF_LSB       16
#define CMICX_SIM_CONTROL_REG_LOG_LEVEL_CUTOFF_MSB       23


/* macros to generate register access functions */
#define PCID_REG_READ_FUNC_GEN(func_name,variable_name)         bool func_name(reg_t *val) { *val = variable_name; return true; }
#define PCID_REG_READ_NULL_FUNC_GEN(func_name)                  bool func_name(reg_t *val) { *val = 0;             return true; }
#define PCID_REG_WRITE_FUNC_GEN(func_name,variable_name)        bool func_name(reg_t  val) { variable_name = val;  return true; }
#define PCID_REG_WRITE_NULL_FUNC_GEN(func_name)                 bool func_name(reg_t  val) {                       return true; }


/* bit and field get/set macros for registers */
#define REG_BIT_SET_TO(reg,bitnum,val)        reg  = (reg & ~(((reg_t)0x1)<<bitnum)) | (((reg_t)val)<<bitnum)
#define REG_BIT_SET(reg,bitnum)               reg |=         (((reg_t)0x1)<<bitnum)
#define REG_BIT_CLEAR(reg,bitnum)             reg &=        ~(((reg_t)0x1)<<bitnum)
#define REG_BIT_GET(reg,bitnum)             ((reg &          (((reg_t)0x1)<<bitnum))>>bitnum)
#define REG_FIELD_SET_TO(reg,msb,lsb,val)     reg  = (reg & (((~((reg_t)0x0))<<(31-msb)) | ((~((reg_t)0x0))>>lsb))) | ((reg_t)val<<lsb)
#define REG_FIELD_GET(reg,msb,lsb)          ((reg<<(31-msb))>>(31-(msb-lsb)))

/* macros to reference subfields of large values (32-bit chunks of a 64-bit uint, etc) */
/* *** NOTE THESE WILL PROBABLY BREAK ON LITTLE ENDIAN SYSTEMS (should work on fix for this) */
#define UINT64_LOWER32_REFERENCE(val)       (*(((uint32_t *)(&(val)))  ))
#define UINT64_UPPER32_REFERENCE(val)       (*(((uint32_t *)(&(val)))+1))


/* structure definition for a cmc submodule of the cmicx */
typedef struct cmicx_cmc_struct {

    /* identification string for the cmc */
    char id_string[CMIC_CMC_ID_STRING_LENGTH];

    /* flags for config settings per-cmc */
    bool enable_early_bresp;

    /* sbus dma and packet dma structures */
    cmicx_sbus_dma_data_t   sbus_dma[CMICX_NUM_SBUS_DMA_PER_CMC];
    cmicx_packet_dma_data_t packet_dma[CMICX_NUM_PACKET_DMA_PER_CMC];

} cmicx_cmc_t;


/* structure definition for the common block inside the cmicx */
typedef struct cmicx_common_struct {

    /* identification string for the common structure */
    char id_string[CMIC_CMC_ID_STRING_LENGTH];

    /* schan and schan fifo structures in the common struct */
    cmicx_schan_data_t schan[CMICX_NUM_SCHAN_IN_COMMON];
    /* cmicx_schan_fifo_data_t schan_fifo; */

} cmicx_common_t;


/* structure definition for the cmicx module */
typedef struct cmicx_struct {

    /* pcid stuff, including function map table for pcid data access, and pcid memory space */
    int                last_pcid_register;
    addr_t             pcid_addrs[      NUM_PCID_REGISTERS];
    pcid_read_func_t  *pcid_read_funcs[ NUM_PCID_REGISTERS];
    pcid_write_func_t *pcid_write_funcs[NUM_PCID_REGISTERS];
    int                last_pcid_memory_address_index;
    addr_t             pcid_memory_addresses[MAX_PCID_MEM_VALUES];
    unsigned char      pcid_memory[          MAX_PCID_MEM_VALUES];

    /* switch register and memory data */
    int                last_switch_register;
    addr_t             switch_register_addresses[CMICX_MAX_SWITCH_REGISTERS];
    reg_t              switch_registers[         CMICX_MAX_SWITCH_REGISTERS];
    int                last_switch_memory;
    addr_t             switch_memory_addresses[CMICX_MAX_SWITCH_MEMORIES];
    reg_t             *switch_memories[        CMICX_MAX_SWITCH_MEMORIES];

    /* sub-structures that are duplicated in the cmicx (cmc, etc) */
    cmicx_cmc_t    cmc0;
    cmicx_cmc_t    cmc1;
    cmicx_common_t common;

    /* schan functionality regs */
    bool  enable_pio_write_non_posted;
    char  sbus_ring_arb_ctrl_schan_common_ch_weight[CMICX_NUM_SCHAN_IN_COMMON];
    char  sbus_ring_arb_ctrl_schan_common_fifo_weight;
    reg_t sbus_timeout_reg;
    reg_t sbus_ring_map_0_7_reg;
    reg_t sbus_ring_map_8_15_reg;
    reg_t sbus_ring_map_16_23_reg;
    reg_t sbus_ring_map_24_31_reg;
    reg_t sbus_ring_map_32_39_reg;
    reg_t sbus_ring_map_40_47_reg;
    reg_t sbus_ring_map_48_55_reg;
    reg_t sbus_ring_map_56_63_reg;
    reg_t sbus_ring_map_64_71_reg;
    reg_t sbus_ring_map_72_79_reg;
    reg_t sbus_ring_map_80_87_reg;
    reg_t sbus_ring_map_88_95_reg;
    reg_t sbus_ring_map_96_103_reg;
    reg_t sbus_ring_map_104_111_reg;
    reg_t sbus_ring_map_112_119_reg;
    reg_t sbus_ring_map_120_127_reg;

    /* sbus dma functionality variables */
    char sbus_ring_arb_ctrl_sbusdma_cmc0_ch_weight[CMICX_NUM_SBUS_DMA_PER_CMC];
    char sbus_ring_arb_ctrl_sbusdma_cmc1_ch_weight[CMICX_NUM_SBUS_DMA_PER_CMC];

    /* packet dma functionality regs */
    bool ip_2_ep_loopback_enable;

} cmicx_t;


/* cmicx top-level functions */
bool cmicx_init(void);

/* switch register/memory read/write functions */
bool cmicx_switch_reg_read(addr_t addr,reg_t *val);
bool cmicx_switch_reg_write(addr_t addr,reg_t val);
void cmicx_switch_registers_dump(void);
bool cmicx_switch_mem_read(addr_t addr,reg_t *mem,int req,int *resp);
bool cmicx_switch_mem_write(addr_t addr,reg_t *mem,int amount);
void cmicx_switch_memories_dump(void);

/* control register read/write functions */
pcid_read_func_t  cmicx_sim_control_reg_read;
pcid_write_func_t cmicx_sim_control_reg_write;


#endif   /* CMICX_H */

