# $Id: Makefile,v 1.3 2012/01/21 00:23:04 reldeeb Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for PTP Common Library
#

LOCALDIR = src/bcm/common/ptp

include ${SDK}/make/Make.config

lib = libptp_common

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
