# $Id: Makefile,v 1.1 2007/02/14 22:58:15 jwd Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/scorpion

include ${SDK}/make/Make.config

lib = libscorpion

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
