/*
 * $Id: cint_logger_tests_tokens.c
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:        cint_logger_tests_tokens.c
 * Purpose:     CINT logger tests tokens
 */


CINT_LOGGER_TESTS_TOKEN(NONE)

CINT_LOGGER_TESTS_TOKEN(UNIT)

CINT_LOGGER_TESTS_TOKEN(API)

CINT_LOGGER_TESTS_TOKEN(TEST_TID_LO)
CINT_LOGGER_TESTS_TOKEN(TEST_TID_HI)

CINT_LOGGER_TESTS_TOKEN(DECL_ARGS)
CINT_LOGGER_TESTS_TOKEN(DECL_ARGS_EXPECTED_BEFORE)
CINT_LOGGER_TESTS_TOKEN(DECL_ARGS_EXPECTED_AFTER)
CINT_LOGGER_TESTS_TOKEN(DECL_ARGS_CHANGES)

CINT_LOGGER_TESTS_TOKEN(INIT_ARGS)
CINT_LOGGER_TESTS_TOKEN(INIT_ARGS_EXPECTED_BEFORE)
CINT_LOGGER_TESTS_TOKEN(INIT_ARGS_EXPECTED_AFTER)
CINT_LOGGER_TESTS_TOKEN(INIT_ARGS_CHANGES)

CINT_LOGGER_TESTS_TOKEN(DECL_LOCAL_VARIABLES)

CINT_LOGGER_TESTS_TOKEN(ARGS_CHECK_BEFORE)
CINT_LOGGER_TESTS_TOKEN(ARGS_CHECK_BEFORE_RES)
CINT_LOGGER_TESTS_TOKEN(ARGS_CHANGES)
CINT_LOGGER_TESTS_TOKEN(ARGS_CHECK_AFTER)
CINT_LOGGER_TESTS_TOKEN(ARGS_CHECK_AFTER_RES)
CINT_LOGGER_TESTS_TOKEN(ARGS_CHECK_AFTER_INCL_CHANGES)
CINT_LOGGER_TESTS_TOKEN(ARGS_CHECK_AFTER_INCL_CHANGES_RES)

CINT_LOGGER_TESTS_TOKEN(API_CALL)

CINT_LOGGER_TESTS_TOKEN(DECL_ARG_PTRS)
CINT_LOGGER_TESTS_TOKEN(SET_ARG_PTRS)
CINT_LOGGER_TESTS_TOKEN(CHECK_ARG_PTRS)

CINT_LOGGER_TESTS_TOKEN(RETVAL)
CINT_LOGGER_TESTS_TOKEN(RETVAL_CHECK)

CINT_LOGGER_TESTS_TOKEN(TEST_ITEM)
CINT_LOGGER_TESTS_TOKEN(TEST_ID)

CINT_LOGGER_TESTS_TOKEN(UNKNOWN)

CINT_LOGGER_TESTS_TOKEN(MAX)

