# $Id: $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# Makefile for Tomahawk2 flexport common library

LOCALDIR = src/soc/esw/tomahawk3/flexport

include ${SDK}/make/Make.config

lib = libsoc_tomahawk3_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend


