# $Id: Makefile,v 1.1 2007/08/07 21:37:05 jwd Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/conqueror

include ${SDK}/make/Make.config

lib = libconqueror

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
