# 
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#
# Makefile for Access Control List (ACL) library.
#
LOCALDIR = src/appl/acl

include ${SDK}/make/Make.config

lib = libacl
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
