#
# $Id: Makefile $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/appl/diag/dnx/knet

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxknet

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend