

/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef _DNXF_DATA_MAX_DEVICE_H_

#define _DNXF_DATA_MAX_DEVICE_H_




#ifndef BCM_DNXF_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_PVT_MONITORS (4)


#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_BASE (43410000)


#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_FACTOR (53504)


#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_CORES (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_ALL_BLOCKS (128)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FMAC (48)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FMAC (4)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FSRD (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FSRD (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCH (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCH (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DCH_LINK_GROUPS (3)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCH (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_CCH (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCQ (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_RTP (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_OCCG (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_ECI (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CMIC (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_OTPC (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMACH (0)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMACL (0)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMAC_AC (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMAC_BD (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_DCH (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_DCML (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_LCM (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MCT (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_QRH (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCML (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCML (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_LCM (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_QRH (24)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_QRH_MCLBT_INSTANCES (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DTM_FIFOS (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FSRD (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_PHY_CORE (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_FMACS_IN_FSRD (2)




#endif 

