/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <bcm/types.h>

#include <bcm_int/ltsw/l3_aacl.h>
#include <bcm_int/ltsw/l3_aacl_int.h>
#include <bcm_int/ltsw/mbcm/mbcm.h>
#include <bcm_int/ltsw/mbcm/l3_aacl.h>
#include <shr/shr_debug.h>

/******************************************************************************
 * Local definitions
 */

#define BSL_LOG_MODULE BSL_LS_BCM_L3

/*!
 * \brief The L3_aacl mbcm drivers.
 */
static mbcm_ltsw_l3_aacl_drv_t mbcm_ltsw_l3_aacl_drv[BCM_MAX_NUM_UNITS];

/******************************************************************************
 * Private functions
 */

/******************************************************************************
 * Public functions
 */

int
mbcm_ltsw_l3_aacl_drv_set(
    int unit,
    mbcm_ltsw_l3_aacl_drv_t *drv)
{
    mbcm_ltsw_l3_aacl_drv_t *local = &mbcm_ltsw_l3_aacl_drv[unit];

    SHR_FUNC_ENTER(unit);


    mbcm_ltsw_drv_init((mbcm_ltsw_drv_t *)local,
                       (mbcm_ltsw_drv_t *)drv,
                       sizeof(*local)/MBCM_LTSW_FNPTR_SZ);

    SHR_EXIT();

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_init(int unit)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_init(unit));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_deinit(int unit)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_deinit(unit));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_validate(
    int unit,
    bcm_l3_aacl_t *aacl,
    bool strict)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_validate(unit, aacl, strict));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_add(
    int unit,
    uint32_t options,
    bcm_l3_aacl_t *aacl)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_add(unit, options, aacl));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_delete(
    int unit,
    bcm_l3_aacl_t *aacl)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_delete(unit, aacl));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_delete_all(
    int unit,
    bcm_l3_aacl_t *aacl)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_delete_all(unit, aacl));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_find(
    int unit,
    bcm_l3_aacl_t *aacl)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_find(unit, aacl));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_traverse(
    int unit,
    bcm_l3_aacl_traverse_cb trav_fn,
    void *user_data)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_traverse(unit, trav_fn, user_data));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_matched_traverse(
    int unit,
    uint32_t flags,
    bcm_l3_aacl_traverse_cb trav_fn,
    void *user_data)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_matched_traverse(unit, flags, trav_fn, user_data));

exit:
    SHR_FUNC_EXIT();
}

int
mbcm_ltsw_l3_aacl_tbl_db_get(
    int unit,
    bcmint_ltsw_l3_aacl_tbl_db_t *tbl_db)
{
    SHR_FUNC_ENTER(unit);

    SHR_IF_ERR_VERBOSE_EXIT
        (mbcm_ltsw_l3_aacl_drv[unit].l3_aacl_tbl_db_get(unit, tbl_db));

exit:
    SHR_FUNC_EXIT();
}
