#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#
# Makefile for dnx/dnx_data subdirectory
#

LOCALDIR = src/soc/dnx/dnx_data

include ${SDK}/make/Make.config


lib = libsoc_dnxdnxdata

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

