# $Id: Makefile,v 1.2 2010/03/15 23:29:33 wyuan Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/titan

include ${SDK}/make/Make.config

lib = libtitan

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
