
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 */
#ifndef _DNXF_DATA_MAX_DEVICE_H_

#define _DNXF_DATA_MAX_DEVICE_H_




#ifndef BCM_DNXF_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif



#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_PVT_MONITORS (4)


#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_BASE (43410000)


#define DNXF_DATA_MAX_DEVICE_GENERAL_PVT_FACTOR (53504)


#define DNXF_DATA_MAX_DEVICE_GENERAL_NOF_CORES (2)


#define DNXF_DATA_MAX_DEVICE_GENERAL_ADAPTER_LIB_VER (5)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_ALL_BLOCKS (302)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FMAC (96)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FMAC (4)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_FSRD (48)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FSRD (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCH (16)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCH (32)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DCH_LINK_GROUPS (4)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CCH (16)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_CCH (32)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCQ (32)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_RTP (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_OCCG (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_ECI (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_CMIC (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MESH_TOPOLOGY (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMACH (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_BRDC_FMACL (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_LCM (16)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_MCT (1)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_QRH (16)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_INSTANCES_DCML (16)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_DCML (32)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_LCM (32)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_QRH (32)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_DTM_FIFOS (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_FSRD (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_LINKS_IN_PHY_CORE (8)


#define DNXF_DATA_MAX_DEVICE_BLOCKS_NOF_FMACS_IN_FSRD (2)




#endif 

