# $Id
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for Firebolt6 SOC driver Library
#

LOCALDIR = src/soc/esw/firebolt6/flexport

include ${SDK}/make/Make.config

lib = libsoc_firebolt6_flexport

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

