/** \file algo/swstate/auto_generated/diagnostic/algo_l2_diagnostic.h
 *
 * sw state functions declarations
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#ifndef __ALGO_L2_DIAGNOSTIC_H__
#define __ALGO_L2_DIAGNOSTIC_H__

#include <soc/dnxc/swstate/dnxc_sw_state_h_includes.h>
#include <soc/dnxc/swstate/dnx_sw_state_dump.h>
#include <soc/dnxc/swstate/dnx_sw_state_size.h>
#include <soc/dnxc/swstate/dnx_sw_state_diagnostic_operation_counters.h>
#include <bcm_int/dnx/algo/swstate/auto_generated/types/algo_l2_types.h>
#include <bcm_int/dnx/algo/l2/algo_l2.h>
#include <bcm_int/dnx/algo/template_mngr/template_mngr.h>
#include <bcm_int/dnx/algo/template_mngr/template_mngr_internal.h>
#if defined(DNX_SW_STATE_DIAGNOSTIC)
typedef enum {
    ALGO_L2_DB_INFO,
    ALGO_L2_DB_EVENT_FORWARDING_PROFILE_INFO,
    ALGO_L2_DB_VSI_LEARNING_PROFILE_INFO,
    ALGO_L2_DB_VSI_AGING_PROFILE_INFO,
    ALGO_L2_DB_INFO_NOF_ENTRIES
} sw_state_algo_l2_db_layout_e;


extern dnx_sw_state_diagnostic_info_t algo_l2_db_info[SOC_MAX_NUM_DEVICES][ALGO_L2_DB_INFO_NOF_ENTRIES];

extern const char* algo_l2_db_layout_str[ALGO_L2_DB_INFO_NOF_ENTRIES];
int algo_l2_db_dump(
    int unit, dnx_sw_state_dump_filters_t filters);

int algo_l2_db_event_forwarding_profile_dump(
    int unit, dnx_sw_state_dump_filters_t filters);

int algo_l2_db_vsi_learning_profile_dump(
    int unit, dnx_sw_state_dump_filters_t filters);

int algo_l2_db_vsi_aging_profile_dump(
    int unit, dnx_sw_state_dump_filters_t filters);

#endif /* DNX_SW_STATE_DIAGNOSTIC */

#endif /* __ALGO_L2_DIAGNOSTIC_H__ */
