
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __DNXF_LAYOUT_H__
#define __DNXF_LAYOUT_H__

#include <include/soc/dnxc/swstate/types/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int dnxf_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_DNXF_STATE = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(DNXF_MODULE_ID, 0),
    DNX_SW_STATE_DNXF_STATE__INFO,
    DNX_SW_STATE_DNXF_STATE__MODID,
    DNX_SW_STATE_DNXF_STATE__MC,
    DNX_SW_STATE_DNXF_STATE__LB,
    DNX_SW_STATE_DNXF_STATE__PORT,
    DNX_SW_STATE_DNXF_STATE__CABLE_SWAP,
    DNX_SW_STATE_DNXF_STATE__INTR,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB,
    DNX_SW_STATE_DNXF_STATE__SYNCE,
    DNX_SW_STATE_DNXF_STATE__SYSTEM_UPGRADE,
    DNX_SW_STATE_DNXF_STATE__HARD_RESET,
    DNX_SW_STATE_DNXF_STATE__INFO__ACTIVE_CORE_BMP,
    DNX_SW_STATE_DNXF_STATE__INFO__SOFT_INIT_REG_ABOVE_64_VAL,
    DNX_SW_STATE_DNXF_STATE__MODID__LOCAL_MAP,
    DNX_SW_STATE_DNXF_STATE__MODID__GROUP_MAP,
    DNX_SW_STATE_DNXF_STATE__MODID__MODID_TO_GROUP_MAP,
    DNX_SW_STATE_DNXF_STATE__MODID__LOCAL_MAP__VALID,
    DNX_SW_STATE_DNXF_STATE__MODID__LOCAL_MAP__MODULE_ID,
    DNX_SW_STATE_DNXF_STATE__MODID__GROUP_MAP__RAW,
    DNX_SW_STATE_DNXF_STATE__MC__MODE,
    DNX_SW_STATE_DNXF_STATE__MC__ID_MAP,
    DNX_SW_STATE_DNXF_STATE__MC__NOF_MC_GROUPS_CREATED,
    DNX_SW_STATE_DNXF_STATE__LB__GROUP_TO_FIRST_LINK,
    DNX_SW_STATE_DNXF_STATE__PORT__CL72_CONF,
    DNX_SW_STATE_DNXF_STATE__PORT__PHY_LANE_CONFIG,
    DNX_SW_STATE_DNXF_STATE__PORT__IS_CONNECTED_TO_REPEATER,
    DNX_SW_STATE_DNXF_STATE__PORT__ISOLATION_STATUS_STORED,
    DNX_SW_STATE_DNXF_STATE__PORT__ORIG_ISOLATED_STATUS,
    DNX_SW_STATE_DNXF_STATE__CABLE_SWAP__IS_ENABLE,
    DNX_SW_STATE_DNXF_STATE__CABLE_SWAP__IS_MASTER,
    DNX_SW_STATE_DNXF_STATE__INTR__FLAGS,
    DNX_SW_STATE_DNXF_STATE__INTR__STORM_TIMED_COUNT,
    DNX_SW_STATE_DNXF_STATE__INTR__STORM_TIMED_PERIOD,
    DNX_SW_STATE_DNXF_STATE__INTR__STORM_NOMINAL,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__LINK_TO_FMAC_LANE_MAP,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__MAP_SIZE,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__LANE2SERDES,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__SERDES2LANE,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__LANE2SERDES__RX_ID,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__LANE2SERDES__TX_ID,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__SERDES2LANE__RX_ID,
    DNX_SW_STATE_DNXF_STATE__LANE_MAP_DB__SERDES_MAP__SERDES2LANE__TX_ID,
    DNX_SW_STATE_DNXF_STATE__SYNCE__MASTER_SYNCE_ENABLED,
    DNX_SW_STATE_DNXF_STATE__SYNCE__SLAVE_SYNCE_ENABLED,
    DNX_SW_STATE_DNXF_STATE__SYNCE__MASTER_SET1_SYNCE_ENABLED,
    DNX_SW_STATE_DNXF_STATE__SYNCE__SLAVE_SET1_SYNCE_ENABLED,
    DNX_SW_STATE_DNXF_STATE__SYSTEM_UPGRADE__STATE_0,
    DNX_SW_STATE_DNXF_STATE__SYSTEM_UPGRADE__STATE_1,
    DNX_SW_STATE_DNXF_STATE__SYSTEM_UPGRADE__STATE_2,
    DNX_SW_STATE_DNXF_STATE__HARD_RESET__CALLBACK,
    DNX_SW_STATE_DNXF_STATE__HARD_RESET__USERDATA,
    
    DNX_SW_STATE_DNXF_STATE_NOF_PARAMS,
} dnxc_sw_state_layout_dnxf_node_id_e;

#endif 
