# $Id:$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/xgs4

include ${SDK}/make/Make.config

lib = libxgs4

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
