#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/kbp

include ${SDK}/make/Make.config

subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxkbp

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

