/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from Logical Table definition files.
 *
 * Tool: $SDK/INTERNAL/fltg/bin/fltg
 *
 * Edits to this file will be lost when it is regenerated.
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#ifndef BCMLTD_CHIP_STR_H
#define BCMLTD_CHIP_STR_H
#ifndef DOXYGEN_IGNORE_AUTOGEN
/*+replace reverse */
#include "../str/bcmltd_common_str.h"
#include "../str/bcm56996_a0/bcm56996_a0_ltd_str.h"
#include "../str/bcm56990_b0/bcm56990_b0_ltd_str.h"
#include "../str/bcm56990_a0/bcm56990_a0_ltd_str.h"
#include "../str/bcm56880_a0/dna_4_6_6/bcm56880_a0_dna_4_6_6_ltd_str.h"
#include "../str/bcm56880_a0/bcm56880_a0_ltd_str.h"
#include "../str/bcm56780_a0/ina_2_4_13/bcm56780_a0_ina_2_4_13_ltd_str.h"
#include "../str/bcm56780_a0/dna_2_4_13/bcm56780_a0_dna_2_4_13_ltd_str.h"
#include "../str/bcm56780_a0/bcm56780_a0_ltd_str.h"
/*-replace*/
#endif /* DOXYGEN_IGNORE_AUTOGEN */
#endif /* BCMLTD_CHIP_STR_H */
