#
# 
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/portmod/pms

include ${SDK}/make/Make.config

lib = libsoc_portmod_pms

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
