# $Id: Makefile,v 1.1.2.1 2013/02/13 10:41:10 wyuan Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM Trident3 driver Library
#

LOCALDIR = src/bcm/esw/trident3

include ${SDK}/make/Make.config

lib = libtrident3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
