# $Id: Makefile,v 1.23 2012/09/21 14:07:38 schacher Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#
LOCALDIR = src/soc/dnxf/cmn

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxfcmn

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
