# $Id: Makefile,v 1.1.2.1 2012/12/27 10:09:57 ako Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/hurricane3

include ${SDK}/make/Make.config

lib = libhurricane3

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
