#
# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/appl/diag/dnx/pp/kleap/auto_generated

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnx_pp_kleap_auto_generated

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
