
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 *
 */

#ifndef _SOC_DRV_CHIP_H
#define _SOC_DRV_CHIP_H

/*
 * Note: ESW devices need similar SOC_IS definitions
 */
typedef enum {
    SOC_INFO_CHIP_TYPE_HERCULES15 = 1, /* only use non-zero values to be able to skip further compares */
    SOC_INFO_CHIP_TYPE_FIREBOLT,
    SOC_INFO_CHIP_TYPE_FELIX,
    SOC_INFO_CHIP_TYPE_HELIX,       /* 5630x */
    SOC_INFO_CHIP_TYPE_GOLDWING,
    SOC_INFO_CHIP_TYPE_HUMV,
    SOC_INFO_CHIP_TYPE_BRADLEY,
    SOC_INFO_CHIP_TYPE_RAPTOR,
    SOC_INFO_CHIP_TYPE_FELIX15,     /* 5611x */
    SOC_INFO_CHIP_TYPE_HELIX15,     /* 5631x */
    SOC_INFO_CHIP_TYPE_FIREBOLT2,
    SOC_INFO_CHIP_TYPE_TRIUMPH,
    SOC_INFO_CHIP_TYPE_TRIUMPH3,
    SOC_INFO_CHIP_TYPE_HELIX4,
    SOC_INFO_CHIP_TYPE_SABER2,
    SOC_INFO_CHIP_TYPE_METROLITE,
    SOC_INFO_CHIP_TYPE_RAVEN,
    SOC_INFO_CHIP_TYPE_GREYHOUND,
    SOC_INFO_CHIP_TYPE_TRIDENT3,
    SOC_INFO_CHIP_TYPE_TOMAHAWK3,
    SOC_INFO_CHIP_TYPE_HELIX5,
    SOC_INFO_CHIP_TYPE_MAVERICK2,
    /** SAND devices section only - Do not add other devices */
    SOC_INFO_CHIP_TYPE_SAND_FIRST,
    SOC_INFO_CHIP_TYPE_ARADPLUS = SOC_INFO_CHIP_TYPE_SAND_FIRST,

    SOC_INFO_CHIP_TYPE_JERICHO_FIRST,
    SOC_INFO_CHIP_TYPE_JERICHO = SOC_INFO_CHIP_TYPE_JERICHO_FIRST,
    SOC_INFO_CHIP_TYPE_QMX,
    SOC_INFO_CHIP_TYPE_JERICHO_PLUS,
    SOC_INFO_CHIP_TYPE_JERICHO_LAST = SOC_INFO_CHIP_TYPE_JERICHO_PLUS,

    SOC_INFO_CHIP_TYPE_QAX_FIRST,
    SOC_INFO_CHIP_TYPE_QAX = SOC_INFO_CHIP_TYPE_QAX_FIRST,
    SOC_INFO_CHIP_TYPE_KALIA,
    SOC_INFO_CHIP_TYPE_QUX,
    SOC_INFO_CHIP_TYPE_QAX_LAST = SOC_INFO_CHIP_TYPE_QUX,
    SOC_INFO_CHIP_TYPE_DNX1_LAST = SOC_INFO_CHIP_TYPE_QAX_LAST,

    /** DNX2 devices section only - Do not add other devices */
    SOC_INFO_CHIP_TYPE_DNX2_FIRST,
    SOC_INFO_CHIP_TYPE_JERICHO2 = SOC_INFO_CHIP_TYPE_DNX2_FIRST,
    SOC_INFO_CHIP_TYPE_J2C,
    SOC_INFO_CHIP_TYPE_J2P,
    SOC_INFO_CHIP_TYPE_J2X,
    SOC_INFO_CHIP_TYPE_Q2A,
    SOC_INFO_CHIP_TYPE_DNX2_LAST = SOC_INFO_CHIP_TYPE_Q2A,
    /** DNX2 devices section only - END */
    /** DNXF devices section only - Do not add other devices */
    SOC_INFO_CHIP_TYPE_DNXF_FIRST,
    SOC_INFO_CHIP_TYPE_RAMON = SOC_INFO_CHIP_TYPE_DNXF_FIRST,
    SOC_INFO_CHIP_TYPE_FE3200,
    SOC_INFO_CHIP_TYPE_DNXF_LAST = SOC_INFO_CHIP_TYPE_FE3200,
    SOC_INFO_CHIP_TYPE_SAND_LAST = SOC_INFO_CHIP_TYPE_DNXF_LAST,
    /** DNXF devices section only - END */
    SOC_INFO_CHIP_TYPE_TKDUMMY,
    SOC_INFO_CHIP_TYPE_SCORPION,
    SOC_INFO_CHIP_TYPE_ACP,
    SOC_INFO_CHIP_TYPE_APACHE,
    SOC_INFO_CHIP_TYPE_HURRICANE3,
    SOC_INFO_CHIP_TYPE_HURRICANE4,
    SOC_INFO_CHIP_TYPE_GREYHOUND2,
    /* TRIDENT2PLUS variants */
    SOC_INFO_CHIP_TYPE_TITAN2PLUS,
    /* TITANHAWK variants */
    SOC_INFO_CHIP_TYPE_TITANHAWK,
    SOC_INFO_CHIP_TYPE_TOMAHAWKPLUS,
    SOC_INFO_CHIP_TYPE_MONTEREY,
    SOC_INFO_CHIP_TYPE_TOMAHAWK2,
    SOC_INFO_CHIP_TYPE_TITANHAWK2,
    SOC_INFO_CHIP_TYPE_FIREBOLT6,
    SOC_INFO_CHIP_TYPE_LT_SWITCHES
} soc_chip_e;
#endif
