# $Id: Makefile,v 1.1 2007/03/21 23:14:50 lokner Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/trx

include ${SDK}/make/Make.config

lib = libtrx

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
