/* 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
*/
#ifndef UI_PURE_DEFI_LINE_TEVB_INCLUDED
/* { */
#define UI_PURE_DEFI_LINE_TEVB_INCLUDED
/*
 * Note:
 * the following definitions must range between PARAM_LINE_TEVB_START_RANGE_ID (9100)
 * and PARAM_LINE_TEVB_END_RANGE_ID (9200).
 * See ui_pure_defi.h
 */
#define PARAM_TEVB_MEM_ID                       (PARAM_LINE_TEVB_START_RANGE_ID + 0)
#define PARAM_TEVB_MEM_READ_ID                  (PARAM_LINE_TEVB_START_RANGE_ID + 1)
#define PARAM_TEVB_MEM_WRITE_ID                 (PARAM_LINE_TEVB_START_RANGE_ID + 2)
#define PARAM_TEVB_MEM_DATA_ID                  (PARAM_LINE_TEVB_START_RANGE_ID + 3)
#define PARAM_TEVB_VERBOSE_ID                   (PARAM_LINE_TEVB_START_RANGE_ID + 4)
#define PARAM_TEVB_FPGA_ID                      (PARAM_LINE_TEVB_START_RANGE_ID + 5)
#define PARAM_TEVB_FPGA_DOWNLOAD_ID             (PARAM_LINE_TEVB_START_RANGE_ID + 6)

#define PARAM_TEVB_FLASH_ID                     (PARAM_LINE_TEVB_START_RANGE_ID + 7)
#define PARAM_TEVB_FLASH_BURN_ID                (PARAM_LINE_TEVB_START_RANGE_ID + 8)
#define PARAM_TEVB_FLASH_DOWNLOAD_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 9)
#define PARAM_TEVB_FLASH_ERASE_ID               (PARAM_LINE_TEVB_START_RANGE_ID + 10)
#define PARAM_TEVB_FLASH_FILENAME_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 11)

#define PARAM_TEVB_FLASH_DFFS_ID                (PARAM_LINE_TEVB_START_RANGE_ID + 12)
#define PARAM_TEVB_FLASH_DFFS_ADD_ATTR_ID       (PARAM_LINE_TEVB_START_RANGE_ID + 13)
#define PARAM_TEVB_FLASH_DFFS_DIR_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 17)
#define PARAM_TEVB_FLASH_DFFS_PRINT_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 19)
#define PARAM_TEVB_FLASH_DFFS_DIR_FORMAT_ID     (PARAM_LINE_TEVB_START_RANGE_ID + 21)
#define PARAM_TEVB_FLASH_DFFS_DEL_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 22)
#define PARAM_TEVB_FLASH_DFFS_DIAGNOSTICS_ID    (PARAM_LINE_TEVB_START_RANGE_ID + 23)
#define PARAM_TEVB_FLASH_DFFS_ATTR1_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 24)
#define PARAM_TEVB_FLASH_DFFS_ATTR2_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 25)
#define PARAM_TEVB_FLASH_DFFS_ATTR3_ID          (PARAM_LINE_TEVB_START_RANGE_ID + 26)
#define PARAM_TEVB_FLASH_DFFS_NAME_ID           (PARAM_LINE_TEVB_START_RANGE_ID + 27)
#define PARAM_TEVB_FLASH_DFFS_PRINT_SIZE_ID     (PARAM_LINE_TEVB_START_RANGE_ID + 28)
#define PARAM_TEVB_FLASH_DFFS_COMMENT_ID        (PARAM_LINE_TEVB_START_RANGE_ID + 29)
#define PARAM_TEVB_FLASH_DFFS_VER_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 30)
#define PARAM_TEVB_FLASH_DFFS_SHOW_COMMENT_ID   (PARAM_LINE_TEVB_START_RANGE_ID + 31)
#define PARAM_TEVB_FLASH_DFFS_DATE_ID           (PARAM_LINE_TEVB_START_RANGE_ID + 32)
#define PARAM_TEVB_FLASH_DFFS_ADD_COMMENT_ID    (PARAM_LINE_TEVB_START_RANGE_ID + 33)
#define PARAM_TEVB_FLASH_DFFS_DLD_ID            (PARAM_LINE_TEVB_START_RANGE_ID + 34)

#define PARAM_TEVB_COMPRESSED_ID                (PARAM_LINE_TEVB_START_RANGE_ID + 35)
#define PARAM_TEVB_FLASH_DIAGNOSTICS_ID         (PARAM_LINE_TEVB_START_RANGE_ID + 36)

/* } */
#endif
