/* 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
*/


#ifndef __UI_PURE_DEFI_SWP_P_API_INCLUDED__
/* { */
#define __UI_PURE_DEFI_SWP_P_API_INCLUDED__

#include <soc/dpp/SAND/Utils/sand_header.h>


#define UI_MC_GRP_MEMBERS_MAX   10

/*
 * Note:
 * the following definitions must range between PARAM_SWP_P_API_START_RANGE_ID
 * and PARAM_SWP_P_API_END_RANGE_ID.
 * See ui_pure_defi.h
 */
typedef enum
{
  PARAM_SWP_P_SSR_SAVE_ID = PARAM_SWP_P_START_RANGE_ID,
  PARAM_SWP_P_SSR_RESTORE_ID,
  PARAM_SWP_P_SSR_ID,
  PARAM_SWP_P_FE_ID,
  PARAM_SWP_P_FE_GRACEFUL_SHUT_DOWN_ID,
  PARAM_SWP_P_FE_GRACEFUL_SHUT_DOWN_FE_ID,
  PARAM_SWP_P_FE_GRACEFUL_RESTORE_ID,
  PARAM_SWP_P_FE_GRACEFUL_RESTORE_FE_ID,
  PARAM_SWP_P_DIAG_NIF_COUNTERS_GET_NIF_COUNTERS_GET_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_RESOLUTION_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_TRAFFIC_SRC_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_TX_PRBS_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_CRC_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_PRBS_DURATION_MIN_SEC_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_LANE_NDX_INDEX_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_LANE_NDX_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_EYE_SCAN_RUN_INFO_NOF_LANE_NDX_ENTRIES_ID,
  PARAM_SWP_P_SRD_EYE_SCAN_RUN_SRD_PRBS_MODE_SET_MODE_ID,
  PARAM_SWP_P_DIAGNOSTICS_ID,
  PARAM_SWP_P_MC_GRP_OPEN_MC_GRP_OPEN_ID,
  PARAM_SWP_P_MC_GRP_OPEN_MC_GRP_OPEN_MC_ID_ID,
  PARAM_SWP_P_MC_GRP_OPEN_MC_GRP_OPEN_MC_TYPE_ID,
  PARAM_SWP_P_MC_GRP_OPEN_MC_GRP_OPEN_MC_GRP_MEMBERS_ID,
  PARAM_SWP_P_MC_GRP_OPEN_MC_GRP_OPEN_PER_MEMBER_CUD_ID,
  PARAM_SWP_P_MC_GRP_CLOSE_MC_GRP_CLOSE_ID,
  PARAM_SWP_P_MC_GRP_CLOSE_MC_GRP_CLOSE_MC_TYPE_ID,
  PARAM_SWP_P_MC_GRP_CLOSE_MC_GRP_CLOSE_MC_ID_ID,
  PARAM_SWP_P_MC_GRP_GET_MC_GRP_GET_ID,
  PARAM_SWP_P_MC_GRP_GET_MC_GRP_GET_MC_ID_ID,
  PARAM_SWP_P_MC_GRP_GET_MC_GRP_GET_MC_TYPE_ID,
  PARAM_SWP_P_API_MULTICAST_ID,
  PARAM_SWP_P_TM_VSQ_TAIL_DROP_APP_TM_VSQ_TAIL_DROP_APP_ID,
  PARAM_SWP_P_TM_VSQ_TAIL_DROP_APP_TM_VSQ_TAIL_DROP_APP_SILENT_ID,
  PARAM_SWP_P_TM_VSQ_WRED_PER_STAG_APP_TM_VSQ_WRED_PER_STAG_APP_ID,
  PARAM_SWP_P_TM_VSQ_WRED_PER_STAG_APP_TM_VSQ_WRED_PER_STAG_APP_SILENT_ID,
  PARAM_SWP_P_TM_VSQ_APP_TM_VSQ_APP_ID,
  PARAM_SWP_P_TM_VSQ_APP_TM_VSQ_APP_SILENT_ID,
  PARAM_SWP_P_TM_VSQ_ID,
  PARAM_SWP_P_TM_ISP_SCHED_SET_TM_ISP_SCHED_SET_ID,
  PARAM_SWP_P_TM_ISP_SCHED_SET_TM_ISP_SCHED_SET_PORT_NDX_ID,
  PARAM_SWP_P_TM_ISP_SCHED_SET_TM_ISP_SCHED_SET_OVERALL_RATE_MBPS_ID,
  PARAM_SWP_P_TM_ISP_SCHED_SET_TM_ISP_SCHED_SET_SILENT_ID,
  PARAM_SWP_P_TM_QOS_INGR_ID,
  PARAM_SWP_P_TM_SCHEDULING_SCHEMES_OPEN_TM_SCHEDULING_SCHEMES_OPEN_ID,
  /*
   *  Must be the last
   */
  PARAM_SWP_P_LAST = PARAM_SWP_P_END_RANGE_ID
}
PARAM_SWP_P_API_IDS;
/* } */

#include <soc/dpp/SAND/Utils/sand_footer.h>


/* } __UI_PURE_DEFI_SWP_P_API_INCLUDED__*/
#endif
