/* 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
*/
#ifndef UI_PURE_DEFI_FAP10M_INCLUDED
/* { */
#define UI_PURE_DEFI_FAP10M_INCLUDED
/*
 * Note:
 * the following definitions must range between PARAM_FAP10M_START_RANGE_ID (800)
 * and PARAM_FAP10M_END_RANGE_ID (1399).
 * See ui_pure_defi.h
 */

#define PARAM_FAP10M_LDU_READ_ID                      819
#define PARAM_FAP10M_LDU_WRITE_ID                     820
#define PARAM_FAP10M_GENRAL_API_ID                    821
#define PARAM_FAP10M_DEFEREED_API_ID                  822
#define PARAM_FAP10M_CELL_API_ID                      823
#define PARAM_FAP10M_LINKS_API_ID                     824
#define PARAM_FAP10M_ROUTING_API_ID                   825
#define PARAM_FAP10M_DIAGNOSTICS_API_ID               826
#define PARAM_FAP10M_STATISTICS_API_ID                827
#define PARAM_FAP10M_SET_DEVICE_ACCESS_ID             828

#define PARAM_FAP10M_REMAIN_OFF_ID                    829
#define PARAM_FAP10M_RESET_DEVICE_ID                  830
#define PARAM_FAP10M_START_DRIVER_ID                  831
#define PARAM_FAP10M_SHUTDOWN_DRIVER_ID               832
#define PARAM_FAP10M_REGISTER_DEVICE_ID               833
#define PARAM_FAP10M_UNREGISTER_DEVICE_ID             834
#define PARAM_FAP10M_CLEAR_DEVICE_PENDING_SERVICES_ID 835
#define PARAM_FAP10M_STOP_POLLING_TRANSACTON_ID       836
#define PARAM_FAP10M_START_AND_REGISTER_ID            837
#define PARAM_FAP10M_UNREGISTER_AND_SHUTDOWN_ID       838
#define PARAM_FAP10M_PRINT_DRIVER_INFORMATION_ID      839

#define PARAM_FAP10M_PHYSICAL_WRITE_ID                840
#define PARAM_FAP10M_LOGICAL_WRITE_ID                 841
#define PARAM_FAP10M_PHYSICAL_READ_ID                 842
#define PARAM_FAP10M_DEFERRED_PHYSICAL_READ_ID        843
#define PARAM_FAP10M_LOGICAL_READ_ID                  844
#define PARAM_FAP10M_DEFERRED_LOGICAL_READ_ID         845
#define PARAM_FAP10M_PHYSICAL_DIRECT_ID               846
#define PARAM_FAP10M_PHYSICAL_INDIRECT_ID             847
#define PARAM_FAP10M_PHYSICAL_OFFSET_ID               848
#define PARAM_FAP10M_PHYSICAL_SIZE_ID                 849
#define PARAM_FAP10M_PHYSICAL_DATA_ID                 850
#define PARAM_FAP10M_POLLING_RATE_ID                  851
#define PARAM_FAP10M_FIELD_ID                         852
#define PARAM_FAP10M_SILENT_ID                        854
#define PARAM_FAP10M_DUMP_REGISTERS                   855
#define PARAM_FAP10M_INCLUDE_INDIRECT_TABLES_ID       856
#define PARAM_FAP10M_SKIP_ZEROS_ID                    857
#define PARAM_FAP10M_ENABLE_MSGS_ID                   858
#define PARAM_FAP10M_CNTRL_MSGS_ID                    859
#define PARAM_FAP10M_FIELD_PRINT_ALL_ID               860

#define PARAM_FAP10M_SEND_CELL_ID                     870
#define PARAM_FAP10M_SEND_CELL_FE2_LINK_ID            871
#define PARAM_FAP10M_SEND_CELL_FE3_LINK_ID            872
#define PARAM_FAP10M_SEND_CELL_FE1_LINK_ID            873
#define PARAM_FAP10M_SEND_CELL_DEST_ENTITY_TYPE_ID    874
#define PARAM_FAP10M_SEND_CELL_SRC_CHIP_ID            875
#define PARAM_FAP10M_SEND_CELL_INIT_OUT_LINK_ID       876
#define PARAM_FAP10M_SEND_CELL_BODY_ID                877
#define PARAM_FAP10M_RECV_CELL_ID                     880
#define PARAM_FAP10M_DEFRRED_RECV_CELL_ID             882
#define PARAM_DEFERRED_FAP10M_RECV_CELL_POLL_MODE_ID  883
#define PARAM_DEFERRED_FAP10M_RECV_CELL_INT_MODE_ID   884

#define PARAM_FAP10M_GET_SERDES_PARAMS_ID                   900
#define PARAM_FAP10M_SET_SERDES_PARAMS_ID                   901
#define PARAM_FAP10M_SET_SERDES_PARAMS_SERDES_NUMBER_ID     902
#define PARAM_FAP10M_SET_SERDES_PARAMS_AMPLITUDE_ID         903
#define PARAM_FAP10M_SET_SERDES_PARAMS_COMMON_MODE_ID       904
#define PARAM_FAP10M_SET_SERDES_PARAMS_MAIN_CONTROL_ID      905
#define PARAM_FAP10M_SET_SERDES_PARAMS_POWER_DOWN_RX_TX_ID  906
#define PARAM_FAP10M_SET_SERDES_PARAMS_PRE_EMPHASIS_ID      907
#define PARAM_FAP10M_GET_CONNECTIVITY_MAP_ID                910
#define PARAM_FAP10M_DEFERRED_GET_CONNECTIVITY_MAP_ID       911
#define PARAM_FAP10M_GET_LINKS_STATUS_ID                    912
#define PARAM_FAP10M_DEFERRED_GET_LINKS_STATUS_ID           913
#define PARAM_FAP10M_LIST_OF_LINKS_ID                       914
#define PARAM_FAP10M_SET_SERDES_PD_PARAMS_ID                915
#define PARAM_FAP10M_SERDES_POWER_UP_ID                     916
#define PARAM_FAP10M_LINK_FC_GET_ID                         917
#define PARAM_FAP10M_LINK_FC_SET_ID                          918
#define PARAM_FAP10M_LINK_FC_RX_ID                           919
#define PARAM_FAP10M_LINK_FC_TX_ID                          920

#define PARAM_FAP10M_GET_UNICAST_TABLE_ID             932
#define PARAM_FAP10M_DEFERRED_GET_UNICAST_TABLE_ID    933
#define PARAM_FAP10M_NOF_ROWS_ID                      934
#define PARAM_FAP10M_STARTING_ROW_ID                  935

#define PARAM_FAP10M_GET_LOOPBACK_ID                  950
#define PARAM_FAP10M_SET_LOOPBACK_ID                  951
#define PARAM_FAP10M_LOOPBACK_TYPE_ID                 952
#define PARAM_FAP10M_GET_PRBS_MODE_ID                 953
#define PARAM_FAP10M_SET_PRBS_MODE_ID                 954
#define PARAM_FAP10M_PRBS_CHECKER_LINK_ID             955
#define PARAM_FAP10M_PRBS_GENERATOR_LINK_ID           956
#define PARAM_FAP10M_PRBS_ACTIVATE_GENERATOR_ID       957
#define PARAM_FAP10M_PRBS_ACTIVATE_CHECKER_ID         958

#define PARAM_FAP10M_GET_BER_COUNTERS_ID              959
#define PARAM_FAP10M_DEFERRED_GET_BER_COUNTERS_ID     960
#define PARAM_FAP10M_START_PRBS_TEST_ID               961
#define PARAM_FAP10M_STOP_PRBS_TEST_ID                962

#define PARAM_FAP10M_GET_OPERATIVE_COUNTERS_ID        968
#define PARAM_FAP10M_GET_ALL_COUNTERS_ID              969
#define PARAM_FAP10M_GET_PKT_ADDED_TO_QUEUES_CNT_ID   970
#define PARAM_FAP10M_GET_TAIL_DISCARD_PKT_CNT_ID      971
#define PARAM_FAP10M_GET_HEAD_DELETE_PKT_CNT_ID       972
#define PARAM_FAP10M_GET_GOOD_PKT_CNT_ID              973
#define PARAM_FAP10M_GET_ERRONEOUS_PKT_CNT_ID         974
#define PARAM_FAP10M_DEFERRED_GET_PKT_ADDED_TO_QUEUES_CNT_ID   975
#define PARAM_FAP10M_DEFERRED_GET_TAIL_DISCARD_PKT_CNT_ID      976
#define PARAM_FAP10M_DEFERRED_GET_HEAD_DELETE_PKT_CNT_ID       977
#define PARAM_FAP10M_DEFERRED_GET_GOOD_PKT_CNT_ID              978
#define PARAM_FAP10M_DEFERRED_GET_ERRONEOUS_PKT_CNT_ID         979


#define PARAM_FAP10M_END_PORT_ID_ID                   998
#define PARAM_FAP10M_SET_SCHEDULER_RECYCLE_PORT_ID    999
#define PARAM_FAP10M_SCHEDULER_PORT_API_ID            1000
#define PARAM_FAP10M_SET_SCHEDULER_PORT_ID            1001
#define PARAM_FAP10M_GET_SCHEDULER_PORT_ID            1002
#define PARAM_FAP10M_CLOSE_SCHEDULER_PORT_ID          1003
#define PARAM_FAP10M_SCHEDULER_PORT_ID_ID             1004
#define PARAM_FAP10M_CREDIT_BANDWIDTH_ID              1005
#define PARAM_FAP10M_NOMINAL_BANDWIDTH_ID             1006
#define PARAM_FAP10M_WFQ0_WEIGHT_ID                   1007
#define PARAM_FAP10M_SCHEDULER_API_ID                 1008

#define PARAM_FAP10M_SPATIAL_MULTICAST_API_ID         1009
#define PARAM_FAP10M_SET_SMS_CONFIGURATION_ID         1010
#define PARAM_FAP10M_GET_SMS_CONFIGURATION_ID         1011
#define PARAM_FAP10M_OPEN_SPATIAL_MULTICAST_FLOW_ID   1012
#define PARAM_FAP10M_UPDATE_SPATIAL_MULTICAST_FLOW_ID 1013
#define PARAM_FAP10M_GET_SPATIAL_MULTICAST_FLOW_PARAMS_ID 1014
#define PARAM_FAP10M_CLOSE_SPATIAL_MULTICAST_FLOW_ID  1015
#define PARAM_FAP10M_SPATIAL_MULTICAST_NUM_ID         1016
#define PARAM_FAP10M_SPATIAL_TYPE_ID                  1017
#define PARAM_FAP10M_SM_USE_MAP_CLS_ID                1018
#define PARAM_FAP10M_MAX_BANDWIDTH_ID                 1019
#define PARAM_FAP10M_SM_PERCENT_ID                    1020
#define PARAM_FAP10M_B_SET_SMS_CONFIGURATION_ID       1021
#define PARAM_FAP10M_MAX_GR_BANDWIDTH_ID              1022
#define PARAM_FAP10M_MAX_BE_BANDWIDTH_ID              1023
#define PARAM_FAP10M_MAX_GR_BURST_ID                  1024
#define PARAM_FAP10M_MAX_BE_BURST_ID                  1025
#define PARAM_FAP10M_SPATIAL_ACTIVE_LINKS_GET_ID      1026
#define PARAM_FAP10M_SPATIAL_ACTIVE_LINKS_SET_ID      1027
#define PARAM_FAP10M_SPATIAL_ACTIVE_LINKS_ID          1028
#define PARAM_FAP10M_SPATIAL_SET_IGNORE_BIT7_ID       1029


#define PARAM_FAP10M_SCHEDULER_FLOW_API_ID            1030
#define PARAM_FAP10M_OPEN_SCHEDULER_FLOW_ID           1031
#define PARAM_FAP10M_UPDATE_SCHEDULER_FLOW_ID         1032
#define PARAM_FAP10M_GET_SCHEDULER_FLOW_PARAMS_ID     1033
#define PARAM_FAP10M_CLOSE_SCHEDULER_FLOW_ID          1034
#define PARAM_FAP10M_FLOW_ID_ID                       1035
#define PARAM_FAP10M_SOURCE_FAP_ID_ID                 1036
#define PARAM_FAP10M_INGRESS_QUEUE_ID_ID              1037
#define PARAM_FAP10M_LOW_JITTER_ENABLE_ID             1038
#define PARAM_FAP10M_SUB_FLOW_0_TYPE_ID               1039
#define PARAM_FAP10M_SUB_FLOW_0_VALUE_ID              1040
#define PARAM_FAP10M_SUB_FLOW_1_TYPE_ID               1041
#define PARAM_FAP10M_SUB_FLOW_1_VALUE_ID              1042
#define PARAM_FAP10M_SCHEDULER_RECYCLE_FLOW_WEIGHT_ID 1043
#define PARAM_FAP10M_AGGREGATE_FLOW_ID                1044
#define PARAM_FAP10M_UPDATE_WEIGHT_ID                 1045
#define PARAM_FAP10M_UPDATE_WEIGHT_SUB_INDX_ID        1046
#define PARAM_FAP10M_UPDATE_WEIGHT_WEIGHT_ID          1047


#define PARAM_FAP10M_AUTO_OPEN_FAP_QUEUES_ID          1134
#define PARAM_FAP10M_AUTO_UPDATE_FAP_QUEUES_ID        1135
#define PARAM_FAP10M_AUTO_CLOSE_FAP_QUEUES_ID         1136
#define PARAM_FAP10M_AUTO_OPEN_FAP_FLOWS_ID           1137
#define PARAM_FAP10M_AUTO_UPDATE_FAP_FLOWS_ID         1138
#define PARAM_FAP10M_AUTO_CLOSE_FAP_FLOWS_ID          1139
#define PARAM_FAP10M_MAX_NOF_FAPS_ID                  1140
#define PARAM_FAP10M_MAX_NOF_PORTS_ID                 1141
#define PARAM_FAP10M_FABRIC_CLASS_ID                  1142
#define PARAM_FAP10M_AUTO_QUEUE_TYPES_ID              1143
#define PARAM_FAP10M_AUTO_GET_QUEUE_TYPE_PARAMS_ID    1144
#define PARAM_FAP10M_AUTO_SET_ONE_FLOW_PARAMS_ID      1145
#define PARAM_FAP10M_FABRIC_CLASS_ENTRY_ID            1146
#define PARAM_FAP10M_AUTO_GET_FLOW_PARAMS_ID          1147
#define PARAM_FAP10M_UPDATE_SCHEDULER_RECYCLE_FLOW_ID 1148
#define PARAM_FAP10M_OPEN_SCHEDULER_RECYCLE_FLOW_ID   1149


#define PARAM_FAP10M_RECYCLE_MULTICAST_API_ID         1050
#define PARAM_FAP10M_OPEN_RECYCLE_INTERNAL_NODE_ID    1051
#define PARAM_FAP10M_OPEN_RECYCLE_LAST_NODE_ID        1052
#define PARAM_FAP10M_CLOSE_RECYCLE_NODE_ID            1053
#define PARAM_FAP10M_OPEN_RECYCLING_QUEUE_ID          1054
#define PARAM_FAP10M_CLOSE_RECYCLING_QUEUE_ID         1055
#define PARAM_FAP10M_TREE_ID_ID                       1056
#define PARAM_FAP10M_NEXT_TREE_ID_ID                  1057
#define PARAM_FAP10M_RECYCLE_Q_INDEX_ID               1058
#define PARAM_FAP10M_QUEUES_ID_ID                     1059
#define PARAM_FAP10M_RECYCLE_Q_INDEX_0_ID             1060
#define PARAM_FAP10M_RECYCLE_Q_INDEX_1_ID             1061
#define PARAM_FAP10M_GET_RECYCLING_QUEUE_ID           1062
#define PARAM_FAP10M_GET_RECYCLE_NODE_ID              1063
#define PARAM_FAP10M_MULTICAST_API_ID                 1064
#define PARAM_FAP10M_UPDATE_SCHEDULER_FLOW_QOS_ID     1065

#define PARAM_FAP10M_QUEUE_ID_ALLOCATOR_API_ID        1069
#define PARAM_FAP10M_SET_QUEUE_ID_RANGE_ID            1070
#define PARAM_FAP10M_ALLOC_QUEUE_ID_BLOCK_ID          1071
#define PARAM_FAP10M_FREE_QUEUE_ID_ID                 1072
#define PARAM_FAP10M_MIN_QUEUE_ID_ID                  1073
#define PARAM_FAP10M_MAX_QUEUE_ID_ID                  1074
#define PARAM_FAP10M_NOF_QUEUES_ID                    1075
#define PARAM_FAP10M_QUEUE_BASE_ID_ID                 1076
#define PARAM_FAP10M_PRINT_ALLOC_QUEUE_ID             1077
#define PARAM_FAP10M_GET_QUEUE_SIZE_ID                1078
#define PARAM_FAP10M_GET_NON_EMPTY_QUEUES_ID          1079


#define PARAM_FAP10M_INGRESS_QUEUE_API_ID             1089
#define PARAM_FAP10M_SET_QUEUE_LABELING_ID            1090
#define PARAM_FAP10M_GET_QUEUE_LABELING_ID            1091
#define PARAM_FAP10M_OPEN_QUEUE_ID                    1092
#define PARAM_FAP10M_UPDATE_QUEUE_ID                  1093
#define PARAM_FAP10M_GET_QUEUE_PARAMS_ID              1094
#define PARAM_FAP10M_CLOSE_QUEUE_ID                   1095
#define PARAM_FAP10M_TARGET_FAP_ID_ID                 1096
#define PARAM_FAP10M_BASE_QUEUE_ID_ID                 1097
#define PARAM_FAP10M_QUEUE_ID_ID                      1099
#define PARAM_FAP10M_TARGET_FLOW_ID_ID                1100
#define PARAM_FAP10M_QUEUE_TYPE_ID                    1101
#define PARAM_FAP10M_QUEUE_LABEL_TYPE_ID              1102

#define PARAM_FAP10M_FLOW_ID_ALLOCATOR_API_ID         1110
#define PARAM_FAP10M_SET_SCHEDULER_FLOW_ID_RANGE_ID   1111
#define PARAM_FAP10M_ALLOC_SCHEDULER_FLOW_ID_ID       1112
#define PARAM_FAP10M_FREE_SCHEDULER_FLOW_ID_ID        1113
#define PARAM_FAP10M_MIN_FLOW_ID_ID                   1114
#define PARAM_FAP10M_MAX_FLOW_ID_ID                   1115
#define PARAM_FAP10M_PRINT_ALLOC_FLOW_ID              1116
#define PARAM_FAP10M_ALLOCATOR_API_ID                 1117


#define PARAM_FAP10M_AUTO_FLOW_MANAGEMENT_API_ID      1129
#define PARAM_FAP10M_AUTO_FLOW_MNGT_SET_PARAMS_ID     1130
#define PARAM_FAP10M_AUTO_FLOW_MNGT_GET_PARAMS_ID     1131
#define PARAM_FAP10M_AUTO_SET_QUEUE_TYPE_PARAMS_ID    1132
#define PARAM_FAP10M_AUTO_OPEN_FAP_QUEUES_ID          1134
#define PARAM_FAP10M_AUTO_UPDATE_FAP_QUEUES_ID        1135
#define PARAM_FAP10M_AUTO_CLOSE_FAP_QUEUES_ID         1136
#define PARAM_FAP10M_AUTO_OPEN_FAP_FLOWS_ID           1137
#define PARAM_FAP10M_AUTO_UPDATE_FAP_FLOWS_ID         1138
#define PARAM_FAP10M_AUTO_CLOSE_FAP_FLOWS_ID          1139
#define PARAM_FAP10M_MAX_NOF_FAPS_ID                  1140
#define PARAM_FAP10M_MAX_NOF_PORTS_ID                 1141
#define PARAM_FAP10M_FABRIC_CLASS_ID                  1142

#define PARAM_FAP10M_SEND_PACKET_ID                   1151
#define PARAM_FAP10M_RECV_PACKET_ID                   1152
#define PARAM_FAP10M_PACKET_DATA_ID                   1153
#define PARAM_FAP10M_DEFRRED_RECV_PACKET_ID           1154
#define PARAM_FAP10M_SEND_PACKET_TEST_FDT_ID          1155
#define PARAM_FAP10M_PACKET_RESET_CAPTURE_BUFFR_ID    1157

#define PARAM_FAP10M_CONFIGURATION_API_ID             1160
#define PARAM_FAP10M_GET_FAP_ID_ID                    1161
#define PARAM_FAP10M_SET_FAP_ID_ID                    1162
#define PARAM_FAP10M_FAP_ID_ID                        1163
#define PARAM_FAP10M_GET_PROFILE_ID                   1164
#define PARAM_FAP10M_SET_PROFILE_ID                   1165
#define PARAM_FAP10M_PROFILE_ID_ID                    1166
#define PARAM_FAP10M_GET_PROFILE_VALUES_ID            1167
#define PARAM_FAP10M_GET_FABRIC_CLASS_ID              1168
#define PARAM_FAP10M_SET_FABRIC_CLASS_ID              1169
#define PARAM_FAP10M_GET_QUEUE_TYPE_PARAMS_ID         1170
#define PARAM_FAP10M_SET_QUEUE_TYPE_PARAMS_ID         1172
#define PARAM_FAP10M_MAX_QUEUE_SIZE_ID                1173
#define PARAM_FAP10M_FLOW_STAT_MSG_ID                 1174
#define PARAM_FAP10M_FLOW_SLOW_TH_ID                  1175
#define PARAM_FAP10M_FLOW_SLOW_HYS_ID                 1176
#define PARAM_FAP10M_RED_EXP_WEIGHT_ID                1177
#define PARAM_FAP10M_GET_WRED_PARAMS_ID               1178
#define PARAM_FAP10M_DROP_PRECEDENCE_ID               1179
#define PARAM_FAP10M_SET_WRED_PARAMS_ID               1180
#define PARAM_FAP10M_MAX_PACKET_SIZE_ID               1181
#define PARAM_FAP10M_MAX_PROBABILITY_ID               1182
#define PARAM_FAP10M_MIN_AVRG_TH_ID                   1183
#define PARAM_FAP10M_MAX_AVRG_TH_ID                   1184
#define PARAM_FAP10M_NOF_PACKETS_ID                   1185
#define PARAM_FAP10M_PACKET_BYTE_SIZE_ID              1186
#define PARAM_FAP10M_PACKET_PATTERN_ID                1187
#define PARAM_FAP10M_GET_EDF1_PRIOR_ID                1188
#define PARAM_FAP10M_SET_EDF1_PRIOR_ID                1189
#define PARAM_FAP10M_EDF1_PRIOR_ID                    1190
#define PARAM_FAP10M_SET_CHOP_EN_ID                   1191
#define PARAM_FAP10M_GET_CHOP_EN_ID                   1192
#define PARAM_FAP10M_CHOP_EN_ID                       1193
#define PARAM_FAP10M_CHOP_MULT_ID_ID                  1194

#define PARAM_FAP10M_TEST_API_ID                      1250
#define PARAM_FAP10M_TEST_SCENARIO_1_ID               1251 /*cells*/
#define PARAM_FAP10M_TEST_SCENARIO_2_ID               1252/*sch-flow*/
#define PARAM_FAP10M_TEST_SCENARIO_3_ID               1253/*sch-port*/
#define PARAM_FAP10M_TEST_SCENARIO_4_ID               1254/*packet*/
#define PARAM_FAP10M_TEST_SCENARIO_5_ID               1255/*links*/
#define PARAM_FAP10M_TEST_SCENARIO_6_ID               1256/*routing*/
#define PARAM_FAP10M_TEST_SCENARIO_7_ID               1257/*statistics*/
#define PARAM_FAP10M_TEST_SCENARIO_8_ID               1258/*diagnostics*/
#define PARAM_FAP10M_TEST_SCENARIO_9_ID               1259/*general*/
#define PARAM_FAP10M_TEST_SCENARIO_PKT_ID             1260
#define PARAM_FAP10M_SEND_PACKET_TEST_PP_ID           1261
#define PARAM_FAP10M_SEND_PACKET_TEST_PP_TYPE_ID      1262
#define PARAM_FAP10M_SEND_PACKET_PRINT_ID             1263
#define PARAM_FAP10M_PORT_ID                          1264
#define PARAM_FAP10M_VLAN_ID_ID                       1265
#define PARAM_FAP10M_TEST_SCENARIO_10_ID              1266/*spatial-multicast*/
#define PARAM_FAP10M_TEST_SCENARIO_11_ID              1267/*recycle-multicast*/
#define PARAM_FAP10M_TEST_SCENARIO_12_ID              1268/*Configuration*/
#define PARAM_FAP10M_TEST_APP_ID                      1269/*App*/
#define PARAM_FAP10M_TEST_APP_OPEN_FLOW_QUEUE_GROUP_ID 1270
#define PARAM_FAP10M_NOF_FLOWS_PER_PORT_ID            1271
#define PARAM_FAP10M_QOS_SCHEME_ID                    1272
#define PARAM_FAP10M_NOF_PORTS_ID                     1273
#define PARAM_FAP10M_TEST_APP_SET_QUEUE_LABEL_GROUP_ID 1274
#define PARAM_FAP10M_QUEUE_BLOCK_SIZE_ID              1276
#define PARAM_FAP10M_START_QUEUE_ID_ID                1277
#define PARAM_FAP10M_NOF_FAP_IDS_ID                   1278
#define PARAM_FAP10M_START_PORT_ID_ID                 1279
#define PARAM_FAP10M_QOS_FREE_PARAM_ID                1280
#define PARAM_FAP10M_TEST_MEM_READ_DELTA_VALUE_STOP_ID 1286
#define PARAM_FAP10M_TEST_MEM_READ_DELTA_VALUE_START_ID 1287
#define PARAM_FAP10M_TEST_MEM_READ_OFFSET_ID          1288
#define PARAM_FAP10M_TEST_MEM_READ_LS_BIT_ID          1289
#define PARAM_FAP10M_TEST_MEM_READ_MS_BIT_ID          1290
#define PARAM_FAP10M_TEST_MEM_READ_FAP_IDS_ID         1291
#define PARAM_FAP10M_TEST_MEM_READ_DELTA_TEST_ID      1292
#define PARAM_FAP10M_TEST_MEM_READ_VALUE_TEST_ID      1293
#define PARAM_FAP10M_TEST_MEM_READ_NORMALIZATION_ID   1294
#define PARAM_FAP10M_TEST_MEM_READ_HIGH_BOUND_ID      1295
#define PARAM_FAP10M_TEST_MEM_READ_LOW_BOUND_ID       1296
#define PARAM_FAP10M_TEST_MEM_READ_SYS_TICKS_ID       1297
#define PARAM_FAP10M_TEST_MEM_READ_PRINT_INTERVAL_ID  1298
#define PARAM_FAP10M_TEST_SCENARIO_8_NOF_PACKETS_ID   1299
#define PARAM_FAP10M_MISC_API_ID                      1300
#define PARAM_FAP10M_GET_LAST_PKT_HEADER_ID           1301
#define PARAM_FAP10M_TEST_SSR_RESET_ID                1302/*SSR*/
#define PARAM_FAP10M_SPATIAL_IGNORE_BIT7_FLAG_VAL_ID  1303


/* } */
#endif /*UI_PURE_DEFI_FAP10M_INCLUDED*/
