#
# $Id: Makefile,v 1.4 2020/07/26 10:43:54 sg943634 Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/appl/diag/dnx/flow

include ${SDK}/make/Make.config

INCDIR += -I${SDK}/include/soc/dnx/flow

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxflow

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

