# $Id: $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# $Id$
# Makefile for Greyhound2 SOC driver Library
#

LOCALDIR = src/soc/esw/greyhound2

include ${SDK}/make/Make.config

lib = libsoc_greyhound2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
