# $Id: Makefile,v 1.1 2005/04/12 00:53:57 mlarsen Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/bradley

include ${SDK}/make/Make.config

lib = libbradley

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
