#
# $Id: Makefile,v 1.4 2017/11/11
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/onesync

include ${SDK}/make/Make.config

#subdirs =

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxknetsync

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

