# $Id: Makefile,v 1.0 2017/05/18 vashisht Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for Flowtracker Library
#

LOCALDIR = src/bcm/esw/flowtracker

include ${SDK}/make/Make.config

lib = libflowtracker

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

