# -*- Makefile -*-
# $Id: Makefile,v 1.9 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#
# Makefile for StrataXGS SDK and diagnostics
#

include $(SDK)/make/Make.config

ifeq ($(HOSTTYPE),i386-linux)
subdirs= 
endif

include $(SDK)/make/Make.subdirs

include $(SDK)/make/Make.depend
