# $Id: Makefile,v 1.1.2.1 2006/06/26 23:09:48 korchakd Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
LOCALDIR = src/appl/diag/esw

include ${SDK}/make/Make.config

subdirs := techsupport

include ${SDK}/make/Make.subdirs

lib = libdiag_esw

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
