/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated by fltg from
 *    INTERNAL/fltg/xgs/npl/bcm56880_a0/dna_4_6_6/bcm56880_a0_dna_4_6_6_L3_IPV6_TUNNEL_EM_TABLE.map.ltl for
 *      bcm56880_a0 variant dna_4_6_6
 *
 * Tool: $SDK/INTERNAL/fltg/bin/fltg
 *
 * Edits to this file will be lost when it is regenerated.
 *
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */
#include <bcmlrd/bcmlrd_internal.h>
#include <bcmlrd/chip/bcmlrd_id.h>
#include <bcmlrd/chip/bcm56880_a0/dna_4_6_6/bcm56880_a0_dna_4_6_6_lrd_field_data.h>
#include <bcmlrd/chip/bcm56880_a0/bcm56880_a0_lrd_ltm_intf.h>
#include <bcmlrd/chip/bcm56880_a0/dna_4_6_6/bcm56880_a0_dna_4_6_6_lrd_ltm_intf.h>
#include <bcmlrd/chip/bcm56880_a0/dna_4_6_6/bcm56880_a0_dna_4_6_6_lrd_xfrm_field_desc.h>
#include <bcmdrd/chip/bcm56880_a0_enum.h>
#include "bcmltd/chip/bcmltd_common_enumpool.h"
#include "../bcm56880_a0_lrd_enumpool.h"
#include "bcm56880_a0_dna_4_6_6_lrd_enumpool.h"
#include <bcmltd/bcmltd_handler.h>
/* L3_IPV6_TUNNEL_EM_TABLE field init */
static const bcmlrd_field_data_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map_field_data_mmd[] = {
    { /* 0 IP_HDR_DIP */
      .flags = BCMLTD_FIELD_F_KEY,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_binary_0x0_128,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_binary_0x0_128,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_binary_0xffffffffffffffffffffffffffffffff_128,
      .depth = 0,
      .width = 128,
      .edata = NULL,
    },
    { /* 1 IP_HDR_SIP */
      .flags = BCMLTD_FIELD_F_KEY,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_binary_0x0_128,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_binary_0x0_128,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_binary_0xffffffffffffffffffffffffffffffff_128,
      .depth = 0,
      .width = 128,
      .edata = NULL,
    },
    { /* 2 ENTRY_VALID */
      .flags = 0,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x0,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x0,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x1,
      .depth = 0,
      .width = 1,
      .edata = NULL,
    },
    { /* 3 L3_IIF */
      .flags = 0,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_u16_0x0,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_u16_0x0,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_u16_0x3fff,
      .depth = 0,
      .width = 14,
      .edata = NULL,
    },
    { /* 4 L3_IIF_STRENGTH */
      .flags = 0,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_u8_0x0,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_u8_0x0,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_u8_0x7,
      .depth = 0,
      .width = 3,
      .edata = NULL,
    },
    { /* 5 USE_OUTER_HEADER_PHB */
      .flags = 0,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x0,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x0,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x1,
      .depth = 0,
      .width = 1,
      .edata = NULL,
    },
    { /* 6 USE_OUTER_HDR_TTL */
      .flags = 0,
      .min = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x0,
      .def = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x0,
      .max = &bcm56880_a0_dna_4_6_6_lrd_ifd_is_true_0x1,
      .depth = 0,
      .width = 1,
      .edata = NULL,
    },
};
const bcmlrd_map_field_data_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map_field_data = {
    .fields = 7,
    .field = bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map_field_data_mmd
};

static const bcmlrd_map_table_attr_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_tablet_attr_entry[] = {
    { /* 0 */
        .key   = BCMLRD_MAP_TABLE_ATTRIBUTE_INTERACTIVE,
        .value = FALSE,
    },
    { /* 1 */
        .key   = BCMLRD_MAP_TABLE_ATTRIBUTE_TABLE_SIZE,
        .value = 8192,
    },
};

static const bcmlrd_map_attr_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_tablet_attr_group = {
    .attributes = 2,
    .attr = bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_tablet_attr_entry,
};


const bcmltd_field_desc_t
bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_src_field_desc_s0[2] = {
    {
        .field_id  = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_IP_HDR_DIPf,
        .field_idx = 0,
        .minbit    = 0,
        .maxbit    = 81,
        .entry_idx = 0,
        .reserved  = 0
    },
    {
        .field_id  = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_IP_HDR_DIPf,
        .field_idx = 0,
        .minbit    = 82,
        .maxbit    = 127,
        .entry_idx = 0,
        .reserved  = 0
    },
};

static const bcmltd_field_desc_t
bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_dst_field_desc[2] = {
    {
        .field_id  = TABLE_FIELDS_1f,
        .field_idx = 0,
        .minbit    = 158,
        .maxbit    = 239,
        .entry_idx = 0,
        .reserved  = 0,
    },
    {
        .field_id  = TABLE_FIELDS_2f,
        .field_idx = 0,
        .minbit    = 243,
        .maxbit    = 288,
        .entry_idx = 0,
        .reserved  = 0,
    },
};

const bcmltd_field_desc_t
bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_src_field_desc_s0[3] = {
    {
        .field_id  = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_IP_HDR_SIPf,
        .field_idx = 0,
        .minbit    = 0,
        .maxbit    = 15,
        .entry_idx = 0,
        .reserved  = 0
    },
    {
        .field_id  = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_IP_HDR_SIPf,
        .field_idx = 0,
        .minbit    = 16,
        .maxbit    = 100,
        .entry_idx = 0,
        .reserved  = 0
    },
    {
        .field_id  = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_IP_HDR_SIPf,
        .field_idx = 0,
        .minbit    = 101,
        .maxbit    = 127,
        .entry_idx = 0,
        .reserved  = 0
    },
};

static const bcmltd_field_desc_t
bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_dst_field_desc[3] = {
    {
        .field_id  = TABLE_FIELDS_2f,
        .field_idx = 0,
        .minbit    = 289,
        .maxbit    = 304,
        .entry_idx = 0,
        .reserved  = 0,
    },
    {
        .field_id  = TABLE_FIELDS_0f,
        .field_idx = 0,
        .minbit    = 35,
        .maxbit    = 119,
        .entry_idx = 0,
        .reserved  = 0,
    },
    {
        .field_id  = TABLE_FIELDS_1f,
        .field_idx = 0,
        .minbit    = 123,
        .maxbit    = 149,
        .entry_idx = 0,
        .reserved  = 0,
    },
};

const bcmlrd_field_xfrm_desc_t
bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_xfrm_handler_fwd_s0_d0_desc = {
    .handler_id = BCMLTD_TRANSFORM_BCM56880_A0_DNA_4_6_6_LTA_BCMLTX_FIELD_DEMUX_WIDE_L3_IPV6_TUNNEL_EM_TABLET_IP_HDR_DIPF_0_XFRM_HANDLER_FWD_S0_D0_ID,
    .src_fields = 2,
    .src = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_src_field_desc_s0,
    .dst_fields = 2,
    .dst = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_dst_field_desc,
};

const bcmlrd_field_xfrm_desc_t
bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_xfrm_handler_rev_s0_d0_desc = {
    .handler_id = BCMLTD_TRANSFORM_BCM56880_A0_DNA_4_6_6_LTA_BCMLTX_FIELD_DEMUX_WIDE_L3_IPV6_TUNNEL_EM_TABLET_IP_HDR_DIPF_0_XFRM_HANDLER_REV_S0_D0_ID,
    .src_fields = 2,
    .src = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_dst_field_desc,
    .dst_fields = 2,
    .dst = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_src_field_desc_s0,
};

const bcmlrd_field_xfrm_desc_t
bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_xfrm_handler_fwd_s0_d0_desc = {
    .handler_id = BCMLTD_TRANSFORM_BCM56880_A0_DNA_4_6_6_LTA_BCMLTX_FIELD_DEMUX_WIDE_L3_IPV6_TUNNEL_EM_TABLET_IP_HDR_SIPF_0_XFRM_HANDLER_FWD_S0_D0_ID,
    .src_fields = 3,
    .src = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_src_field_desc_s0,
    .dst_fields = 3,
    .dst = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_dst_field_desc,
};

const bcmlrd_field_xfrm_desc_t
bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_xfrm_handler_rev_s0_d0_desc = {
    .handler_id = BCMLTD_TRANSFORM_BCM56880_A0_DNA_4_6_6_LTA_BCMLTX_FIELD_DEMUX_WIDE_L3_IPV6_TUNNEL_EM_TABLET_IP_HDR_SIPF_0_XFRM_HANDLER_REV_S0_D0_ID,
    .src_fields = 3,
    .src = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_dst_field_desc,
    .dst_fields = 3,
    .dst = bcm56880_a0_dna_4_6_6_lrd_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_src_field_desc_s0,
};


static const bcmlrd_map_entry_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_tablet_ifta30_e2t_00_b0_quad_map_entry[] = {
    { /* 0 */
        .entry_type = BCMLRD_MAP_ENTRY_MAPPED_VALUE,
        .desc = {
            .field_id  = TABLE_FIELDS_3f,
            .field_idx = 0,
            .minbit    = 452,
            .maxbit    = 465,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .mapped = {
                .src = {
                    .field_id = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_L3_IIFf,
                    .field_idx = 0,
                    .minbit    = 0,
                    .maxbit    = 13,
                    .entry_idx = 0,
                    .reserved  = 0
                }
            }
        },
    },
    { /* 1 */
        .entry_type = BCMLRD_MAP_ENTRY_MAPPED_VALUE,
        .desc = {
            .field_id  = TABLE_FIELDS_3f,
            .field_idx = 0,
            .minbit    = 468,
            .maxbit    = 468,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .mapped = {
                .src = {
                    .field_id = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_ENTRY_VALIDf,
                    .field_idx = 0,
                    .minbit    = 0,
                    .maxbit    = 0,
                    .entry_idx = 0,
                    .reserved  = 0
                }
            }
        },
    },
    { /* 2 */
        .entry_type = BCMLRD_MAP_ENTRY_MAPPED_VALUE,
        .desc = {
            .field_id  = TABLE_FIELDS_3f,
            .field_idx = 0,
            .minbit    = 474,
            .maxbit    = 474,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .mapped = {
                .src = {
                    .field_id = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_USE_OUTER_HDR_TTLf,
                    .field_idx = 0,
                    .minbit    = 0,
                    .maxbit    = 0,
                    .entry_idx = 0,
                    .reserved  = 0
                }
            }
        },
    },
    { /* 3 */
        .entry_type = BCMLRD_MAP_ENTRY_MAPPED_VALUE,
        .desc = {
            .field_id  = TABLE_FIELDS_3f,
            .field_idx = 0,
            .minbit    = 476,
            .maxbit    = 478,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .mapped = {
                .src = {
                    .field_id = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_L3_IIF_STRENGTHf,
                    .field_idx = 0,
                    .minbit    = 0,
                    .maxbit    = 2,
                    .entry_idx = 0,
                    .reserved  = 0
                }
            }
        },
    },
    { /* 4 */
        .entry_type = BCMLRD_MAP_ENTRY_MAPPED_VALUE,
        .desc = {
            .field_id  = TABLE_FIELDS_3f,
            .field_idx = 0,
            .minbit    = 473,
            .maxbit    = 473,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .mapped = {
                .src = {
                    .field_id = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt_USE_OUTER_HEADER_PHBf,
                    .field_idx = 0,
                    .minbit    = 0,
                    .maxbit    = 0,
                    .entry_idx = 0,
                    .reserved  = 0
                }
            }
        },
    },
    { /* 5 */
        .entry_type = BCMLRD_MAP_ENTRY_FIXED_KEY,
        .desc = {
            .field_id  = BASE_VALID_0f,
            .field_idx = 0,
            .minbit    = 0,
            .maxbit    = 2,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .fixed = {
                .value = 5,
            }
        },
    },
    { /* 6 */
        .entry_type = BCMLRD_MAP_ENTRY_FIXED_KEY,
        .desc = {
            .field_id  = BASE_VALID_1f,
            .field_idx = 0,
            .minbit    = 120,
            .maxbit    = 122,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .fixed = {
                .value = 6,
            }
        },
    },
    { /* 7 */
        .entry_type = BCMLRD_MAP_ENTRY_FIXED_KEY,
        .desc = {
            .field_id  = BASE_VALID_2f,
            .field_idx = 0,
            .minbit    = 240,
            .maxbit    = 242,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .fixed = {
                .value = 6,
            }
        },
    },
    { /* 8 */
        .entry_type = BCMLRD_MAP_ENTRY_FIXED_KEY,
        .desc = {
            .field_id  = BASE_VALID_3f,
            .field_idx = 0,
            .minbit    = 360,
            .maxbit    = 362,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .fixed = {
                .value = 7,
            }
        },
    },
    { /* 9 */
        .entry_type = BCMLRD_MAP_ENTRY_FIXED_KEY,
        .desc = {
            .field_id  = KEY_TYPEf,
            .field_idx = 0,
            .minbit    = 3,
            .maxbit    = 6,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .fixed = {
                .value = 1,
            }
        },
    },
    { /* 10 */
        .entry_type = BCMLRD_MAP_ENTRY_FWD_KEY_FIELD_XFRM_HANDLER,
        .desc = {
            .field_id  = 0,
            .field_idx = 0,
            .minbit    = 0,
            .maxbit    = 0,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .xfrm = {
                /* handler: bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_xfrm_handler_fwd_s0_d0 */
                .desc = &bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_xfrm_handler_fwd_s0_d0_desc,
            },
        },
    },
    { /* 11 */
        .entry_type = BCMLRD_MAP_ENTRY_REV_KEY_FIELD_XFRM_HANDLER,
        .desc = {
            .field_id  = 0,
            .field_idx = 0,
            .minbit    = 0,
            .maxbit    = 0,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .xfrm = {
                /* handler: bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_xfrm_handler_rev_s0_d0 */
                .desc = &bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_dipf_0_xfrm_handler_rev_s0_d0_desc,
            },
        },
    },
    { /* 12 */
        .entry_type = BCMLRD_MAP_ENTRY_FWD_KEY_FIELD_XFRM_HANDLER,
        .desc = {
            .field_id  = 0,
            .field_idx = 0,
            .minbit    = 0,
            .maxbit    = 0,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .xfrm = {
                /* handler: bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_xfrm_handler_fwd_s0_d0 */
                .desc = &bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_xfrm_handler_fwd_s0_d0_desc,
            },
        },
    },
    { /* 13 */
        .entry_type = BCMLRD_MAP_ENTRY_REV_KEY_FIELD_XFRM_HANDLER,
        .desc = {
            .field_id  = 0,
            .field_idx = 0,
            .minbit    = 0,
            .maxbit    = 0,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            .xfrm = {
                /* handler: bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_xfrm_handler_rev_s0_d0 */
                .desc = &bcm56880_a0_dna_4_6_6_lta_bcmltx_field_demux_wide_l3_ipv6_tunnel_em_tablet_ip_hdr_sipf_0_xfrm_handler_rev_s0_d0_desc,
            },
        },
    },
};
static const bcmlrd_map_entry_t
bcm56880_a0_dna_4_6_6_lrd_bcmltx_l3_ipv6_tunnel_em_table_validate_entry[] = {
    { /* 0 */
        .entry_type = BCMLRD_MAP_ENTRY_KEY_FIELD_VALIDATION,
        .desc = {
            .field_id  = 0,
            .field_idx = 0,
            .minbit    = 0,
            .maxbit    = 0,
            .entry_idx = 0,
            .reserved  = 0
        },
        .u = {
            /* handler: bcm56880_a0_dna_4_6_6_lta_bcmltx_l3_ipv6_tunnel_em_table_std_key_fv_handler */
            .handler_id = BCMLTD_VALIDATE_BCM56880_A0_DNA_4_6_6_LTA_BCMLTX_L3_IPV6_TUNNEL_EM_TABLE_STD_KEY_FV_HANDLER_ID
        }
    },
};
static const bcmlrd_map_group_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map_group[] = {
    {
        .dest = {
            .kind = BCMLRD_MAP_PHYSICAL,
            .id = IFTA30_E2T_00_B0_QUADm,
        },
        .entries = 14,
        .entry = bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_tablet_ifta30_e2t_00_b0_quad_map_entry
    },
    {
        .dest = {
            .kind = BCMLRD_MAP_VALIDATION,
            .id = 0,
        },
        .entries = 1,
        .entry = bcm56880_a0_dna_4_6_6_lrd_bcmltx_l3_ipv6_tunnel_em_table_validate_entry
    },
};
const bcmlrd_map_t bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map = {
    .src_id = BCM56880_A0_DNA_4_6_6_L3_IPV6_TUNNEL_EM_TABLEt,
    .field_data = &bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map_field_data,
    .groups = 2,
    .group  = bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_table_map_group,
    .table_attr = &bcm56880_a0_dna_4_6_6_lrd_l3_ipv6_tunnel_em_tablet_attr_group,
    .entry_ops = BCMLRD_MAP_TABLE_ENTRY_OPERATION_LOOKUP | BCMLRD_MAP_TABLE_ENTRY_OPERATION_TRAVERSE | BCMLRD_MAP_TABLE_ENTRY_OPERATION_INSERT | BCMLRD_MAP_TABLE_ENTRY_OPERATION_UPDATE | BCMLRD_MAP_TABLE_ENTRY_OPERATION_DELETE
};
