# $Id: Makefile,v 1.1 2004/02/24 07:46:44 csm Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/hercules

include ${SDK}/make/Make.config

lib = libherc

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
