# $Id$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# 

export TARGET
export BLDDIR
export LIBDIR

LOCALDIR = systems/sim/dpp/ChipSim

include ${SDK}/make/Make.config

lib = libchipsim_sim

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
