#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Linux driver documentation make file
#

.PHONY: all

all:
	@echo This make file is only for building documentation.

# Common developer targets
include $(SDK)/make/devtools.mk
