/***********************************************************************************
 *                                                                                 *
 * Copyright: (c) 2021 Broadcom.                                                   *
 * Broadcom Proprietary and Confidential. All rights reserved.                     *
 *                                                                                 *
 ***********************************************************************************/

/***********************************************************************************
 ***********************************************************************************
 *                                                                                 *
 *  Revision      :   *
 *                                                                                 *
 *  Description   :  This file contains print messages for decoded bit fields      *
 *                   of structs.                                                   *
 *                                                                                 *
 ***********************************************************************************
 ***********************************************************************************/

/* THIS FILE IS GENERATED USING AN AUTOMATED SCRIPT... PLEASE DO NOT EDIT THIS FILE DIRECTLY !!! */


#ifdef __cplusplus
extern "C" { /* __cplusplus */
#endif

#ifndef MERLIN7_PCIEG3_API_DECODE_PRINT_H
#define MERLIN7_PCIEG3_API_DECODE_PRINT_H

#include "common/srds_api_err_code.h"
#include "merlin7_pcieg3_dependencies.h"
#include "merlin7_pcieg3_usr_includes.h"

/*! @file
 *  @brief Decode bit fields
 */

/*! @addtogroup APITag
 * @{
 */

/*! @defgroup SerdesAPIDecodePrintTag Decode Bits  */

/*! @addtogroup SerdesAPIDecodePrintTag
 * @{
 */

/*! @} SerdesAPIDecodePrintTag */
/*! @} APITag */
#endif /* SERDES_API_DECODE_PRINT_H */
#ifdef __cplusplus
}
#endif /* __cplusplus */
