#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Top-level makefile for building SDK libraries
#
# Should be invoked, e.g. like this:
#
#   make -C $(SDK)
#

# Make rules to build and install consolidated library and header files.
include $(SDK)/make/sdkinst.mk

# Make rules to build and install shared ISSU library.
include $(SDK)/make/sdkissu.mk
