/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:    monterey_mmu.c
 * Purpose: Maintains all the debug information for mmu
 *          feature for monterey.
*/

#include <appl/diag/techsupport.h>
#include <soc/mcm/allenum.h>

extern char * techsupport_mmu_diag_cmdlist[];
extern char * techsupport_mmu_sw_dump_cmdlist[];

/* "mmu" feature's diag command list valid for monterey */
char * techsupport_mmu_monterey_diag_cmdlist[] = {
     NULL /* Must be the last element in this structure */
 };

#ifndef BCM_SW_STATE_DUMP_DISABLE
/* "MMU" feature's software dump command list valid for monterey */
char * techsupport_mmu_monterey_sw_dump_cmdlist[] = {
    NULL /* Must be the last element in this structure */
};
#endif /* BCM_SW_STATE_DUMP_DISABLE */


/* Structure that maintains memory list for
 * "mmu" feature for monterey chipset. */
static soc_mem_t techsupport_mmu_monterey_memory_table_list[] = {
    CPU_COS_MAPm,
    EGR_EDB_XMIT_CTRLm,
    EGR_FLEX_PREEMPT_START_LOOKUP0m,
    EGR_FLEX_PREEMPT_START_LOOKUP1m,
    EGR_FLEX_PREEMPT_START_LOOKUP10m,
    EGR_FLEX_PREEMPT_START_LOOKUP11m,
    EGR_FLEX_PREEMPT_START_LOOKUP12m,
    EGR_FLEX_PREEMPT_START_LOOKUP13m,
    EGR_FLEX_PREEMPT_START_LOOKUP14m,
    EGR_FLEX_PREEMPT_START_LOOKUP15m,
    EGR_FLEX_PREEMPT_START_LOOKUP2m,
    EGR_FLEX_PREEMPT_START_LOOKUP3m,
    EGR_FLEX_PREEMPT_START_LOOKUP4m,
    EGR_FLEX_PREEMPT_START_LOOKUP5m,
    EGR_FLEX_PREEMPT_START_LOOKUP6m,
    EGR_FLEX_PREEMPT_START_LOOKUP7m,
    EGR_FLEX_PREEMPT_START_LOOKUP8m,
    EGR_FLEX_PREEMPT_START_LOOKUP9m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP0m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP1m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP10m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP11m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP12m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP13m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP14m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP15m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP2m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP3m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP4m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP5m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP6m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP7m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP8m,
    EGR_FLEX_PREEMPT_TERMINATE_LOOKUP9m,
    EGR_FLEX_PREEMPT_XFR_COUNT0m,
    EGR_FLEX_PREEMPT_XFR_COUNT1m,
    EGR_FLEX_PREEMPT_XFR_COUNT10m,
    EGR_FLEX_PREEMPT_XFR_COUNT11m,
    EGR_FLEX_PREEMPT_XFR_COUNT12m,
    EGR_FLEX_PREEMPT_XFR_COUNT13m,
    EGR_FLEX_PREEMPT_XFR_COUNT14m,
    EGR_FLEX_PREEMPT_XFR_COUNT15m,
    EGR_FLEX_PREEMPT_XFR_COUNT2m,
    EGR_FLEX_PREEMPT_XFR_COUNT3m,
    EGR_FLEX_PREEMPT_XFR_COUNT4m,
    EGR_FLEX_PREEMPT_XFR_COUNT5m,
    EGR_FLEX_PREEMPT_XFR_COUNT6m,
    EGR_FLEX_PREEMPT_XFR_COUNT7m,
    EGR_FLEX_PREEMPT_XFR_COUNT8m,
    EGR_FLEX_PREEMPT_XFR_COUNT9m,
    EGR_PORT_MNFS_MFS_CONFIGm,
    EGR_PORT_PREEMPTION_MODEm,
    EGR_PREEMPT_EDB_XMIT_CTRLm,
    EGR_PREEMPT_ENABLEm,
    EGR_PREEMPT_MAX_USED_ENTRIESm,
    EGR_PREEMPT_MMU_CREDIT_LIMITm,
    EGR_PREEMPT_MMU_REQUESTSm,
    EGR_PREEMPT_PER_PORT_BUFFER_OVERFLOWm,
    EGR_PREEMPT_PFC_CONTROLm,
    HSP_SCHED_L0_NODE_WEIGHTm,
    HSP_SCHED_L1_NODE_WEIGHTm,
    HSP_SCHED_L2_MC_QUEUE_WEIGHTm,
    HSP_SCHED_L2_UC_QUEUE_WEIGHTm,
    HSP_SCHED_LAST_PORT_INFOm,
    HSP_SCHED_LAST_PREEMPT_PORT_INFOm,
    IDB_OBM0_MPLS_MAP_PORT0m,
    IDB_OBM0_MPLS_MAP_PORT1m,
    IDB_OBM0_MPLS_MAP_PORT2m,
    IDB_OBM0_MPLS_MAP_PORT3m,
    IDB_OBM1_MPLS_MAP_PORT0m,
    IDB_OBM1_MPLS_MAP_PORT1m,
    IDB_OBM1_MPLS_MAP_PORT2m,
    IDB_OBM1_MPLS_MAP_PORT3m,
    IDB_OBM2_MPLS_MAP_PORT0m,
    IDB_OBM2_MPLS_MAP_PORT1m,
    IDB_OBM2_MPLS_MAP_PORT2m,
    IDB_OBM2_MPLS_MAP_PORT3m,
    IDB_OBM3_MPLS_MAP_PORT0m,
    IDB_OBM3_MPLS_MAP_PORT1m,
    IDB_OBM3_MPLS_MAP_PORT2m,
    IDB_OBM3_MPLS_MAP_PORT3m,
    IDB_OBM4_MPLS_MAP_PORT0m,
    IDB_OBM4_MPLS_MAP_PORT1m,
    IDB_OBM4_MPLS_MAP_PORT2m,
    IDB_OBM4_MPLS_MAP_PORT3m,
    IDB_OBM5_MPLS_MAP_PORT0m,
    IDB_OBM5_MPLS_MAP_PORT1m,
    IDB_OBM5_MPLS_MAP_PORT2m,
    IDB_OBM5_MPLS_MAP_PORT3m,
    IDB_OBM6_MPLS_MAP_PORT0m,
    IDB_OBM6_MPLS_MAP_PORT1m,
    IDB_OBM6_MPLS_MAP_PORT2m,
    IDB_OBM6_MPLS_MAP_PORT3m,
    IDB_OBM7_MPLS_MAP_PORT0m,
    IDB_OBM7_MPLS_MAP_PORT1m,
    IDB_OBM7_MPLS_MAP_PORT2m,
    IDB_OBM7_MPLS_MAP_PORT3m,
    IDB_OBM0_PRI_MAP_PORT0m,
    IDB_OBM0_PRI_MAP_PORT1m,
    IDB_OBM0_PRI_MAP_PORT2m,
    IDB_OBM0_PRI_MAP_PORT3m,
    IDB_OBM1_PRI_MAP_PORT0m,
    IDB_OBM1_PRI_MAP_PORT1m,
    IDB_OBM1_PRI_MAP_PORT2m,
    IDB_OBM1_PRI_MAP_PORT3m,
    IDB_OBM2_PRI_MAP_PORT0m,
    IDB_OBM2_PRI_MAP_PORT1m,
    IDB_OBM2_PRI_MAP_PORT2m,
    IDB_OBM2_PRI_MAP_PORT3m,
    IDB_OBM3_PRI_MAP_PORT0m,
    IDB_OBM3_PRI_MAP_PORT1m,
    IDB_OBM3_PRI_MAP_PORT2m,
    IDB_OBM3_PRI_MAP_PORT3m,
    IDB_OBM4_PRI_MAP_PORT0m,
    IDB_OBM4_PRI_MAP_PORT1m,
    IDB_OBM4_PRI_MAP_PORT2m,
    IDB_OBM4_PRI_MAP_PORT3m,
    IDB_OBM5_PRI_MAP_PORT0m,
    IDB_OBM5_PRI_MAP_PORT1m,
    IDB_OBM5_PRI_MAP_PORT2m,
    IDB_OBM5_PRI_MAP_PORT3m,
    IDB_OBM6_PRI_MAP_PORT0m,
    IDB_OBM6_PRI_MAP_PORT1m,
    IDB_OBM6_PRI_MAP_PORT2m,
    IDB_OBM6_PRI_MAP_PORT3m,
    IDB_OBM7_PRI_MAP_PORT0m,
    IDB_OBM7_PRI_MAP_PORT1m,
    IDB_OBM7_PRI_MAP_PORT2m,
    IDB_OBM7_PRI_MAP_PORT3m,
    MMU_MCQE_MAPPERm,
    MMU_MTRO_BUCKET_L0_MEMm,
    MMU_MTRO_BUCKET_L1_MEMm,
    MMU_MTRO_BUCKET_L2_MEMm,
    MMU_MTRO_EGRMETERINGBUCKET_MEMm,
    MMU_MTRO_EGRMETERINGCONFIG_MEMm,
    MMU_MTRO_EGRMETERINGCONFIG_MEM_Am,
    MMU_MTRO_EGRMETERINGCONFIG_MEM_Bm,
    MMU_MTRO_L0_MEMm,
    MMU_MTRO_L0_MEM_Am,
    MMU_MTRO_L0_MEM_Bm,
    MMU_MTRO_L1_MEMm,
    MMU_MTRO_L1_MEM_Am,
    MMU_MTRO_L1_MEM_Bm,
    MMU_MTRO_L2_MEMm,
    MMU_MTRO_L2_MEM_Am,
    MMU_MTRO_L2_MEM_Bm,
    MMU_THDM_MCQE_PORTSP_CONFIG_0Cm,
    MMU_CTR_ING_DROP_MEMm,
    MMU_CTR_UC_DROP_MEMm,
    MMU_CTR_MC_DROP_MEM0m,
    MMU_CTR_MTRI_DROP_MEMm,
    MMU_CTR_COLOR_DROP_MEMm,
    MMU_INTFI_FC_ST_TBL0m,
    MMU_INTFI_FC_ST_TBL1m,
    MMU_INTFI_FC_ST_TBL2m,
    MMU_INTFI_PFC_ST_TBLm,
    MMU_INTFI_XPIPE_FC_MAP_TBL0m,
    MMU_INTFI_XPIPE_FC_MAP_TBL1m,
    MMU_INTFI_XPIPE_FC_MAP_TBL2m,
    MMU_THDU_XPIPE_CONFIG_PORTm,
    MMU_THDU_XPIPE_CONFIG_QGROUPm,
    MMU_THDU_XPIPE_CONFIG_QUEUEm,
    MMU_THDU_XPIPE_COUNTER_PORTm,
    MMU_THDU_XPIPE_COUNTER_QGROUPm,
    MMU_THDU_XPIPE_COUNTER_QUEUEm,
    MMU_THDU_XPIPE_OFFSET_QGROUPm,
    MMU_THDU_XPIPE_OFFSET_QUEUEm,
    MMU_THDU_XPIPE_Q_TO_QGRP_MAPm,
    MMU_THDU_XPIPE_RESUME_PORTm,
    MMU_THDU_XPIPE_RESUME_QGROUPm,
    MMU_THDU_XPIPE_RESUME_QUEUEm,
    MMU_THDM_DB_PORTSP_CONFIG_0m,
    MMU_THDM_DB_QUEUE_CONFIG_0m,
    MMU_THDM_DB_QUEUE_COUNT_0m,
    MMU_THDM_DB_QUEUE_OFFSET_0m,
    MMU_THDM_DB_QUEUE_RESUME_0m,
    MMU_THDM_MCQE_PORTSP_CONFIG_0m,
    MMU_THDM_MCQE_QUEUE_CONFIG_0m,
    MMU_THDM_MCQE_QUEUE_COUNT_0m,
    MMU_THDM_MCQE_QUEUE_OFFSET_0m,
    MMU_THDM_MCQE_QUEUE_RESUME_0m,
    PORT_COS_MAPm,
    THDI_PORT_PG_CNTRS_RT1_Xm,
    THDI_PORT_PG_CNTRS_RT2_Xm,
    THDI_PORT_PG_CONFIG_Xm,
    THDI_PORT_SP_CNTRS_RT_Xm,
    THDI_PORT_SP_CONFIG_Xm,
    EGR_PORT_PREEMPTION_MODEm,
    EGR_PORT_MNFS_MFS_CONFIGm,
    INVALIDm /* Must be the last element in this structure */
};

/* Structure that maintains register list for
 * "mmu" feature for monterey chipset. */
techsupport_reg_t techsupport_mmu_monterey_reg_list[] = {
    {EGR_DATABUF_RAM_CONTROL_5r, register_type_global},
    {EGR_EDB_EN_COR_ERR_RPT_PKT_LENr, register_type_global},
    {EGR_EDB_EN_COR_ERR_RPT_PREEMPT_LOOKUPr, register_type_global},
    {EGR_EDB_EN_COR_ERR_RPT_PREEMPT_XFR_COUNTr, register_type_global},
    {EGR_EDB_PKT_LEN_PARITY_ENr, register_type_global},
    {EGR_EDB_PREEMPT_LOOKUP_PARITY_ENr, register_type_global},
    {EGR_EDB_PREEMPT_XFR_COUNT_PARITY_ENr, register_type_global},
    {ES_PIPE0_MMU_PORT_CREDIT_EXPRESSr, register_type_global},
    {ES_PIPE0_MMU_PORT_CREDIT_PREEMPTr, register_type_global},
    {ES_PIPE0_MMU_PORT_CURRENT_CREDIT_EXPRESSr, register_type_global},
    {ES_PIPE0_MMU_PORT_CURRENT_CREDIT_PREEMPTr, register_type_global},
    {ES_PIPE0_OVR_SUB_GRP_WT4r, register_type_global},
    {ES_PIPE0_OVR_SUB_GRP_WT5r, register_type_global},
    {ES_PIPE0_OVR_SUB_GRP_WT6r, register_type_global},
    {ES_PIPE0_OVR_SUB_GRP_WT7r, register_type_global},
    {ES_PIPE0_TDM_PORT_CREDIT_MODE_0_31r, register_type_global},
    {ES_PIPE0_TDM_PORT_CREDIT_MODE_32_63r, register_type_global},
    {MCQE_MAPPER_MEM_DEBUG_TMr, register_type_global},
    {MCTHD_MEMORY_DEBUG_TMr, register_type_global},
    {MMU_ENQ_PIPE_DELAY_MEM_TMr, register_type_global},
    {SAV_THDI_CFG_TMr, register_type_global},
    {VBS_FC_CONFIGr, register_type_global},
    {HSP_MEMORY_TM_2r, register_type_global},
    {HSP_MEMORY_TM_3r, register_type_global},
    {HSP_MEMORY_TM_4r, register_type_global},
    {HSP_SCHED_L0_NODE_4_CONNECTION_CONFIGr, register_type_global},
    {HSP_SCHED_L2_MC_CPU_QUEUE_CONFIG0r, register_type_global},
    {HSP_SCHED_L2_MC_CPU_QUEUE_CONFIG1r, register_type_global},
    {HSP_SCHED_L2_MC_CPU_QUEUE_CONFIG2r, register_type_global},
    {HSP_SCHED_PORT_PREEMPT_CONFIGr, register_type_global},
    {THDI_BUFFER_CELL_LIMIT_PUBLIC_POOLr, register_type_global},
    {THDI_BUFFER_CELL_LIMIT_SPr, register_type_global},
    {THDI_BYPASSr, register_type_global},
    {THDI_CELL_RESET_LIMIT_OFFSET_SPr, register_type_global},
    {THDI_CELL_SPAP_RED_OFFSET_SPr, register_type_global},
    {THDI_CELL_SPAP_YELLOW_OFFSET_SPr, register_type_global},
    {THDI_EN_COR_ERR_RPTr, register_type_global},
    {THDI_FLOW_CONTROL_XOFF_STATEr, register_type_global},
    {THDI_GLOBAL_HDRM_COUNT_PIPEXr, register_type_global},
    {THDI_GLOBAL_HDRM_LIMIT_PIPEXr, register_type_global},
    {THDI_GLOBAL_HDRM_RESERVED_PIPEXr, register_type_global},
    {THDI_INPUT_PORT_XON_ENABLESr, register_type_global},
    {THDI_MEMORY_PTPG_CFG_MEM_TM_0r, register_type_global},
    {THDI_MEMORY_PTSP_CFG_MEM_TM_0r, register_type_global},
    {THDI_MEM_INIT_STATUSr, register_type_global},
    {THDI_POOL_CONFIGr, register_type_global},
    {THDI_POOL_DROP_STATEr, register_type_global},
    {THDI_POOL_SHARED_COUNT_SPr, register_type_global},
    {THDI_PORT_LIMIT_STATESr, register_type_global},
    {THDI_PORT_MAX_PKT_SIZEr, register_type_global},
    {THDI_PORT_PG_SPIDr, register_type_global},
    {THDI_PORT_PRI_GRP0r, register_type_global},
    {THDI_PORT_PRI_GRP1r, register_type_global},
    {THDI_TOTAL_CELL_COUNT_PUBLIC_POOLr, register_type_global},
    {THDI_TO_OOBFC_SP_STr, register_type_global},
    {THDU_BYPASSr, register_type_global},
    {THDU_DEBUGr, register_type_global},
    {THDU_OUTPUT_PORT_RX_ENABLE0_64r, register_type_global},
    {THDU_OUTPUT_PORT_RX_ENABLE1_64r, register_type_global},
    {THDU_PORT_E2ECC_COS_SPIDr, register_type_global},
    {MMU_THDU_EN_COR_ERR_RPTr, register_type_global},
    {OP_THDU_CONFIGr, register_type_global},
    {MMU_THDM_DB_DEVICE_BYPASSr, register_type_global},
    {MMU_THDM_DB_DEVICE_THR_CONFIGr, register_type_global},
    {MMU_THDM_DB_EN_COR_ERR_RPTr, register_type_global},
    {MMU_THDM_DB_MEMORY_TMr, register_type_global},
    {MMU_THDM_DB_POOL_DROP_STATESr, register_type_global},
    {MMU_THDM_DB_POOL_RED_RESUME_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_RED_SHARED_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_RESUME_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_SHARED_COUNTr, register_type_global},
    {MMU_THDM_DB_POOL_SHARED_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_YELLOW_RESUME_LIMITr, register_type_global},
    {MMU_THDM_DB_POOL_YELLOW_SHARED_LIMITr, register_type_global},
    {MMU_THDM_DB_PORTSP_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RED_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RX_ENABLE0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_RX_ENABLE1_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_SHARED_COUNTr, register_type_global},
    {MMU_THDM_DB_PORTSP_THRESHOLD_PROFILE_SELr, register_type_global},
    {MMU_THDM_DB_PORTSP_TOTAL_COUNTr, register_type_global},
    {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_DB_PORTSP_YELLOW_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_DB_QUEUE_RESUME_OFFSET_PROFILE_REDr, register_type_global},
    {MMU_THDM_DB_QUEUE_RESUME_OFFSET_PROFILE_YELLOWr, register_type_global},
    {MMU_THDM_MCQE_DEVICE_BYPASSr, register_type_global},
    {MMU_THDM_MCQE_DEVICE_THR_CONFIGr, register_type_global},
    {MMU_THDM_MCQE_EN_COR_ERR_RPTr, register_type_global},
    {MMU_THDM_MCQE_MEMORY_TMr, register_type_global},
    {MMU_THDM_MCQE_POOL_DROP_STATESr, register_type_global},
    {MMU_THDM_MCQE_POOL_RED_RESUME_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_RED_SHARED_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_RESUME_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_SHARED_COUNTr, register_type_global},
    {MMU_THDM_MCQE_POOL_SHARED_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_YELLOW_RESUME_LIMITr, register_type_global},
    {MMU_THDM_MCQE_POOL_YELLOW_SHARED_LIMITr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RED_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RX_ENABLE0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_RX_ENABLE1_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_SHARED_COUNTr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_THRESHOLD_PROFILE_SELr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_TOTAL_COUNTr, register_type_global},
    {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP0_64r, register_type_global},
    {MMU_THDM_MCQE_PORTSP_YELLOW_DROP_STATE_BMP1_64r, register_type_global},
    {MMU_THDM_MCQE_QUEUE_RESUME_OFFSET_PROFILE_REDr, register_type_global},
    {MMU_THDM_MCQE_QUEUE_RESUME_OFFSET_PROFILE_YELLOWr, register_type_global},
    {MMU_THDR_DB_BYPASSr, register_type_global},
    {MMU_THDR_DB_CONFIGr, register_type_global},
    {MMU_THDR_DB_CONFIG1_PRIQr, register_type_global},
    {MMU_THDR_DB_CONFIG_PRIQr, register_type_global},
    {MMU_THDR_DB_CONFIG_SPr, register_type_global},
    {MMU_THDR_DB_LIMIT_COLOR_PRIQr, register_type_global},
    {MMU_THDR_DB_LIMIT_MIN_PRIQr, register_type_global},
    {MMU_THDR_DB_MIN_COUNT_PRIQr, register_type_global},
    {MMU_THDR_DB_RESET_OFFSET_COLOR_PRIQr, register_type_global},
    {MMU_THDR_DB_RESUME_COLOR_LIMIT_SPr, register_type_global},
    {MMU_THDR_DB_SHARED_COUNT_PRIQr, register_type_global},
    {MMU_THDR_DB_SHARED_COUNT_SPr, register_type_global},
    {MMU_THDR_DB_SP_SHARED_LIMITr, register_type_global},
    {MMU_THDR_DB_STATUS_PRIQr, register_type_global},
    {MMU_THDR_DB_STATUS_SPr, register_type_global},
    {MMU_THDR_QE_BYPASSr, register_type_global},
    {MMU_THDR_QE_CONFIGr, register_type_global},
    {MMU_THDR_QE_CONFIG1_PRIQr, register_type_global},
    {MMU_THDR_QE_CONFIG_PRIQr, register_type_global},
    {MMU_THDR_QE_CONFIG_SPr, register_type_global},
    {MMU_THDR_QE_LIMIT_COLOR_PRIQr, register_type_global},
    {MMU_THDR_QE_LIMIT_MIN_PRIQr, register_type_global},
    {MMU_THDR_QE_MIN_COUNT_PRIQr, register_type_global},
    {MMU_THDR_QE_RESET_OFFSET_COLOR_PRIQr, register_type_global},
    {MMU_THDR_QE_RESUME_COLOR_LIMIT_SPr, register_type_global},
    {MMU_THDR_QE_SHARED_COLOR_LIMIT_SPr, register_type_global},
    {MMU_THDR_QE_SHARED_COUNT_PRIQr, register_type_global},
    {MMU_THDR_QE_SHARED_COUNT_SPr, register_type_global},
    {MMU_THDR_QE_STATUSr, register_type_global},
    {MMU_THDR_QE_STATUS_PRIQr, register_type_global},
    {MMU_THDR_QE_STATUS_SPr, register_type_global},
    {IDB_OBM0_CONTROLr, register_type_global},
    {IDB_OBM0_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM0_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM0_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM0_SHARED_CONFIGr, register_type_global},
    {IDB_OBM0_PORT_CONFIGr, register_type_global},
    {IDB_OBM1_CONTROLr, register_type_global},
    {IDB_OBM1_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM1_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM1_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM1_SHARED_CONFIGr, register_type_global},
    {IDB_OBM1_THRESHOLDr, register_type_global},
    {IDB_OBM1_PORT_CONFIGr, register_type_global},
    {IDB_OBM2_CONTROLr, register_type_global},
    {IDB_OBM2_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM2_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM2_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM2_SHARED_CONFIGr, register_type_global},
    {IDB_OBM2_THRESHOLDr, register_type_global},
    {IDB_OBM2_PORT_CONFIGr, register_type_global},
    {IDB_OBM3_CONTROLr, register_type_global},
    {IDB_OBM3_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM3_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM3_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM3_SHARED_CONFIGr, register_type_global},
    {IDB_OBM3_THRESHOLDr, register_type_global},
    {IDB_OBM3_PORT_CONFIGr, register_type_global},
    {IDB_OBM4_CONTROLr, register_type_global},
    {IDB_OBM4_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM4_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM4_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM4_SHARED_CONFIGr, register_type_global},
    {IDB_OBM4_THRESHOLDr, register_type_global},
    {IDB_OBM4_PORT_CONFIGr, register_type_global},
    {IDB_OBM5_CONTROLr, register_type_global},
    {IDB_OBM5_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM5_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM5_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM5_SHARED_CONFIGr, register_type_global},
    {IDB_OBM5_PORT_CONFIGr, register_type_global},
    {IDB_OBM6_CONTROLr, register_type_global},
    {IDB_OBM6_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM6_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM6_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM6_SHARED_CONFIGr, register_type_global},
    {IDB_OBM6_PORT_CONFIGr, register_type_global},
    {IDB_OBM7_CONTROLr, register_type_global},
    {IDB_OBM7_PROTOCOL_CONTROL_0r, register_type_global},
    {IDB_OBM7_PROTOCOL_CONTROL_1r, register_type_global},
    {IDB_OBM7_PROTOCOL_CONTROL_2r, register_type_global},
    {IDB_OBM7_SHARED_CONFIGr, register_type_global},
    {IDB_OBM7_PORT_CONFIGr, register_type_global},
    {IDB_OBM0_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM0_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM0_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM0_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM0_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM0_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM0_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM0_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM0_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM0_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM0_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM0_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM0_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM0_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM0_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM0_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM0_THRESHOLD_0r, register_type_global},
    {IDB_OBM0_THRESHOLD_1r, register_type_global},
    {IDB_OBM1_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM1_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM1_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM1_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM1_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM1_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM1_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM1_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM1_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM1_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM1_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM1_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM1_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM1_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM1_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM1_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM1_THRESHOLD_0r, register_type_global},
    {IDB_OBM1_THRESHOLD_1r, register_type_global},
    {IDB_OBM2_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM2_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM2_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM2_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM2_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM2_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM2_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM2_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM2_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM2_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM2_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM2_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM2_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM2_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM2_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM2_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM2_THRESHOLD_0r, register_type_global},
    {IDB_OBM2_THRESHOLD_1r, register_type_global},
    {IDB_OBM3_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM3_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM3_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM3_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM3_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM3_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM3_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM3_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM3_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM3_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM3_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM3_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM3_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM3_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM3_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM3_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM3_THRESHOLD_0r, register_type_global},
    {IDB_OBM3_THRESHOLD_1r, register_type_global},
    {IDB_OBM4_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM4_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM4_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM4_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM4_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM4_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM4_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM4_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM4_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM4_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM4_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM4_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM4_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM4_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM4_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM4_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM4_THRESHOLD_0r, register_type_global},
    {IDB_OBM4_THRESHOLD_1r, register_type_global},
    {IDB_OBM5_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM5_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM5_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM5_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM5_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM5_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM5_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM5_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM5_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM5_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM5_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM5_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM5_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM5_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM5_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM5_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM5_THRESHOLD_0r, register_type_global},
    {IDB_OBM5_THRESHOLD_1r, register_type_global},
    {IDB_OBM6_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM6_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM6_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM6_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM6_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM6_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM6_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM6_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM6_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM6_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM6_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM6_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM6_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM6_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM6_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM6_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM6_THRESHOLD_0r, register_type_global},
    {IDB_OBM6_THRESHOLD_1r, register_type_global},
    {IDB_OBM7_BUCKET_COUNT_CONFIGr, register_type_global},
    {IDB_OBM7_EXPRESS_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM7_EXPRESS_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM7_EXPRESS_BYTE_DROP_COUNTr, register_type_global},
    {IDB_OBM7_EXPRESS_FLOW_CONTROL_CONFIGr, register_type_global},
    {IDB_OBM7_EXPRESS_PKT_DROP_COUNTr, register_type_global},
    {IDB_OBM7_FC_THRESHOLD_0r, register_type_global},
    {IDB_OBM7_FC_THRESHOLD_1r, register_type_global},
    {IDB_OBM7_LOSSLESS0_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM7_LOSSLESS0_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM7_LOSSLESS1_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM7_LOSSLESS1_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM7_LOSSY_HI_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM7_LOSSY_HI_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM7_LOSSY_LO_ARRIVAL_BYTE_COUNTr, register_type_global},
    {IDB_OBM7_LOSSY_LO_ARRIVAL_PKT_COUNTr, register_type_global},
    {IDB_OBM7_THRESHOLD_0r, register_type_global},
    {IDB_OBM7_THRESHOLD_1r, register_type_global},
    {ASF_PORT_CFGr, register_type_global},
    {CELL_ASM_CUT_THRU_THRESHOLD0r, register_type_global},
    {CFAPFULLSETPOINTr, register_type_global},
    {CFAPFULLRESETPOINTr, register_type_global},
    {ENQ_ASF_HS_OVERSUB_ENr, register_type_global},
    {ENQ_CONFIGr, register_type_global},
    {ES_PIPE0_ASF_CREDIT_THRESH_HIr, register_type_global},
    {ES_PIPE0_ASF_CREDIT_THRESH_LOr, register_type_global},
    {ING_COS_MODE_64r, register_type_global},
    {PORT_PFC_CFG0r, register_type_global},
    {PORT_PFC_CFG1r, register_type_global},
    {PORT_PFC_CFG2r, register_type_global},
    {PRIO2COS_PROFILEr, register_type_global},
    {MMU_TO_XPORT_BKPr, register_type_global},
    {XPORT_TO_MMU_BKPr, register_type_global},
    {MMU_LLFC_TX_CONFIG_1r, register_type_global},
    {MMU_LLFC_TX_CONFIG_2r, register_type_global},
    {XLMAC_PFC_CTRLr, register_type_global},
    {XLMAC_PAUSE_CTRLr, register_type_global},
    {XLMAC_PFC_TYPEr, register_type_global},
    {XLMAC_PFC_OPCODEr, register_type_global},
    {XLMAC_PFC_DAr, register_type_global},
    {XLMAC_TX_MAC_SAr, register_type_global},
    {XLMAC_B0_PFC_CTRLr, register_type_global},
    {XLMAC_B0_PAUSE_CTRLr, register_type_global},
    {XLMAC_B0_PFC_TYPEr, register_type_global},
    {XLMAC_B0_PFC_OPCODEr, register_type_global},
    {XLMAC_B0_PFC_DAr, register_type_global},
    {XLMAC_B0_TX_MAC_SAr, register_type_global},
    {CLMAC_PFC_CTRLr, register_type_global},
    {CLMAC_PAUSE_CTRLr, register_type_global},
    {CLMAC_PFC_TYPEr, register_type_global},
    {CLMAC_PFC_OPCODEr, register_type_global},
    {CLMAC_PFC_DAr, register_type_global},
    {CLMAC_TX_MAC_SAr, register_type_global},
    {CLG2MAC_PFC_CTRLr, register_type_global},
    {CLG2MAC_PAUSE_CTRLr, register_type_global},
    {CLG2MAC_PFC_TYPEr, register_type_global},
    {CLG2MAC_PFC_OPCODEr, register_type_global},
    {CLG2MAC_PFC_DAr, register_type_global},
    {CLG2MAC_TX_MAC_SAr, register_type_global},
    {PGW_OBM_PARSING_CONTROLr, register_type_global},
    {HSP_SCHED_PORT_PREEMPT_CONFIGr, register_type_global},
    {CLMAC_MERGE_CONFIGr, register_type_global},
    {CLMAC_MERGE_VERIFY_STATEr, register_type_global},
    {CLMAC_MERGE_RX_TIMEOUT_CONFIGr, register_type_global},
    {CLMAC_TX_TIMESTAMP_FIFO_STATUSr, register_type_global},
    {CLPORT_MIB_MIN_FRAG_SIZEr, register_type_global},
    {XLMAC_MERGE_CONFIGr, register_type_global},
    {XLMAC_MERGE_VERIFY_STATEr, register_type_global},
    {XLMAC_MERGE_RX_TIMEOUT_CONFIGr, register_type_global},
    {XLMAC_TX_TIMESTAMP_FIFO_STATUSr, register_type_global},
    {XLPORT_MIB_MIN_FRAG_SIZEr, register_type_global},
    {INVALIDr, register_type_global } /* Must be the last element in this structure */
};

/* Structure that maintains  diag cmdlist, reg_list, mem_list  for
 * "mmu" feature for monterey chipset. */
techsupport_data_t techsupport_mmu_monterey_data = {
    techsupport_mmu_diag_cmdlist,
    techsupport_mmu_monterey_reg_list,
    techsupport_mmu_monterey_memory_table_list,
    techsupport_mmu_monterey_diag_cmdlist
#ifndef BCM_SW_STATE_DUMP_DISABLE
    , techsupport_mmu_sw_dump_cmdlist,
   techsupport_mmu_monterey_sw_dump_cmdlist
#endif /* BCM_SW_STATE_DUMP_DISABLE */
};

