# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2022 Broadcom Inc. All rights reserved.
#
# Makefile for BCM Tomahawk driver Library
#

LOCALDIR = src/bcm/esw/tomahawk

include ${SDK}/make/Make.config

lib = libtomahawk

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
