# $Id: Makefile,v 1.4 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#
# Makefile for SOC SAL support
#
LOCALDIR = src/sal/core

include ${SDK}/make/Make.config

subdirs=${targetbase}
include ${SDK}/make/Make.subdirs

lib = libsal_core
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
