#
# $Id: Makefile,v 1.0 2019/01/11 15:32:17 ya889855 Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/bcm/dnx/cosq/latency

include ${SDK}/make/Make.config

#subdirs = port

include ${SDK}/make/Make.subdirs

lib = libbcm_dnxcosqlatency

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend


