/*
 * 
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * File:        ramon_mbcm.c
 * Purpose:     Init the bcm multiplexing function table for RAMON
 */


#include <soc/dnxf/cmn/mbcm.h>

#include <soc/dnxc/dnxc_captured_buffer.h>
#include <soc/dnxc/dnxc_cells_buffer.h>

#include <soc/dnxf/ramon/ramon_stat.h>
#include <soc/dnxf/ramon/ramon_stack.h>
#include <soc/dnxf/ramon/ramon_drv.h>
#include <soc/dnxf/ramon/ramon_diag.h>
#include <soc/dnxf/ramon/ramon_link.h>
#include <soc/dnxf/ramon/ramon_intr.h>
#include <soc/dnxf/ramon/ramon_fabric_links.h>
#include <soc/dnxf/ramon/ramon_fabric_topology.h>
#include <soc/dnxf/ramon/ramon_fabric_cell.h>
#include <soc/dnxf/ramon/ramon_port.h>
#include <soc/dnxf/ramon/ramon_fabric_cell_snake_test.h>
#include <soc/dnxf/ramon/ramon_fifo_dma.h>
#include <soc/dnxf/ramon/ramon_cosq.h>
#include <soc/dnxf/ramon/ramon_multicast.h>
#include <soc/dnxf/ramon/ramon_rx.h>
#include <soc/dnxf/ramon/ramon_fabric_status.h>
#include <soc/dnxf/ramon/ramon_fabric_multicast.h>
#include <soc/dnxf/ramon/ramon_cgm.h>

#include <soc/dnxc/dnxc_intr.h>

#include <soc/portmod/portmod.h>

mbcm_dnxf_functions_t mbcm_ramon_driver = {
    soc_ramon_tbl_is_dynamic,
    soc_dnxc_ser_init,
    soc_ramon_reset_device,
    soc_ramon_drv_soft_init,
    soc_ramon_drv_blocks_reset,
    soc_ramon_drv_reg_access_only_reset,
    soc_ramon_sr_cell_send,
    soc_ramon_cell_filter_init,
    soc_ramon_cell_filter_set,
    soc_ramon_cell_filter_clear,
    soc_ramon_cell_filter_count_get,
    soc_ramon_control_cell_filter_set,
    soc_ramon_control_cell_filter_clear,
    soc_ramon_control_cell_filter_receive,
    soc_ramon_cell_snake_test_prepare,
    soc_ramon_cell_snake_test_run,
    soc_ramon_diag_fabric_cell_snake_test_interrupts_name_get,
    soc_ramon_diag_cell_pipe_counter_get,
    soc_ramon_diag_mesh_topology_get,
    soc_ramon_drv_mbist,        
    soc_ramon_drv_link_to_block_mapping,
    soc_ramon_drv_block_pbmp_get,
    soc_ramon_fabric_cell_get,
    soc_ramon_fabric_cell_parse_table_get,
    soc_ramon_cgm_threshold_to_reg_table_get,
    soc_ramon_cgm_link_profile_set,
    soc_ramon_cgm_link_profile_get,
    soc_ramon_cgm_rci_resolution_set,
    soc_ramon_cgm_rci_resolution_get,
    soc_ramon_fabric_links_validate_link,
    soc_ramon_fabric_links_isolate_set,
    soc_ramon_fabric_links_isolate_get,
    soc_ramon_fabric_links_flow_status_control_cell_format_set,
    soc_ramon_fabric_links_flow_status_control_cell_format_get,
    soc_ramon_fabric_links_llf_control_source_set,
    soc_ramon_fabric_links_llf_control_source_get,
    soc_ramon_fabric_links_aldwp_config,
    soc_ramon_fabric_links_aldwp_init,
    soc_ramon_fabric_links_pcp_enable_set,
    soc_ramon_fabric_links_pcp_enable_get,
    soc_ramon_fabric_multicast_low_prio_drop_select_priority_set,
    soc_ramon_fabric_multicast_low_prio_drop_select_priority_get,
    soc_ramon_fabric_multicast_low_prio_threshold_validate,
    soc_ramon_fabric_multicast_low_prio_threshold_set,
    soc_ramon_fabric_multicast_low_prio_threshold_get,
    soc_ramon_fabric_multicast_low_priority_drop_enable_set,
    soc_ramon_fabric_multicast_low_priority_drop_enable_get,
    soc_ramon_fabric_multicast_priority_range_validate,
    soc_ramon_fabric_multicast_priority_range_set,
    soc_ramon_fabric_multicast_priority_range_get,
    soc_ramon_fabric_multicast_multi_set,
    soc_ramon_fabric_multicast_multi_get,
    soc_ramon_fabric_multicast_multi_write_range,
    soc_ramon_fabric_multicast_multi_read_range,
    soc_ramon_fabric_multicast_local_route_default_init,
    soc_ramon_fabric_multicast_local_route_bit_get,
    soc_ramon_fabric_multicast_direct_offset_set,
    soc_ramon_fabric_multicast_direct_offset_get,
    soc_ramon_fabric_link_repeater_enable_set,
    soc_ramon_fabric_link_repeater_enable_get,
    soc_ramon_fabric_link_retimer_calibrate,
    soc_ramon_fabric_link_retimer_connect_set,
    soc_ramon_fabric_link_retimer_connect_get,
    soc_ramon_fabric_link_status_get,
    soc_ramon_fabric_reachability_status_get,
    soc_ramon_fabric_link_connectivity_status_get,
    soc_ramon_fabric_stat_get,
    soc_ramon_fabric_links_pipe_map_set,
    soc_ramon_fabric_links_pipe_map_get,
    soc_ramon_fabric_links_link_integrity_down_set,
    soc_ramon_fabric_topology_isolate_set,
    soc_ramon_fabric_topology_isolate_get,
    soc_ramon_fabric_topology_rmgr_set,
    soc_ramon_fabric_topology_local_route_control_cells_enable_set,
    soc_ramon_fabric_topology_lb_set,
    soc_ramon_fabric_topology_lb_get,
    soc_ramon_fabric_topology_modid_group_map_set,
    soc_ramon_fabric_topology_mc_sw_control_set,
    soc_ramon_fabric_topology_mc_sw_control_get,
    soc_ramon_fabric_topology_mc_set,
    soc_ramon_fabric_topology_mc_get,
    soc_ramon_fifo_dma_channel_init,
    soc_ramon_fifo_dma_channel_deinit,
    soc_ramon_fifo_dma_channel_read_entries,
    soc_ramon_fifo_dma_fabric_cell_validate,
    soc_ramon_nof_interrupts,
    soc_ramon_nof_block_instances,
    soc_ramon_multicast_egress_add,
    soc_ramon_multicast_egress_delete,
    soc_ramon_multicast_egress_delete_all,
    soc_ramon_multicast_egress_get,
    soc_ramon_multicast_egress_set,
    soc_ramon_multicast_mode_get,
    soc_ramon_multicast_table_size_get,
    soc_ramon_multicast_table_entry_size_get,
    soc_ramon_port_soc_init,
    soc_ramon_port_init,
    soc_ramon_port_deinit,
    soc_ramon_port_detach,
    soc_ramon_port_probe,
    soc_dnxf_lane_map_db_map_set,
    soc_dnxf_lane_map_db_map_get,
    soc_dnxc_port_control_power_set,
    soc_dnxc_port_control_power_get,
    soc_dnxc_port_control_low_latency_llfc_set,
    soc_dnxc_port_control_low_latency_llfc_get,
    soc_dnxc_port_control_fec_error_detect_set,
    soc_dnxc_port_control_fec_error_detect_get,
    soc_dnxc_port_control_llfc_after_fec_enable_set,
    soc_dnxc_port_control_llfc_after_fec_enable_get,
    soc_dnxc_port_cl72_set,
    soc_dnxc_port_cl72_get,
    soc_dnxc_port_phy_control_set,
    soc_dnxc_port_phy_control_get,
    soc_dnxc_port_loopback_set,
    soc_dnxc_port_loopback_get,
    soc_ramon_port_fault_get,
    soc_ramon_port_speed_max,
    soc_ramon_port_serdes_power_disable,
    soc_ramon_port_link_status_get,
    soc_ramon_port_bucket_fill_rate_validate,
    soc_dnxc_port_prbs_tx_enable_set,
    soc_dnxc_port_prbs_tx_enable_get,
    soc_dnxc_port_prbs_rx_enable_set,
    soc_dnxc_port_prbs_rx_enable_get,
    soc_dnxc_port_prbs_rx_status_get,
    soc_dnxc_port_prbs_polynomial_set,
    soc_dnxc_port_prbs_polynomial_get,
    soc_dnxc_port_prbs_tx_invert_data_set,
    soc_dnxc_port_prbs_tx_invert_data_get,
    soc_ramon_port_pump_enable_set,
    soc_dnxc_port_rate_egress_ppt_set,
    soc_dnxc_port_rate_egress_ppt_get,
    soc_ramon_port_burst_control_set,
    soc_dnxc_port_extract_cig_from_llfc_enable_set,
    soc_dnxc_port_extract_cig_from_llfc_enable_get,
    soc_dnxc_port_phy_reg_get,
    soc_dnxc_port_phy_reg_set,
    soc_dnxc_port_phy_reg_modify,
    soc_ramon_port_dynamic_port_update,
    soc_ramon_port_enable_set,
    soc_dnxc_port_enable_get,
    soc_ramon_port_sync_e_link_set,
    soc_ramon_port_sync_e_divider_set,
    soc_ramon_port_sync_e_link_get,
    soc_ramon_port_sync_e_divider_get,
    soc_ramon_set_mesh_topology_config,
    soc_ramon_stk_modid_set,
    soc_ramon_stk_modid_get,
    soc_ramon_stk_module_max_all_reachable_verify,
    soc_ramon_stk_module_max_all_reachable_set,
    soc_ramon_stk_module_max_all_reachable_get,
    soc_ramon_stk_module_max_fap_verify,
    soc_ramon_stk_module_max_fap_set,
    soc_ramon_stk_module_max_fap_get,
    soc_ramon_stk_module_all_reachable_ignore_id_set,
    soc_ramon_stk_module_all_reachable_ignore_id_get,
    soc_ramon_stk_valid_module_id_verify,
    soc_ramon_stat_init,
    soc_ramon_stat_is_supported_type,
    soc_ramon_stat_counter_length_get,
    soc_ramon_stat_get,
    soc_ramon_mapping_stat_get,
    soc_ramon_counters_get_info,
    soc_ramon_queues_get_info,
    soc_ramon_fabric_link_device_mode_get,
    soc_ramon_controlled_counter_set,
    soc_ramon_linkctrl_init,
    soc_dnxc_interrupts_init,
    soc_dnxc_interrupts_deinit,
    soc_dnxc_interrupt_all_enable_set,
    NULL,
    soc_ramon_temperature_monitor_regs_get,
    soc_ramon_cosq_pipe_weight_set,
    soc_ramon_cosq_pipe_weight_get,
    soc_ramon_rx_cpu_address_modid_set,
    soc_ramon_rx_cpu_address_modid_init,
    soc_ramon_drv_block_valid_get,
    soc_ramon_port_stat_gtimer_config_set,
    soc_ramon_port_stat_gtimer_config_get
};
