
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __DNX_DRAM_LAYOUT_H__
#define __DNX_DRAM_LAYOUT_H__

#include <include/soc/dnxc/swstate/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int dnx_dram_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_DNX_DRAM_DB = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(DNX_DRAM_MODULE_ID, 0),
    DNX_SW_STATE_DNX_DRAM_DB__FIRST,
    DNX_SW_STATE_DNX_DRAM_DB__FIRST_SUB = DNX_SW_STATE_DNX_DRAM_DB__FIRST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__IS_INITIALIZED,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK,
    DNX_SW_STATE_DNX_DRAM_DB__OVERRIDE_BIST_CONFIGURATIONS_DURING_TUNING,
    DNX_SW_STATE_DNX_DRAM_DB__CHANNEL_SOFT_INIT_AFTER_BIST,
    DNX_SW_STATE_DNX_DRAM_DB__TRAFFIC_TUNING_CORE_MODE,
    DNX_SW_STATE_DNX_DRAM_DB__DYNAMIC_CALIBRATION_ENABLED,
    DNX_SW_STATE_DNX_DRAM_DB__DYNAMIC_CALIBRATION_WAS_ENABLED_AFTER_DRAM_TUNE,
    DNX_SW_STATE_DNX_DRAM_DB__TEMPERATURE_MONITORING_THREAD_STATE,
    DNX_SW_STATE_DNX_DRAM_DB__TEMPERATURE_MONITORING_THREAD_HANDLER,
    DNX_SW_STATE_DNX_DRAM_DB__TEMPERATURE_MONITORING_LAST_READ,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO,
    DNX_SW_STATE_DNX_DRAM_DB__LAST,
    DNX_SW_STATE_DNX_DRAM_DB__LAST_SUB = DNX_SW_STATE_DNX_DRAM_DB__LAST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__FIRST,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__FIRST_SUB = DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__FIRST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__DELETED_BUFFERS_FILE_MUTEX,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__FIRMWARE_MUTEX,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__LAST,
    DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__LAST_SUB = DNX_SW_STATE_DNX_DRAM_DB__SYNC_MANAGER__LAST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__FIRST,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__FIRST_SUB = DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__FIRST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__CALLBACK,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__POWER_ON,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__USERDATA,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__LAST,
    DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__LAST_SUB = DNX_SW_STATE_DNX_DRAM_DB__POWER_DOWN_CALLBACK__LAST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__FIRST,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__FIRST_SUB = DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__FIRST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__IS_INIT,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__GEN2_TEST,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__ECC,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__DENSITY,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__MANUFACTURER_ID,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__MANUFACTURING_LOCATION,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__MANUFACTURING_YEAR,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__MANUFACTURING_WEEK,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__SERIAL_NUMBER,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__ADDRESSING_MODE,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__CHANNEL_AVAILABLE,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__HBM_STACK_HIGHT,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__MODEL_PART_NUMBER,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__LAST,
    DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__LAST_SUB = DNX_SW_STATE_DNX_DRAM_DB__VENDOR_INFO__LAST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__FIRST,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__FIRST_SUB = DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__FIRST - 1,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__IS_INIT,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__MANUFACTURER_VENDOR_CODE,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__REVISION_ID,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__DENSITY,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__INTERNAL_WCK,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__WCK_GRANULARITY,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__WCK_FREQUENCY,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__VDDQ_OFF,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__LAST,
    DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__LAST_SUB = DNX_SW_STATE_DNX_DRAM_DB__GDDR6_VENDOR_INFO__LAST - 1,
    
    DNX_SW_STATE_DNX_DRAM_DB_NOF_PARAMS,
} dnxc_sw_state_layout_dnx_dram_node_id_e;

#endif 
