
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __DNX_FIFODMA_LAYOUT_H__
#define __DNX_FIFODMA_LAYOUT_H__

#include <include/soc/dnxc/swstate/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int dnx_fifodma_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_DNX_FIFODMA_INFO = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(DNX_FIFODMA_MODULE_ID, 0),
    DNX_SW_STATE_DNX_FIFODMA_INFO__FIRST,
    DNX_SW_STATE_DNX_FIFODMA_INFO__FIRST_SUB = DNX_SW_STATE_DNX_FIFODMA_INFO__FIRST - 1,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY,
    DNX_SW_STATE_DNX_FIFODMA_INFO__FIFODMA_THREAD_SHR_THREAD_MANAGER_HANDLER,
    DNX_SW_STATE_DNX_FIFODMA_INFO__LAST,
    DNX_SW_STATE_DNX_FIFODMA_INFO__LAST_SUB = DNX_SW_STATE_DNX_FIFODMA_INFO__LAST - 1,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__FIRST,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__FIRST_SUB = DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__FIRST - 1,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__MAX_ENTRIES,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__ENTRY_SIZE,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__HOST_BUFF_LO,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__HOST_BUFF_HI,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__IS_MEM,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__MEM,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__REG,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__ARRAY_INDEX,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__COPYNO,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__FORCE_ENTRY_SIZE,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__THRESHOLD,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__TIMEOUT,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__IS_POLL,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__IS_ALLOCED,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__IS_STARTED,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__IS_PAUSED,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__LAST_ENTRY_ID,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__HANDLER,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__LAST,
    DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__LAST_SUB = DNX_SW_STATE_DNX_FIFODMA_INFO__ENTRY__LAST - 1,
    
    DNX_SW_STATE_DNX_FIFODMA_INFO_NOF_PARAMS,
} dnxc_sw_state_layout_dnx_fifodma_node_id_e;

#endif 
