
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __DNX_FIELD_TCAM_ACCESS_LAYOUT_H__
#define __DNX_FIELD_TCAM_ACCESS_LAYOUT_H__

#include <include/soc/dnxc/swstate/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int dnx_field_tcam_access_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(DNX_FIELD_TCAM_ACCESS_MODULE_ID, 0),
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FIRST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_LOCATION_HASH,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PREFIX_PER_CORE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__CACHE_INSTALL_IN_PROGRESS,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__LAST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__LAST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__FIRST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__V_BIT,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__LAST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__LAST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__VALID_BMP__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__FIRST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__V_BIT,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__LAST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__LAST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__ENTRY_IN_USE_BMP__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__FIRST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__DT_BANK_ID,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__STAGE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__BANK_ALLOCATION_MODE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__KEY_SIZE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__ACTION_SIZE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__ACTUAL_ACTION_SIZE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__PREFIX_SIZE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__DIRECT_TABLE,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__CONTEXT_SHARING_HANDLERS_CB,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__LAST,
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__LAST_SUB = DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW__FG_PARAMS__LAST - 1,
    
    DNX_SW_STATE_DNX_FIELD_TCAM_ACCESS_SW_NOF_PARAMS,
} dnxc_sw_state_layout_dnx_field_tcam_access_node_id_e;

#endif 
