
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __DNX_FIELD_ACTIONS_LAYOUT_H__
#define __DNX_FIELD_ACTIONS_LAYOUT_H__

#include <include/soc/dnxc/swstate/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int dnx_field_actions_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(DNX_FIELD_ACTIONS_MODULE_ID, 0),
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FIRST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__LAST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__LAST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__FIRST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__FIELD_ID,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__FLAGS,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__BCM_ID,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__VALID,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__SIZE,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__PREFIX,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__REF_COUNT,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__BASE_DNX_ACTION,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__PREFIX_SIZE,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__LAST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__LAST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__INFO__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FIRST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__LAST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__LAST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__FIRST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__FEM_ENCODED_ACTIONS,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__SECOND_FG_ID,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__FG_ID,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__INPUT_OFFSET,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__INPUT_SIZE,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__IGNORE_ACTIONS,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__LAST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__LAST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__FEM_INFO__FG_ID_INFO__LAST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__FIRST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__FIRST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__FIRST - 1,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__FIELD_ID,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__LAST,
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__LAST_SUB = DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB__PREDEFINED__LAST - 1,
    
    DNX_SW_STATE_DNX_FIELD_ACTION_SW_DB_NOF_PARAMS,
} dnxc_sw_state_layout_dnx_field_actions_node_id_e;

#endif 
