
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifndef __TRUNK_LAYOUT_H__
#define __TRUNK_LAYOUT_H__

#include <include/soc/dnxc/swstate/dnxc_sw_state_layout.h>
#include <include/soc/dnxc/swstate/auto_generated/types/dnxc_module_ids_types.h>


int trunk_init_layout_structure(int unit);

typedef enum
{
    DNX_SW_STATE_TRUNK_DB = DNXC_SW_STATE_LAYOUT_NODE_ID_GET(TRUNK_MODULE_ID, 0),
    DNX_SW_STATE_TRUNK_DB__FIRST,
    DNX_SW_STATE_TRUNK_DB__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO,
    DNX_SW_STATE_TRUNK_DB__LAST,
    DNX_SW_STATE_TRUNK_DB__LAST_SUB = DNX_SW_STATE_TRUNK_DB__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS__FIRST,
    DNX_SW_STATE_TRUNK_DB__POOLS__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__POOLS__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS,
    DNX_SW_STATE_TRUNK_DB__POOLS__LAST,
    DNX_SW_STATE_TRUNK_DB__POOLS__LAST_SUB = DNX_SW_STATE_TRUNK_DB__POOLS__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__FIRST,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__PSC,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__PSC_PROFILE_ID,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__NOF_MEMBERS,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__LAST_MEMBER_ADDED_INDEX,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__IN_USE,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__PP_PORTS,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__IN_HEADER_TYPE,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__OUT_HEADER_TYPE,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__FLAGS,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MASTER_TRUNK_ID,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__LAST,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__LAST_SUB = DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__FIRST,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__SYSTEM_PORT,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__FLAGS,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__INDEX,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__SPA_MEMBER_ID,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__PROTECTING_SYSTEM_PORT,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__LAST,
    DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__LAST_SUB = DNX_SW_STATE_TRUNK_DB__POOLS__GROUPS__MEMBERS__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__FIRST,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__LAST,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__LAST_SUB = DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__FIRST,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__TRUNK_ID,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__FLAGS,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__LAST,
    DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__LAST_SUB = DNX_SW_STATE_TRUNK_DB__TRUNK_SYSTEM_PORT_DB__TRUNK_SYSTEM_PORT_ENTRIES__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__FIRST,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__CHM_HANDLE,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__LAST,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__LAST_SUB = DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__FIRST,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__PSC_PROFILE_TYPE,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__MAX_NOF_MEMBERS,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__LAST,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__LAST_SUB = DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__PROFILE_INFO__LAST - 1,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__FIRST,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__FIRST_SUB = DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__FIRST - 1,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__ASSIGNED_PSC_PROFILE,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__REF_COUNTER,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__LAST,
    DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__LAST_SUB = DNX_SW_STATE_TRUNK_DB__PSC_GENERAL_INFO__USER_PROFILE_INFO__LAST - 1,
    
    DNX_SW_STATE_TRUNK_DB_NOF_PARAMS,
} dnxc_sw_state_layout_trunk_node_id_e;

#endif 
