/** \file algo/swstate/auto_generated/layout/algo_tunnel_layout.c
 *
 * sw state layout structure
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2022 Broadcom Inc. All rights reserved.
 */

#ifdef BSL_LOG_MODULE
#error "BSL_LOG_MODULE redefined"
#endif
#define BSL_LOG_MODULE BSL_LS_SWSTATEDNX_GENERAL

#include <bcm_int/dnx/algo/swstate/auto_generated/types/algo_tunnel_types.h>
#include <bcm_int/dnx/algo/swstate/auto_generated/layout/algo_tunnel_layout.h>

dnxc_sw_state_layout_t layout_array_algo_tunnel[DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB_NOF_PARAMS)];

shr_error_e
algo_tunnel_init_layout_structure(int unit)
{

    int idx;

    DNXC_SW_STATE_INIT_FUNC_DEFS;

    idx = DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB);
    layout_array_algo_tunnel[idx].name = "algo_tunnel_db";
    layout_array_algo_tunnel[idx].type = "algo_tunnel_sw_state_t";
    layout_array_algo_tunnel[idx].doc = "Algo Tunnel sw state";
    layout_array_algo_tunnel[idx].total_size = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].size_of = sizeof(algo_tunnel_sw_state_t);
    layout_array_algo_tunnel[idx].parent  = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].first_child_index = DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB__FIRST);
    layout_array_algo_tunnel[idx].last_child_index = DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB__LAST);

    idx = DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB__TUNNEL_IPV6_SIP_PROFILE);
    layout_array_algo_tunnel[idx].name = "algo_tunnel_db__tunnel_ipv6_sip_profile";
    layout_array_algo_tunnel[idx].type = "dnx_algo_template_t";
    layout_array_algo_tunnel[idx].doc = "TUNNEL IPV6 SIP PROFILE TEMPLATE";
    layout_array_algo_tunnel[idx].total_size = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].size_of = sizeof(dnx_algo_template_t);
    layout_array_algo_tunnel[idx].parent  = 0;
    layout_array_algo_tunnel[idx].first_child_index = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].last_child_index = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].labels = DNXC_SW_STATE_LAYOUT_LABEL_ALLOC_EXCEPTION;

    idx = DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB__UDP_PORTS_PROFILE);
    layout_array_algo_tunnel[idx].name = "algo_tunnel_db__udp_ports_profile";
    layout_array_algo_tunnel[idx].type = "dnx_algo_template_t";
    layout_array_algo_tunnel[idx].doc = "This template mirrors the additional header profiles reserved for UDP tunnels. Each UDP tunnel lif can point to a profile to get its UDP src and destination port.";
    layout_array_algo_tunnel[idx].total_size = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].size_of = sizeof(dnx_algo_template_t);
    layout_array_algo_tunnel[idx].parent  = 0;
    layout_array_algo_tunnel[idx].first_child_index = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].last_child_index = DNXC_SW_STATE_LAYOUT_INVALID;

    idx = DNXC_SW_STATE_LAYOUT_GET_PARAM_IDX(DNX_SW_STATE_ALGO_TUNNEL_DB__FLOW_GPORT_TO_TUNNEL_TYPE);
    layout_array_algo_tunnel[idx].name = "algo_tunnel_db__flow_gport_to_tunnel_type";
    layout_array_algo_tunnel[idx].type = "sw_state_htbl_t";
    layout_array_algo_tunnel[idx].total_size = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].size_of = sizeof(sw_state_htbl_t);
    layout_array_algo_tunnel[idx].parent  = 0;
    layout_array_algo_tunnel[idx].first_child_index = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].last_child_index = DNXC_SW_STATE_LAYOUT_INVALID;
    layout_array_algo_tunnel[idx].labels = DNXC_SW_STATE_LAYOUT_LABEL_ALLOC_EXCEPTION;


    dnxc_sw_state_layout_init_structure(unit, DNX_SW_STATE_ALGO_TUNNEL_DB, layout_array_algo_tunnel, sw_state_layout_array[unit][ALGO_TUNNEL_MODULE_ID], DNX_SW_STATE_ALGO_TUNNEL_DB_NOF_PARAMS);

    DNXC_SW_STATE_FUNC_RETURN;
}

#undef BSL_LOG_MODULE
