# $Id: Makefile,v 1.3 Broadcom SDK $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/dpp/ptp

include ${SDK}/make/Make.config

#CFLAGS += -DPTP_RX_CALLBACK_DEBUG

lib = libptp_dpp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
