# $Id$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
LOCALDIR = src/soc/dpp/TMC

include ${SDK}/make/Make.config

lib = libbcm_dpp_tmc

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
