# $Id: Makefile,v 1.1 2009/06/04 15:13:02 srajesh Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SOC driver Library
#

LOCALDIR = src/bcm/esw/hurricane2

include ${SDK}/make/Make.config

lib = libhurricane2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
