#
# $Id:$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/soc/dnxf/swstate

include ${SDK}/make/Make.config
#
# Take the subdirs 'auto_generated'
#
subdirs = auto_generated

include ${SDK}/make/Make.subdirs

lib = libsoc_dnxfswstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
