#
# $Id: Makefile,v 1.1.2.1 2013/09/08 10:10:28 eliad Exp $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dpp/DRC/

include ${SDK}/make/Make.config

lib = libsoc_dpp_drc

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

