# 
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2019 Broadcom Inc. All rights reserved.
# 
# Makefile for Katana2 SOC driver Library
#

LOCALDIR = src/soc/esw/saber2

include ${SDK}/make/Make.config

lib = libsoc_saber2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

