#
# $Id: Makefile,v 1.4 2017/02/02 10:43:54 rsportas Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#


LOCALDIR = src/appl/diag/dnx/dram

include ${SDK}/make/Make.config

include ${SDK}/make/Make.subdirs

lib = libdiag_dnxdram

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend

