#
# $Id: Makefile,v 1.3 Broadcom SDK $
#
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2021 Broadcom Inc. All rights reserved.
#

LOCALDIR = src/soc/dpp/QAX/QAX_PP

include ${SDK}/make/Make.config

lib = libsoc_dpp_qax_pp

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
