# $Id:$
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for SDK board driver Library
#

LOCALDIR = src/board/driver

include ${SDK}/make/Make.config

lib = libboard_dvr
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
