# $Id: Makefile,v 1.1 2011/06/19 17:04:39 srajesh Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/esw/katana2

include ${SDK}/make/Make.config

lib = libkatana2

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
