
/* *INDENT-OFF* */
/*
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2021 Broadcom Inc. All rights reserved.
 */
#ifndef _DNX_DATA_MAX_MACSEC_H_

#define _DNX_DATA_MAX_MACSEC_H_




#ifndef BCM_DNX_SUPPORT
#error "This file is for use by DNX (JR2) family only!"
#endif


#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_NOF (10)

#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_IN_CORE_NOF (5)

#define DNX_DATA_MAX_MACSEC_GENERAL_PORTS_IN_MACSEC_NOF (16)

#define DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOF (4)

#define DNX_DATA_MAX_MACSEC_GENERAL_ETYPE_NOT_ZERO_VERIFY (0)

#define DNX_DATA_MAX_MACSEC_GENERAL_TX_THRESHOLD (3)

#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_MAX_DEPTH (129)

#define DNX_DATA_MAX_MACSEC_GENERAL_MACSEC_TDM_CAL_HW_DEPTH (129)

#define DNX_DATA_MAX_MACSEC_INGRESS_FLOW_NOF (1536)

#define DNX_DATA_MAX_MACSEC_INGRESS_POLICY_NOF (1024)

#define DNX_DATA_MAX_MACSEC_INGRESS_SECURE_ASSOC_NOF (2048)

#define DNX_DATA_MAX_MACSEC_INGRESS_UDF_NOF_BITS (440)

#define DNX_DATA_MAX_MACSEC_INGRESS_MGMT_RULE_EXACT_NOF (8)

#define DNX_DATA_MAX_MACSEC_INGRESS_TPID_NOF (5)

#define DNX_DATA_MAX_MACSEC_INGRESS_CPU_FLEX_MAP_NOF (16)

#define DNX_DATA_MAX_MACSEC_INGRESS_SC_TCAM_NOF (1280)

#define DNX_DATA_MAX_MACSEC_EGRESS_SECURE_ASSOC_NOF (1024)

#define DNX_DATA_MAX_MACSEC_EGRESS_SOFT_EXPIRY_THRESHOLD_PROFILES_NOF (4)

#define DNX_DATA_MAX_MACSEC_EGRESS_AN_BIT_NOF (1)

#define DNX_DATA_MAX_MACSEC_WRAPPER_MACSEC_ARB_PORTS_NOF (0)

#define DNX_DATA_MAX_MACSEC_WRAPPER_PER_PORT_SPEED_MAX_MBPS (0)

#define DNX_DATA_MAX_MACSEC_WRAPPER_WRAPPER_SPEED_MAX_MBPS (0)

#define DNX_DATA_MAX_MACSEC_WRAPPER_FRAMER_PORTS_OFFSET (0)




#endif 

