# -*- Makefile -*-
# $Id: Makefile,v 1.1.2.1 2010/08/18 00:10:14 sanjayg Exp $
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenBCM/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#
# Makefile for BCM PCRE library
#

LOCALDIR = src/bcm/esw/regex

include ${SDK}/make/Make.config

lib = libbcm_regex
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
